--md5:5d0ab1a452ae969084200ff8fe4bcfd6
Table_RoleData = { 
	[1] = {id = 1, PropName = '??????ID', VarName = 'CharID', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[2] = {id = 2, PropName = '????????????', VarName = 'CharName', IsPercent = 0, IsClientPercent = 0, RuneName = '', }, 
	[3] = {id = 3, PropName = '??????', VarName = 'Sex', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[4] = {id = 4, PropName = '??????', VarName = 'Class', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', }, 
	[5] = {id = 5, PropName = '????????????', VarName = 'BaseLv', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', }, 
	[6] = {id = 6, PropName = '??????', VarName = 'Exp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[7] = {id = 7, PropName = '????????????', VarName = 'JobLv', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', }, 
	[8] = {id = 8, PropName = '????????????', VarName = 'JobExp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[100] = {id = 100, PropName = '??????', VarName = 'Str', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Str', BaseTag = 9, }, 
	[101] = {id = 101, PropName = '??????', VarName = 'Int', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Int', BaseTag = 17, }, 
	[102] = {id = 102, PropName = '??????', VarName = 'Agi', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Agi', BaseTag = 33, }, 
	[103] = {id = 103, PropName = '??????', VarName = 'Dex', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Dex', BaseTag = 65, }, 
	[104] = {id = 104, PropName = '??????', VarName = 'Vit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Vit', BaseTag = 129, }, 
	[105] = {id = 105, PropName = '??????', VarName = 'Luk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Luk', BaseTag = 257, }, 
	[200] = {id = 200, PropName = '????????????', VarName = 'Atk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Atk', CombatTag = 257, }, 
	[201] = {id = 201, PropName = '????????????%', VarName = 'AtkPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Atk', CombatTag = 257, }, 
	[202] = {id = 202, PropName = '????????????', VarName = 'Def', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Def', CombatTag = 258, }, 
	[203] = {id = 203, PropName = '????????????%', VarName = 'DefPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Def', CombatTag = 258, }, 
	[204] = {id = 204, PropName = '????????????', VarName = 'MAtk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Matk', CombatTag = 513, }, 
	[205] = {id = 205, PropName = '????????????%', VarName = 'MAtkPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Matk', CombatTag = 513, }, 
	[206] = {id = 206, PropName = '????????????', VarName = 'MDef', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Mdef', CombatTag = 514, }, 
	[207] = {id = 207, PropName = '????????????%', VarName = 'MDefPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Mdef', CombatTag = 514, }, 
	[208] = {id = 208, PropName = 'MaxHp', VarName = 'MaxHp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Hp', BaseTag = 512, CombatTag = 4, }, 
	[209] = {id = 209, PropName = 'MaxHp%', VarName = 'MaxHpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Hp', BaseTag = 512, CombatTag = 4, }, 
	[210] = {id = 210, PropName = 'MaxSp', VarName = 'MaxSp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Sp', BaseTag = 1024, CombatTag = 4, }, 
	[211] = {id = 211, PropName = 'MaxSp%', VarName = 'MaxSpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Sp', BaseTag = 1024, CombatTag = 4, }, 
	[212] = {id = 212, PropName = 'Hp', VarName = 'Hp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[213] = {id = 213, PropName = 'Sp', VarName = 'Sp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[214] = {id = 214, PropName = '??????', VarName = 'Hit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Hit', CombatTag = 65537, }, 
	[215] = {id = 215, PropName = '??????', VarName = 'Flee', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Flee', CombatTag = 549755813890, }, 
	[216] = {id = 216, PropName = '??????', VarName = 'Cri', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Cri', CombatTag = 16385, }, 
	[217] = {id = 217, PropName = '????????????', VarName = 'CriRes', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '????????????', CombatTag = 32770, }, 
	[218] = {id = 218, PropName = '??????%', VarName = 'CriDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'CriDam', CombatTag = 16385, }, 
	[219] = {id = 219, PropName = '????????????%', VarName = 'CriDefPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '????????????', CombatTag = 32770, }, 
	[220] = {id = 220, PropName = '????????????', VarName = 'AtkSpd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'Aspd', CombatTag = 8193, }, 
	[221] = {id = 221, PropName = '????????????', VarName = 'MoveSpd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'Speed', CombatTag = 4194308, }, 
	[222] = {id = 222, PropName = '????????????', VarName = 'CastSpd', IsPercent = 1, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 131076, }, 
	[223] = {id = 223, PropName = 'Hp??????', VarName = 'RestoreSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Hp??????', BaseTag = 512, CombatTag = 262148, }, 
	[224] = {id = 224, PropName = 'Sp??????', VarName = 'SpRestoreSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Sp??????', BaseTag = 1024, CombatTag = 262148, }, 
	[225] = {id = 225, PropName = 'Hp????????????', VarName = 'ItemRestoreSpd', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 512, CombatTag = 262148, }, 
	[226] = {id = 226, PropName = 'Sp????????????', VarName = 'ItemSpRestoreSpd', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 1024, CombatTag = 262148, }, 
	[227] = {id = 227, PropName = 'Hp%??????', VarName = 'RestoreSpdPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Hp??????', BaseTag = 512, CombatTag = 262148, }, 
	[228] = {id = 228, PropName = 'Sp%??????', VarName = 'SpRestoreSpdPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Sp??????', BaseTag = 1024, CombatTag = 262148, }, 
	[229] = {id = 229, PropName = '??????%', VarName = 'CriPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Cri', CombatTag = 16385, }, 
	[300] = {id = 300, PropName = '????????????', VarName = 'Refine', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '??????Atk', BaseTag = 32768, CombatTag = 257, }, 
	[301] = {id = 301, PropName = '????????????', VarName = 'MRefine', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '??????Matk', BaseTag = 32768, CombatTag = 513, }, 
	[302] = {id = 302, PropName = '????????????%', VarName = 'MoveSpdPer', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'Speed', CombatTag = 4194308, }, 
	[303] = {id = 303, PropName = '????????????', VarName = 'EquipASPD', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'EquipAspd', CombatTag = 8193, }, 
	[304] = {id = 304, PropName = '????????????', VarName = 'SkillASPD', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'SkillAspd', CombatTag = 8193, }, 
	[305] = {id = 305, PropName = '????????????', VarName = 'HitPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[306] = {id = 306, PropName = '????????????', VarName = 'FleePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[307] = {id = 307, PropName = '????????????', VarName = 'StrPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[308] = {id = 308, PropName = '????????????', VarName = 'IntPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[309] = {id = 309, PropName = '????????????', VarName = 'AgiPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[310] = {id = 310, PropName = '????????????', VarName = 'DexPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[311] = {id = 311, PropName = '????????????', VarName = 'VitPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[312] = {id = 312, PropName = '????????????', VarName = 'LukPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[400] = {id = 400, PropName = '????????????', VarName = 'ShowAtk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 257, }, 
	[401] = {id = 401, PropName = '????????????', VarName = 'ShowDef', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 258, }, 
	[402] = {id = 402, PropName = '????????????', VarName = 'ShowMAtk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 513, }, 
	[403] = {id = 403, PropName = '????????????', VarName = 'ShowMDef', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 514, }, 
	[404] = {id = 404, PropName = 'MaxHp', VarName = 'ShowMaxHp', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[405] = {id = 405, PropName = 'MaxSp', VarName = 'ShowMaxSp', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[406] = {id = 406, PropName = '??????', VarName = 'ShowHit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 65537, }, 
	[407] = {id = 407, PropName = '??????', VarName = 'ShowFlee', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 549755813890, }, 
	[408] = {id = 408, PropName = '??????', VarName = 'ShowCri', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16385, }, 
	[409] = {id = 409, PropName = '??????', VarName = 'ShowCriRes', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 32770, }, 
	[410] = {id = 410, PropName = '????????????', VarName = 'ShowAtkSpd', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 8193, }, 
	[411] = {id = 411, PropName = '????????????', VarName = 'ShowMoveSpd', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 4194308, }, 
	[412] = {id = 412, PropName = '????????????', VarName = 'ShowCastSpd', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 131076, }, 
	[413] = {id = 413, PropName = '????????????', VarName = 'ShowRestoreSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 262148, }, 
	[414] = {id = 414, PropName = '????????????', VarName = 'DamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[415] = {id = 415, PropName = '????????????', VarName = 'MDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[416] = {id = 416, PropName = '????????????', VarName = 'IgnoreDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4353, }, 
	[417] = {id = 417, PropName = '????????????', VarName = 'IgnoreMDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4609, }, 
	[418] = {id = 418, PropName = '????????????', VarName = 'DamRebound', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8388868, }, 
	[419] = {id = 419, PropName = '????????????', VarName = 'MDamRebound', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8389124, }, 
	[420] = {id = 420, PropName = '????????????', VarName = 'DamIncrease', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2305, }, 
	[421] = {id = 421, PropName = '????????????', VarName = 'MDamIncrease', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2561, }, 
	[422] = {id = 422, PropName = '??????????????????', VarName = 'Vampiric', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[423] = {id = 423, PropName = '?????????????????????', VarName = 'BeVampiric', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[424] = {id = 424, PropName = '????????????', VarName = 'HarmImmune', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, }, 
	[425] = {id = 425, PropName = '????????????', VarName = 'RealDamage', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554435, }, 
	[426] = {id = 426, PropName = '????????????', VarName = 'RangeDam', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 129, }, 
	[427] = {id = 427, PropName = '????????????????????????', VarName = 'ShortRangeDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1314, }, 
	[428] = {id = 428, PropName = '????????????????????????', VarName = 'LongRangeDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1298, }, 
	[429] = {id = 429, PropName = '????????????????????????', VarName = 'LongRangeMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1554, }, 
	[430] = {id = 430, PropName = '??????????????????', VarName = 'IgnoreEquipDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[431] = {id = 431, PropName = '???????????????????????????', VarName = 'ShapeAtkPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[432] = {id = 432, PropName = '????????????', VarName = 'DamSpike', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4353, }, 
	[433] = {id = 433, PropName = '????????????', VarName = 'MDamSpike', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4609, }, 
	[434] = {id = 434, PropName = '????????????', VarName = 'RefineDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 32768, CombatTag = 1, }, 
	[435] = {id = 435, PropName = '????????????', VarName = 'RefineMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 32768, CombatTag = 1, }, 
	[436] = {id = 436, PropName = '????????????????????????', VarName = 'EnergyDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[437] = {id = 437, PropName = '????????????????????????', VarName = 'SteelDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[438] = {id = 438, PropName = '????????????????????????', VarName = 'SteelMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[439] = {id = 439, PropName = '????????????????????????', VarName = 'ProtectDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[440] = {id = 440, PropName = '????????????????????????', VarName = 'ProtectMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[441] = {id = 441, PropName = '????????????????????????', VarName = 'HideDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[442] = {id = 442, PropName = '????????????????????????', VarName = 'HideMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[443] = {id = 443, PropName = '?????????????????????', VarName = 'DragonDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[444] = {id = 444, PropName = '?????????????????????', VarName = 'DragonMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[445] = {id = 445, PropName = '????????????????????????', VarName = 'NormalRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554689, }, 
	[446] = {id = 446, PropName = '????????????????????????', VarName = 'NormalMRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554945, }, 
	[447] = {id = 447, PropName = '????????????????????????', VarName = 'SkillRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554697, }, 
	[448] = {id = 448, PropName = '????????????????????????', VarName = 'SkillMRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554953, }, 
	[449] = {id = 449, PropName = '???????????????', VarName = 'NormalAtk', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1, }, 
	[450] = {id = 450, PropName = '??????????????????', VarName = 'NormalAtkDam', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, }, 
	[451] = {id = 451, PropName = '??????????????????', VarName = 'NormalAtkRes', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1025, }, 
	[452] = {id = 452, PropName = '??????????????????', VarName = 'SkillDam', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, }, 
	[453] = {id = 453, PropName = '??????????????????', VarName = 'SkillRes', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1025, }, 
	[454] = {id = 454, PropName = '?????????????????????', VarName = 'WindMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[455] = {id = 455, PropName = '??????????????????', VarName = 'DeadDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[456] = {id = 456, PropName = '??????????????????', VarName = 'DeadMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[500] = {id = 500, PropName = '??????????????????', VarName = 'CalcDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 257, }, 
	[501] = {id = 501, PropName = '????????????????????????', VarName = 'CalcCriDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 16641, }, 
	[502] = {id = 502, PropName = '??????????????????', VarName = 'CalcMDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 513, }, 
	[503] = {id = 503, PropName = '????????????????????????', VarName = 'CalcCriMDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 16897, }, 
	[504] = {id = 504, PropName = '???????????????', VarName = 'CalcHit', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 65537, }, 
	[505] = {id = 505, PropName = '???????????????', VarName = 'CalcCri', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 16385, }, 
	[506] = {id = 506, PropName = '??????????????????', VarName = 'CalAspd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = '', CombatTag = 8193, }, 
	[507] = {id = 507, PropName = '??????????????????', VarName = 'CalcMoveSpd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = '', CombatTag = 4194308, }, 
	[508] = {id = 508, PropName = '??????????????????', VarName = 'CalcCastSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 131076, }, 
	[509] = {id = 509, PropName = '??????????????????', VarName = 'CTChange', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 131076, }, 
	[510] = {id = 510, PropName = '??????????????????%', VarName = 'CTChangePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 131076, }, 
	[511] = {id = 511, PropName = '??????????????????', VarName = 'CDChange', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 524292, }, 
	[512] = {id = 512, PropName = '??????????????????%', VarName = 'CDChangePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 524292, }, 
	[513] = {id = 513, PropName = '???????????????', VarName = 'Purify', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[514] = {id = 514, PropName = '?????????', VarName = 'PurifyMax', IsPercent = 0, Default = 1000, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[515] = {id = 515, PropName = 'SP????????????', VarName = 'SpCost', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[516] = {id = 516, PropName = 'SP????????????%', VarName = 'SpCostPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[517] = {id = 517, PropName = '??????????????????', VarName = 'AtkDistance', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 1, }, 
	[518] = {id = 518, PropName = '??????????????????%', VarName = 'AtkDistancePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1, }, 
	[519] = {id = 519, PropName = '????????????????????????', VarName = 'CTFixed', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 131076, }, 
	[520] = {id = 520, PropName = '??????????????????%??????', VarName = 'CTFixedPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 131076, }, 
	[521] = {id = 521, PropName = '????????????', VarName = 'SellDiscount', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[522] = {id = 522, PropName = '????????????', VarName = 'BuyDiscount', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[523] = {id = 523, PropName = 'HP????????????', VarName = 'HpCost', IsPercent = 0, Default = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[524] = {id = 524, PropName = 'HP????????????%', VarName = 'HpCostPer', IsPercent = 1, Default = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[533] = {id = 533, PropName = '????????????', VarName = 'CartNum', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[534] = {id = 534, PropName = '????????????', VarName = 'DelayCDChange', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[535] = {id = 535, PropName = '????????????%', VarName = 'DelayCDChangePer', IsPercent = 1, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[536] = {id = 536, PropName = '??????????????????', VarName = 'DChange', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[537] = {id = 537, PropName = '??????????????????%', VarName = 'DChangePer', IsPercent = 1, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[600] = {id = 600, PropName = '??????????????????', VarName = 'NoSkill', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 1073741828, }, 
	[601] = {id = 601, PropName = '?????????????????????', VarName = 'NoAct', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[602] = {id = 602, PropName = '????????????', VarName = 'NoMove', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 68719476740, }, 
	[603] = {id = 603, PropName = '????????????', VarName = 'NoStiff', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[604] = {id = 604, PropName = '????????????', VarName = 'NoAttack', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[605] = {id = 605, PropName = '????????????', VarName = 'FearRun', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 536870916, }, 
	[606] = {id = 606, PropName = '??????', VarName = 'Hiding', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 134217728, }, 
	[607] = {id = 607, PropName = '????????????', VarName = 'Taunt', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[608] = {id = 608, PropName = '??????', VarName = 'Freeze', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 2147483652, }, 
	[609] = {id = 609, PropName = '????????????', VarName = 'NoEffectMove', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 68719476740, }, 
	[610] = {id = 610, PropName = '????????????', VarName = 'StateEffect', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[611] = {id = 611, PropName = '????????????', VarName = 'AttrEffect', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[612] = {id = 612, PropName = '???????????????(??????)', VarName = 'NoAttacked', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 67108868, }, 
	[613] = {id = 613, PropName = '??????????????????', VarName = 'AttrFunction', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 8, }, 
	[614] = {id = 614, PropName = '????????????', VarName = 'AttrEffect2', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[615] = {id = 615, PropName = '????????????', VarName = 'FuncLimit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[700] = {id = 700, PropName = '??????????????????', VarName = 'AtkAttr', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 268435460, }, 
	[701] = {id = 701, PropName = '??????????????????', VarName = 'DefAttr', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 268435460, }, 
	[702] = {id = 702, PropName = '????????????????????????%', VarName = 'WindDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 262146},
	[703] = {id = 703, PropName = '????????????????????????%', VarName = 'EarthDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 2097154},
	[704] = {id = 704, PropName = '????????????????????????%', VarName = 'WaterDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 1048578},
	[705] = {id = 705, PropName = '????????????????????????%', VarName = 'FireDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 524290},
	[706] = {id = 706, PropName = '????????????????????????%', VarName = 'NeutralDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 131074},
	[707] = {id = 707, PropName = '????????????????????????%', VarName = 'HolyDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 4194306},
	[708] = {id = 708, PropName = '????????????????????????%', VarName = 'ShadowDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 8388610},
	[709] = {id = 709, PropName = '????????????????????????%', VarName = 'GhostDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 16777218},
	[710] = {id = 710, PropName = '???????????????????????????%', VarName = 'UndeadDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 67108866},
	[711] = {id = 711, PropName = '????????????????????????%', VarName = 'PoisonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 33554434},
	[712] = {id = 712, PropName = '????????????????????????%', VarName = 'BeWindDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 262146},
	[713] = {id = 713, PropName = '????????????????????????%', VarName = 'BeEarthDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 2097154},
	[714] = {id = 714, PropName = '????????????????????????%', VarName = 'BeWaterDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 1048578},
	[715] = {id = 715, PropName = '????????????????????????%', VarName = 'BeFireDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 524290},
	[716] = {id = 716, PropName = '????????????????????????%', VarName = 'BeNeutralDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 131074},
	[717] = {id = 717, PropName = '????????????????????????%', VarName = 'BeHolyDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 4194306},
	[718] = {id = 718, PropName = '????????????????????????%', VarName = 'BeShadowDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 8388610},
	[719] = {id = 719, PropName = '????????????????????????%', VarName = 'BeGhostDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 16777218},
	[720] = {id = 720, PropName = '???????????????????????????%', VarName = 'BeUndeadDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 268435458},
	[721] = {id = 721, PropName = '????????????????????????%', VarName = 'BePoisonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 33554434},
	[722] = {id = 722, PropName = '???????????????', VarName = 'WindAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WindAtk', CombatTag = 1, AdjTag = 262146},
	[723] = {id = 723, PropName = '???????????????', VarName = 'EarthAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'EarthAtk', CombatTag = 1, AdjTag = 2097154},
	[724] = {id = 724, PropName = '???????????????', VarName = 'FireAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'FireAtk', CombatTag = 1, AdjTag = 524290},
	[725] = {id = 725, PropName = '???????????????', VarName = 'WaterAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WaterAtk', CombatTag = 1, AdjTag = 1048578},
	[726] = {id = 726, PropName = '???????????????', VarName = 'NeutralAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'NeutralAtk', CombatTag = 1, AdjTag = 131074},
	[727] = {id = 727, PropName = '???????????????', VarName = 'HolyAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'HolyAtk', CombatTag = 1, AdjTag = 4194306},
	[728] = {id = 728, PropName = '???????????????', VarName = 'DarkAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'DarkAtk', CombatTag = 1, AdjTag = 8388610},
	[729] = {id = 729, PropName = '???????????????', VarName = 'WindDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WindDef', CombatTag = 2, AdjTag = 262146},
	[730] = {id = 730, PropName = '???????????????', VarName = 'EarthDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'EarthDef', CombatTag = 2, AdjTag = 2097154},
	[731] = {id = 731, PropName = '???????????????', VarName = 'FireDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'FireDef', CombatTag = 2, AdjTag = 524290},
	[732] = {id = 732, PropName = '???????????????', VarName = 'WaterDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WaterDef', CombatTag = 2, AdjTag = 1048578},
	[733] = {id = 733, PropName = '???????????????', VarName = 'NeutralDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'NeutralDef', CombatTag = 2, AdjTag = 131074},
	[734] = {id = 734, PropName = '???????????????', VarName = 'HolyDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'HolyDef', CombatTag = 2, AdjTag = 4194306},
	[735] = {id = 735, PropName = '???????????????', VarName = 'DarkDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'DarkDef', CombatTag = 2, AdjTag = 8388610},
	[736] = {id = 736, PropName = '???????????????', VarName = 'GhostAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'GhostAtk', CombatTag = 1, AdjTag = 16777218},
	[737] = {id = 737, PropName = '??????????????????', VarName = 'UndeadAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'UndeadAtk', CombatTag = 1, AdjTag = 268435458},
	[738] = {id = 738, PropName = '???????????????', VarName = 'PoisoningAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'PoisoningAtk', CombatTag = 1, AdjTag = 33554434},
	[800] = {id = 800, PropName = '???????????????%', VarName = 'BruteDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 1025},
	[801] = {id = 801, PropName = '???????????????%', VarName = 'DemiHumanDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 2049},
	[802] = {id = 802, PropName = '???????????????%', VarName = 'DemonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 513},
	[803] = {id = 803, PropName = '???????????????%', VarName = 'PlantDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 16385},
	[804] = {id = 804, PropName = '???????????????%', VarName = 'DeadLessDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 4097},
	[805] = {id = 805, PropName = '???????????????%', VarName = 'FormlessDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 8193},
	[806] = {id = 806, PropName = '???????????????%', VarName = 'FishDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 32769},
	[807] = {id = 807, PropName = '???????????????%', VarName = 'AngelDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 134217729},
	[808] = {id = 808, PropName = '???????????????%', VarName = 'InsectDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 65537},
	[809] = {id = 809, PropName = '???????????????%', VarName = 'DragonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 67108865},
	[810] = {id = 810, PropName = '???????????????%', VarName = 'BruteResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 1025},
	[811] = {id = 811, PropName = '???????????????%', VarName = 'DemiHumanResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 2049},
	[812] = {id = 812, PropName = '???????????????%', VarName = 'DemonResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 513},
	[813] = {id = 813, PropName = '???????????????%', VarName = 'PlantResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 16385},
	[814] = {id = 814, PropName = '???????????????%', VarName = 'DeadLessResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 4097},
	[815] = {id = 815, PropName = '???????????????%', VarName = 'FormlessResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 8193},
	[816] = {id = 816, PropName = '???????????????%', VarName = 'FishResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 32769},
	[817] = {id = 817, PropName = '???????????????%', VarName = 'AngelResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 134217729},
	[818] = {id = 818, PropName = '???????????????%', VarName = 'InsectResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 65537},
	[819] = {id = 819, PropName = '???????????????%', VarName = 'DragonResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 67108865},
	[900] = {id = 900, PropName = '??????????????????%', VarName = 'SmallDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 32},
	[901] = {id = 901, PropName = '??????????????????%', VarName = 'SmallResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 32},
	[902] = {id = 902, PropName = '??????????????????%', VarName = 'MidDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 64},
	[903] = {id = 903, PropName = '??????????????????%', VarName = 'MidResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 64},
	[904] = {id = 904, PropName = '??????????????????%', VarName = 'BigDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 128},
	[905] = {id = 905, PropName = '??????????????????%', VarName = 'BigResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 128},
	[906] = {id = 906, PropName = '???BOSS??????%', VarName = 'BossDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 4096, CombatTag = 2049, }, 
	[907] = {id = 907, PropName = '???BOSS??????%', VarName = 'BossResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 4096, CombatTag = 1026, }, 
	[908] = {id = 908, PropName = '??????BOSS????????????%', VarName = 'MonsterDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 2048, CombatTag = 2049, }, 
	[909] = {id = 909, PropName = '??????BOSS????????????%', VarName = 'MonsterResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 2048, CombatTag = 1026, }, 
	[910] = {id = 910, PropName = '???????????????%', VarName = 'NpcDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2113, }, 
	[911] = {id = 911, PropName = '???????????????%', VarName = 'NpcResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1090, }, 
	[1000] = {id = 1000, PropName = '????????????', VarName = 'SilenceAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1073741828, }, 
	[1001] = {id = 1001, PropName = '????????????', VarName = 'SilenceDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1073741828, }, 
	[1002] = {id = 1002, PropName = '????????????', VarName = 'FreezeAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2147483652, }, 
	[1003] = {id = 1003, PropName = '????????????', VarName = 'FreezeDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2147483652, }, 
	[1004] = {id = 1004, PropName = '????????????', VarName = 'StoneAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4294967300, }, 
	[1005] = {id = 1005, PropName = '????????????', VarName = 'StoneDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4294967300, }, 
	[1006] = {id = 1006, PropName = '????????????', VarName = 'StunAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8589934596, }, 
	[1007] = {id = 1007, PropName = '????????????', VarName = 'StunDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8589934596, }, 
	[1008] = {id = 1008, PropName = '????????????', VarName = 'BlindAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 17179869188, }, 
	[1009] = {id = 1009, PropName = '????????????', VarName = 'BlindDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 17179869188, }, 
	[1010] = {id = 1010, PropName = '????????????', VarName = 'PoisonAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 34359738372, }, 
	[1011] = {id = 1011, PropName = '????????????', VarName = 'PoisonDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 34359738372, }, 
	[1012] = {id = 1012, PropName = '????????????', VarName = 'SlowAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 68719476740, }, 
	[1013] = {id = 1013, PropName = '????????????', VarName = 'SlowDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 68719476740, }, 
	[1014] = {id = 1014, PropName = '????????????', VarName = 'ChaosAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 536870916, }, 
	[1015] = {id = 1015, PropName = '????????????', VarName = 'ChaosDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 536870916, }, 
	[1016] = {id = 1016, PropName = '????????????', VarName = 'CurseAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 0, }, 
	[1017] = {id = 1017, PropName = '????????????', VarName = 'CurseDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 137438953476, }, 
	[1018] = {id = 1018, PropName = '????????????', VarName = 'StateAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4, }, 
	[1019] = {id = 1019, PropName = '????????????', VarName = 'StateDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4, }, 
	[1020] = {id = 1020, PropName = '????????????', VarName = 'StateReflect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8388612, }, 
	[1021] = {id = 1021, PropName = '??????????????????', VarName = 'StateTimeEnc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1022] = {id = 1022, PropName = '?????????????????????', VarName = 'BeStateTimeDec', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1023] = {id = 1023, PropName = '??????????????????', VarName = 'StateAbnorResist', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1024] = {id = 1024, PropName = '??????ID', VarName = 'TransformID', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[1025] = {id = 1025, PropName = '????????????', VarName = 'SleepAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1099511627780, }, 
	[1026] = {id = 1026, PropName = '????????????', VarName = 'SleepDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1099511627780, }, 
	[1100] = {id = 1100, PropName = '????????????', VarName = 'WeaponBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1101] = {id = 1101, PropName = '????????????', VarName = 'EquipBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1102] = {id = 1102, PropName = '????????????', VarName = 'HeadBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1103] = {id = 1103, PropName = '????????????', VarName = 'ShieldBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1104] = {id = 1104, PropName = '????????????', VarName = 'ShoesBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1105] = {id = 1105, PropName = '????????????', VarName = 'RobeBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1106] = {id = 1106, PropName = '???????????????', VarName = 'AccessoryBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1107] = {id = 1107, PropName = '????????????', VarName = 'WeaponProtect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1108] = {id = 1108, PropName = '????????????', VarName = 'EquipProtect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1109] = {id = 1109, PropName = '????????????', VarName = 'AccessoryProtect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1110] = {id = 1110, PropName = '???????????????', VarName = 'BeHealEncPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 274877906948, }, 
	[1111] = {id = 1111, PropName = '????????????', VarName = 'HealEncPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 274877906948, }, 
	[1112] = {id = 1112, PropName = '?????????????????????%', VarName = 'AutoHealEncPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 262148, }, 
	[1113] = {id = 1113, PropName = '??????????????????', VarName = 'HpSuckRate', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 16777220, }, 
	[1114] = {id = 1114, PropName = '????????????%', VarName = 'HpSuckPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 16777220, }, 
	[1115] = {id = 1115, PropName = '????????????', VarName = 'HpSuck', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16777220, }, 
	[1116] = {id = 1116, PropName = '????????????', VarName = 'EquipBrake', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1200] = {id = 1200, PropName = '??????????????????', VarName = 'DamAbsorb', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16777220, }, 
	[1201] = {id = 1201, PropName = '??????????????????', VarName = 'DamAbsorbTime', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16777220, }, 
	[1202] = {id = 1202, PropName = '????????????', VarName = 'PowerShock', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1203] = {id = 1203, PropName = '????????????', VarName = 'PowerAbsorb', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 16777220, }, 
	[1204] = {id = 1204, PropName = '????????????', VarName = 'CastBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1205] = {id = 1205, PropName = '?????????', VarName = 'CastBreakRes', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1206] = {id = 1206, PropName = '????????????', VarName = 'SizeCorrection', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1207] = {id = 1207, PropName = '????????????', VarName = 'Slv', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 8, }, 
	[1208] = {id = 1208, PropName = '????????????', VarName = 'DeadSoon', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[1209] = {id = 1209, PropName = 'HP??????', VarName = 'SaveHp', IsPercent = 0, Default = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[1210] = {id = 1210, PropName = 'SP??????', VarName = 'SaveSp', IsPercent = 0, Default = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[1211] = {id = 1211, PropName = '????????????', VarName = 'SlimHeight', IsPercent = 0, Default = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[1212] = {id = 1212, PropName = '????????????', VarName = 'SlimWeight', IsPercent = 0, Default = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[1213] = {id = 1213, PropName = '????????????Base??????', VarName = 'BaseExpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 8194, AdjTag = 4},
	[1214] = {id = 1214, PropName = '????????????Job??????', VarName = 'JobExpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 8196, AdjTag = 4},
}

Table_RoleData_fields = { "id","PropName","VarName","IsPercent","Default","IsClientPercent","SyncFloat","RuneName","BaseTag","CombatTag","AdjTag",}
return Table_RoleData