--md5:252eb7fbc4427ec95036d690b6f503f1
Table_Expression = { 
	[1] = {id = 1, NameZh = '??????', NameEn = 'Emoji_god', Type = '2'},
	[2] = {id = 2, NameZh = '??????', NameEn = 'Emoji_heart', Type = '2'},
	[3] = {id = 3, NameZh = '??????', NameEn = 'Emoji_kiss_left', Type = '2'},
	[4] = {id = 4, NameZh = '??????', NameEn = 'Emoji_kiss_right', Type = '2'},
	[5] = {id = 5, NameZh = '??????', NameEn = 'Emoji_sinister', Type = '2'},
	[6] = {id = 6, NameZh = '??????', NameEn = 'Emoji_thanks', Type = '2'},
	[7] = {id = 7, NameZh = '?????????', NameEn = 'Emoji_exclamation_mark', Type = '2'},
	[8] = {id = 8, NameZh = '??????', NameEn = 'Emoji_question_mark', Type = '2'},
	[9] = {id = 9, NameZh = '??????', NameEn = 'Emoji_happy', Type = '2'},
	[10] = {id = 10, NameZh = '?????????', NameEn = 'Emoji_cold_sweat', Type = '2'},
	[11] = {id = 11, NameZh = '??????', NameEn = 'Emoji_inspiration', Type = '2'},
	[12] = {id = 12, NameZh = '??????', NameEn = 'Emoji_angry', Type = '2'},
	[13] = {id = 13, NameZh = '??????', NameEn = 'Emoji_money', Type = '2'},
	[14] = {id = 14, NameZh = '??????', NameEn = 'Emoji_silent', Type = '2'},
	[15] = {id = 15, NameZh = '??????', NameEn = 'Emoji_helpless', Type = '2'},
	[16] = {id = 16, NameZh = '??????', NameEn = 'Emoji_sorry', Type = '2'},
	[17] = {id = 17, NameZh = '??????', NameEn = 'Emoji_laughter', Type = '2'},
	[18] = {id = 18, NameZh = '??????', NameEn = 'Emoji_sweat', Type = '2'},
	[19] = {id = 19, NameZh = '??????', NameEn = 'Emoji_confused', Type = '2'},
	[20] = {id = 20, NameZh = '?????????', NameEn = 'Emoji_great', Type = '2'},
	[21] = {id = 21, NameZh = '??????', NameEn = 'Emoji_looking_for', Type = '2'},
	[22] = {id = 22, NameZh = '??????', NameEn = 'Emoji_sos', Type = '2'},
	[23] = {id = 23, NameZh = '??????', NameEn = 'Emoji_set_out', Type = '2'},
	[24] = {id = 24, NameZh = '??????', NameEn = 'Emoji_cry', Type = '2'},
	[25] = {id = 25, NameZh = '???', NameEn = 'Emoji_hu', Type = '2'},
	[26] = {id = 26, NameZh = '??? ', NameEn = 'Emoji_en', Type = '2'},
	[27] = {id = 27, NameZh = '?????????', NameEn = 'Emoji_big_heart', Type = '2'},
	[28] = {id = 28, NameZh = '??????', NameEn = 'Emoji_saliva', Type = '2'},
	[29] = {id = 29, NameZh = '????????????', NameEn = 'Emoji_anthomaniac', Type = '2'},
	[30] = {id = 30, NameZh = '??????', NameEn = 'Emoji_touch', Type = '2'},
	[31] = {id = 31, NameZh = '???', NameEn = 'Emoji_error', Type = '2'},
	[32] = {id = 32, NameZh = '???', NameEn = 'Emoji_correct', Type = '2'},
	[33] = {id = 33, NameZh = '??????', NameEn = 'Emoji_stone', Type = '2'},
	[34] = {id = 34, NameZh = '??????', NameEn = 'Emoji_scissors', Type = '2'},
	[35] = {id = 35, NameZh = '???', NameEn = 'Emoji_cloth', Type = '2'},
	[36] = {id = 36, NameZh = '??????', NameEn = 'Emoji_sleep', Type = '2'},
	[37] = {id = 37, NameZh = '??????', NameEn = 'Emoji_afraid', Type = '2'},
	[500] = {id = 500, NameZh = '??????????????????', NameEn = 'Emoji_peingles_delicipus', Type = '2'},
}

Table_Expression_fields = { "id","NameZh","NameEn","Type",}
return Table_Expression