--md5:dbd25abd1f5cec6d393fe93b29831998
Table_Map_WW = { 
	[68001] = {id = 68001, NameZh = '???????????????', NameEn = 'room_xmas3', CallZh = '1019', LvRange = _EmptyTable, Type = 3, Mode = 3, MapScale = 40, MonsterRatio = _EmptyTable, Desc = '???????????????', ShowInList = 0, SceneAnimation = 0, PVPmap = 0, Position = _EmptyTable, Camera = 1, LeapsMapNavigation = 1, MapUi = 7, EnterCond = _EmptyTable, IndexRange = _EmptyTable},
	[68002] = {id = 68002, NameZh = '???????????????', NameEn = 'room_xmas3', CallZh = '1019', LvRange = _EmptyTable, Type = 3, Mode = 3, MapScale = 40, MonsterRatio = _EmptyTable, Desc = '???????????????', ShowInList = 0, SceneAnimation = 0, PVPmap = 0, Position = _EmptyTable, Camera = 1, LeapsMapNavigation = 1, MapUi = 7, EnterCond = _EmptyTable, IndexRange = _EmptyTable},
	[68003] = {id = 68003, NameZh = '???????????????', NameEn = 'room_xmas3', CallZh = '1019', LvRange = _EmptyTable, Type = 3, Mode = 3, MapScale = 40, MonsterRatio = _EmptyTable, Desc = '???????????????', ShowInList = 0, SceneAnimation = 0, PVPmap = 0, Position = _EmptyTable, Camera = 1, LeapsMapNavigation = 1, MapUi = 7, EnterCond = _EmptyTable, IndexRange = _EmptyTable},
	[68004] = {id = 68004, NameZh = '??????????????????', NameEn = 'room_xmas1', CallZh = '??????????????????', LvRange = _EmptyTable, Type = 3, Mode = 3, MapScale = 40, MonsterRatio = _EmptyTable, Desc = '???????????????', ShowInList = 0, SceneAnimation = 0, PVPmap = 0, Position = _EmptyTable, Camera = 1, LeapsMapNavigation = 1, MapUi = 7, EnterCond = _EmptyTable, IndexRange = _EmptyTable},
	[68005] = {id = 68005, NameZh = '????????????', NameEn = 'room_xmas2', CallZh = '?????????', LvRange = _EmptyTable, Type = 3, Mode = 3, MapScale = 40, MonsterRatio = _EmptyTable, Desc = '???????????????', ShowInList = 0, SceneAnimation = 0, PVPmap = 0, Position = _EmptyTable, Camera = 1, LeapsMapNavigation = 1, MapUi = 7, EnterCond = _EmptyTable, IndexRange = _EmptyTable},
	[68006] = {id = 68006, NameZh = '??????????????????', NameEn = 'xmas', CallZh = '48', LvRange = _EmptyTable, Type = 3, Mode = 3, MapScale = 40, MonsterRatio = _EmptyTable, Desc = '???????????????', ShowInList = 0, SceneAnimation = 0, PVPmap = 0, Position = _EmptyTable, Camera = 1, LeapsMapNavigation = 1, MapUi = 7, EnterCond = _EmptyTable, IndexRange = _EmptyTable},
	[1] = {id = 1, NameZh = '????????????', NameEn = 'Prontera', CallZh = '????????????', LvRange = _EmptyTable, Type = 6, Mode = 1, Range = 4001, MoneyType = 1, Money = 400, MapTips = 1, MapScale = 80, MonsterRatio = _EmptyTable, Desc = '??????-??????????????????????????????', ShowInList = 1, AdventureValue = -1, SceneAnimation = 1, PVPmap = 0, Position = {4,9}, Camera = 1, MapArea = 1, MapUi = 7, EnterCond = _EmptyTable, IndexRange = _EmptyTable},
}

Table_Map_WW_fields = { "id","NameZh","NameEn","CallZh","LvRange","Type","Mode","Range","MoneyType","Money","MapTips","MapScale","MonsterRatio","Desc","ShowInList","AdventureValue","SceneAnimation","PVPmap","Position","Camera","MapArea","LeapsMapNavigation","MapNavigation","MapUi","EnterCond","IsDangerous","IndexRange",}
return Table_Map_WW