--md5:466060e876338f0a63e4088f6c6ef1bf
Table_Guild_Faith = { 
	[1] = {id = 1, Index = 1, Name = '生命', Attr = '生命上限', AttrName = '生命上限', Type = 0},
	[2] = {id = 2, Index = 2, Name = '战斗', Attr = '物理攻击', AttrName = '物理攻击', Type = 0},
	[3] = {id = 3, Index = 3, Name = '智慧', Attr = '魔法攻击', AttrName = '魔法攻击', Type = 0},
	[4] = {id = 4, Index = 4, Name = '生存', Attr = '物理防御', AttrName = '物理防御', Type = 0},
	[5] = {id = 5, Index = 5, Name = '抗魔', Attr = '魔法防御', AttrName = '魔法防御', Type = 0},
	[101] = {id = 101, Index = 1, Name = '攻击', Attr = '对人形增伤%', AttrName = '对人形增伤', Type = 1},
	[102] = {id = 102, Index = 2, Name = '攻击', Attr = '暴伤%', AttrName = '暴击伤害', Type = 1},
	[103] = {id = 103, Index = 3, Name = '攻击', Attr = '忽视物防', AttrName = '忽视物理防御', Type = 1},
	[104] = {id = 104, Index = 4, Name = '攻击', Attr = '物理穿刺', AttrName = '物理穿刺', Type = 1},
	[105] = {id = 105, Index = 5, Name = '攻击', Attr = '物理攻击', AttrName = '物理攻击', Type = 1},
	[106] = {id = 106, Index = 6, Name = '攻击', Attr = '精炼物攻', AttrName = '精炼物攻', Type = 1},
	[107] = {id = 107, Index = 7, Name = '攻击', Attr = '忽视魔防', AttrName = '忽视魔法防御', Type = 1},
	[108] = {id = 108, Index = 8, Name = '攻击', Attr = '魔法穿刺', AttrName = '魔法穿刺', Type = 1},
	[109] = {id = 109, Index = 9, Name = '攻击', Attr = '魔法攻击', AttrName = '魔法攻击', Type = 1},
	[110] = {id = 110, Index = 10, Name = '攻击', Attr = '精炼魔攻', AttrName = '精炼魔攻', Type = 1},
	[201] = {id = 201, Index = 1, Name = '防御', Attr = 'MaxHp', AttrName = '生命上限', Type = 2},
	[202] = {id = 202, Index = 2, Name = '防御', Attr = '对无属性伤害减免%', AttrName = '对无属性伤害减免', Type = 2},
	[203] = {id = 203, Index = 3, Name = '防御', Attr = '物伤减免', AttrName = '物伤减免', Type = 2},
	[204] = {id = 204, Index = 4, Name = '防御', Attr = '暴伤减免%', AttrName = '暴伤减免', Type = 2},
	[205] = {id = 205, Index = 5, Name = '防御', Attr = '暴击防护', AttrName = '暴击防护', Type = 2},
	[206] = {id = 206, Index = 6, Name = '防御', Attr = '魔伤减免', AttrName = '魔伤减免', Type = 2},
	[207] = {id = 207, Index = 7, Name = '防御', Attr = '物理防御%', AttrName = '物理防御%', Type = 2},
	[208] = {id = 208, Index = 8, Name = '防御', Attr = '魔法防御%', AttrName = '魔法防御%', Type = 2},
	[301] = {id = 301, Index = 1, Name = '元素', Attr = '风属性攻击', AttrName = '风属性攻击', Type = 3},
	[302] = {id = 302, Index = 2, Name = '元素', Attr = '地属性攻击', AttrName = '地属性攻击', Type = 3},
	[303] = {id = 303, Index = 3, Name = '元素', Attr = '火属性攻击', AttrName = '火属性攻击', Type = 3},
	[304] = {id = 304, Index = 4, Name = '元素', Attr = '水属性攻击', AttrName = '水属性攻击', Type = 3},
	[305] = {id = 305, Index = 6, Name = '元素', Attr = '对风属性伤害减免%', AttrName = '对风属性伤害减免', Type = 3},
	[306] = {id = 306, Index = 7, Name = '元素', Attr = '对地属性伤害减免%', AttrName = '对地属性伤害减免', Type = 3},
	[307] = {id = 307, Index = 8, Name = '元素', Attr = '对水属性伤害减免%', AttrName = '对水属性伤害减免', Type = 3},
	[308] = {id = 308, Index = 9, Name = '元素', Attr = '对火属性伤害减免%', AttrName = '对火属性伤害减免', Type = 3},
	[309] = {id = 309, Index = 5, Name = '元素', Attr = '圣属性攻击', AttrName = '圣属性攻击', Type = 3},
	[310] = {id = 310, Index = 10, Name = '元素', Attr = '对圣属性伤害减免%', AttrName = '对圣属性伤害减免', Type = 3},
}

Table_Guild_Faith_fields = { "id","Index","Name","Attr","AttrName","Type",}
return Table_Guild_Faith