--md5:ec5c1dc7a9a89af8dc7cf06a95a2cc97
Table_Guild_Incident = { 
	[1] = {id = 1, Page = 1, txt = '%s正式创建了公会%s。'},
	[2] = {id = 2, Page = 1, txt = '%s发起了解散公会审核中！'},
	[3] = {id = 3, Page = 1, txt = '%s取消了解散公会。'},
	[4] = {id = 4, Page = 1, txt = '%s修改了公告。'},
	[5] = {id = 5, Page = 1, txt = '%s修改了招募信息。'},
	[6] = {id = 6, Page = 1, txt = '%s将会长交接给了%s。'},
	[7] = {id = 7, Page = 1, txt = '%s指派%s为副会长。'},
	[8] = {id = 8, Page = 1, txt = '%s踢出成员%s。'},
	[9] = {id = 9, Page = 1, txt = '%s更改了职位名称。'},
	[10] = {id = 10, Page = 1, txt = '%s加入了本公会。'},
	[11] = {id = 11, Page = 1, txt = '%s退出了本公会。'},
	[12] = {id = 12, Page = 2, txt = '成员%s向公会捐赠了华丽金属'},
	[13] = {id = 13, Page = 1, txt = '%s开启了%s的%s权限。'},
	[14] = {id = 14, Page = 1, txt = '%s关闭了%s的%s权限。'},
	[15] = {id = 15, Page = 1, txt = '%s开启了%s的%s权限。'},
	[16] = {id = 16, Page = 1, txt = '%s关闭了%s的%s权限。'},
	[17] = {id = 17, Page = 1, txt = '会长%s将公会改名为%s。'},
	[18] = {id = 18, Page = 3, txt = '%s 开始建造 %s。'},
	[19] = {id = 19, Page = 3, txt = '%s 开始升级 %s。'},
	[20] = {id = 20, Page = 5, txt = '%s制造了%s 。'},
	[21] = {id = 21, Page = 5, txt = '%s 将 %s 分配给了 %s。'},
	[22] = {id = 22, Page = 5, txt = '%s归还了%s 。'},
	[23] = {id = 23, Page = 5, txt = '%s从%s取回了%s。'},
	[24] = {id = 24, Page = 6, txt = '%s开启了%s。'},
	[25] = {id = 25, Page = 6, txt = '%s花费了%s%s开启了%s。'},
	[26] = {id = 26, Page = 6, txt = '%s花费了%s%s开启了%s。'},
	[27] = {id = 27, Page = 3, txt = '%s在公会设施”%s”建设中,提交了一份贡献。'},
	[28] = {id = 28, Page = 4, txt = '%s年%s月%s日在公会GVG据点争夺活动中，占领了%s据点！'},
	[29] = {id = 29, Page = 4, txt = '%s年%s月%s日在公会GVG据点争夺活动中，失去了%s据点！'},
	[30] = {id = 30, Page = 4, txt = '%s年%s月%s日在公会GVG决战活动中,取得了%s名次！'},
	[31] = {id = 31, Page = 5, txt = '%s完成了%s神器任务,解锁了%s'},
}

Table_Guild_Incident_fields = { "id","Page","txt",}
return Table_Guild_Incident