--md5:c3d23b4aba40cf7ee63b08fb368ffc88
Table_GuideID = { 
	[1] = {id = 1, Explain = '打开角色界面', uiID = 'MainView', ButtonID = 101, text = '点击自己的头像', position = {x=-437,y=149}, rotation = {x=180,y=180,z=0}, press = 1, ServerEvent = '', }, 
	[2] = {id = 2, Explain = '打开角色加点切页', Preguide = 1, uiID = 'Charactor', ButtonID = 5, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[3] = {id = 3, Explain = '检查人物剩余素质点', Preguide = 2, optionId = 1, uiID = 'Charactor', ButtonID = 6, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
	[4] = {id = 4, Explain = '点击加点确认按钮', Preguide = 3, uiID = 'Charactor', ButtonID = 7, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[5] = {id = 5, Explain = '点击角色界面中的关闭界面按钮×', Preguide = 4, uiID = 'Charactor', ButtonID = 8, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[10] = {id = 10, Explain = '点击道具商人的杂货铺按钮', uiID = 'DialogView', ButtonID = 10, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', }, 
	[11] = {id = 11, Explain = '点击道具商人里面的红色药水一行', Preguide = 10, uiID = 'HappyShop', ButtonID = 11, targetID = 12001, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = 'GuideEvent_SessionShopQueryShopConfigCmd', FailJump = 1},
	[12] = {id = 12, Explain = '检测购买药水数量是否达到5瓶及以上', Preguide = 11, optionId = 2, uiID = 'HappyShop', ButtonID = 16, text = '长按后能快速增加数量', position = {x=-185,y=41}, rotation = {x=0,y=0,z=0}, press = 0, ServerEvent = '', }, 
	[13] = {id = 13, Explain = '点击确认购买按钮', Preguide = 12, uiID = 'HappyShop', ButtonID = 17, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[14] = {id = 14, Explain = '点击道具商人关闭界面按钮', Preguide = 13, uiID = 'HappyShop', ButtonID = 15, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[21] = {id = 21, Explain = '点击角色界面里的“查看技能”', Preguide = 1, uiID = 'Charactor', ButtonID = 9, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[22] = {id = 22, Explain = '检查剩余技能点数', Preguide = 21, optionId = 3, uiID = 'SkillView', ButtonID = 32, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
	[23] = {id = 23, Explain = '点击技能加点确认按钮', Preguide = 22, uiID = 'SkillView', ButtonID = 30, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[24] = {id = 24, Explain = '点击技能界面上的返回按钮', Preguide = 23, uiID = 'SkillView', ButtonID = 31, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[25] = {id = 25, Explain = '点击角色加点切页', Preguide = 24, uiID = 'Charactor', ButtonID = 5, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[30] = {id = 30, Explain = '打开背包界面', uiID = 'PackageView', ButtonID = 103, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', }, 
	[31] = {id = 31, Explain = '点击强化切页', Preguide = 30, uiID = 'PackageView', ButtonID = 35, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[40] = {id = 40, Explain = '打开更多界面', uiID = 'MainView', ButtonID = 102, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', }, 
	[41] = {id = 41, Explain = '打开冒险手册界面', uiID = 'MainView', ButtonID = 106, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[42] = {id = 42, Explain = '点击魔物切页', Preguide = 41, uiID = 'AdventurePanel', ButtonID = 40, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[48] = {id = 48, Explain = '点击魔物卡片切页', Preguide = 41, uiID = 'AdventurePanel', ButtonID = 41, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[50] = {id = 50, Explain = '打开乐园团商店', uiID = 'DialogView', ButtonID = 18, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', }, 
	[51] = {id = 51, Explain = '点击乐园团商店中的乐园团帽子图纸', Preguide = 50, uiID = 'HappyShop', ButtonID = 19, targetID = 14076, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = 'GuideEvent_SessionShopQueryShopConfigCmd', FailJump = 1},
	[52] = {id = 52, Explain = '点击乐园团商店中的确认购买按钮', Preguide = 51, uiID = 'HappyShop', ButtonID = 17, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[55] = {id = 55, Explain = '点击头饰制作卷轴上的制作按钮', Preguide = 56, uiID = 'PicMakeView', ButtonID = 20, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[56] = {id = 56, Explain = '点击微笑小姐对话框上的制作头饰按钮', uiID = 'DialogView', ButtonID = 21, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', }, 
	[100] = {id = 100, Explain = '"任务点都标记在地图上，请留意感叹号"', uiID = '', BubbleID = 1, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
	[101] = {id = 101, Explain = '"拖动技能图标，把不需要的技能都替换掉吧！"', uiID = '', BubbleID = 3, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
	[102] = {id = 102, Explain = '"使用蝴蝶翅膀可以瞬间回到这里"', uiID = '', BubbleID = 4, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
	[110] = {id = 110, Explain = '点击小地图按钮', uiID = 'MainView', ButtonID = 107, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', }, 
	[111] = {id = 111, Explain = '访问地图上任意“！”可接取任务', uiID = '', BubbleID = 10, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', RepeatDeltaTime = 60, }, 
	[112] = {id = 112, Explain = '我们已经为你标记了波伊的位置啦~快去找它吧', Preguide = 110, uiID = '', BubbleID = 15, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
	[113] = {id = 113, Explain = '我们已经为你标记了班尼的位置啦~快去找他吧', Preguide = 110, uiID = '', BubbleID = 17, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
	[60] = {id = 60, Explain = '点击冒险技能学习界面中的“战斗技巧”', Preguide = 61, uiID = 'UIViewControllerAdventureSkill', ButtonID = 36, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[64] = {id = 64, Explain = '点击冒险技能学习界面中的“魔物锁定”', Preguide = 61, uiID = 'UIViewControllerAdventureSkill', ButtonID = 45, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[61] = {id = 61, Explain = '点击学习冒险技能', uiID = 'DialogView', ButtonID = 37, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', }, 
	[62] = {id = 62, Explain = '点击学习按钮', Preguide = 60, uiID = 'UIViewAdventureSkillDetail', ButtonID = 38, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[63] = {id = 63, Explain = '点击学习冒险技能上的关闭按钮', Preguide = 62, uiID = 'UIViewControllerAdventureSkill', ButtonID = 39, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 1, ServerEvent = '', FailJump = 1},
	[120] = {id = 120, Explain = '自动战斗锁定疯兔', uiID = 'MainView', BubbleID = 20, text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', guideLockMonster = 10002, }, 
	[125] = {id = 125, Explain = '空的引导任务，陈涛用', uiID = '', text = '', position = _EmptyTable, rotation = _EmptyTable, press = 0, ServerEvent = '', }, 
}

Table_GuideID_fields = { "id","Explain","Preguide","optionId","uiID","ButtonID","targetID","BubbleID","text","position","rotation","press","ServerEvent","RepeatDeltaTime","guideLockMonster","FailJump",}
return Table_GuideID