autoImport("RoleDefines")
autoImport("SkillDefines")
autoImport("TransformData")
autoImport("CreatureData")
autoImport("PlayerData")
autoImport("NpcData")
autoImport("MyselfData")
autoImport("PetData")
autoImport("PartnerData")
autoImport("HandNpcData")
autoImport("ExpressNpcData")
DataStructureManager = class("DataStructureManager")
function DataStructureManager:ctor()
end
function DataStructureManager:Update(time, deltaTime)
end
