--md5:46bb4de32b12d9be32987a6852135398
Table_Valentine = { 
	[1] = {id = 1, Type = 1, Title = '', Option = {{"是的","ff2e2e"},{"不是","00c0ff"}}, TitleDesc = '比起梦罗克这样的神秘沙漠之都，你更喜欢依斯鲁得那样浪漫的海边城市。', Language = '嗯哼~~没想到你会选这样的答案~~'},
	[2] = {id = 2, Type = 1, Title = '', Option = {{"是的","ffe400"},{"不是","00c0ff"}}, TitleDesc = '比起吉芬神秘的魔法气息，你更喜欢普隆德拉气派华丽的皇宫景观。', Language = '亲，你想好了这样选的结果么~~'},
	[3] = {id = 3, Type = 2, Title = '', Option = {{"冰波利","00c0ff"},{"土波利","ffe400"}}, TitleDesc = '你们在冒险的途中遇到一只波利，你认为它是…', Language = '不错，你的品味和我果然一模一样呢~~'},
	[4] = {id = 4, Type = 2, Title = '', Option = {{"头饰","ffe400"},{"武器","00c0ff"}}, TitleDesc = '你和你的另一半都收到了一只神秘的礼物盒，你们觉得里面是…', Language = '你竟然这么说，你的小伙伴ta知道么~~'},
	[5] = {id = 5, Type = 2, Title = '', Option = {{"酸甜的苹果汁","ffe400"},{"甜甜的蜂蜜","00c0ff"}}, TitleDesc = '你的另一半对你来说更像是…', Language = '从选择中看得出来，你们的关系相当好呢~~'},
	[6] = {id = 6, Type = 2, Title = '', Option = {{"是的","ffe400"},{"不是","00c0ff"}}, TitleDesc = '你和你的另一半一个是主输出，一个是辅助，合作相当愉快。', Language = '这么快就做出选择啦，难道你不再想想吗？'},
	[7] = {id = 7, Type = 2, Title = '', Option = {{"五个人","ff2e2e"},{"单独两人","00c0ff"}}, TitleDesc = '你们一般喜欢五个人组队打怪，还是单独两个人冒险？', Language = '嗯哼~~没想到你会选这样的答案~~'},
	[8] = {id = 8, Type = 2, Title = '', Option = {{"暖身料理","ffe400"},{"万能药","00c0ff"}}, TitleDesc = '你的另一半对你来说，更像是…', Language = '亲，你想好了这样选的结果么~~'},
	[9] = {id = 9, Type = 2, Title = '', Option = {{"白幽灵","ff2e2e"},{"傀儡娃娃","00c0ff"}}, TitleDesc = '你们在拍照时，意外拍出了一只幽灵魔物，你觉得那会是…', Language = '不错，你的品味和我果然一模一样呢~~'},
	[10] = {id = 10, Type = 2, Title = '', Option = {{"是的","ffe400"},{"不是","e400ff"}}, TitleDesc = '你们都学习了很多拍照的冒险技能。', Language = '你竟然这么说，你的小伙伴ta知道么~~'},
	[11] = {id = 11, Type = 2, Title = '', Option = {{"MINI","ff2e2e"},{"MVP","00c0ff"}}, TitleDesc = '你们很幸运地从一只魔物身上获得了一张图纸，你认为那是一只…', Language = '从选择中看得出来，你们的关系相当好呢~~'},
	[12] = {id = 12, Type = 2, Title = '', Option = {{"蓝色","00c0ff"},{"黄色","ffe400"}}, TitleDesc = '你们一起去理发店准备染成同一个发色，你更喜欢…', Language = '这么快就做出选择啦，难道你不再想想吗？'},
	[13] = {id = 13, Type = 2, Title = '', Option = {{"是的","ffe400"},{"不是","e400ff"}}, TitleDesc = '你们在一次偶然中得到了一枚幻银之证，你们会选择马上使用它吗？', Language = '嗯哼~~没想到你会选这样的答案~~'},
	[14] = {id = 14, Type = 2, Title = '', Option = {{"红色","ff2e2e"},{"白色","a5a5a5"}}, TitleDesc = '你们一起去理发店准备染成同一个发色，你更喜欢…', Language = '亲，你想好了这样选的结果么~~'},
	[15] = {id = 15, Type = 2, Title = '', Option = {{"是的","ff2e2e"},{"不是","e400ff"}}, TitleDesc = '你们接到的任务不相同时，你的另一半还是常愿意陪你一起完成吗？', Language = '不错，你的品味和我果然一模一样呢~~'},
	[16] = {id = 16, Type = 2, Title = '', Option = {{"是的","ff2e2e"},{"不是","00c0ff"}}, TitleDesc = '你认为头饰的实用性比美观性要重要。', Language = '你竟然这么说，你的小伙伴ta知道么~~'},
	[17] = {id = 17, Type = 2, Title = '', Option = {{"是的","ff2e2e"},{"不是","e400ff"}}, TitleDesc = '你们一起的合影，通常会喜欢把NPC和魔物一起照进画面里吗？', Language = '从选择中看得出来，你们的关系相当好呢~~'},
	[18] = {id = 18, Type = 2, Title = '', Option = {{"是的","ff2e2e"},{"不是","00c0ff"}}, TitleDesc = '你们在冒险时，一般都喜欢牵着手吗？', Language = '这么快就做出选择啦，难道你不再想想吗？'},
	[19] = {id = 19, Type = 2, Title = '', Option = {{"制作头饰","ffe400"},{"制作装备","e400ff"}}, TitleDesc = '你们收集材料，一般是为了…', Language = '嗯哼~~没想到你会选这样的答案~~'},
	[20] = {id = 20, Type = 2, Title = '', Option = {{"小雨","ffe400"},{"晴天","00c0ff"}}, TitleDesc = '你们最喜欢的天气是…', Language = '亲，你想好了这样选的结果么~~'},
	[21] = {id = 21, Type = 2, Title = '', Option = {{"痒痒棒","ff2e2e"},{"变傻光波","e400ff"}}, TitleDesc = '如果让你捉弄一下你的另一半，你会选择用…', Language = '不错，你的品味和我果然一模一样呢~~'},
	[22] = {id = 22, Type = 2, Title = '', Option = {{"忍者猫","ff2e2e"},{"功夫猫","00c0ff"}}, TitleDesc = '如果让你形容你的另一半像哪一种B格猫星人，你觉得像…', Language = '你竟然这么说，你的小伙伴ta知道么~~'},
	[23] = {id = 23, Type = 2, Title = '', Option = {{"喜欢","ffe400"},{"不喜欢","e400ff"}}, TitleDesc = '你们拍照时喜欢使用变身卷轴拍照吗？', Language = '从选择中看得出来，你们的关系相当好呢~~'},
	[24] = {id = 24, Type = 2, Title = '', Option = {{"守护永恒的爱","ff2e2e"},{"樱之季节","00c0ff"}}, TitleDesc = '你们一起去南门听歌，你会选择播放…', Language = '这么快就做出选择啦，难道你不再想想吗？'},
	[25] = {id = 25, Type = 2, Title = '', Option = {{"红蝙蝠","ff2e2e"},{"黑狐","e400ff"}}, TitleDesc = '你的另一半在拍照时使用了变身卷轴，你觉得ta变成了…', Language = '嗯哼~~没想到你会选这样的答案~~'},
	[26] = {id = 26, Type = 2, Title = '', Option = {{"武器卡片","ff2e2e"},{"盔甲卡片","00c0ff"}}, TitleDesc = '你们幸运地一人得到了一张卡片，你觉得那是一张…', Language = '亲，你想好了这样选的结果么~~'},
	[27] = {id = 27, Type = 2, Title = '', Option = {{"装死","ffe400"},{"使用苍蝇翅膀","e400ff"}}, TitleDesc = '你们在冒险途中遇到了一只绝对打不过的魔物，你选择…', Language = '不错，你的品味和我果然一模一样呢~~'},
	[28] = {id = 28, Type = 2, Title = '', Option = {{"看板任务","ff2e2e"},{"修复裂隙","e400ff"}}, TitleDesc = '你们日常更喜欢一起执行…', Language = '你竟然这么说，你的小伙伴ta知道么~~'},
	[29] = {id = 29, Type = 2, Title = '', Option = {{"一样","ffe400"},{"不一样","00c0ff"}}, TitleDesc = '你们现在的委托看板，内容大致是一样的吗？', Language = '从选择中看得出来，你们的关系相当好呢~~'},
	[30] = {id = 30, Type = 2, Title = '', Option = {{"是的","ff2e2e"},{"不是","e400ff"}}, TitleDesc = '你们是一起参加转职考试的吗？', Language = '这么快就做出选择啦，难道你不再想想吗？'},
	[31] = {id = 31, Type = 2, Title = '', Option = {{"是的","ff2e2e"},{"不是","e400ff"}}, TitleDesc = '比起裂隙，你更喜欢接看板任务那样比较轻松的任务。', Language = '嗯哼~~没想到你会选这样的答案~~'},
	[32] = {id = 32, Type = 2, Title = '', Option = {{"会","ffe400"},{"不会","e400ff"}}, TitleDesc = '如果可以让你们重新选一次职业，你们还会选与现在相同的职业吗？', Language = '亲，你想好了这样选的结果么~~'},
	[33] = {id = 33, Type = 2, Title = '', Option = {{"一个礼物","ff2e2e"},{"一个任务","00c0ff"}}, TitleDesc = '冒险者总部交给你一封信，你认为这封信里是…', Language = '不错，你的品味和我果然一模一样呢~~'},
	[34] = {id = 34, Type = 2, Title = '', Option = {{"吉芬塔地下","ffe400"},{"斐扬洞窟","e400ff"}}, TitleDesc = '《国家地理》派你们俩去拍一个隐藏景点，你认为那个隐藏景点在…', Language = '你竟然这么说，你的小伙伴ta知道么~~'},
	[35] = {id = 35, Type = 2, Title = '', Option = {{"自己用","ff2e2e"},{"交易所","00c0ff","e400ff"}}, TitleDesc = '你得到了一把非常不错的本职业装备，你是选择自己用，还是卖去交易所？', Language = '从选择中看得出来，你们的关系相当好呢~~'},
	[36] = {id = 36, Type = 2, Title = '', Option = {{"会","ffe400"},{"不会","e400ff"}}, TitleDesc = '你们在游戏中会常常给对方发表情，做动作吗？', Language = '这么快就做出选择啦，难道你不再想想吗？'},
	[37] = {id = 37, Type = 2, Title = '', Option = {{"自由视角","ffe400"},{"高级构图","00c0ff"}}, TitleDesc = '你的另一半学习了新的冒险技能，你认为那是…', Language = '嗯哼~~没想到你会选这样的答案~~'},
	[38] = {id = 38, Type = 2, Title = '', Option = {{"NPC","ffe400"},{"景点","e400ff"}}, TitleDesc = '你们在冒险的途中，发现了一个隐藏的…', Language = '亲，你想好了这样选的结果么~~'},
	[39] = {id = 39, Type = 2, Title = '', Option = {{"工蚁","ff2e2e"},{"兵蚁","00c0ff"}}, TitleDesc = '你们在冒险的时候不小心拉了一大群魔物，你觉得这群魔物是…', Language = '不错，你的品味和我果然一模一样呢~~'},
	[40] = {id = 40, Type = 2, Title = '', Option = {{"迷藏森林","ffe400"},{"斐扬树林","e400ff"}}, TitleDesc = '如果要选一个地点与你的另一半捉迷藏，你想最好是在…', Language = '你竟然这么说，你的小伙伴ta知道么~~'},
	[41] = {id = 41, Type = 2, Title = '', Option = {{"安全帽","ff2e2e"},{"绅士帽","00c0ff"}}, TitleDesc = '一个神秘人出现在你们面前，说要送你们一顶帽子，你觉得那是顶…', Language = '从选择中看得出来，你们的关系相当好呢~~'},
	[42] = {id = 42, Type = 2, Title = '', Option = {{"天地树果实","ffe400"},{"蜂胶","e400ff"}}, TitleDesc = '塞尼亚拜托你们帮她去找一份罕见的食材，你认为那是…', Language = '这么快就做出选择啦，难道你不再想想吗？'},
	[43] = {id = 43, Type = 2, Title = '', Option = {{"有","ff2e2e"},{"没有","00c0ff"}}, TitleDesc = '你们因为某种原因，一起跳过世界线吗？', Language = '选好了可就不能反悔喽~~'},
	[44] = {id = 44, Type = 2, Title = '', Option = {{"交易所买","ffe400"},{"自己打","00c0ff"}}, TitleDesc = '如果你的另一半说要找一种材料，你会建议ta…', Language = '请记住现在的你们是牵着手做着相当有意义的一件事呢~~'},
	[45] = {id = 45, Type = 3, Title = '挑战与变化', Option = _EmptyTable, TitleDesc = '你们的关系就像是未转职的冒险者，前方是新的挑战和变化。', Language = ''},
	[46] = {id = 46, Type = 3, Title = '心心相惜', Option = _EmptyTable, TitleDesc = '固执的你们要多为对方考虑噢~别让你们的关系生出裂隙~~', Language = ''},
	[47] = {id = 47, Type = 3, Title = '守护安全感', Option = _EmptyTable, TitleDesc = '你们两人的关系就像两个初心者，等待着未展开的冒险。', Language = ''},
	[48] = {id = 48, Type = 3, Title = '变化的前奏', Option = _EmptyTable, TitleDesc = '你们的关系将迎来巨大变化，准备好花冠头饰步入神圣的殿堂吧~~', Language = ''},
	[49] = {id = 49, Type = 3, Title = '坚定不移', Option = _EmptyTable, TitleDesc = '你们的关系坚定不移，无论你们在冒险途中受到怎样的困阻，都能一起面对挑战。', Language = ''},
	[50] = {id = 50, Type = 3, Title = '密不可分', Option = _EmptyTable, TitleDesc = '你们的关系如同精炼的武器，虽然紧密，可也要小心过度束缚对方而伤害到彼此哟~', Language = ''},
	[51] = {id = 51, Type = 3, Title = '默默守候', Option = _EmptyTable, TitleDesc = '其实你们一直都默默守护着彼此，就差对方一个回头。', Language = ''},
	[52] = {id = 52, Type = 3, Title = '宿命伴侣', Option = _EmptyTable, TitleDesc = '你与ta就是，我要你出现在我景点照片的每一页。', Language = ''},
	[53] = {id = 53, Type = 3, Title = '默契和谐', Option = _EmptyTable, TitleDesc = '你们珍惜彼此如同珍惜牵着手的每分每秒，即使不打怪，也可以腻在一起看美丽风景。', Language = ''},
	[54] = {id = 54, Type = 3, Title = '彼此依赖', Option = _EmptyTable, TitleDesc = '你们的关系就像一个输出和一个坚实的后盾，在前英勇杀敌的那个你也要时常顾忌后方支持你的ta噢~', Language = ''},
	[55] = {id = 55, Type = 3, Title = '俏皮陪伴', Option = _EmptyTable, TitleDesc = '古灵精怪的你们，就是我对你使用变傻光波，你还我恶作剧魔棒，每天都充满乐趣。', Language = ''},
	[56] = {id = 56, Type = 3, Title = '稳定成长', Option = _EmptyTable, TitleDesc = '你们两人的关系就如同你们的冒险成长一般，稳定长久~', Language = ''},
	[57] = {id = 57, Type = 3, Title = '暖心浪漫', Option = _EmptyTable, TitleDesc = '你们就是对方的暖心料理，总能治愈你们在冒险途中的身和心。', Language = ''},
	[58] = {id = 58, Type = 3, Title = '危险关系', Option = _EmptyTable, TitleDesc = '你们的关系就像摇摆不定的摩卡，是时候稳定下来了噢~', Language = ''},
	[59] = {id = 59, Type = 3, Title = '甜蜜吸引', Option = _EmptyTable, TitleDesc = '优柔寡断的你们仿佛走进了迷藏森林，手牵手一起找出路吧~', Language = ''},
}

Table_Valentine_fields = { "id","Type","Title","Option","TitleDesc","Language",}
return Table_Valentine