--md5:6bbf8118a7c4ac20147174852223ee9d
Table_ItemAccess = {
	[1] = {id = 1, ItemName = '信仰之证', ItemID = 5034, Name = '瓦尔基里', Icon = 'Guild', GotoMode = _EmptyTable, Desc = '可在公会领地瓦尔基里处使用', ErrorMsgEvent = _EmptyTable},
	[3] = {id = 3, ItemName = '银质勋章', ItemID = 5260, Name = '公会副本', Icon = 'Guild', GotoMode = _EmptyTable, Desc = '可在公会领地废墟入口处使用', ErrorMsgEvent = _EmptyTable},
	[4] = {id = 4, ItemName = '金质勋章', ItemID = 5261, Name = '阿萨神碑', Icon = 'Rune', GotoMode = _EmptyTable, Desc = '可点亮阿萨神碑的符文', ErrorMsgEvent = _EmptyTable},
	[5] = {id = 5, ItemName = '冒险的终点', ItemID = 4000, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[6] = {id = 6, ItemName = '历战的勇者', ItemID = 4001, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[7] = {id = 7, ItemName = '塔之下', ItemID = 4002, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[8] = {id = 8, ItemName = '斐扬的回忆', ItemID = 4003, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[9] = {id = 9, ItemName = '守护永恒的爱', ItemID = 4004, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[10] = {id = 10, ItemName = '樱之季节', ItemID = 4005, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[11] = {id = 11, ItemName = '十三月圣诞节', ItemID = 4006, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[12] = {id = 12, ItemName = '艾尔贝塔', ItemID = 4007, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[13] = {id = 13, ItemName = '梦想家的梦', ItemID = 4008, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[14] = {id = 14, ItemName = '春天生活', ItemID = 4009, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[15] = {id = 15, ItemName = '你在坠落', ItemID = 4010, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[16] = {id = 16, ItemName = '别来惹我', ItemID = 4011, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[17] = {id = 17, ItemName = '鲸鱼的梦', ItemID = 4012, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[18] = {id = 18, ItemName = '我想念你', ItemID = 4013, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[19] = {id = 19, ItemName = '宝贝别哭', ItemID = 4014, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[20] = {id = 20, ItemName = '白色圣诞', ItemID = 4015, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[21] = {id = 21, ItemName = '银铃', ItemID = 4016, Name = '音乐盒', Icon = 'yinyuehui', GotoMode = {12}, Desc = '可在南门音乐盒处使用', ErrorMsgEvent = _EmptyTable},
	[22] = {id = 22, ItemName = '遗忘之水', ItemID = 5044, Name = '梅菲尔林瑟', Icon = 'Skill', GotoMode = {501}, Desc = '可在梅菲尔林瑟处重置冒险技能', ErrorMsgEvent = _EmptyTable},
	[23] = {id = 23, ItemName = '轮回之石', ItemID = 12353, Name = '雷诺里瑟', Icon = 'forever', GotoMode = {502}, Desc = '可在雷诺里瑟处重置素质点', ErrorMsgEvent = _EmptyTable},
	[24] = {id = 24, ItemName = '莫拉币', ItemID = 135, Name = '猫小友', Icon = 'item_135', GotoMode = {62}, Desc = '可在猫小友处使用', ErrorMsgEvent = _EmptyTable},
	[25] = {id = 25, ItemName = '友情之证', ItemID = 147, Name = '猫小友', Icon = 'item_147', GotoMode = {62}, Desc = '可在猫小友处使用', ErrorMsgEvent = _EmptyTable},
	[26] = {id = 26, ItemName = '卡普拉传送服务券', ItemID = 5040, Name = '卡普拉', Icon = '', GotoMode = {980,981,982,983,984,985,986}, Desc = '卡普拉服务人员处使用', ErrorMsgEvent = _EmptyTable},
	[27] = {id = 27, ItemName = '卡普拉仓库服务券', ItemID = 5041, Name = '卡普拉 ', Icon = '', GotoMode = {980,981,982,983,984,985,986}, Desc = '卡普拉服务人员处使用', ErrorMsgEvent = _EmptyTable},
	[29] = {id = 29, ItemName = '幻想之证·银', ItemID = 5035, Name = '摩天轮', Icon = '', GotoMode = {64}, Desc = '可在哥布林森林路德维希处使用', ErrorMsgEvent = _EmptyTable},
	[30] = {id = 30, ItemName = '银河的结晶', ItemID = 710001, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[32] = {id = 32, ItemName = '美发体验券·自由', ItemID = 710029, Name = '发型', Icon = '', GotoMode = {961,962,963,964,965,966}, Desc = '可在美发师处使用', ErrorMsgEvent = _EmptyTable},
	[33] = {id = 33, ItemName = '染发剂·极彩', ItemID = 710030, Name = '发型', Icon = '', GotoMode = {961,962,963,964,965,966}, Desc = '可在美发师处使用', ErrorMsgEvent = _EmptyTable},
	[34] = {id = 34, ItemName = '神秘佣兵券', ItemID = 710031, Name = '佣兵', Icon = '', GotoMode = {65,66,67,68}, Desc = '可在猫猫佣兵团处使用', ErrorMsgEvent = _EmptyTable},
	[35] = {id = 35, ItemName = '星之碎片·白羊座', ItemID = 710002, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[36] = {id = 36, ItemName = '星之碎片·金牛座', ItemID = 710003, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[37] = {id = 37, ItemName = '星之碎片·双子座', ItemID = 710004, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[38] = {id = 38, ItemName = '星之碎片·巨蟹座', ItemID = 710005, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[39] = {id = 39, ItemName = '星之碎片·狮子座', ItemID = 710006, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[40] = {id = 40, ItemName = '星之碎片·处女座', ItemID = 710007, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[41] = {id = 41, ItemName = '星之碎片·天秤座', ItemID = 710008, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[42] = {id = 42, ItemName = '星之碎片·天蝎座', ItemID = 710009, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[43] = {id = 43, ItemName = '星之碎片·人马座', ItemID = 710010, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[44] = {id = 44, ItemName = '星之碎片·摩羯座', ItemID = 710011, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[45] = {id = 45, ItemName = '星之碎片·宝瓶座', ItemID = 710012, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[46] = {id = 46, ItemName = '星之碎片·双鱼座', ItemID = 710013, Name = '占卜', Icon = '', GotoMode = {72}, Desc = '可在普隆德拉贝尔丹迪处使用', ErrorMsgEvent = _EmptyTable},
	[47] = {id = 47, ItemName = '乐园币', ItemID = 110, Name = '微笑小姐', Icon = '', GotoMode = {6,16,17,18,23,33,301,302}, Desc = '可在微笑小姐处使用', ErrorMsgEvent = _EmptyTable},
	[49] = {id = 49, ItemName = '巅峰碎片', ItemID = 5550, Name = '爱丽丝·芙娜', Icon = '', GotoMode = {1002}, Desc = '可以在公会领地爱丽丝·芙娜处使用', ErrorMsgEvent = _EmptyTable},
	[50] = {id = 50, ItemName = '婚礼邀请函', ItemID = 6056, Name = '幸福小姐', Icon = '', GotoMode = {1003}, Desc = '可以在幸福小姐处使用', ErrorMsgEvent = _EmptyTable},
}
Table_ItemAccess_fields = { "id","ItemName","ItemID","Name","Icon","GotoMode","Desc","SuccessMsgID","ErrorMsgEvent",}
return Table_ItemAccess
