--md5:0c419ad41627a9d18febec4ecf4d5df1
Table_Body_WW = { 
	[301] = {id = 301, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_M1', AvatarBody = 'Body_Black_Knight_M1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[302] = {id = 302, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_M2', AvatarBody = 'Body_Black_Knight_M2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[303] = {id = 303, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_M3', AvatarBody = 'Body_Black_Knight_M3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[304] = {id = 304, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_M4', AvatarBody = 'Body_Black_Knight_M4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[311] = {id = 311, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_F1', AvatarBody = 'Body_Black_Knight_F1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[312] = {id = 312, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_F2', AvatarBody = 'Body_Black_Knight_F2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[313] = {id = 313, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_F3', AvatarBody = 'Body_Black_Knight_F3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[314] = {id = 314, AssesoriesDiePoint = _EmptyTable, Texture = 'Black_Knight_F4', AvatarBody = 'Body_Black_Knight_F4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[321] = {id = 321, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_M1', AvatarBody = 'Body_Beach_M1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[322] = {id = 322, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_M2', AvatarBody = 'Body_Beach_M2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[323] = {id = 323, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_M3', AvatarBody = 'Body_Beach_M3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[324] = {id = 324, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_M4', AvatarBody = 'Body_Beach_M4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[331] = {id = 331, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_F1', AvatarBody = 'Body_Beach_F1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[332] = {id = 332, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_F2', AvatarBody = 'Body_Beach_F2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[333] = {id = 333, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_F3', AvatarBody = 'Body_Beach_F3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[334] = {id = 334, AssesoriesDiePoint = _EmptyTable, Texture = 'Beach_F4', AvatarBody = 'Body_Beach_F4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[1524] = {id = 1524, AssesoriesDiePoint = _EmptyTable, Texture = 'Turkey_food', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[10330] = {id = 10330, AssesoriesDiePoint = _EmptyTable, Texture = 'Rudolf_pet', AvatarBody = '', ShowWeaponType = 2, PaintColor = _EmptyTable, HeadIcon = ''},
	[10331] = {id = 10331, AssesoriesDiePoint = _EmptyTable, Texture = 'Rudolf_pet_10', AvatarBody = '', ShowWeaponType = 2, PaintColor = _EmptyTable, HeadIcon = ''},
	[461] = {id = 461, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_M1', AvatarBody = 'Body_Navidad_M1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[462] = {id = 462, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_M2', AvatarBody = 'Body_Navidad_M2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[463] = {id = 463, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_M3', AvatarBody = 'Body_Navidad_M3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[464] = {id = 464, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_M4', AvatarBody = 'Body_Navidad_M4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[471] = {id = 471, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_F1', AvatarBody = 'Body_Navidad_F1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[472] = {id = 472, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_F2', AvatarBody = 'Body_Navidad_F2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[473] = {id = 473, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_F3', AvatarBody = 'Body_Navidad_F3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[474] = {id = 474, AssesoriesDiePoint = _EmptyTable, Texture = 'Navidad_F4', AvatarBody = 'Body_Navidad_F4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[1611] = {id = 1611, AssesoriesDiePoint = _EmptyTable, Texture = 'Tai_car_1', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[1612] = {id = 1612, AssesoriesDiePoint = _EmptyTable, Texture = 'Tai_car_2', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[1613] = {id = 1613, AssesoriesDiePoint = _EmptyTable, Texture = 'Tai_car_3', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[1614] = {id = 1614, AssesoriesDiePoint = _EmptyTable, Texture = 'Tai_car_4', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[1615] = {id = 1615, AssesoriesDiePoint = _EmptyTable, Texture = 'Tai_car_4a', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[1616] = {id = 1616, AssesoriesDiePoint = _EmptyTable, Texture = 'Tai_car_4b', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[1617] = {id = 1617, AssesoriesDiePoint = _EmptyTable, Texture = 'Tai_car_4c', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[10287] = {id = 10287, AssesoriesDiePoint = _EmptyTable, Texture = 'Cat_pet3', AvatarBody = '', ShowWeaponType = 2, PaintColor = _EmptyTable, HeadIcon = ''},
	[1600] = {id = 1600, AssesoriesDiePoint = _EmptyTable, Texture = 'Cat_face', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
	[491] = {id = 491, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_M1', AvatarBody = 'Body_Archangel_M1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[492] = {id = 492, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_M2', AvatarBody = 'Body_Archangel_M2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[493] = {id = 493, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_M3', AvatarBody = 'Body_Archangel_M3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[494] = {id = 494, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_M4', AvatarBody = 'Body_Archangel_M4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[501] = {id = 501, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_F1', AvatarBody = 'Body_Archangel_F1', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[502] = {id = 502, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_F2', AvatarBody = 'Body_Archangel_F2', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[503] = {id = 503, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_F3', AvatarBody = 'Body_Archangel_F3', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[504] = {id = 504, AssesoriesDiePoint = _EmptyTable, Texture = 'Archangel_F4', AvatarBody = 'Body_Archangel_F4', Feature = 1, ShowWeaponType = 3, PaintColor = _EmptyTable, HeadIcon = ''},
	[1478] = {id = 1478, AssesoriesDiePoint = _EmptyTable, Texture = 'Pumpkinpc', AvatarBody = '', PaintColor = _EmptyTable, HeadIcon = ''},
}

Table_Body_WW_fields = { "id","AssesoriesDiePoint","Texture","AvatarBody","Feature","AlwaysAnimate","ShowWeaponType","DefaultColor","PaintColor","HeadIcon",}
return Table_Body_WW