PrepDataProxyCommand = class("PrepDataProxyCommand",pm.SimpleCommand)

SceneProxy = autoImport("SceneProxy")
UserProxy = autoImport("UserProxy")
autoImport("SceneObjectProxy")
autoImport("SceneTrapProxy")

BagProxy = autoImport("BagProxy")
UIProxy = autoImport("UIProxy")
MyselfProxy = autoImport("MyselfProxy")
AccountProxy = autoImport("AccountProxy")
autoImport("SkillProxy")
autoImport("ShortCutProxy")
autoImport("SceneItemProxy")

autoImport('QuestProxy')
autoImport('GuideProxy')
autoImport("MsgParserProxy")
autoImport("DungeonProxy")
autoImport("QuickUseProxy")
autoImport("BlackSmithProxy")
autoImport("TeamProxy")
autoImport("GuildProxy")
autoImport("PostProxy")
autoImport("UIManagerProxy")
autoImport("UIStackProxy")
autoImport("PanelProxy")
autoImport("ResolveEquipProxy")
autoImport("SceneCarrierProxy")
autoImport("SceneFilterProxy")
autoImport("HappyShopProxy")
autoImport("WorldMapProxy")
autoImport("SceneTriggerProxy")
autoImport("ChatRoomProxy")
autoImport("ChatRoomNetProxy")
autoImport("RedTipProxy")
autoImport("ChatZoomProxy")
autoImport("CDProxy")
autoImport("RepositoryViewProxy")
autoImport("ProfessionProxy")
autoImport("AstrolabeProxy")
autoImport("EndlessTowerProxy")
autoImport("SimulateSkillProxy")
autoImport("SealProxy")
autoImport("EquipRepairProxy")
autoImport("GainWayTipProxy")
autoImport("InstituteChallengeProxy")
autoImport("ShopSaleProxy")
autoImport("AdventureDataProxy")
autoImport("FriendProxy")
autoImport("ShopMallProxy")
autoImport("LocalSaveProxy")
autoImport("DojoProxy")
autoImport("ToolsProxy")
autoImport("SceneAINpcProxy")
autoImport("EquipMakeProxy")
autoImport("EquipRecoverProxy")
autoImport("ChangeZoneProxy")
autoImport("ChangeHeadProxy")
autoImport("ShopDressingProxy")
autoImport("ShareAnnounceQuestProxy")
autoImport("AuguryProxy")
autoImport("PvpProxy");
autoImport("BusinessmanMakeProxy")
autoImport("AdventureAchieveProxy")
autoImport("CardMakeProxy")
autoImport("ShopProxy")
autoImport("TitleProxy")
autoImport("FoodProxy")
autoImport("PhotoDataProxy")
autoImport("StarProxy")
autoImport("LotteryProxy")
autoImport("PetProxy")
autoImport("PetAdventureProxy")
autoImport("ActivityDataProxy")
autoImport("AuctionProxy")
autoImport("TutorProxy")
autoImport("GvgProxy");
autoImport("SuperGvgProxy");
autoImport("QuickBuyProxy")
autoImport("QuotaCardProxy")
autoImport("ActivityEventProxy")
autoImport("CreatureSkillProxy")
autoImport("GuildBuildingProxy")
autoImport("ArtifactProxy")
autoImport("GuildTreasureProxy")
autoImport("WeddingProxy")
autoImport("PetWorkSpaceProxy")
autoImport("ServantRecommendProxy")
autoImport("MultiProfessionSaveProxy")
autoImport("BranchInfoSaveProxy")
autoImport("SaveInfoProxy")
autoImport("GVoiceProxy")
autoImport("EnchantTransferProxy")
autoImport("BoothProxy")
autoImport("PushProxy")
---refactory
autoImport("NSceneNpcProxy")
autoImport("NSceneUserProxy")
autoImport("NSceneEffectProxy")
autoImport("NScenePetProxy")
---refactory


-- autoImport("CSVReader")

function PrepDataProxyCommand:execute(noti)
	GameFacade.Instance:registerProxy(AccountProxy.new())
	GameFacade.Instance:registerProxy(PanelProxy.new())
	GameFacade.Instance:registerProxy(SceneProxy.new())
	GameFacade.Instance:registerProxy(UserProxy.new())
	GameFacade.Instance:registerProxy(SceneTriggerProxy.new())
	GameFacade.Instance:registerProxy(BagProxy.new())
	-- GameFacade.Instance:registerProxy(UIProxy.new())
	GameFacade.Instance:registerProxy(UIManagerProxy.new())
	GameFacade.Instance:registerProxy(UIStackProxy.new())
	GameFacade.Instance:registerProxy(MyselfProxy.new())
	GameFacade.Instance:registerProxy(SkillProxy.new())
	GameFacade.Instance:registerProxy(ShortCutProxy.new())
	GameFacade.Instance:registerProxy(QuestProxy.new())
	GameFacade.Instance:registerProxy(ShareAnnounceQuestProxy.new())
	GameFacade.Instance:registerProxy(GuideProxy.new())
	GameFacade.Instance:registerProxy(MsgParserProxy.new())
	GameFacade.Instance:registerProxy(SceneItemProxy.new())
	GameFacade.Instance:registerProxy(DungeonProxy.new())
	GameFacade.Instance:registerProxy(QuickUseProxy.new())
	GameFacade.Instance:registerProxy(BlackSmithProxy.new())
	GameFacade.Instance:registerProxy(TeamProxy.new())
	GameFacade.Instance:registerProxy(GuildProxy.new())
	GameFacade.Instance:registerProxy(PostProxy.new())
	GameFacade.Instance:registerProxy(SceneTrapProxy.new())
	GameFacade.Instance:registerProxy(ResolveEquipProxy.new())
	GameFacade.Instance:registerProxy(SceneCarrierProxy.new())
	GameFacade.Instance:registerProxy(SceneFilterProxy.new())
	GameFacade.Instance:registerProxy(HappyShopProxy.new())
	GameFacade.Instance:registerProxy(WorldMapProxy.new())
	GameFacade.Instance:registerProxy(ChatRoomProxy.new())
	GameFacade.Instance:registerProxy(ChatRoomNetProxy.new())
	GameFacade.Instance:registerProxy(RedTipProxy.new())
	GameFacade.Instance:registerProxy(ChatZoomProxy.new())
	GameFacade.Instance:registerProxy(CDProxy.new())
	GameFacade.Instance:registerProxy(RepositoryViewProxy.new())
	GameFacade.Instance:registerProxy(ProfessionProxy.new())
	GameFacade.Instance:registerProxy(AstrolabeProxy.new())
	GameFacade.Instance:registerProxy(EndlessTowerProxy.new())
	GameFacade.Instance:registerProxy(SimulateSkillProxy.new())
	GameFacade.Instance:registerProxy(SealProxy.new())
	GameFacade.Instance:registerProxy(EquipRepairProxy.new())
	GameFacade.Instance:registerProxy(GainWayTipProxy.new())
	GameFacade.Instance:registerProxy(InstituteChallengeProxy.new())
	GameFacade.Instance:registerProxy(ShopSaleProxy.new())
	GameFacade.Instance:registerProxy(AdventureDataProxy.new())
	GameFacade.Instance:registerProxy(FriendProxy.new())
	GameFacade.Instance:registerProxy(ShopMallProxy.new())
	GameFacade.Instance:registerProxy(LocalSaveProxy.new())
	GameFacade.Instance:registerProxy(DojoProxy.new())
	GameFacade.Instance:registerProxy(ToolsProxy.new())
	GameFacade.Instance:registerProxy(SceneAINpcProxy.new())
	GameFacade.Instance:registerProxy(EquipMakeProxy.new())
	GameFacade.Instance:registerProxy(EquipRecoverProxy.new())
	GameFacade.Instance:registerProxy(ChangeZoneProxy.new())
	GameFacade.Instance:registerProxy(ChangeHeadProxy.new())
	GameFacade.Instance:registerProxy(ShopDressingProxy.new())
	GameFacade.Instance:registerProxy(AuguryProxy.new())
	GameFacade.Instance:registerProxy(PvpProxy.new());
	GameFacade.Instance:registerProxy(BusinessmanMakeProxy.new())
	GameFacade.Instance:registerProxy(CardMakeProxy.new())
	GameFacade.Instance:registerProxy(ShopProxy.new())
	GameFacade.Instance:registerProxy(TitleProxy.new())
	GameFacade.Instance:registerProxy(FoodProxy.new())
	GameFacade.Instance:registerProxy(PhotoDataProxy.new())
	GameFacade.Instance:registerProxy(AdventureAchieveProxy.new())
	GameFacade.Instance:registerProxy(StarProxy.new())
	GameFacade.Instance:registerProxy(LotteryProxy.new())
	GameFacade.Instance:registerProxy(PetProxy.new())
	GameFacade.Instance:registerProxy(PetAdventureProxy.new())
	GameFacade.Instance:registerProxy(ActivityDataProxy.new())
	GameFacade.Instance:registerProxy(AuctionProxy.new())
	GameFacade.Instance:registerProxy(TutorProxy.new())
	GameFacade.Instance:registerProxy(GvgProxy.new())
	GameFacade.Instance:registerProxy(QuickBuyProxy.new())
	GameFacade.Instance:registerProxy(QuotaCardProxy.new())
	GameFacade.Instance:registerProxy(ActivityEventProxy.new())
	GameFacade.Instance:registerProxy(CreatureSkillProxy.new())
	GameFacade.Instance:registerProxy(GuildBuildingProxy.new())
	GameFacade.Instance:registerProxy(ArtifactProxy.new())
	GameFacade.Instance:registerProxy(GuildTreasureProxy.new())
	GameFacade.Instance:registerProxy(WeddingProxy.new())
	GameFacade.Instance:registerProxy(PetWorkSpaceProxy.new())
	GameFacade.Instance:registerProxy(ServantRecommendProxy.new())
	GameFacade.Instance:registerProxy(MultiProfessionSaveProxy.new())
	GameFacade.Instance:registerProxy(BranchInfoSaveProxy.new())
	GameFacade.Instance:registerProxy(SaveInfoProxy.new())
	GameFacade.Instance:registerProxy(SuperGvgProxy.new())
	GameFacade.Instance:registerProxy(GVoiceProxy.new())
	GameFacade.Instance:registerProxy(EnchantTransferProxy.new())
	GameFacade.Instance:registerProxy(BoothProxy.new())
	GameFacade.Instance:registerProxy(PushProxy.new())
---refactory
	GameFacade.Instance:registerProxy(NSceneNpcProxy.new())
	GameFacade.Instance:registerProxy(NSceneUserProxy.new())
	GameFacade.Instance:registerProxy(NSceneEffectProxy.new())
	GameFacade.Instance:registerProxy(NScenePetProxy.new())
	
---refactory

	-- BagProxy.Instance:TestOutPut()
	-- BagProxy.Instance:TestSetData("test1",10)
	-- BagProxy.Instance:TestOutPut()
	-- BagProxy.Instance:TestAddData("test1",2)
	-- BagProxy.Instance:TestOutPut()

	-- UserProxy.Instance:Test()
	-- local start = os.clock()
	-- self:Test()
	-- print("read csv string " .. (os.clock() - start));

	-- start = os.clock()
	-- self:Test2()
	-- print("read csv bytes " .. (os.clock() - start));

	-- start = os.clock()
	-- self:Test3()
	-- print("test load big lua " .. (os.clock() - start));

	-- print("test remove")
	-- BagProxy.Instance:TestSetData("test2",nil)
	-- BagProxy.Instance:TestOutPut()
end