ZhString = 
{
	--符号
	Colon = "：",

	ChinaNumber = {
		"一","二","三","四","五","六","七","八","九","十"
	},

	Game_FullScreen = "全屏",

	HoursFormat = "%s小时",
	MinutesFormat = "%s分钟",
	SecondsFormat = "%s秒",
	StartGamePanel_NoChooseServer = "未选择服务器",
	StartGamePanel_ChooseServerPrompt = "请选择服务器",
	StartGamePanel_InputPrompt = "请输入账号",
	StartGamePanel_InputErrorPrompt = "请输入大于100的数字",
	StartGamePanel_SelectTipLabel = "点击选服",
	StartGamePanel_Version = "客户端版本:%s  资源版本:%s",
	StartGamePanel_WaitingLabel = "o( =•ω•= )m正在连接服务器",
	StartGamePanel_AgreetmentLabel = "我已经仔细阅读并同意 [c][93d8ff]心动网络游戏许可及服务协议[-][/c]",
	StartGamePanel_AgreetmentContent = "　　[c][000000]《游戏许可及服务协议》（以下简称“本协议”）由您与心动网络共同缔结，本协议具有合同效力。请您务必审慎阅读、充分理解各条款内容，特别是免除或者限制心动网络责任的条款（该等条款通常含有“不负任何责任”、“无义务”、“不保证”等词汇）、对用户权利进行限制的条款（该等条款通常含有“不得”、“不应”、“无权”等词汇）、约定争议解决方式和司法管辖的条款，以及开通或使用某项服务的单独协议。前述限制、免责及争议解决方式和管辖条款可能以黑体加粗或其他合理方式提示您注意。[-][/c]\n　　[c][000000]如果您未满18周岁，请在监护人的陪同下阅读本协议，并特别注意未成年人使用条款。[-][/c]\n　　[c][000000]一、定义[-][/c]\n　　1.1 [c][000000]本协议：[-][/c]指本协议正文、[c][000000]游戏规则[-][/c]及其修订版本。上述内容一经正式发布，即为本协议不可分割的组成部分。[c][000000]本协议同时还包括文化部根据《网络游戏管理暂行办法》（文化部令第49号）制定的《网络游戏服务格式化协议必备条款》。[-][/c]\n　　1.2 [c][000000]游戏规则：[-][/c]指心动网络不时发布并修订的关于心动游戏软件及心动游戏服务的用户守则、玩家条例、游戏公告及通知等内容。\n　　1.3 [c][000000]心动网络：[-][/c]指向您提供心动游戏软件及心动游戏服务的心动网络股份有限公司，在本协议中简称为“心动或[c][000000]心动网络”。[-][/c]\n　　1.4 [c][000000]心动游戏软件：[-][/c]指由心动网络负责运营的游戏产品的统称，包括计算机客户端游戏、网页游戏、HTML5游戏（H5游戏）、移动终端游戏、电视端游戏以及其他可在不同操作系统及设备终端上运行操作的产品版本，并包括该相关的网络服务器、网站、电子媒体、印刷材料、软件及相关文档。\n　　1.5 [c][000000]心动游戏服务：[-][/c]指心动网络向您提供的，与心动游戏软件相关的各项在线运营服务，并包括心动游戏软件本身。\n　　1.6 [c][000000]您：[-][/c]又称[c][000000]“玩家”[-][/c]或[c][000000]“用户”[-][/c]，指被授权使用心动游戏服务的自然人。\n　　1.7 [c][000000]游戏数据：[-][/c]指您在使用心动游戏服务过程中产生的被服务器记录的各种数据，包括游戏日志、安全日志等数据。\n　　[c][000000]二、协议的变更和生效[-][/c]\n　　2.1 心动网络有权在必要时变更本协议条款，并在相关页面进行通知。您可以在心动游戏服务相关页面查阅最新版本的协议条款。\n　　2.2 本协议条款变更后，如果您继续使用心动游戏服务，即视为您已接受变更后的协议。如果您不接受变更后的协议，应当停止使用心动游戏服务。\n　　三、[c][000000]游戏账号[-][/c]\n　　3.1 您如果需要使用和享受心动游戏服务，则您需要将您享有使用权的心动网络账号或心动网络认可的其他合作方账号作为游戏账号，并按照《网络游戏管理暂行规定》及文化部《网络游戏服务格式化协议必备条款》的要求，登录实名注册系统并进行实名注册。您进行实名注册时，应提供有关您本人真实、合法、准确、有效的身份信息及其他相关信息，且不得以他人身份资料进行实名注册。否则，心动网络有权终止为您提供心动游戏服务，并有权对您的游戏账号采取包括但不限于警告、限制或禁止使用游戏帐号全部或部分功能、删除游戏账号及游戏数据、删除相关信息、游戏账号封禁（以下有时简称“封号”）直至注销暂的处理措施（为描述方便，以下有时也将该等处理措施称为“处罚”），因此造成的一切后果由您自行承担。\n　　3.2 [c][000000]您充分理解并同意：心动网络会按照国家相关要求将您的实名注册信息运用于防沉迷系统之中，即心动网络可能会根据您的实名注册信息判断您是否年满18周岁，从而决定是否对您的游戏账号予以防沉迷限制。[-][/c]\n　　3.3 [c][000000]您应妥善保管您的游戏账号，包括妥善保管您游戏账号所对应的密码；您应在知晓您的游戏账号被盗用后第一时间通知心动网络。[-][/c]\n　　3.4 [c][000000]您充分理解并同意，为提高心动游戏服务的安全水平，心动网络有权将有关技术或软件应用到心动游戏服务中，但心动网络不保证这些安全保障措施可以完全杜绝游戏账号被他人窃取或丢失的风险。[-][/c]\n　　3.5 [c][000000]您充分理解并同意，若心动网络依照相关业务规则限制、冻结或终止您的游戏账号的使用，可能会导致您游戏账号下游戏数据及相关信息被删除，以及相关权益的丧失，该损失由您自行承担，对此心动网络不承担任何责任。[-][/c]\n　　3.6 [c][000000]您充分理解并同意，为高效利用服务器资源，如果您长期未使用游戏账号登录心动游戏软件，心动网络有权视需要，在提前通知的情况下，对该账号及其账号下的游戏数据及相关信息采取删除等处置措施，上述处置可能导致您对该游戏账号下相关权益的丧失，对此心动网络不承担任何责任。[-][/c]\n　　[c][000000]四、用户信息收集、使用及保护[-][/c]\n　　4.1 您同意并授权心动网络为履行本协议之目的收集您的用户信息，这些信息包括您在实名注册系统中注册的信息、您游戏账号下的游戏数据以及其他您在使用心动游戏服务的过程中向心动网络提供或心动网络基于安全、用户体验优化等考虑而需收集的信息，心动网络对您的用户信息的收集将遵循相关法律的规定。\n　　4.2 [c][000000]您充分理解并同意：心动网络或其合作的第三方可以根据您的用户信息，通过短信、电话、邮件等各种方式向您提供关于心动游戏服务的活动信息、推广信息等各类信息。[-][/c]\n　　4.3 [c][000000]保护用户信息及隐私是心动网络的一项基本原则。除本协议另有规定外，心动游戏服务对用户信息收集、使用及保护等将遵循心动网络统一公布的相关隐私政策。[-][/c]\n　　五、[c][000000]心动游戏服务[-][/c]\n　　5.1 在您遵守本协议及相关法律法规的前提下，心动网络给予您一项个人的、不可转让及非排他性的许可，以使用心动游戏服务。您仅可为非商业目的使用心动游戏服务，包括：\n　　（1）接收、下载、安装、启动、升级、登录、显示、运行和/或截屏心动游戏软件；\n　　（2）创建游戏角色，设置网名，查阅游戏规则、用户个人资料、游戏对局结果，开设游戏房间、设置游戏参数，在游戏中购买、使用游戏道具、游戏装备、游戏币等，使用聊天功能、社交分享功能；\n　　（3）使用心动游戏软件支持并允许的其他某一项或几项功能。\n　　5.2 [c][000000]您在使用心动游戏服务过程中不得未经心动网络许可以任何方式录制或向他人传播心动游戏服务内容，包括不得利用任何第三方软件进行网络传播等。[-][/c]\n　　5.3 在心动网络所提供游戏服务存在提供心动游戏软件的情况下，您在使用心动游戏服务时还应符合本协议第六条关于软件许可的规定。\n　　5.4 本条及本协议其他条款未明示授权的其他一切权利仍由心动网络保留，您在行使这些权利时须另外取得心动网络的书面许可。\n　　5.5 如果心动网络发现或收到他人举报或投诉用户违反本协议约定的，心动网络有权不经通知随时对相关内容进行删除，并视行为情节对违规游戏账号处以包括但不限于警告、限制或禁止使用全部或部分功能、游戏账号封禁直至注销的处罚，并公告处理结果。\n　　5.6 您充分理解并同意，心动网络有权依合理判断对违反有关法律法规或本协议规定的行为进行处罚，对违法违规的任何用户采取适当的法律行动，并依据法律法规保存有关信息向有关部门报告等，用户应独自承担由此而产生的一切法律责任。\n　　5.7 您充分理解并同意，因您违反本协议或相关服务条款的规定，导致或产生第三方主张的任何索赔、要求或损失，您应当独立承担责任；心动网络因此遭受损失的，您也应当一并赔偿。\n　　5.8 [c][000000]您充分理解并同意：游戏道具、游戏装备、游戏币等是心动网络所提供心动游戏服务的一部分，心动网络在此许可您依本协议而获得其使用权。您购买、使用游戏道具、游戏装备、游戏币等应遵循本协议、游戏具体规则的要求；同时，游戏道具、游戏装备、游戏币等可能受到一定有效期限的限制，若您在规定的有效期内未使用，除不可抗力或可归责于心动网络的原因外，一旦有效期届满，将会自动失效。[-][/c]\n　　[c][000000]您充分理解并同意：为更好地向用户提供心动游戏服务，心动网络有权对您购买或正在使用的游戏装备及其他游戏道具的性能及相关数值设置等作出调整、更新或优化。且如心动网络做出相应调整、更新或优化的，您同意不会因此追究心动网络的任何法律责任。[-][/c]\n　　5.9 [c][000000]您充分理解并同意：为营造公平、健康的游戏环境，在您使用心动游戏服务的过程中，心动网络有权通过技术手段了解您终端设备的随机存储内存以及与心动游戏服务同时运行的相关程序。一经发现有任何未经授权的、危害心动网络正常提供游戏服务的相关程序，心动网络将收集所有与此有关的信息并采取合理措施予以打击。[-][/c]\n　　5.10 您充分理解并同意：为了保证您及其他用户的游戏速度，心动网络有权定期转移或者清除服务器上存储的一些过往的游戏数据。\n　　5.11 心动网络将按照相关法律法规和本协议的规定，采取切实有效的措施保护未成年人在使用心动游戏服务过程中的合法权益，包括可能采取技术措施、禁止未成年人接触不适宜的游戏或者游戏功能、限制未成年人的游戏时间、预防未成年人沉迷网络。作为游戏规则的一部分，心动网络还将在适当位置发布相关游戏用户指引和警示说明，包括游戏内容介绍、正确使用游戏的方法以及防止危害发生的方法。所有未成年人用户都应在监护人的指导下仔细阅读并遵照执行这些指引和说明；其他玩家在使用心动游戏服务的过程中应避免发布、产生任何有损未成年人身心健康的内容，共同营造健康游戏环境。\n　　[c][000000]5.12 为了正常运行游戏服务器，心动网络需要定期对游戏服务器进行停机维护或针对突发事件进行紧急停机维护；发生以下一种或多种情形时，心动网络有权中止或中断游戏服务器所提供的全部或部分服务，对因此而产生的不便或损害，心动网络对您或第三人均不承担任何责任：[-][/c]\n　　[c][000000]（1）定期检查或施工，更新软硬件等，心动网络有权暂停服务，但心动网络会尽快完成维护、更新工作；[-][/c]\n　　[c][000000]（2）游戏服务器遭受损害，无法正常运作； [-][/c]\n　　[c][000000]（3）突发性的软硬件设备与电子通信设备故障；[-][/c]\n　　[c][000000]（4）网络提供商线路或其他故障；[-][/c] \n　　[c][000000]（5）在紧急情况下依照法律规定或为您或他人的人身安全；[-][/c]\n　　[c][000000]（6）第三方原因或其他不可抗力的情形。[-][/c]\n　　5.13 [c][000000]如果您未满18周岁的，为保障您的合法权益，心动网络有权依据国家有关法律法规及政策规定、本协议其他条款规定或根据您监护人的合理要求采取以下一种或多种措施：[-][/c]\n　　[c][000000]（1）将与您游戏相关的信息（包括但不限于您游戏帐号的登录信息、充值流水信息等）提供给您的监护人，使得您监护人可及时或同步了解您游戏情况；[-][/c]\n　　[c][000000]（2）限制您游戏账号的消费额度；[-][/c]\n　　[c][000000]（3）采取技术措施屏蔽某些游戏或游戏的某些功能，或限定您游戏时间或游戏时长；[-][/c]\n　　[c][000000]（4）注销或删除您游戏账号及游戏数据等相关信息；[-][/c]\n　　[c][000000]（5）您监护人要求采取的，且心动网络认为合适的其他措施。[-][/c]\n　　[c][000000]六、软件许可[-][/c]\n　　6.1 使用心动游戏服务可能需要下载并安装相关软件，您可以直接从心动网络的相关网站上获取该软件，也可以从得到心动网络授权的第三方获取。[c][000000]如果您从未经心动网络授权的第三方获取心动游戏软件或与心动游戏软件名称相同的游戏，将视为您未获得心动网络授权，心动网络无法保证该游戏能够正常使用，并对因此给您造成的损失不予负责。[-][/c]\n　　6.2 [c][000000]心动网络可能为不同的终端设备或操作系统开发了不同的软件版本，包括但不限于Windows、iOS、Android、Windows Phone、Symbian、Blackberry等多个应用版本，您应当根据实际情况选择下载合适的版本进行安装，下载安装程序后，您需要按照该程序提示的步骤正确安装。[-][/c]\n　　6.3 [c][000000]若心动游戏服务以软件形式提供，心动给予您一项个人的、不可转让及非排他性的许可。您仅可为非商业目的在单一台终端设备上下载、安装、登录、使用该心动游戏服务。[-][/c]\n　　6.4 为提供更加优质、安全的服务，在软件安装时心动网络可能推荐您安装其他软件，您可以选择安装或不安装。\n　　6.5 如果您不再需要使用该软件或者需要安装新版，可以自行卸载。如果您愿意帮助心动网络改进产品服务，请告知卸载的原因。\n　　6.6 为了保证心动游戏服务的安全性和功能的一致性，心动网络有权不经向您特别通知而对软件进行更新，或者对软件的部分功能效果进行改变或限制。\n　　6.7 软件新版本发布后，旧版本的软件可能无法使用。心动网络不保证旧版本软件继续可用及相应的客户服务，请您随时核对并下载最新版本。\n　　[c][000000]七、用户行为规范[-][/c]\n　　7.1 您充分了解并同意，您必须为自己游戏账号下的一切行为负责，包括您所发表的任何内容以及由此产生的任何后果。您应对心动游戏服务中的内容自行加以判断，并承担因使用心动游戏服务而引起的所有风险，包括因对心动游戏服务内容的正确性、完整性或实用性的依赖而产生的风险。心动网络无法且不会对因前述风险而导致的任何损失或损害承担责任。\n　　7.2 您除了可以按照本协议的约定使用心动游戏服务之外，不得进行任何侵犯心动游戏服务的知识产权的行为，或者进行其他的有损于心动网络或其他第三方合法权益的行为。\n　　7.3 除非法律允许或心动网络书面许可，您不得从事下列行为：\n　　（1）删除游戏软件及其副本上关于著作权的信息；\n　　（2）对游戏软件进行反向工程、反向汇编、反向编译或者以其他方式尝试发现软件的源代码；\n　　（3）对游戏软件进行扫描、探查、测试，以检测、发现、查找其中可能存在的BUG或弱点；\n　　（4）对游戏软件或者软件运行过程中释放到任何终端内存中的数据、软件运行过程中客户端与服务器端的交互数据，以及软件运行所必需的系统数据，进行复制、修改、增加、删除、挂接运行或创作任何衍生作品，形式包括但不限于使用插件、外挂或非经合法授权的第三方工具/服务接入软件和相关系统；\n　　（5）修改或伪造软件运行中的指令、数据，增加、删减、变动软件的功能或运行效果，或者将用于上述用途的软件、方法进行运营或向公众传播，无论上述行为是否为商业目的；\n　　（6）通过非心动网络开发、授权的第三方软件、插件、外挂、系统，使用心动游戏服务，或制作、发布、传播非心动网络开发、授权的第三方软件、插件、外挂、系统；\n　　（7）对游戏中心动网络拥有知识产权的内容进行使用、出租、出借、复制、修改、链接、转载、汇编、发表、出版、建立镜像站点等；\n　　（8）建立有关心动游戏服务的镜像站点，或者进行网页（络）快照，或者利用架设服务器等方式，为他人提供与心动游戏服务完全相同或者类似的服务；\n　　（9）将心动游戏服务的任意部分分离出来单独使用，或者进行其他的不符合本协议的使用；\n　　（10）使用、修改或遮盖心动游戏服务的名称、商标或其它知识产权；\n　　（11）其他未经心动网络明示授权的行为。\n　　7.4 [c][000000]您在使用心动游戏服务过程中有如下行为的，心动网络有权视情节严重程度，依据本协议及相关游戏规则的规定，对您做出包括但不限于警告、限制或禁止使用全部或部分功能、暂时或永久性地禁止登录（即封号）、删除游戏账号及游戏数据、删除相关信息等处理措施，情节严重的将移交有关行政管理机关给予行政处罚，或者追究您的刑事责任：[-][/c]\n　　[c][000000]（1）以某种方式暗示或伪称心动网络内部员工或某种特殊身份，企图得到不正当利益或影响其他用户权益的行为；[-][/c]\n　　[c][000000]（2）在心动游戏服务中使用非法或不当词语、字符等，包括用于角色命名；[-][/c]\n　　[c][000000]（3）以任何方式破坏心动游戏服务或影响心动游戏服务的正常进行；[-][/c]\n　　[c][000000]（4）各种非法外挂行为；[-][/c]\n　　[c][000000]（5）传播非法言论或不当信息；[-][/c]\n　　[c][000000]（6）盗取或通过欺诈行为获得他人游戏账号、游戏物品；[-][/c]\n　　[c][000000]（7）私自进行游戏账号交易；[-][/c]\n　　[c][000000]（8）私自进行游戏虚拟货币、游戏装备、游戏币及其他游戏道具等交易；[-][/c]\n　　[c][000000]（9）违反本协议任何约定的；[-][/c]\n　　[c][000000]（10）其他在行业内被广泛认可的不当行为，无论是否已经被本协议或游戏规则明确列明。[-][/c]\n　　7.5 您知悉并同意，如心动网络依据本协议对您的游戏账号采取封号处理措施的，[c][000000]具体封号期间由心动网络根据您违规行为情节而定。[-][/c]\n　　您知悉并同意：[c][000000]（1）在封号期间，您游戏账号中的游戏虚拟货币、游戏装备、游戏币及其他游戏道具可能都将无法使用；（2）如前述游戏虚拟货币、游戏装备、游戏币及其他游戏道具存在一定有效期，该有效期可能会在封号期间过期，您游戏账号解封后，您将无法使用该等已过期的游戏虚拟货币、游戏装备、游戏币及其他游戏道具。据此，您也同意不会因发生前述第（1）和（或）第（2）点规定的情形而追究心动网络任何法律责任。[-][/c]\n　　[c][000000]八、免责声明[-][/c]\n　　8.1 心动游戏服务以“现状”提供给您。心动网络不保证：心动游戏服务无错误及不会中断、所有缺陷已被更正、或心动游戏服务不会受到病毒或任何其它因素的损害。除非有法律明确规定，心动网络在此明确声明不承担任何明示或默示的担保责任，包括但不限于对心动游戏服务的性能、适用性或不侵权的担保。\n　　8.2 在任何情况下，心动网络不对因不可抗力导致的您在使用心动游戏服务过程中遭受的损失承担责任。该等不可抗力事件包括但不限于国家法律、法规、政策及国家机关的命令及其他政府行为或者其它的诸如地震、水灾、雪灾、火灾、海啸、台风、罢工、战争等不可预测、不可避免且不可克服的事件。\n　　8.3心动网络可独立决定随时变更、终止、中止您对任何心动游戏服务的使用，无须向您发出任何提前通知，但根据法律法规规定或您与心动网络的约定需要提前通知的除外。若因您的行为违反法律法规的规定或本协议的规定，心动网络根据相关规定终止、中止您使用任何心动游戏服务，则心动网络无须向您承担任何责任，且有权要求您承担相应的责任。\n　　8.4 [c][000000]心动游戏服务可能因游戏软件BUG、版本更新缺陷、第三方病毒攻击或其他任何因素导致您的游戏角色、游戏道具、游戏装备及游戏币等账号数据发生异常，对此心动网络将及时采取补救措施。在数据异常的原因未得到查明前，心动网络有权暂时冻结该游戏账号；若查明数据异常为非正常游戏行为，心动网络有权恢复游戏账号数据至异常发生前的原始状态（包括向第三方追回被转移数据），且心动网络无须向您承担任何责任。[-][/c]\n　　8.5 [c][000000]心动网络未授权您从任何第三方通过购买、接受赠与或者其他的方式获得游戏账号、游戏道具、游戏装备、游戏币等，心动网络不对第三方交易的行为负责，并且不受理因任何第三方交易发生纠纷而带来的申诉。[-][/c]\n　　8.6 [c][000000]您充分理解到：第三方在心动游戏服务中投放的广告、链接或者其它形式的推广内容，均是由其自行提供的，您应当自行判断其真实性，心动网络对其推广内容不作任何明示或者默示的担保。[-][/c]\n　　8.7 [c][000000]您充分理解到：不同操作系统之间存在不互通的客观情况，该客观情况并非心动网络造成，由此可能导致您在某一操作系统中的充值和游戏数据不能顺利转移到另一操作系统中。由于您在不同系统进行切换造成的充值损失和游戏数据丢失风险应由您自行承担，不得要求心动网络承担任何责任。[-][/c]\n　　8.8 您充分理解到：心动游戏服务中可能会设置强制对战区域或玩法，如果您不同意强制对战，请您不要进入该游戏或游戏区域；您的进入，将被视为同意该玩法并接受相应后果。\n　　[c][000000]九、知识产权[-][/c]\n　　9.1 除非另有规定，心动网络是心动游戏服务的知识产权权利人。心动游戏服务的一切著作权、商标权、专利权、商业秘密等知识产权，以及与心动游戏服务相关的所有信息内容（包括文字、图片、音频、视频、图表、界面设计、版面框架、有关数据或电子文档等）均受中华人民共和国法律法规和相应的国际条约保护，心动网络享有上述知识产权，但相关权利人依照法律规定应享有的权利除外。\n　　9.2 您在使用心动游戏服务中产生的游戏数据的所有权和知识产权归心动网络所有，心动网络有权处置该游戏数据。\n　　9.3 心动游戏服务可能涉及第三方知识产权，而该等第三方对您基于本协议在心动游戏服务中使用该等知识产权有要求的，心动网络将以适当方式向您告知该要求，您应当一并遵守。\n　　[c][000000]十、遵守当地法律监管[-][/c]\n　　10.1 您在使用心动游戏服务过程中应当遵守当地相关的法律法规，并尊重当地的道德和风俗习惯。[c][000000]如果您的行为违反了当地法律法规或道德风俗，您应当为此独立承担责任。[-][/c]\n　　10.2 您应避免因使用心动游戏服务而使心动网络卷入政治和公共事件，否则心动网络有权暂停或终止对您的服务。\n　　[c][000000]十一、管辖与法律适用[-][/c]\n　　11.1 [c][000000]本协议签订地为中华人民共和国上海市闵行区。[-][/c]\n　　11.2 [c][000000]本协议的成立、生效、履行、解释及纠纷解决，适用中华人民共和国大陆地区法律（不包括冲突法）。[-][/c]\n　　11.3 [c][000000]若您和心动网络之间因本协议发生任何纠纷或争议（包括但不限于合同或者其他财产性权益纠纷），首先应友好协商解决；协商不成的，您同意将纠纷或争议提交至本协议签订地有管辖权的人民法院管辖。[-][/c]\n　　11.4 本协议所有条款的标题仅为阅读方便，本身并无实际涵义，不能作为本协议涵义解释的依据。\n　　11.5 本协议条款无论因何种原因部分无效，其余条款仍有效，对各方具有约束力。\n　　[c][000000]十二、其他[-][/c]\n　　12.1 根据国家新闻出版总署关于健康游戏的忠告，心动网络提醒您：[c][000000]抵制不良游戏，拒绝盗版游戏；注意自我保护，谨防受骗上当；适度游戏益脑，沉迷游戏伤身。[-][/c]\n　　12.2 [c][000000]除非您已阅读并接受本协议所有条款，否则您无权使用心动游戏服务。您使用心动游戏服务即视为您已阅读并同意签署本协议。此后您不得以未阅读/未同意本协议内容或类似理由提出任何形式的抗辩。[-][/c]\n　　12.3 如果您对本协议或心动游戏服务有意见或建议，可与心动客户服务部门联系，我们会给予您必要的帮助。（全文完）\n　　　　　　　　　　　　　　　　　　　　　　　[c][000000]心动网络[-][/c]",
	StartGamePanel_AgreetmentTitle = "心动网络游戏许可及服务协议",
	StartGamePanel_AgreetmentTips = "许可及服务协议",
	StartGamePanel_CopyRightTips = "著作权人：GRAVITY CO., LTD. 出版单位：心动网络股份有限公司 出版许可证号：新出网证(沪)字080号\n批准文号：新广出审 [2017] 16号 文网文号：沪网文[2017]9298-701号 版号：ISBN 978-7-7979-3942-3 文网文备案：文网游备字[2017]Ｍ-RPG 0130 号",
	--通用
	Float_PlayerScoreUp = "人物评分+",
	-- 功能开启
	SystemUnLock_DefaultTip = "小铁铺匠开启了",
	SystemUnLock_Open = "%s开启了",
	-- Boss界面
	BossView_All = "全部",
	Boss_Show = "已现身",
	Boss_RefreshTimeH = "%d小时%d分钟",
	Boss_RefreshTimeM = "%d分钟",
	Boss_RefreshMinTime = "15分钟内",
	Boss_AppearPosition = "出现地点：%s",

	BossCell_Appear = "已现身",
	BossCell_UpComing = "即将刷新",
	BossCell_Short = "较短时间",
	BossCell_Long = "较长时间",
	BossCell_ToSet = "待点名",
	BossCell_Set = "已点名",
	-- 包包
	Bag_StrMasterLv = "强化大师%d级",
	Bag_StrMasterNextLvTip = "（全身装备强化%d级）",

	PackageHighRefine_Title_1 = "·初级",
	PackageHighRefine_Title_2 = "·中级",
	PackageHighRefine_Title_3 = "·高级",
	PackageHighRefine_Title_4 = "·终级",
	PackageHighRefine_colon = "：",
	PackageHighRefine_AddEffectTip = "%s强化精炼加成",
	PackageHighRefine_AddEffectTip2 = "+%s及以上%s将获得%s加成",
	
	ItemNormalList_PullRefresh = "请用力向下拉进行包包整理 (≧∇≦)",
	RepositoryNormalList_PullRefresh = "请用力向下拉进行仓库整理 (≧∇≦)",
	ItemNormalList_CanRefresh = "松开进行包包整理 (≧∇≦)",
	RepositoryNormalList_CanRefresh = "松开进行仓库整理 (≧∇≦)",
	ItemNormalList_Refreshing = "努力整理中 (>_<)",
	-- 卡片
	Card_All = "全部",
	Card_Weapon = "武器",
	Card_Shield = "副手",
	Card_Pauldron = "护肩",
	Card_Body = "身体",
	Card_Shoe = "鞋子",
	Card_Accessory = "饰品",
	Card_NoCardTip = "卡册中没有卡片",
	Card_NoChipTip = "卡册中没有碎片",

	ItemData_PetEggName = "%s宠物蛋",

	-- itemtip
	Itemtip_EquipScore = "装备评分：",
	ItemTip_EquipCollectionLv = "评级：%s",
	ItemTip_DecomposeLv = "装备等级：%s",
	ItemTip_EquipLotteryTip = "Base升至%s级后，装备效果：",
	ItemTip_BaseAttri = "基础属性：",
	ItemTip_HRefineAddEffect = "强化精炼加成：",
	ItemTip_AddAttri = "叠加属性：",
	ItemTip_EquipAttri = "穿戴属性：",
	ItemTip_SpecialAttri = "特色属性：",
	ItemTip_PicSpecialAttri = "成品属性：",
	ItemTip_StrengthLv = "强化%d/%d：",
	ItemTip_StrengthLv_NoMax = "强化%d：",
	ItemTip_StrengthLv2 = "加固 %d：%s",
	ItemTip_RefineLv = "精炼%d/%d：",
	ItemTip_UpgradeTip = "装备升级：",
	ItemTip_UpgradeFinalTip = "可升级成%s",
	ItemTip_NoUpgradeInfoEffectTip = "[c][B9202C]（%s转职业有效）[-][/c]",
	ItemTip_NoUpgradeTip = "[c][9d9d9d]（达到%s转职业后可继续升级）[-][/c]",
	ItemTip_UpgradeNpcTip = "由%s-%s进行升级",
	ItemTip_UpEndBuffTip = "升级为%s，%s",
	ItemTip_UpMaterialTip = "升级下一级所需材料：",
	ItemTip_Enchant = "附魔属性：",
	ItemTip_LimitLv = "使用等级：",
	ItemTip_ItemType = "道具类型：",
	ItemTip_UseTimeLimit = "使用次数：每周%s/%s次",
	ItemTip_MonthNoLimit = "使用次数：限定特典期间无次数限制",
	ItemTip_GetLimit = "获取上限：",
	ItemTip_GetLimit_Day = "每日",
	ItemTip_GetLimit_Weak = "每周",
	ItemTip_GetLimit_Ge = "个",
	ItemTip_NoCard = "未装备卡片",
	ItemTip_CardLv = "卡片：%s/%s",
	ItemTip_PicMake = "所需材料：",
	ItemTip_Compose = "合成%s",
	ItemTip_SuitInfo = "[c][1B5EB1]套装效果%s[-][/c]",
	ItemTip_SuitInfoTip = "%s件效果：",
	ItemTip_Profession = "职业：",
	ItemTip_AllPro = "全职业",
	ItemTip_Desc = "描述：",
	ItemTip_Position = "存储位置：",
	ItemTip_SellPrice = "出售价格：",
	ItemTip_UnLockItem = "通过[获得]激活道具",
	ItemTip_UnLockCard = "通过[获得]激活卡片",
	ItemTip_UnLockFashion = "通过[制作]激活头饰",
	ItemTip_DropFrom = "获取途径",
	ItemTip_BuyGetItem = "购买捕捉道具",
	ItemTip_TradePrice = "交易所价格：",
	ItemTip_TradePriceWait = "正在查询价格…",
	ItemTip_EquipCanTip = "此装备",
	ItemTip_PvpEquipTip = "PVP与GVG额外属性",
	ItemTip_NoTradeTip = "不可交易",
	ItemTip_TimeTradeTip = "交易时间：%s",
	ItemTip_NoStrength = "不可强化",
	ItemTip_NoRefine = "不可精炼",
	ItemTip_NoEnchant = "不可附魔",
	ItemTip_NoStorage = "不可存入%s仓库",
	ItemTip_CommonStorage = "通用",
	ItemTip_BarrowStorage = "手推车",
	ItemTip_PersonStorage = "个人",
	ItemTip_NoMakeCard = "不可被国王波利吞食",
	ItemTip_EmptyCardSlot = "空的卡槽",
	ItemTip_LockCardSlot = "未打洞",
	ItemTip_UnlockProperyRewardTip = "放入%s",
	ItemTip_CombineRewardTip = "孵化%s",
	ItemTip_NoEffectTip = "失效：与正在使用的武器类型不一致，当前外观失效",
	Itemtip_SavePower = "热量储备：",
	ItemTip_SavePower_Add = "增加",
	ItemTip_SavePower_And = "，",
	ItemTip_SavePower_Desc = "%s热量[c][00ff00]%s[-][/c]",
	ItemTip_Food_EffectTip = "营养价值：",
	ItemTip_Food_CookHardTip = "料理难度：",
	ItemTip_Food_FullProgressTip = "持续时间：%s分钟",
	ItemTip_Food_WeightTip_Add = "肥胖指数：",
	ItemTip_Food_HeightTip_Add = "增高指数：",
	ItemTip_Food_WeightTip_Minus = "瘦身指数：",
	ItemTip_Food_HeightTip_Minus = "变矮指数：",
	ItemTip_Food_AffixTip = "效果：",
	ItemTip_Colon = "：",
	ItemTip_CHSpace = "　　",
	ItemTip_ChAnd = "、",
	ItemTip_CHBracket = "【%s】",
	ItemTip_PetEgg_MonsterName = "魔物：%s",
	ItemTip_PetEgg_Level = "等级：%s",
	ItemTip_PetEgg_Friendly = "好感度：%s",
	ItemTip_PetEgg_Skill = "技能：",
	ItemTip_PetEgg_Equip = "装备：",
	ItemTip_PetEgg_Exchange_Can = "可以进行交易",
	ItemTip_PetEgg_Exchange_NotCan = "技能等级全部到达Lv10才能交易。",
	ItemTip_LotteryMaxTip = "此装备已升至当前版本最高级",
	ItemTip_ManualInTip = "存入奖励：",
	ItemTip_ManualUnlockTip = "解锁奖励：",
	ItemTip_DelRefreshTip = "%s 后将从包包中消失",
	ItemTip_DelRefreshTip_Day = "天",
	ItemTip_DelRefreshTip_Hour = "小时",
	ItemTip_DelRefreshTip_Min = "分",
	ItemTip_DelRefreshTip_Sec = "秒",
	ItemTip_None = "无",
	ItemTip_CombineTip = "请选择合成方式",
	ItemTip_InviteWeddingDesc = "",
	ItemTip_WeddingTip = "%s与%s\n于%s 在世界%s线 永结连理",
	ItemTip_Line = "世界%s线",
	ItemTip_WeddingCememony_TimeFormat = "%Y年%m月%d日%H时%M分",
	ItemTip_Code_Desc = "券码：%s",
	ItemTip_FoodCookTip = "烹饪熟练度Lv.%s：%s+%s",
	ItemTip_FoodTasteTip = "品尝熟练度Lv.%s：%s+%s",
	ItemTip_DeadLv = "净化等级：Lv.%s",
	ItemTip_DeadCoinNum = "亡者气息：%s/%s",
	ItemTip_TodayGet = "今日获得：%s",
    ItemTip_Recommend = "推荐理由：%s",
	ItemTip_MonsterLVTip = "[c][CF1C0F]掉落解锁:亡者LV.%d[-][/c]",

	EquipUpgradePopUp_QuickBuy = "快速购买",
	EquipUpgradePopUp_Upgrade = "升级",

	TipCardEquipCell_EmptySlot = "[B8B8B8]空的卡槽[-]",

	-- 雇佣猫tip
	HireCatTip_ProfessionTip = "职业：%s",
	HireCatTip_GenderTip = "性别：%s",
	HireCatTip_SkillTip = "能力：%s",
	HireCatTip_DescTip = "描述：%s",
	HireCatTip_HirePosTip = "雇佣地点：%s",
	HireCatTip_HirePriceTip = "雇用价格：{itemicon=100}%s/天",
	HireCatTip_HireLeftTimeTip = "剩余雇佣时间：%s",
	HireCatTip_Day = "天",
	HireCatTip_And = "、",
	
	CollectGroupScoreTip_EDBtn = "ED",
	CollectGroupScoreTip_HeadTip = "集齐以上所有线索%s/%s，%s",
	CollectGroupScoreTip_HeadTip_Unlock = "[c][22222291]集齐以上所有线索%s/%s，%s[-][/c]",
	CollectSaleConfirmPopUp_SaleTip = "将背包中 [c][2A7CC2FF]有使用等级、不可升级、不可在交易所交易[-][/c] 的装备进行一键出售：\n\n%s",
	-- monstertip
	MonsterScoreTip_Condition = "",
	ItemScoreTip_GetPathDes = "获取",
	ItemScoreTip_MakeHeadDress = "制作头饰",
	MonsterTip_None = "无",
	MonsterTip_Story = "[故事]",
	MonthTip_QualityRate = "[评级]",
	MonsterTip_FixAttrCt = "解锁后，永久增加",
	MonsterTip_Position = "[出现地点]",
	MonsterTip_MonstDetail = "[魔物详情]",
	MonsterTip_UnLockMonstDetail = "对%s拍照解锁魔物详情，",
	MonsterTip_LockTitle = "解锁条件",
	MonsterTip_LockReward = "[解锁奖励]",
	MonsterTip_MakeMaterial = "[制作材料]",
	MonsterTip_LockProperyReward = "[属性奖励]",
	MonsterTip_Characteristic = "魔物特性：",
	MonsterTip_PropertyTitle = "魔物属性",
	MonsterTip_DropTitle = "魔物掉落",
	MonsterTip_SpecialTitle = "魔物特征",
	MonsterTip_CharacteristicDetail = "魔物详情",
	MonsterTip_UnlockRewardTip = "魔物解锁:",
	MonsterTip_UnlockRewardSelfieTip = "详情解锁:",
	MonsterTip_Characteristic_Level = "等级",
	MonsterTip_Characteristic_Race = "种族",
	MonsterTip_Characteristic_Shape = "体型",
	MonsterTip_UnLockMonster = "通过[击杀]激活魔物";
	-- npctip
	NpcTip_None = "无",
	NpcTip_Guild = "[c][FF622CFF][所属][-][/c]  ",
	NpcTip_Func = "[c][FF622CFF][功能][-][/c]  ",
	NpcTip_Position = "[c][FF622CFF][位置][-][/c]  ",
	NpcTip_PhotoTip = "{uiicon=photo_icon_photo} 请对[FFC539]%s[-]进行拍照，拍照解锁怪物属性",
	NpcTip_UnLockNpc = "通过[对话]激活NPC",
	--FoodScoreTip
	FoodScoreTip_Effect = "[c][FF622CFF][效果][-][/c]",	
	FoodScoreTip_UnlockRecipeTitle= "[c][FF622CFF][解锁食谱][-][/c]",	
	FoodScoreTip_UnlockRecipe= "烹饪出%s，{uiicon=Adventure_icon_05}冒险经验x%s",	
	FoodScoreTip_UnlockLv= "[c][FF622CFF][解锁熟练度][-][/c]",	
	FoodScoreTip_UnlockCookLv= "烹饪熟练度达到Lv.%s，%s",	
	FoodScoreTip_UnlockTasteLv= "品尝熟练度达到Lv.%s，%s",	
	FoodScoreTip_CurCookExpLv= "%s烹饪熟练度：%s级%s",	
	FoodScoreTip_CurTasteExpLv= "%s品尝熟练度：%s级%s",	
	PetScoreTip_UnlockPet= "%s%s，{uiicon=Adventure_icon_05}冒险经验x%s",	

	NpcTip_UnLockNpc = "通过[对话]激活NPC",
	-- 角色面板
	Charactor_LeftPointLabel = "剩余点数：",
	Charactor_PlayerID = "角色ID：",
	Charactor_ProfessionPageOne = "当前职业可进阶成为【%s】。\n点击下面职业头像可查看相关详细信息哦~",
	Charactor_ProfessionPageTwo ="当前职业可进阶成为【%s】或者【%s】。\n点击下面职业头像可查看相关详细信息哦~",
	Charactor_ProfessionPageMax = "已经不能再进阶了哦~",
	Charactor_ProfessionPage_NotOpen = "未开放",
	Charactor_Unlocked = "级解锁",
	Charactor_UnlockedCondition = "解锁条件：",
	Charactor_PingFen = "评分：",
	Charactor_ViewSkill = "查看技能",
	Charactor_Infomation = "信息",
	Charactor_AddPoint = "加点",
	Charactor_Profession = "职业",
	Charactor_TitleLabel = "加点方案推荐",
	Charactor_ProfessionTipText = "点击下方加点方案，即对剩余点数进行自动分配",
	Charactor_ProfessionInfoSpc = "职业特色：[ff8a00ff]%s[-]",
	Charactor_ProfessionInfoUnlockDes = "进阶解锁技能",
	Charactor_MonthCardTime = "限定特典：%s天",
	Charactor_BaseAttriViewFixedTitle= "永久属性加成展示",
	Charactor_HPEnergyDes = "HP低于30%时，消耗热量恢复HP",
	Charactor_SPEnergyDes= "SP低于30%时，消耗热量恢复SP",
	Charactor_SlimHeightDes_L =  "（偏高）",
	Charactor_SlimHeightDes_S =  "（偏矮）",
	Charactor_SlimWeightDes_L =  "（偏胖）",
	Charactor_SlimWeightDes_S =  "（偏瘦）",
	Charactor_SlimDes_Nomal =  "（正常）",
	Charactor_SatieTyDes =  "料理有效堆叠层数",

	--悬赏任务版
	AnnounceQuestPanel_RewardRatio = "基础奖励：",
	AnnounceQuestPanel_DaiLyWanted = "每日悬赏：",
	AnnounceQuestPanel_RefreshTime = "刷新时间：",
	AnnounceQuestPanel_BottomLabel = "基础奖励：[c][FF2A00]%s%%[-][/c] 今日已完成：%s 刷新时间：%s",
	AnnounceQuestPanel_HelpTeammemberReward = "帮助好友将获得{itemicon=%s}[c][1881B7]%s[-][/c]",
	AnnounceQuestPanel_Complete = "已完成",
	AnnounceQuestPanel_Ongoing = "进行中",
	AnnounceQuestPanel_CanGetAward = "可领取",
	AnnounceQuestPanel_AbadonQuest = "放弃任务",
	AnnounceQuestPanel_AcceptQuest = "接取任务",
	AnnounceQuestPanel_LeaderAceeptBtn = "组队接取",
	AnnounceQuestPanel_CommitQuest = "提交任务",
	AnnounceQuestPanel_HelpQuest = "帮助完成",
	AnnounceQuestPanel_GetReward = "领取奖励",
	AnnounceQuestPanel_TeamOngingLabel = "接取的队友",
	AnnounceQuestPanel_MultiRewardTip = "奖励",
	--QuestPanel
	QuestPanel_CanBeAccep = "可接",
	QuestPanel_NoQuest = "没有任务",
	QuestPanel_MainType = "主-",
	QuestPanel_BranchaType = "支-",
	QuestPanel_AnnType = "赏-",

	--技能
	SkillView_LevelExtra = "Lv.%s[c][00ff00]（+%s）[-][/c]",
	SkillView_MaskText = "升级[c][FFC53A]%s[-][/c]技能需[c][FFC53A]%s[-][/c]消耗40个技能点",
	SkillView_LeftSkillPointText = "剩余点数：  [c][54B30A]%s[-][/c]",
	SkillCell_LeftValues = "剩余次数:%s/%s",
	SkillCell_Source = "来自于%s",
	SkillCell_Level = "[c][%s]%s[-][/c]/%s",
	SkillTip_NextLevelSperator = "下一等级",
	SkillTip_CannotLevelUpSperator = "技能不可升级",
	SkillTip_LevelMaxSperator = "技能已满级",
	SkillTip_LeftValues = "剩余次数:%s/%s",
	SkillTip_LeftValuesRefresh = "剩余次数:%s/%s（%s后恢复1点）",
	SkillTip_DelayCDTime = "技能延迟：%s秒",
	SkillTip_FitQuest = "需要完成\"%s\"任务",
	SkillTip_NeedFitQuest = "需要完成[c][FF3B0D]\"%s\"[-][/c]任务",
	SkillTip_FitJobLV = "需要%sJob%s级",
	SkillTip_FitBaseLV = "需要%sLevel%s级",
	SkillTip_NeedFitJobLV = "需要%sJob[c][FF3B0D]%s[-][/c]级",
	SkillTip_NeedFitBaseLV = "需要%sLevel[c][FF3B0D]%s[-][/c]级",
	SkillTip_SkillLV = "需要%s的%sLv.%s",
	SkillTip_NeedSkillLV = "需要%s的[c][FF3B0D]%sLv.%s[-][/c]",
	SkillTip_SkillCost = "需要消耗%s点技能点",
	SkillTip_NeedSkillCost = "需要消耗[c][ff0000]%s[-][/c]点技能点",
	SkillTip_FitRisk = "需要%s",
	SkillTip_NeedFitRisk = "需要[c][ff0000]%s[-][/c]",
	SkillTip_PreviousProfessSkillPoints = "需要%s职业消耗%s技能点",
	SkillTip_NeedPreviousProfessSkillPoints = "需要%s职业消耗[c][FF3B0D]%s[-][/c]技能点",
	SkillTip_NeedSpecialSplit = "和",
	SkillTip_NeedSpecialCost = "特殊消耗：%s",
	SkillTip_NormalAtkLabel = "选中目标自动进行普通攻击",

	SkillTip_RuneSpecialTitle = "符文效果:",
	SkillTip_RuneSpecialEnabelTitle = "符文启用",

	SkillTip_OptionSummon = "召唤%s",
	PealSkillTip_Info = "突破技能等级上限预览",

	SkillTip_DelayCDTime = {normal="技能延迟：%s秒",buff="技能延迟：%s秒[c][00ff00]（%s%.2f秒）[-][/c]",debuff="技能延迟：%s秒[c][ff0000]（%s%.2f秒）[-][/c]"},
	SkillTip_CastTime = {normal="吟唱时间：%s秒",buff="吟唱时间：%s秒[c][00ff00]（%s%.2f秒）[-][/c]",debuff="吟唱时间：%s秒[c][ff0000]（%s%.2f秒）[-][/c]"},
	SkillTip_LaunchRange = {normal="施法距离：%sm",debuff="施法距离：%sm[c][00ff00]（%s%.1fm）[-][/c]",buff="施法距离：%sm[c][ff0000]（%s%.1fm）[-][/c]"},
	SkillTip_CDTime = {normal="技能冷却：%s秒",buff="技能冷却：%s秒[c][00ff00]（%s%.2f秒）[-][/c]",debuff="技能冷却：%s秒[c][ff0000]（%s%.2f秒）[-][/c]"},
	SkillTip_SPCost = {normal="SP消耗：%s",buff="SP消耗：%s[c][00ff00]（%s%.0f）[-][/c]",debuff="SP消耗：%s[c][ff0000]（%s%.0f）[-][/c]"},
	SkillTip_HPCost = {normal="HP消耗：%s",buff="HP消耗：%s[c][00ff00]（%s%.0f）[-][/c]",debuff="HP消耗：%s[c][ff0000]（%s%.0f）[-][/c]"},
	SkillTip_ItemCost = {normal = "%sx%s",buff="%sx%s[c][00ff00]（%s）[-][/c]",debuff="%sx%s[c][ff0000]（%s）[-][/c]"},
	SkillTip_BuffCost = {normal = "［%s］x%s",buff="［%s］x%s[c][00ff00]（%s）[-][/c]",debuff="［%s］x%s[c][ff0000]（%s）[-][/c]"},

	SkillTip_Shared = "（账号共享）",
	--右下角快捷框
	QuickUsePopupFuncCell_EquipBtn = "装备",
	QuickUsePopupFuncCell_UseBtn = "使用",
	QuickUsePopupFuncCell_CameraBtn = "拍照",
	QuickUsePopupFuncCell_Catch = "捕捉",
	QuickUsePopupFuncCell_Give = "赠送",
	--商店
	HappyShop_haveObtain="已拥有：",
	HappyShop_todayCanBuy="[c][595959]今日可购买：[-][/c]%s/%s",
	HappyShop_AccUserCanBuy = "[c][595959]账号每日购买次数：[-][/c]%s/%s",
	HappyShop_AccUserWeekCanBuy = "[c][595959]角色每周购买次数：[-][/c]%s/%s",
	HappyShop_AccWeekCanBuy = "[c][595959]账号每周购买次数：[-][/c]%s/%s",
	HappyShop_AccMonthCanBuy = "[c][595959]账号每月购买次数：[-][/c]%s/%s",
	HappyShop_AlwaysCanBuy = "[c][595959]剩余购买次数：[-][/c]%s/%s",
	HappyShop_ActivityCanBuy = "[c][595959]%d折可购买：[-][/c]%s/%s",
	HappyShop_silverNotEnough="银币不足无法购买。",
	HappyShop_overtime="已下架",
	HappyShop_levelNotEnough="等级不够无法购买。",
	HappyShop_NotEnough="%s不足无法购买",
	HappyShop_originalCost = "原价：",
	HappyShop_discount = "%d%%",
	HappyShop_Lock = "完成%s任务后解锁",
	HappyShop_BuyCheap = "总价-%d%%，节省%sZeny",
	HappyShop_PriceTitle = "购买单价",
	HappyShop_TotalPriceTitle = "购买总价",
	HappyShop_OwnInfo = "已拥有：[c][1F74BF]%s[-][/c]",
	HappyShop_OwnGuild = "公会已拥有：[c][1F74BF]%s[-][/c]",
	HappyShop_SoldCount = "剩余库存：[c][1F74BF]%s/%s[-][/c]",
	HappyShop_LimitCount = "%s剩余获取数量：[c][1F74BF]%s[-][/c]",
	HappyShop_ProduceNum = "数量：%s/%s",
	HappyShop_defaultDesc = "来看看本店热卖的东西吧，你一定会喜欢的！",
	HappyShop_SoldOut = "售罄",
	HappyShop_Buy = "购买",
	--精炼
	RefinePanel_ChooseEquip = "选择装备",
	RefinePanel_ChooseMat = "选择材料",
	RefinePanel_InvalidRepairMatTip = "+6以上不能作为材料",
	EquipChooseCell_ForbidTip = "[c][ff0000]已精炼的装备[-][/c]",
	EquipRefinePage_RepairTip = "精炼再强的装备，要是损坏了，虽然不会影响使用，但会无法继续精炼，怎么样？是不是先把它修理好呢？",
	EquipRefinePage_RefineTip = "这装备不错，我可以把它精练到+%s，要不要试试呢？",
	EquipRefinePage_DamageTip = "%s+%s\n（已损坏）",
	EquipRefinePage_RefineLevelTip1 = "精炼等级+1~+4必然成功",
	EquipRefinePage_RefineLevelTip2 = "↑请选择上方的精炼技术，改变成功率",
	EquipRefinePage_RefineLevelTip3 = "↑请选择上方的精炼技术，当前成功率100%",
	EquipRefinePage_RefineLevelTip4 = "↑请选择普通精炼",
	EquipRefinePage_RefineLevelTip5 = "已精炼至最高等级",
	EquipRefinePage_ChooseMaterialTip = "请选择%s件作为安全精炼的消耗",
	EquipRefinePage_TopSafeRefine = "安全精炼最高+%s",
	EquipRefinePage_ClickRefineTip = "点击调整",

	EquipRefinePage_EffectSperator = "：",

	NpcRefinePanel_ChooseEquip = "选择装备",
	NpcRefinePanel_RepairTip = "精炼再强的装备，要是损坏了，虽然不会影响使用，但会无法继续精炼，怎么样？是不是先把它修理好呢？",
	NpcRefinePanel_RefineTip = "这装备不错，我可以把它精练到+%s，要不要试试呢？",
	NpcRefinePanel_FashionRefineTip = "突突..这是一台魔法缝纫机，把装备放进去就进行秘银精炼和秘银强化！！突突突...",

	--精炼
	EquipRefineBord_EffectSperator = "：",
	EquipRefineBord_DamageTip = "%s+%s\n（已损坏）",
	EquipRefineBord_InvalidRepairMatTip = "+6以上不能作为材料",
	EquipRefineBord_ChooseMat = "选择材料",
	EquipRefineBord_RefineTip_DefiniteSuccess = "精炼等级+1~+4必然成功",
	EquipRefineBord_RefineTip_ChooseNormal = "↑请选择上方的精炼技术，改变成功率",
	EquipRefineBord_RefineTip_ChooseNormal2 = "↑请选择上方的精炼技术，当前成功率100%",
	EquipRefineBord_RefineTip_ChooseNormal3 = "↑请选择普通精炼",
	EquipRefineBord_RefineTip_Full = "已精炼至最高等级",
	EquipRefineBord_TopSafeRefine = "安全精炼最高+%s",
	EquipRefineBord_RepairTip="任意洞数的%s都可以进行修复",
	--精炼

	HRefineAddEffectTip_Shield = "副手",
	
	--分解
	DeComposeView_InvalidTip = "还原装备后可分解",
	DeComposeView_DecomposeTip = "吼~~吼吼~~~我要分解所有装备！所有的！",
	DecomposeView_BusinessTip1 = "金属研究",
	DecomposeView_BusinessTip2 = "分解获得的金属增加%s%%",

	EquipRefinePage_EffectSperator = "：",
	--世界地图
	WorldMapListView_zoomIn="显示区域",
	WorldMapListView_zoomOut="全图浏览",
	WorldMapListView_infoShow="信息显示",
	WorldMapListView_infoHide="信息隐藏",
	--新版理发店
	HairDressingView_HairCutPageTitle="理\n发",
	HairDressingView_HairDyePageTitle="染\n发",
	HairDressingView_HideHeadgear="隐藏头饰",
	HairDressingView_Replace="更换",
	HairdressingView_cost="费用：",
	HairDressingView_consume="消耗：",
	HairDressingView_dyeNotEnough="染色剂不足",
	HairDressingView_bSameColor="已是此颜色",
	HairDressingView_bSameHair="已是此款发型",
	-- 美瞳
	EyeLensesView_title="美\n瞳",
	EyeLensesView_sameEyeLenses="已是此款美瞳",
	EyeLensesView_hideFacegear="隐藏脸饰",
	-- 服装店
	ClothDressingView_title = "服\n装",
	ClothDressingView_same="已是此款服装",
	--聊天
	Chat_cantTalk="此频道不能发言，请切换至其他频道",
	Chat_inputTooFrequently="输入太频繁",
	Chat_send="请输入要发送的内容",
	Chat_notInParty="你不在队伍中，无法发言",
	Chat_notInGuild="你不在公会中，无法发言",
	Chat_channel = "频道",
	Chat_privateChat = "私聊",
	Chat_chatZone = "聊天室",
	Chat_current="附近",
	Chat_team="组队",
	Chat_guild="公会",
	Chat_friend="私聊",
	Chat_world="世界",
	Chat_map="地图",
	Chat_system="系统",
	Chat_privateTitle = "[6c6c6c]与 [ffffff]%s[-] 私聊[-]",
	Chat_emptyChat = "没有私聊内容",
	Chat_join = "进入房间",
	Chat_exit = "退出房间",
	Chat_kick = "被踢出房间",
	Chat_ownerchange = "更换为房主",
	Chat_owner = "房主",
	Chat_visitor = "访客",
	Chat_speechRecognizer = "手指划开，取消发送",
	Chat_speechCancel = "松开手指，取消发送",
	Chat_zoneName = "的聊天室",
	Chat_newMessage = "条新消息",
	Chat_speechTime = "%s秒",
	Chat_ScrollScreenEmpty = "没有%s聊天信息 ",
	Chat_PrivateMainView = "%s对[-] %s %s说：[-]",
	Chat_MainView = " %s%s：[-]",
	Chat_Barrage = "弹",
	Chat_PetTalk = "宠",
	--仓库
	Repository_storeLv = "角色%s级后才可存入",
	Repository_takeoutLv = "非限定特典角色%s级后才可取出",
	--无尽之塔
	EndlessTower_name = "恩德勒斯塔",
	EndlessTower_cantChallenge="当前层不可挑战！",
	EndlessTower_layer="第%s层",
	EndlessTower_notLeaderCantChallenge="您不是队长无法开启挑战。",
	EndlessTower_noneMembers="目前没有队友",
	EndlessTower_refreshDay="%s天",
	EndlessTower_refreshHour="%s小时",
	EndlessTower_refreshTime="%s分钟后更新",
	EndLessTowerCountDownInfo_CountDown = "[c][0071B6]%s[-][/c]天[c][0071B6]%s[-][/c]小时[c][0071B6]%s[-][/c]分钟",
	--队伍
	TeamMemberListPopUp_HireTip = "雇主：%s",
	TeamMemberListPopUp_FreePick = "自由拾取",
	TeamMemberListPopUp_RandomPick = "随机分配",

	TeamInviteMembCell_RestTime = "休整%02s:%02s",
	TeamInviteMembCell_ExpireTime = "已到期",
	TeamInviteMembCell_ReHire = "续约",
	TeamInviteMembCell_MasterTip = "雇主：%s",

	TeamFindPopUp_NoneFilterLevel = "全部等级",
	TeamFindPopUp_StartLevel = "Lv%d以上",
	TeamCell_Apply = "申请",
	TeamCell_Applied = "已申请",
	TMInfoCell_RestTip = "休整%02d:%02d",
	TMInfoCell_line = "世界线%s",

	TeamOptionPopUp_AutoApplyTip1 = "关闭",
	TeamOptionPopUp_AutoApplyTip2 = "所有人",
	TeamOptionPopUp_AutoApplyTip3 = "仅公会和好友",
	--装备修复
	EquipRepair_notSelectEquip="请选择需要修复的装备。",
	EquipRepair_MatNotEnough="修复装备所需材料不足！",
	EquipRepair_success="修复装备成功！",
	EquipRepair_RepairTip="任意洞数的XX都可以进行修复",
	--研究所
	InstituteChallenge_score="积分+",
	InstituteChallenge_des="分",
	InstituteChallenge_notTeam="必须要组队才能进入",

	InstituteResultPopUp_Multiple = "×",
	--商店出售
	ShopSale_canSaleNums="还可出售的数量:",
	ShopSale_notItems="请选择需要出售的物品。",
	ShopSale_cantSale="此物品不可出售。",
	ShopSale_SellExpensive = "总价+%d%%，多得%sZeny",
	--获取途径
	GainWayTip_notOpen="此途径未开启。",
	--转职长廊
	ChangeJob_ConfirmBtn="转职",


	AdventureRewardPanel_AdventureScore = "冒险经验+",
	AdventureRewardPanel_AdventureExp = "冒险经验",
	AdventureRewardPanel_AdventureUnlockSkill = "解锁冒险技能",
	AdventureRewardPanel_HasGetAward = "已领取",
	AdventureRewardPanel_Adventure_Score = "冒险分数",
	AdventureRewardPanel_Des = "对于您在德加尔特大陆上做出的卓越贡献，我们授予您“%s”的荣誉",
	AdventureRewardPanel_RewardLabel = "查看详情",
	AdventureSceneCell_PicLost = "图片信息丢失",
	AdventureHomePage_manualLevel = "[冒险等级] Lv.%d",
	AdventureHomePage_manualPoint = "冒险技能点：%d",
	AdventureHomePage_MyRank = "我的排名：[c][0074BCFF]%d[-][/c]",
	AdventureHomePage_NoneAppellation = "未获得",
	AdventureHomePage_AppellationDes = "对于您在德加尔特大陆上做出的卓越贡献，冒险者协会授予你“[c][0074BCFF]%s[-][/c]”的称谓\n\n提升冒险等级，获得冒险技能点和属性，每提升冒险者称号，可大幅提升属性，还会解锁新的冒险技能。",
	AdventureHomePage_SecondContentTitle = "冒险进度",
	AdventureHomePage_ThirdContentTitle = "冒险等级Lv.%s->Lv.%s\n[c][0074BCFF]%s[-][/c]",
	AdventureHomePage_FourThContentTitle = "升至下一称号（需要冒险等级达到%s）\n%s",
	AdventureHomePage_UnlockSkillitle = "解锁冒险技能",
	AdventureHomePage_PropBordBtn = "属性加成",
	AdventureHomePage_PropBordTitleDes= "冒险手册属性加成",
	AdventureHomePage_EmptyPropDes= "请进行冒险收集属性",
	AdventureHomePage_PropBordPropTitleDes= "手册属性",
	AdventureHomePage_PropBordAppllationTitleDes= "%s属性",
	AdventureHomePage_CardName= "卡片",
	AdventureHomePage_TitleDes=  "授予 “[c][0074BCFF]%s[-][/c]“称谓[c][0074BCFF]",
	AdventureHomePage_PropTitle=  "属性",
	AdventureHomePage_PropKeyworkTitle=  "关键字",
	AdventureHomePage_PropKeyEmptyTitle=  "请先选择上方属性",

	AdventureAppendRewardPanel_Reward = "领取",
	AdventureAppendRewardPanel_MonstUnlock = "完成后，魔物详情解锁",
	AdventureAppendRewardPanel_Unlock = "完成后%s解锁",	
	AdventureAppendRewardPanel_BufferUnlock = "完成后，%s",	
	AdventureAppendRewardPanel_AppendTarget = "追加目标",	

	AdventureAchievePage_EmptyContentLabel = "未找到成就",	
	AdventureAchievePage_RewardTitle = "[c][FF6D2FFF][奖励][-][/c]",	
	AdventureAchievePage_CompleteDate = "完成于%s",	
	AdventureAchievePage_RecentAchiveTitle = "最近完成的成就",	
	AdventureAchievePage_BornAndToulInfo = "%s出生于普隆德拉南门\n距今已%s天，进入世界共%s次",	
	AdventureAchievePage_TotalTourDis = "在世界总行走了%s米",	
	AdventureAchievePage_ChangeProfessionInfo = "[c][6C6C6CFF]%s[-][/c]   就职%s",
	AdventureAchievePage_Max_team = "与[c][FF8A29FF]%s[-][/c]组队时间最长",
	AdventureAchievePage_Max_hand = "与[c][FF8A29FF]%s[-][/c]牵手时间最长",
	AdventureAchievePage_Max_wheel = "与[c][FF8A29FF]%s[-][/c]坐摩天轮次数最多",
	AdventureAchievePage_Max_chat = "与[c][FF8A29FF]%s[-][/c]私聊次数最多",
	AdventureAchievePage_Max_music = "播放[c][FF8A29FF]%s[-][/c]次数最多",
	AdventureAchievePage_Max_save = "复活[c][FF8A29FF]%s[-][/c]次数最多",
	AdventureAchievePage_Max_besave = "被[c][FF8A29FF]%s[-][/c]复活次数最多",
	AdventureAchievePage_AchievementTabTitle = "成就达成度%s%%",
	AdventureAchievePage_SubAchieveText = "完成成就：%s",
	AdventureAchievePage_SubQuestText = "完成任务：%s",
	AdventureAchievePage_PreFinishQuestText = "%s  [%s]",
	AdventureAchievePage_Finish = "已完成",
	AdventureAchievePage_Accept = "已接取",
	AdventureAchievePage_UnAccept = "未接取",
	AdventureAchievePage_AwardTitlePropTitle = "已解锁称号属性",
	AdventureAchievePage_PropShowBtnLabel = "解锁属性",
	AdventureAchievePage_AllAchieve = "全部",
	AdventureAchievePage_Complete = "已完成",
	AdventureAchievePage_UnComplete = "未完成",
	Common_Comma = "/",
	ItemUtil_NoBufferDes = " 该特色属性还未添加描述",
	ItemUtil_NoMonsterDrop = "道具 %d 没有找到怪物掉落",

	UnlockAchievenment="解锁成就[c][1F74BF]%s[-][/c]获得",
	AchievementTitle_unfix= "卸下",
	AchievementTitle_Unlock = "未解锁",
	AchievementTitle_NoTitle = "无称号",

	AdventurePanel_AllTab = "所有%s",
	AdventurePanel_Row = "%s图鉴",
	AdventurePanel_ResearchTabTitle = "探索",
	AdventurePanel_FilterConditionLabel= "本职业",

	AdventureFoodPage_CookLv = "烹饪等级 [c][007EEAFF]Lv.%s[-][/c]",
	AdventureFoodPage_TasteLv = "品尝等级 [c][007EEAFF]Lv.%s[-][/c]",
	AdventureFoodPage_FoundTitle = "已发现配方：",
	AdventureFoodPage_RecentCook = "最近烹饪料理：",
	AdventureFoodPage_NextLevel = "升至下一级：",
	AdventureFoodPage_RecipeCellText = "%s星配方[c][007EEAFF]%s[-][/c]个",
	AdventureFoodPage_CookDes = "料理协会因你在烹饪各类美食上的杰出表现，授予[c][1F74BF]“%s”[-][/c]称谓\n\n提升烹饪等级，当制作低于烹饪等级的料理成功率将大幅度提升，并且会获得更丰富的料理配方和包包空间",
	AdventureFoodPage_NextLevelReward = "授予[c][007EEAFF]“%s”[-][/c]称谓\n包包空间增加%s格\n获得[c][007EEAFF][%s][-][/c]增加[c][007EEAFF]%s%%[-][/c]成功率。",
	AdventureFoodPage_NextTasteLevelReward = "授予[c][007EEAFF]“%s”[-][/c]称谓\n\n品尝料理时，提升料理buff有效堆叠上限：%s层",
	AdventureFoodPage_NextLevelTitle = "升至下一级",
	AdventureFoodPage_RecentCookTitle = "最近烹饪料理",
	AdventureFoodPage_UnlockRecipeTitle = "已发现配方",
	AdventureFoodPage_RecentTasteState = "目前饮食状态",
	AdventureFoodPage_CookTitleTitle = "烹饪资格",
	AdventureFoodPage_TasteTitleTitle = "品尝资格",
	AdventureFoodPage_FoodInstitul = "料理协会颁发",
	AdventureFoodPage_AllFoods = "所有料理",
	AdventureFoodPage_FoodsTab = "%s星料理",
	AdventureFoodPage_FilterDesc = "筛选",
	AdventureFoodPage_TasteDes = "料理协会因你在品尝各类美食上的杰出表现，授予[c][1F74BF]“%s”[-][/c]称谓\n\n品尝料理时，提升料理buff有效堆叠上限：%s层\n\n有效堆叠层数：%s",

	AdventurePanel_ItemIntoAdventurePackage= "存入头饰",
	AdventurePanel_ItemOutAdventurePackage= "取出头饰",
	AdventurePanel_CardIntoAdventurePackage= "存入卡片",
	AdventurePanel_CardOutAdventurePackage= "取出卡片",
	PersonalPicturePanel_AlbumStateFull= "相册已满，请选择照片替换",
	PersonalPicturePanel_AlbumStateEmpty= "本相册没有照片，请您快去拍摄一些吧~",
	PersonalPicturePanel_ShowModeEditor= "编辑",
	PersonalPicturePanel_ShowModeEditor_1= "退出",
	PersonalPictureCell_PicLost= "图片丢失",
	PersonalPictureCell_Downloading= "下载中（%s%%）",
	PersonalPictureCell_Uploading= "上传中（%s%%）",
	PersonalPictureCell_AscentSort= "最近拍摄",
	PersonalPictureCell_DescentSort= "较早拍摄",
	PersonalPictureCell_CurrentShow= "照片墙",
	PersonalPictureCell_LoadingText= "加载中...",
	PersonalPictureCell_CurSyncState = "(%s/%s)上传",
	PersonalPictureCell_CurFrameShowState = "展示中：%s/%s",
	PersonalPictureCell_CurAlbumState = "本相册一共有%s张照片在展示",
	PersonalPictureCell_UploadSusmsg = "成功上传%s张照片至本相框",
	PersonalPictureCell_HasUpOtherFrame = "照片正在其他相框展示，请取消后再重新上传",
	PersonalPictureCell_PictureDesNotime = "时间不详",
	PersonalPictureCell_PictureShowCur = "正在当前相框展示",
	PersonalPictureCell_PictureShowOther = "正在其他相框展示",
	PersonalPictureCell_DetailPictureShowCur = "本照片正在当前相框展示",
	PersonalPictureCell_DetailPictureShowOther = "本照片正在其他相框展示",
	DetailPictureShowOther_TipMsg = "这些照片会自动轮流展示啦~",
	WeddingPictureDownloading = "正在下载请稍后..",
	WeddingPictureDiyDes = "上传的照片将会在婚后给与的【结婚证】上显示",
	WeddingPictureDiyUploadTitle = "上传照片",
	WeddingPictureDiyReplace = "替换照片",
	WeddingPictureShareLabel = "分享",

	TempPersonalPicture_CloseTime = "临时相册剩余存在%s天",
	TempPersonalPicture_CloseTime_ = "临时相册剩余存在%s",
	AdventurePanel_AdventureFoodPageLv= "%s等级 [c][1F74BFFF]Lv.%s[-][/c]",
	AdventurePanel_AdventureFoodPageCook= "烹饪",
	AdventurePanel_AdventureFoodPageEat= "美食",

	UniqueConfirmView_Confirm = "确认",
	UniqueConfirmView_CanCel = "取消",

	-- 修复时空裂隙
	SealInfo_SealTip = "时空裂隙剩余时间: %d秒",
	SealTaskPopUp_Accept = "接取任务",
	SealTaskPopUp_GiveUp = "放弃任务",
	SealTaskPopUp_ExtraTimesTip = "增加领取奖励：%s次",
	--任务
	TaskQuestCell_Dis = "地点:%s",
	TaskQuestCell_CurDis = "地点:当前地图",
	TaskQuestCell_GuildTimeOut = "%s\n[c][FF0000FF]%s分后失效[-][/c]",
	TaskQuestTip_Accepted = "已接任务",
	TaskQuestTip_Empty = "没有可以追踪的任务哦",

	SceneNameView_Husong = "护送中",
	SceneNameView_MasterName = "%s\n%s[雇主]",
	--死亡框
	DeathPopView_Title = "你已经死亡",
	DeathPopView_ReliveInSavePoint = "回到记录点",
	DeathPopView_ReliveInRelivePoint = "复活",
	DeathPopView_ReliveInSitu = "原地复活",
	DeathPopView_ReliveAndLeave = "离开并复活",
	DeathPopView_TitleHint = "[c][fedd4fff]%s[-][/c]打败了你\nBase经验减少[c][fedd4fff]%s[-][/c]",
	DeathPopView_TitleHintPvP = "[c][fedd4fff]%s[-][/c]打败了你",
	DeathPopView_TitleReliveHintGVG = "[c][00E228FF]%s[-][/c]复活了你",
	DeathPopView_ReliveHintDesGVG = "%s秒后复活",

	-- AdventureRewardPanel_AdventureScore

	MainUseEquipPopup_MakeTip = "制作饰品",
	MainUseEquipPopup_Make = "制作",

	--好友
	Friend_ListTitle = "好友名册",
	Friend_EmptyGuild = "无公会信息",
	Friend_SearchContent = "输入玩家ID号/名字/关键字",
	Friend_ListTip = "目前还没有好友",
	Friend_ApplyTip = "没有申请信息",
	Friend_SearchTip = "输入搜索内容搜索好友",
	Friend_EmptySearch = "没有找到符合条件的玩家",
	Friend_MapOffline = "离线",
	Friend_MapOnline = "在线",
	Friend_Zone = "世界线%s",
	Friend_RecallTip = "你将对%s发送召回邀请，对方重新登录游戏并与你签订契约后，双方可获得%s个[url=%s]%s[/url]和持续%s天的%sBUFF",
	Friend_RecallFirstRewardTip = "首次分享可获得",
	Friend_DunHao = "、",
	Friend_RecallContractTip = "有%s名好友向你发送了召回邀请，请选择1人与之签订“[c][1F74BF]回归·契约书[-][/c]”，契约书[c][1F74BF]有效期为%d天[-][/c]，期间双方将获得",
	Friend_RecallRewardItem = "%s个%s",
	Friend_RecallRewardBuff = "持续%s天的%sBUFF",

	--黑名单
	Blacklist_ListTip = "目前还没有黑名单成员",
	Blacklist_Time = "剩余%s天",
	Blacklist_Forever = "永久",

	-- 小地图
	MiniMapWindow_Go = "",

	--
	TeamMemberCell_line = "世界线%s",
	TeamMemberCell_Offline = "离线",
	TeamMemberCell_CatRest = "休整中\n",
	TeamMemberCell_Expire = "已到期",
	
	TeamInviteMembCell_Invite = "邀请";
	TeamInviteMembCell_Invited = "已邀请";

	InviteConfirmView_Agree = "同意";
	InviteConfirmView_Join = "加入";
	InviteConfirmView_Follow = "跟随";
	InviteConfirmView_Desert_Agree="接受";
	InviteConfirmView_Desert_Refuse="拒绝";

	MapInfoCell_Enter = "入口";

	NpcFun_DefeatBossCount = "今日已抗击魔潮%s次，还可抗击魔潮%s次\n（每日会发布魔潮2次，最多保留6次）",
	NpcFun_DefeatBoss = "击杀越强的魔物，完成速度越快，请保重~",
	
	MainViewSealInfo_BeginRepairSeal = "开始修复时空裂隙",
	MainViewSealInfo_EndRepairSeal = "时空裂隙修复完成",
	MainViewSealInfo_TraceTitle = "时空裂隙（组队）",
	MainViewSealInfo_GoRepairPct = "前往修复时空裂隙",
	MainViewSealInfo_RepairPct = "[FF0000]正在修复：%d%%[-]",
	MainViewSealInfo_FinishRepair = "[00FF00]时空裂隙即将修复，消灭剩余魔物[-]",

	MatchInfoCell_PoringInfo = "正在匹配...",
	PoringFightTipView_MonsterTip = "拾取 [609AF2]%s[-] 个苹果后重新加入",

	MainViewInfoPage_Auto = "自动",
	MainViewInfoPage_Cancel = "取消",
	MainViewInfoPage_line = "界线%s",
	MainViewInfoPage_MapCurrentline = "世界线%s",
	MainViewInfoPage_BuffLeftTimeTip = "剩余时长：%s",
	MainViewInfoPage_Min = "分钟",
	MainViewInfoPage_Sec = "秒",
	MainViewInfoPage_FullProgress = "饱腹度：%s/%s",
	MainViewInfoPage_DunHao = "、",

	MainViewInfoPage_seal = "裂隙（%s/%s）",
	MainViewInfoPage_board = "看板（%s/%s）",
	MainViewInfoPage_laboratory = "训练场（%s/%s）",
	MainViewInfoPage_tower = "恩德勒斯塔（%s/%s）",
	MainViewInfoPage_donate = "公会捐赠（%s/%s）",
	MainViewInfoPage_MvpFightLine = "Mvp竞争战",

	MainViewHeadPage_Name = "名字：%s",
	MainViewHeadPage_Master = "主人：%s",
	MainViewHeadPage_Friend = "好感度：%s",

	ProfessionInfoPanel_PropDes = "Job满级总加成：",
	ProfessionInfoPanel_Introduce = "%s介绍",
	ProfessionInfoPanel_Unlock = "职业解锁内容",

	DialogView_Left = "离开",

	MainViewAddTrace_ItemTraceInfo = "%s掉落\n已拥有：%s",

	MainViewAddTrace_HelpTeamTraceInfo = "%s\n队友完成：%s",

	MainViewMiniMap_WorldMap = "世界",
	MainViewMiniMap_ReturnHome = "离开此地",

	FloatAwardView_Confirm = "确定",
	CommonZhString_Close = "关闭",
	FloatAwardView_IntoPackage = "放入包包",
	FloatAwardView_Equip = "立即装备",
	ShareAwardView_RefineSus = "精炼成功",
	ShareAwardView_GetCard = "卡片获得",
	ShareAwardView_GetItem = "道具获得",
	ShareAwardView_RefineProperty = "精炼加成",
	ShareAwardView_EmptyPath = "图片未找到",

	--select role 
	SelectServerPanel_PanelTitle = "服务器选择",
	SelectServerPanel_StateNormal = "流畅",
	SelectServerPanel_StateCrowd = "拥挤",
	SelectServerPanel_StateHot = "火爆",
	SelectServerPanel_StateMaintain = "维护",
	SelectServerPanel_MyServer = "我的服务器",
	SelectServerPanel_Region = "区",
	SelectServerPanel_RecentLogin = "最近登录",
	SelectServerPanel_HasRoles = "拥有角色",

	WorldMapMenuCell_LvTip = "（Lv.%s-%s）",
	AdventureRewardPanel_GetRewardBtnLabel = "学习技能",
	AdventureRewardPanel_SkillUnlock = "冒险技能解锁",

	CapraTransmission_Area = "区域",

	TeamInvitePopUp_FriendTog = "好友",
	TeamInvitePopUp_GuideTog = "公会",
	TeamInvitePopUp_TeammateTog = "曾经队友",
	TeamInvitePopUp_HireTog = "佣兵猫",
	TeamInvitePopUp_NoMemberTip = "未找到符合要求的玩家!",
	TeamInvitePopUp_NoCatTip = "未雇佣佣兵猫",

	GuildAsset_AssetNum = "公会资金:%s",

	GuildInfoView_DailyCostTip = "%s/日（公会资金）",
	GuildInfoPage_Nothing = "暂无",
	GuildInfoPage_DismissGuildTip = "解散公会审核中",
	GuildInfoPage_GuildChangeline = "公会将搬家至世界线%s\n",
	GuildInfoPage_line = "世界线%s",

	GuildActivityCell_Go = "前往",
	GuildActivityCell_Show = "查看",

	GuildMemberCell_line = "世界线%s",
	GuildCell_line = "世界线%s",
	GuildFindPage_Loading = "加载中",
	GuildFindPage_ExitCDTip = "退出公会倒计时：%s小时",

	GuildHeadCell_Examine = "审核中",
	GuildHeadCell_Forbid = "未通过",
	--商城
	ShopMall_ExchangeClassify = "请选择[c][FFBA32]%s[-][/c]商品分类",
	ShopMall_ExchangeLevelFilter = "Lv.%s-Lv.%s",
	ShopMall_ExchangeRefine = "精炼",
	ShopMall_ExchangePrice = "价格",
	ShopMall_ExchangeSortInc = "↓",
	ShopMall_ExchangeSortDes = "↑",
	ShopMall_ExchangeSellTip = "上架后强化/卡片会自动返还",
	ShopMall_ExchangeSellTitle = "正在出售：%s/%s",
	ShopMall_ExchangeRateTitle = "当前税率：%s％",
	ShopMall_ExchangeSellPriceRate = "推荐价格%s",
	ShopMall_ExchangeSell = "上架",
	ShopMall_ExchangeResell = "重新上架",
	ShopMall_ExchangeCancel = "取消",
	ShopMall_ExchangeCancelSell = "取回",
	ShopMall_ExchangeRecordMaxLog = "交易所记录保存%s天，赠送状态保留%s天，未领取的金额和道具保留%s天",
	ShopMall_ExchangePullRefresh = "请用力向下拉进行交易所刷新(≧∇≦)",
	ShopMall_ExchangeCanRefresh = "松开进行交易所刷新(≧∇≦)",
	ShopMall_ExchangeRefreshing = "努力刷新中(>▽<)",
	ShopMall_ExchangeNormalTitle = "商品统计",
	ShopMall_ExchangePublicityTitle = "上架信息",
	ShopMall_ExchangePublicityCountDown = "抢购期剩余%s分%s秒",
	ShopMall_ExchangeEnchant = "此装备拥有极品附魔属性",
	ShopMall_ExchangeHideEnchant = "此装备附魔属性一般",
	ShopMall_ExchangeBuyInfo = "%s购买了",
	ShopMall_ExchangeBuyEmpty = "找了一圈都没有人卖哦",
	ShopMall_ExchangeBuySearching = "正在查看货架...",
	ShopMall_ExchangePriceWait = "正在查询价格…",
	ShopMall_ExchangeRecordReceive = "还有%s条未领取",
	ShopMall_ExchangeRecordNormalBuyNotOverLap = "购买[c][FF8A00]%s[-][/c]〔%s〕的%s，花费%s",
	ShopMall_ExchangeRecordNormalBuyOverLap = "购买[c][FF8A00]%s[-][/c]〔%s〕的共%s个%s，花费%s",
	ShopMall_ExchangeRecordNormalSellNotOverLap = "出售%s给[c][FF8A00]%s[-][/c]〔%s〕，扣税%s共赚取%s",
	ShopMall_ExchangeRecordNormalSellOverLap = "出售%s个%s给[c][FF8A00]%s[-][/c]〔%s〕，扣税%s共赚取%s",
	ShopMall_ExchangeRecordPublicityBuySuccessNotOverLap = "抢购成功%s，出售者[c][FF8A00]%s[-][/c]〔%s〕，花费%s",
	ShopMall_ExchangeRecordPublicityBuySuccessOverLap = "抢购%s个%s，成功%s个，出售者[c][FF8A00]%s[-][/c]〔%s〕，花费%s",
	ShopMall_ExchangeRecordPublicityBuyFail = "抢购%s个%s，失败%s个，退款%s",
	ShopMall_ExchangeRecordPublicityBuyingNotOverLap = "正在抢购%s，预付款%s",
	ShopMall_ExchangeRecordPublicityBuyingOverLap = "正在抢购%s个%s，预付款%s",
	ShopMall_ExchangeRecordBoothCost = "消耗%s打赏积分",
	ShopMall_ExchangeRecordBoothLock = "冻结%s打赏积分",
	ShopMall_ExchangeRecordBoothUnLock = "解冻%s打赏积分",
	ShopMall_ExchangeRecordExpressGived = "，已赠送好友[c][FF8A00]%s[-][/c]〔%s〕",
	ShopMall_ExchangeRecordExpressRefuse = "，赠送好友[c][FF8A00]%s[-][/c]〔%s〕被拒绝",
	ShopMall_ExchangeRecordExpressGiving = "，正在赠送好友[c][FF8A00]%s[-][/c]〔%s〕",
	ShopMall_ExchangeRecordDetailSell = "出售共%s个%s",
	ShopMall_ExchangeRecordDetailSellDetail = "出售给[c][FF8A00]%s[-][/c]〔%s〕%s个",
	ShopMall_ExchangeRecordDetailNormalBuy = "购买共%s个%s",
	ShopMall_ExchangeRecordDetailPublicityBuySuccess = "抢购%s个%s\n\n成功%s个",
	ShopMall_ExchangeRecordDetailBuyDetail = "向[c][FF8A00]%s[-][/c]〔%s〕购买了%s个",
	ShopMall_ExchangeRecordReceived = "[c][1F74BF]已领取[-][/c]",
	ShopMall_ExchangeRecordGiving = "[c][41C419]正在赠送[-][/c]",
	ShopMall_ExchangeRecordGived = "[c][383838]已赠送[-][/c]",
	ShopMall_ExchangeRecordAutoOff = "%s现已无法在交易所中上架出售，请领取您未售出的物品和上架费用",
	ShopMall_ExchangeExpressCredit = "所需额度：%s/%s",
	ShopMall_ExchangeExpressFrom = "%s   赠",
	ShopMall_ExchangeExpressConfirmTip = "是否确认将[c][c65394]%s[-][/c]赠送给好友[c][c65394]%s[-][/c]？",
	ShopMall_ExchangeExpressConfirmBtn = "确认赠送",
	ShopMall_ExchangeExpressConfirmToggle = "匿名赠送",
	ShopMall_ExchangeExpressCan = "购买后可赠送此商品给好友",
	ShopMall_ExchangeExpressCannot = "额度不足，购买后不可赠送",
	ShopMall_IntroduceCount = "交易所数量：[c][1F74BF]%s[-][/c]",
	ShopMall_IntroduceBuyerCount = "已抢购的人数：[c][1F74BF]%s[-][/c]",


	--不在提示
	DontShowAgainCheckStringWithDays = "%s天内不再提示",
	DontShowAgainCheckString = "不再提示",

	AdventureSkill_AdventureSkill = "冒险技能",
	AdventureSkill_CostAdventureSkillPoint1 = "需要消耗%s点冒险技能点",
	AdventureSkill_NeedCostAdventureSkillPoint = "需要消耗[c][ff0000]%s[-][/c]点冒险技能点",
	AdventureSkill_AdventureLevelCanLearn = "%s可学技能",
	AdventureSkill_NeedReachAdventureLevel = "需成为%s",
	AdventureSkill_LearnCondition = "学习条件",
	AdventureSkill_PreSkill = "前置技能",
	AdventureSkill_CostAdventureSkillPoint2 = "消耗冒险技能点：%s",

	GuildData_Chairman = "会长",
	GuildData_ViceChairman = "副会长",
	GuildData_Member1 = "队员1",
	GuildData_Member2 = "队员2",
	GuildData_Member3 = "队员3",

	FunctionNpcFunc_GuildUpgradeConfirm = "公会资金到达%s才能进行升级。\n升级还需消耗%s个%s。",
	FunctionNpcFunc_GuildUpgrade = "公会等级提升",
	FunctionNpcFunc_GetOldConsumeTip = "非常感谢你对预言之地测试的支持呢！[ffff00]你可以领取的Zeny为%s，限定特典%s张，是否要现在就领取呢？领取后你的其他角色就不能领取了哦~[-]",
	FunctionNpcFunc_LaterGetOldConsumeTip = "没关系，我会一直为你保管至[ffff00]%02d月%02d号%02d点[-]，一定要记得来拿哦！",
	FunctionNpcFunc_GetOldConsumeButton = "确认领取",
	FunctionNpcFunc_LaterGetOldConsumeButton = "稍后领取",
	FunctionNpcFunc_RandomReportPvp = "随机报名",
	FunctionNpcFunc_SecretReportPvp = "密码报名",
	FunctionNpcFunc_CancelReporting = "取消报名",
	FunctionNpcFunc_Reporting = "报名中",
	FunctionNpcFunc_UnlockTip = "解锁%s试炼需要消耗%s。",
	FunctionNpcFunc_Unlock = "解锁",
	FunctionNpcFunc_Cancel = "取消",

	FunctionItemFunc_UseFail = "使用失败~~",

	FunctionNpcFunc_GiveUpGuildLand = "放弃据点",
	FunctionNpcFunc_CancelGiveUpGuildLand = "放弃中",


	ClientTimeUtil_Online = "[c][166C01]在线[-][/c]",
	ClientTimeUtil_OfflineSecond = "1分钟",
	ClientTimeUtil_OfflineMinute = "%d分钟前",
	ClientTimeUtil_OfflineHour = "%d小时前",
	ClientTimeUtil_OfflineDay = "%d天前",
	ClientTimeUtil_OfflineWeek = "%d周前",
	ClientTimeUtil_OfflineMonth = "%d个月前",
	ClientTimeUtil_OfflineToday = "今天",
	
	-- 公会创建
	FunctionGuild_GuildCreateTip = "创建公会必须满足以下几点：",
	FunctionGuild_GuildCreateLvCondition = "1、等级到达%s级",
	FunctionGuild_GuildCreateItemCondition = "%s、需要%s ×%s",
	FunctionGuild_GuildCreateGoldCondition = "%s、身上需要携带%s%s",

	GuildOpenRaidDialog_OpenFuben_Dialog = "通向瓦尔哈拉遗迹的大门，需要消耗%s才能进入。",
	GuildOpenRaidDialog_Ge = "个",
	GuildOpenRaidDialog_OpenFuben_LevelLimit = "（需要等级%s才能开启）",
	GuildOpenRaidDialog_OpenFuben_Dialog_1 = "（大门将在%02d:%02d:%02d:%02d后重置）",
	GuildOpenRaidDialog_OpenFuben_Dialog_2 = "（大门将在[c][ff0000]%02d天%02d:%02d:%02d[-][/c]后重置，大门内的空间很不稳定，无法开启/解锁）",
	GuildOpenRaidDialog_EnterFuben_Dialog = "通向幽暗的试炼场，似乎藏着很多危险，带上同伴进行挑战吧。",
	GuildOpenRaidDialog_EnterFuben_LockTip = "公会大门暂未解锁，需要公会至%s级。",

	GPrayTypeCell_Pray = "祝福",
	GFaithTypeCell_Pray = "祝福",
	GuildPrayDialog_Title = "祈祷等级上限受公会等级影响",
	GuildPrayDialog_PrayTip = "您将获得[ff0000]%s祝福[-]，%s提升%s\n需使用银币%s（优先使用%s），贡献%s。",
	GuildPrayDialog_Pray_FullTip = "[ff0000]%s祝福[-]已提升至满级。",

	GvGPvPPray_Dialog = "%s提升%s\n需使用%s个%s。",
	GvGPvPPray_DialogLimit = "[ff0000]%s[-]已提升至满级。",

	PlayerTip_AlreadyHaveTeam = "已有组队",
	PlayerTip_NoGuildTip = "[c][777777]暂无公会[-][/c]",
	PlayerTip_GuildTip = "[c][1F9403]%s[-][/c]",
	PlayerTip_MasterTip = "雇主：%s",
	PlayerTip_DoubleAction = "双人动作",
	PlayerTip_ExpireTime = "剩余时间：%s",
	PlayerTip_Day = "天",

	FunctionPlayerTip_TalkAuthorization = "授权麦克风",

	ItemTipFuncCell_Down = "卸下箭矢",

	--副本倒计时
	Dungeon_CountDown = "正在进入%s",

	--附魔
	EnchantView_Attri = "属性列表",
	EnchantView_PrimaryEnchant = "初级附魔",
	EnchantView_MediumEnchant = "中级附魔",
	EnchantView_SeniorEnchant = "高级附魔",
	EnchantView_EnchantTip = "你需要为这件“%s”进行1次%s吗？当然为此需要支付些费用",

	EnchantInfo_RefineCondition = "精炼+%s有效",

	EnchantInfoLabelCell_CombineEffectFormat = "%s %s\n效果 %s",

	-- 附魔转移
	EnchantTransferView_BtnName = "转移",
	EnchantTransferView_Empty = "没有找到合适的装备",
	EnchantTransferView_NoEnchant = "无附魔",

	--邮件
	Post_Receive = "领取",
	Post_Delete = "删除",
	Post_Tip = "邮件最多保存%s天",

	InstituteResultPopUp_DailyScore = "本次得分：",
	InstituteResultPopUp_RewardScore = "[FC7508]（超过今日最高得分%s，获得奖励）[-]",
	InstituteResultPopUp_FailScore = "[FC7508]（未超过今日最高得分）[-]",

	Login_SDKLoginFailure = "sdk登陆失败",
	Login_SDKLoginCancel = "sdk登陆取消",
	Login_SDKLaunchFailure = "sdk启动失败",
	Login_AuthHostHandlerFailure = "AuthHostHandler failure(获取'验证地址acctoken_url'失败) status:%s,content:%s",
	Login_AuthAccTokenHandlerFailure = "AuthAccTokenHandler failure status:%s,content:%s,token:%s",
	Login_CheckAccTokenValidFailure = "checkAccTokenValid failure content:%s,token:%s,resson:%s",
	Login_ActiveFailure = "activeCallback active failure status:%s,content:%s,cdkey:%s",
	Login_TokenInValid = "登陆成功，但token 为空！",
	Login_ConnectingServer = "o(╯□╰)o正在连接服务器......",
	Login_SdkLoginNoneSdkType = "sdkType is %s:",
	ActivePanel_Title = "输入激活码，开启冒险之旅",
	ActiveErrorBord_ErrorTitle = "您输入的激活码无效或已被使用！请核对您的激活码！",
	ActiveErrorBord_Cancel = "重新输入",
	ActiveErrorBord_Confirm = "获取激活码",

	--设置
	Set_GameTime = "[383838]今日战斗时长：[-]%s[1f74bf]/%s[-] [383838]分钟[-]",
	Set_GameTimeTip = "获得%s分钟美妙旋律的宁静",
	Set_GameTutortimeTip = "获得%s分钟来自学生的激励",

	PlayerDetailView_PartnerName = "伴侣：%s",
	PlayerDetailView_CompareTip = "对比",

	UIWarning_ReconnectLabel = "等待重连",

	ReplaceView_ReplaceTitle = "置换材料（%s/%s）",
	ReplaceView_ReplaceTip = "你身上穿戴的”%s“我可以帮你置换成”%s“哦~",
	ReplaceView_ReplaceSuccess = "你的装备已经置换成功了，试试新装备吧",

	GuildDonateItemCell_ItemName = "%s（%s/%s）",

	GuildDonateConfirmTip_NeedNum = "需求：%s个",
	GuildDonateConfirmTip_HaveNum = "已拥有：%s个",
	GuildDonateConfirmTip_GuildReward = "公会获得：",
	GuildDonateConfirmTip_MyReward = "%sx%s",
	GuildDonateConfirmTip_And = "、",

	GuildDonateView_NextRefreshTimeTip = "下个订单 ",
	GuildDonateView_OrderCountTip = "已有订单  %s/%s",
	QuestDetailTip_Process = "进度：%s",
	QuestDetailTip_Reward = "奖励：",
	QuestDetailTip_MultReward = "选择性奖励，不可查看",

	NearlyCreatureCell_NameTip = "%s %s",

	FunctionDialogEvent_And = "，",
	FunctionDialogEvent_MaterialFormat = "%s（%s/%s）",
	FunctionDialogEvent_ZenyCost = "以及Zeny×%s",
	FunctionDialogEvent_Replace = "打洞",
	FunctionDialogEvent_Upgrade = "升级",

	--摩天轮
	SkyWheel_Invite = "心中存有对某人的思念以及爱慕之心，才能驱动［%s］那么，你心中那个心心念念的人是谁呢？",
	SkyWheel_Accept = "[6a9af6]%s[-]满怀着一份真挚的情感邀请你一起乘坐恋之［%s］，你是否愿意回应这份心意呢？",
	SkyWheel_Countdown = "%s秒",

	--装备制作
	EquipMake_Title = "制作材料（%s/%s）",

	--配方Tips
	Formula_Tips = "%s        %s/%s",
	Formula_Make = "制作配方",
	Formula_LvUp = "升级配方",
	Formula_LvUpFrom = "通过%s升级",
	Fromula_format="阶段 %s :",
	Formula_End="End",

	--装备熔炉
	EquipRecover_Strength = "还原强化和加固等级",
	EquipRecover_Card = "拆卸%s",
	EquipRecover_EmptyCard = "拆卸卡片",
	EquipRecover_Enchant = "附魔移除",
	EquipRecover_Upgrade = "还原升级档",

	SceneBottomNameFactionCell_Husong = "[护送中]",

	--通服切线
	ChangeZone_Name = "世界线%s",
	ChangeZone_Type = " （%s）",
	ChangeZone_Guild = "公会",
	ChangeZone_Team = "队伍",
	ChangeZone_User = "最近",
	ChangeZone_ChangeLine = "跳跃世界线",
	ChangeZone_BackGuildLine = "前往公会线",
	ChangeZone_ChangeGuildLine = "确认搬家",
	ChangeZone_CancelChangeGuildLine = "取消搬家",
	ChangeZone_Tip = "请输入想前往的世界线编号",
	ChangeZone_FreeTip = "第%s条世界线目前处于空闲状态，请享受你的旅途与冒险",
	ChangeZone_BusyTip = "第%s条世界线现在非常拥挤，传送时请注意安全",
	ChangeZone_VeryBusyTip = "第%s条世界线已完全饱和，传送会变的很危险，请小心",

	ChangeZoneProxy_PvpLine = "斗技场",

	ChangeGuildZone_Name = "%s搬家",
	ChangeGuildZone_Current = "当前世界线：%s",

	--礼包码
	GiftActive_Title = "请输入礼包码",

	ServiceErrorUserCmdProxy_Maintain = "公告",
	ServiceErrorUserCmdProxy_Confirm = "确认",

	-- login role
	LoginRole_CreateRole = '创建角色',
	LoginRole_LoginRole = '开始游戏',
	LoginRole_CancelDelete = '取消删除',
	Hours = '%d小时',

	--道场
	CountDownTip = "全部阵亡，道场将在[ff8a00]%s秒[-]后关闭",
	Dojo_Reward = "获得奖励",
	Dojo_HelpReward = "协助奖励",
	Dojo_Secend = "%s秒",

	FunctionXO_AlreadyAnswerdTip = "恭喜你通过了本次答题环节，那么你还能在下一次找到我时，接受我的脑力考验。",
	FunctionXO_AlreadyAnswerdFailedTip = "很抱歉，你回答错误，那么你只能在下一次找到我时，接受我的脑力考验吧！",

	--自动锁定魔物
	AutoAimMonster_Tip = "锁定目标：%s",

	TempPackageView_RefreshTip = "%s 后将从临时包包中消失",

	GuildEventCell_TimeTipMonth = "1个月前",
	GuildEventCell_TimeTipWeek = "1周前",
	GuildEventCell_TimeTipDay = "%s天前",
	GuildEventCell_TimeTipYestaday = "昨天",
	GuildEventCell_GuildTreasure = "%s[c][FF8A00FF][查看宝箱奖励][-][/c]",

	Giving = "赠",

	OriginalResolution = "原始分辨率",

	BuffCell_BuffActive = "（生效中）",
	BuffCell_BuffInActive = "（暂停中）",
	BuffCell_DELeftTimeTip = "剩余加速时长：%s分钟",

	PhotoCameraDisTip = "高度%sM",
	PhotoFilter_Effect = "显示特效",

	Transmit = "传送",
	TeammateTransmit = "组队传送",
	KaplaTransmit_SelectTransmitType = "请选择传送的服务类型",
	KaplaTransmit_SelectTransmitDestination = "请选择你想选择的地方^_^",
	KaplaTransmit_TeammateTransmitTutorial = "请选择你队伍想前往的地方，只有跟随你的队友才能一起抵达哦^_^\n*每多一位跟随队友都需要你额外多支付一份传送费用。",
	kaplaTransmit_HandInHandTransmitTutorial = "请选择你想选择的地方^_^\n你和%s牵手传送需要支付20%%的服务费，以保证一起安全抵达^_^",

	MainViewFightPage_YoyoPvpName = "溜溜猴大乱斗",
	MainViewFightPage_GorgeousMetalPvpName = "华丽金属抢夺战",
	MainViewFightPage_DesertWolfPvpName = "沙漠之狼斗技场",
	MainViewFightPage_YoyoPvpScore = "当前人数：%s/%s\n个人积分：%s",
	MainViewFightPage_DesertWolfPvpScore = "己方积分：%s/%s\n敌方积分：%s/%s",
	MainViewFightPage_GorgeousMetalPvpScore = "剩余血量%s%%",

	MainViewGvgPage_LeftTime = "%02d:%02d",
	MainViewGvgPage_GvgPageTitleDes = "占领公会:\n%s\n%s",
	MainViewGvgPage_GvgPageNoDefine = "未被占领的城池",
	MainViewGvgPage_DangerState_Def = "[c][00D2F5FF]距完美保护华丽水晶取胜还有%s[-][/c]",
	MainViewGvgPage_DangerState_Attack = "[c][F8121FFF]距敌方完美保护华丽水晶还有%s[-][/c]",
	MainViewGvgPage_FinishState_SpecialSus = "[c][00D2F5FF]已夺下此城，无需防守[-][/c]",
	MainViewGvgPage_FinishState_Unbreak = "华丽金属未被击破",
	MainViewGvgPage_FinishState_Break = "华丽金属已被击破",
	MainViewGvgPage_FinishState_DefSusCountLabel = "[c][F8121FFF]防守方完美胜利[-][/c]",
	MainViewGvgPage_FinishState_AttackSusCountLabel = "[c][F8121FFF]华丽水晶被击破[-][/c]",
	MainViewGvgPage_TitleDes = "公会战%02d:%02d",
	MainViewGvgPage_HonorValue = "本场荣誉值%s/%s",
	MainViewGvgPage_GvgQuestTip_Accepted = "个人目标",
	MainViewGvgPage_GvgQuestTip_Empty = "个人目标为空",
	MainViewGvgPage_GvgQuestTip_KillUser = "每击杀1名敌方玩家",
	MainViewGvgPage_GvgQuestTip_KillUserDes = "累计击杀敌方阵营玩家（%s人）",
	MVPFightInfoBord_Title = "MVP竞争战",


	MainViewGvgPage_NormalState_Def = "[c][00D2F5FF]保护华丽水晶直到公会战结束[-][/c]",
	MainViewGvgPage_NormalState_Attack = "[c][F8121FFF]请尽快击破华丽水晶[-][/c]",

	MainViewPolyFightPage_GoldAppleNum = "拥有：%s {itemicon=%s}",
	MainViewPolyFightPage_TimeLineDes = "%02d:%02d:%02d",
	MainViewPolyFightPage_Title = "波利大乱斗",
	MainViewPolyFightPage_CurPersonNum = "当前人数：%s/%s",
	MainViewPolyFightPage_MyRank = "我的排名：第%s名",

	DesertWolf_Challenge="挑战",
	DesertWolf_WaitChallenge="等待挑战",
	DesertWolf_SendChallenge="已发起挑战",
	DesertWolf_InviteChallenge="%s%s\n向你发起[e59118]沙漠之狼挑战[-]",
	DesertWolf_ChallengeEnter="进入",
	DesertWolf_OwnRoom="[e59118]我的队伍[-]",

	GorgeouseMetalRoomCell_RoomTip = "房间%02d",
	GorgeouseMetalRoomCell_MyRoomTip = "我的房间",

	--商人
	Businessman_ProduceRate = "成功率：%.2f%%",
	Businessman_Need = "需要学习",
	Businessman_AttributeWeaponTitle = "属性武器制作",
	Businessman_MagicStoneTitle = "魔石制作",
	Businessman_SharpGoldTitle = "尖锐合金制作",
	Businessman_MedicineTitle = "药水制作",
	Businessman_PropertyTitle = "炼金用品制作",
	Businessman_RunestoneTitle = "符文石制作",

	--pvp
	Pvp_DesertWolfJoinName = "%s_的队伍",
	--溜溜猴
	PullRefreshYoyoRoom = "下拉刷新房间列表(≧∇≦)",
	LoosenRefreshYoyoRoom = "松开刷新房间列表 (≧∇≦)",
	YoyoRoomRefreshing = "努力刷新中 (>_<)",

	TeamPws_TenThousand = "%s万",
	TeamPws_Preparing = "准备中",
	TeamPws_InMatch = "匹配中",
	TeamPws_FightCount = "本周排位赛剩余次数：%d/%d",
	TeamPws_MyLevel = "我的段位：%s",
	TeamPws_MyScore = "我的积分：%d",
	TeamPws_TeamScore = "当前战队均分：%d",

	GorgeousMetalView_PullRefreshTip = "下拉刷新房间列表(≧∇≦)",
	GorgeousMetalView_BackRefreshTip = "松开刷新房间列表 (≧∇≦)",
	GorgeousMetalView_RefreshingTip = "努力刷新中 (>_<)",
	
	SetViewSecurityPage_TabText = "详细设置",
	SetViewSecurityPage_SwitchRoleLabel = "切换角色",
	SetViewSecurityPage_SecurityEventTipText = "开启后进行下列行为需要输入安全码",
	SetViewSecurityPage_TipLabelText = "安全密码状态:%s",
	SecurityPanel_PwFormatTip = "安全密码可以由6到12位数字与字母组成",
	SetViewSecurityPage_UnSet = "未设置",
	SetViewSecurityPage_ResetPassDelay = "安全密码状态:[c][FFC956FF]%s后重置[-][/c]",
	SetViewSecurityPage_valiable = "已生效",
	SetViewSecurityPage_SecurityModifyBtnText = "修改",
	SetViewSecurityPage_SecuritySetBtnText = "设置",
	SetViewSecurityPage_SecurityCancelBtnText = "取消",
	SetViewSecurityPage_SecurityResetBtnText = "重置",
	SetViewSecurityPage_SecurityResetTimeLeft = "%s天%s时%s分",
	
	SecurityPanel_Title_Set = "安全密码设置",
	SecurityPanel_Title_Confirm = "安全密码验证",
	SecurityPanel_CodeInputTipOrigin = "原密码",
	SecurityPanel_CodeInputTip = "输入密码",
	SecurityPanel_CodeInputTipConfirm = "确认密码",
	SecurityPanel_CodeInputTipType = "点击输入",

	--卡片制作
	CardMark_EndDialog = "期待您的下次光临~",
	CardMark_Tip = "长按卡片查看详细，剩余次数：%s/%s",

	AstrolabeView_Active = "激活",
	AstrolabeView_Reset = "重置",
	AstrolabeView_infoShow = "信息显示",
	AstrolabeView_infoHide = "信息隐藏",

	HireCatPopUp_Hire = "续约",
	HireCatPopUp_Cancel = "取消",
	HireCatPopUp_HireDay = "雇佣%s天",

	--帮助
	Help_Title = "帮助",
	Help_RuleDes="规则说明",

	CardPosChoosePopUp_Title = "请选择插槽",
	CardPosChoosePopUp_CostTip = "消耗：",
	CardPosChoosePopUp_Confirm = "确认",
	CardPosChoosePopUp_Cancel = "取消",

	NpcCharactorSplit = "\n",

	--网络错误
	FunctionNetError_UnKnownError = "未知错误%s",

	--载具界面
	CarrierSubView_Leave = "离开",

	FoodMakeView_ChoosePotTip = "请选择烹饪厨具",
	FoodMakeView_SuccessRateTip = "成功率：",
	FoodGetPopUp_MakeTip = "由%s烹饪成功",
	FoodGetPopUp_FoodType1 = "煎炒类",
	FoodGetPopUp_FoodType2 = "烧烤类",
	FoodGetPopUp_FoodType3 = "汤类",
	FoodGetPopUp_FoodType4 = "点心生煎类",

	FoodGetPopUp_EffectTip = "营养价值：\n",
	FoodGetPopUp_SaveHSpTip = "储备效果：\n",
	FoodGetPopUp_SavePower_Desc = "增加%s储备%s",
	FoodGetPopUp_SavePower_And = "，",
	FoodMakeView_Diff_All = "全部",
	FoodMakeView_Diff_Star = "星",

	FoodRecipeTip_PutMaterials = "放入食材",
	FoodRecipeTip_RecipeTip = "食谱：",
	FoodRecipeTip_Recipe_Family_Tip = "%s熟练度：",
	FoodRecipeTip_RecipeMaterial_FamilyTip = "%s　　%s/%s",
	FoodRecipeTip_Cook_Proficiency = "%s烹饪熟练度：%s级 %s%%",
	FoodRecipeTip_Eat_Proficiency = "%s品尝熟练度：%s级 %s%%\n每提升1级熟练度，营养价值持续时间增加%s分钟",
	FoodRecipeTip_MinusSuccrateTip = "[c][ff0000]厨师等级不够，制作这个料理成功率很低。[-][/c]",

	FunctionFood_UnLockRecipe = "解锁新配方 %s",
	FunctionFood_FoodCookLvUp = "%s 烹饪熟练度升至Lv.%s",
	FunctionFood_FoodTasteLvUp = "%s 品尝熟练度升至Lv.%s",

	FoodMakeLvUpPopUp_TitleTip = "料理协会因你在烹饪各类美食上的杰出表现，授予“[c][1F74BF]%s[-][/c]”称谓",
	FoodMakeLvUpPopUp_TitleTip2 = "包包空间增加%s格\n获得[[c][1F74BF]%s[-][/c]]增加[c][1F74BF]%s[-][/c]成功率",

	FoodTastLvUpPopUp_TitleTip = "料理协会因你在品尝各类美食上的杰出表现，授予“[c][1F74BF]%s[-][/c]”称谓",
	FoodTastLvUpPopUp_TitleTip2 = "品尝料理后，增加料理buff有效堆叠上限至[c][1F74BF]%s[-][/c]层",

	EatFoodPopUp_EatTip = "有%s位冒险者正在食用中",
	EatFoodPopUp_EatSelf = "自己品尝",
	EatFoodPopUp_PetEat = "宠物品尝",
	EatFoodPopUp_EditTitle = "请选择可食用人群",

	--星座絮语
	Star_Content = "[c][3171B0]To:%s[-][/c]\n%s",

	-- 活动 B格猫
	ActivityData_BCAT_TraceTitle = "B格猫入侵中",
	ActivityData_BCAT_EACTPROGRESS_1 = "入侵预警中",
	ActivityData_BCAT_EACTPROGRESS_2 = "猫飞碟高空盘旋中",
	ActivityData_BCAT_EACTPROGRESS_3 = "猫飞碟低空作战中",
	ActivityData_BCAT_EACTPROGRESS_SUCCESS = "退治成功",
	ActivityData_BCAT_EACTPROGRESS_FAIL = "抵抗失败",
	ActivityData_BCAT_MapInfo = "[ff0000]发生事件：B格猫入侵[-]",
	-- 活动 白幽灵
	ActivityData_CRAZYGHOST_TraceTitle = "幽灵暴走事件",
	ActivityData_CRAZYGHOST_EACTPROGRESS_1 = "有什么要来了...",
	ActivityData_CRAZYGHOST_EACTPROGRESS_2 = "它来了...",
	ActivityData_CRAZYGHOST_EACTPROGRESS_SUCCESS = "净化成功",
	ActivityData_CRAZYGHOST_EACTPROGRESS_FAIL = "它逃跑了...",
	ActivityData_CRAZYGHOST_MapInfo = "[ff0000]发生事件：白幽灵暴走[-]",
	ActivityData_HourDes = "%s\n%s天%s小时%s",
	ActivityData_TimeLineDes = "%s\n%02d:%02d:%02d%s",
	ActivityData_SubActHourDes = "%s天%s小时%s",
	ActivityData_SubActTimeLineDes = "%02d:%02d:%02d%s",
	ActivityData_Start = "后开启",
	ActivityData_Finish = "后结束",
	ActivityData_ViewDetailLabelText = "了解详情",
	ActivityData_GoLabelText = "立即前往",
	ActivityData_Kapula_TraceTitle = "[8064B4]神秘的声音[-]",
	ActivityData_Kapula_TraceText = "（请···帮帮···我们）",
	ActivityData_PositionTip = "地点：",

	DecomposeItemCell_ResultTip1 = "超低概率",
	DecomposeItemCell_ResultTip2 = "低概率",
	DecomposeItemCell_ResultTip3 = "大概率",
	DecomposeItemCell_ResultTip4 = "超大概率",
	DecomposeItemCell_ResultTip5 = "百分百",

	RoleEquipBagData_Shield = "副手",

	RoleEquipStrengthCell_NoEquip = "未装备",
	RoleEquipStrengthCell_StrengthLv = "强化等级：",

	UIPlayerSceneInfo_IDTip = "ID：[78BFE7FF]%s[-]",

	FunctionPlayerTip_SendMessage = "发送消息",
	FunctionPlayerTip_InviteMember = "组队",
	FunctionPlayerTip_ApplyTeam = "申请入队",
	FunctionPlayerTip_AddFriend = "添加好友",
	FunctionPlayerTip_ShowDetail = "查看详情",
	FunctionPlayerTip_SetLeader = "升为队长",
	FunctionPlayerTip_KickMember = "踢出队伍",
	FunctionPlayerTip_LeaverTeam = "离开队伍",
	FunctionPlayerTip_FollowMember = "前往跟随",
	FunctionPlayerTip_CancelFollowMember = "取消跟随",
	FunctionPlayerTip_CreateTeam = "创建队伍",
	FunctionPlayerTip_JoinTeam = "加入队伍",
	FunctionPlayerTip_InviteFriend = "邀请队员",
	FunctionPlayerTip_InviteJoinHand = "邀请牵手",
	FunctionPlayerTip_CancelJoinHand = "取消牵手",
	FunctionPlayerTip_ApplyList = "申请列表",
	FunctionPlayerTip_GuildRecruit = "公会招募",
	FunctionPlayerTip_GiveGift = "赠送礼物",
	FunctionPlayerTip_DeleteFriend = "删除好友",
	FunctionPlayerTip_ApplyEnterGuild = "申请入会",
	FunctionPlayerTip_InviteEnterGuild = "招募会员",
	FunctionPlayerTip_KickGuildMember = "逐出公会",
	FunctionPlayerTip_DistributeArtifact = "分配神器",
	FunctionPlayerTip_ChangeGuildJob = "职位变更",
	FunctionPlayerTip_KickChatMember = "踢出房间",
	FunctionPlayerTip_ExchangeRoomOwner = "转移房主",
	FunctionPlayerTip_AddBlacklist = "加入黑名单",
	FunctionPlayerTip_ForeverBlacklist = "永久拉黑",
	FunctionPlayerTip_RemoveFromBlacklist = "移出",
	FunctionPlayerTip_FireHireman = "解雇此喵",
	FunctionPlayerTip_ReHireCat = "续约此喵",
	FunctionPlayerTip_Pet_GiveGift = "赠礼",
	FunctionPlayerTip_Pet_Touch = "抚摸",
	FunctionPlayerTip_Pet_CallBack = "休息",
	FunctionPlayerTip_Pet_ShowDetail = "查看",
	FunctionPlayerTip_Pet_Hug = "抱起",
	FunctionPlayerTip_Pet_CancelHug = "放下",
	FunctionPlayerTip_Pet_HandInHand = "牵手",
	FunctionPlayerTip_Pet_AutoFight = "战斗-开",
	FunctionPlayerTip_Pet_CancelAutoFight = "战斗-关",
	FunctionPlayerTip_Pet_CancelHandInHand = "取消牵手",
	FunctionPlayerTip_Tutor_Tutor = "拜为导师",
	FunctionPlayerTip_Tutor_Student = "招收学生",
	FunctionPlayerTip_Tutor_DeleteTutor = "移除关系",
	FunctionPlayerTip_WeddingMissYou = "好想你",
	FunctionPlayerTip_WeddingCallBack = "欢迎回来",
	FunctionPlayerTip_Booth = "查看摊位",

	PropEffect_NoGrow = "无成长属性",

	--扭蛋机
	Lottery_MonthGroupFirst = "%d年上",
	Lottery_MonthGroupSecond = "%d年下",
	Lottery_Discount = "%d%%OFF",
	Lottery_RecoverTitle = "换取%s",
	Lottery_DetailRate = "概率:%.3f%%",
	Lottery_TodayLimit = "今日抽取上限：%s/%s",
	Lottery_DiscountLimit = "活动折扣上限：%s/%s",
	Lottery_DiscountTime = "折扣时间：%s月%s日-%s月%s日",
	Lottery_RateUrl = "《仙境传说RO：守护永恒的爱》随机抽取类玩法概率、结果公示：https://www.taptap.com/topic/2984410",
	Lottery_RateTip = "抽取概率：%.3f%%",
	Lottery_Left = "其他",
	Lottery_MagicRateTip = "*每个大类下不同道具抽取概率略有不同",
	Lottery_SendTip = "赠送给好友的扭蛋盒正在打包中…每个扭蛋盒内含10个当月扭蛋哦~",
	Lottery_PresentReceiver = "请选择收件人",
	Lottery_PresentFrom = "%s 赠",
	Lottery_TitleDesc = "%s年%s月扭蛋盒（10枚)",
	Lottery_BuyCount = "今日限购%s/%s",
	LotteryRedLimit = "[c][e91010]%s[-][/c]",

	-- 宠物
	PetInfoView_UnlockBody = "Lv.%s 解锁",
	PetInfoView_UnlockTip = "好感度Lv.%s 解锁%s",
	PetInfoView_EquipUnlockTip = "[c][ff0000]好感度%s级解锁制作图纸[-][/c]",
	PetInfoView_Unlock = "解锁",
	PetInfoView_Unlock_Adventure = "派遣",
	PetInfoView_Unlock_PetWort = "打工",
	PetInfoView_Unlock_PetWort_MulTime = "好感度Lv.%s 提高打工效率%s%%",
	PetInfoView_Unlock_Fashion = "饰品部位",
	PetInfoView_Unlock_Equip = "装备",
	PetInfoView_Unlock_Unload = "卸下",
	PetInfoView_NoGet = "尚未获得",
	PetInfoView_CanEquip = "[c][166C01]可装备[-][/c]",
	PetInfoView_AttriNoEffect  = "[c][166C01]可装备，属性无法生效[-][/c]",
	PetSkillTip_NoUpgrade = "不可升级",
	
	PetMakeNamePopUp_Cancle = "取消",
	PetMakeNamePopUp_Confirm = "确认",
	PetMakeNamePopUp_PutInBag = "放入背包",
	PetMakeNamePopUp_Hatch = "孵化",

	PetFashionCell_UnlockTip = "Lv.%s 解锁",

	-- 宠物打工
	PetWorkSpace_Introduce = "亲爱的冒险者\n  卢恩王国因人口老龄化的原因出现了一批空缺的职位，国王决定征召冒险者的宠物们作为小小雇佣工～～不管什么体型，什么性格，什么能力的宠物，都能在这里找到一份适合的工作，我们会给予宠物们丰厚的奖励！",
	PetWorkSpace_Tips = "宠物等级和好感度越高，频率越快",
	PetWorkSpace_Level = "要求：Lv.%s",
	PetWorkSpace_DescFrequency = "频率：每[c][1d9fff]%s分钟[-][/c]获得1次报酬[%s/%s]",
	PetWorkSpace_Working = "工作中 %s",
	PetWorkSpace_IntroduceTitle = "王国招募",
	PetWorkSpace_unLockSpaceName = "?",
	PetWorkSpace_Rest = "休息中",
	PetWorkSpace_UnlockDesc = "[c][1d9fff][%s][-][/c]每%s分钟获得",
	PetWorkSpace_TitleTip = "账号共享、同时可进行%s/%s场所打工",
	PetWorkSpace_WorkingFlag = "已派遣",
	PetWorkSpace_Scene = "已出战",
	PetWorkSpace_PetName = "[%s]",
	PetWorkSpace_LockDesc = "[c][6c6c6c][%s] %s[-][/c]",
	PetWorkSpace_NoPets = "没有符合打工要求的宠物",
	PetWorkSpace_DefaultAppellation = "见习生",


	-- 宠物冒险
	PetAdventure_Process = "进行中：%s/%s",
	PetAdventure_RecommendPet = "推荐宠物能力:",
	PetAdventure_RecommendPetDes = "每满足一个所需的宠物能力，即可获得一个稀有道具",
	PetAdventure_ConsumeFightTime = "消耗%s分钟战斗时长",
	PetAdventure_UnderWay = "进行中...",
	PetAdventure_ChoosePet = "选择宠物",
	PetAdventure_RewardPreview = "战利品预览",
	PetAdventure_Reward = "战利品",
	PetAdventure_FightEfficiency = "%s%%",
	PetAdventure_OnAdventureTime = "冒险中...剩余%s",
	PetAdventure_MatchPetCount = "派遣数量%s/%s",
	PetAdventure_Fighting = "出战中",
	PetAdventure_OnAdventure = "冒险中",
	PetAdventure_LevelLimited = "需宠物等级Lv.%s",
	PetAdventure_FriendlyLvLimited = "需好感度Lv.%s",
	PetAdventure_Lv = "Lv.%s",
	PetAdventure_newline="%s\n%s",
	PetAdventure_ThreePets="需要%s只宠物参与冒险",
	PetAdventure_Finished="已完成",
	PetAdventure_GetRewardWhenFinshed="冒险完成后获得",
	PetAdventure_NewAdventureName ="%s -%s",
	PetAdventure_PetEffTips="%s的效率\n*等级 %s\n*好感度 %s\n*地图适应 %s\n",
	PetAdventure_RoleTip = "我的效率\n*装备精炼 %s\n*装备附魔 %s\n*星盘 %s\n*冒险家等级 %s\n*卡片存储 %s\n*头饰存储 %s",
	PetAdventure_TipColor = "[c][ffffff]%s[-][/c]",
	PetAdventure_PetEffFunDesc = "（好感度效率+等级效率）*地图收益效率",

	RedeemCodeView_Desc = "您的雷蒙盖顿背包兑换码",
	RedeemCodeView_Tip = "请妥善保管激活码，不要相信任何诈骗信息",

	-- 福袋
	LuckyBag_PurchaseTimesMonth = '[4185C6FF]本月购买次数：%s/[-]%s',
	LuckyBag_PurchaseTimesDay = '今天购买次数：%d/%d',

	-- 拍卖
	Auction_CountdownName = "拍卖行\n%02d:%02d:%02d开启",
	Auction_CountdownDayName = "拍卖行\n%d天后开启",
	Auction_ProgressName = "拍卖行\n正在进行",
	Auction_EndName = "拍卖行\n已结束",
	Auction_MainViewCountdownName = "%02d:%02d",
	Auction_MainViewProgressName = "正在进行",
	Auction_MainViewEndName = "已结束",
	Auction_Countdown = "距离拍卖开始时间：%d天%d小时%d分%d秒",
	Auction_DelayCountdown = "拍品太少，延迟拍卖：%d天%d小时%d分%d秒",
	Auction_Rate = "拍卖成交税：%d％",
	Auction_Price = "出价\n+",
	Auction_DialogAtAuction = "正在拍卖本次第%s个竞拍品！温馨提示：单品拍卖上限%sB格猫金币，出价超过此金额则立即成交。",
	Auction_DialogCountdown = "倒计时%s秒",
	Auction_DialogNextAuction = "即将开始拍卖第%s个商品！",
	Auction_DialogEndTip = "拍卖已结束，次日将公布下次竞拍可提交的商品，请留意！",
	Auction_DialogPublicity = "这些商品将参与本次拍卖！",
	Auction_EventStart = "[%s]拍卖正式开始，拍卖底价B格猫金币%s",
	Auction_EventOfferPrice = "[c][FF8A00][u][url=%s]%s[/url][/u][-][/c]〔%s〕出价B格猫金币%s",
	Auction_EventResult1 = "若无竞价，拍品将由[c][FF8A00][u][url=%s]%s[/url][/u][-][/c]〔%s〕获得",
	Auction_EventResult2 = "拍品即将落锤，还有没有竞价者？",
	Auction_EventResult3 = "最后十秒，拍品即将归[c][FF8A00][u][url=%s]%s[/url][/u][-][/c]〔%s〕",
	Auction_EventResultSuccess = "恭喜[c][FF8A00][u][url=%s]%s[/url][/u][-][/c]〔%s〕成功拍得[%s]",
	Auction_EventResultFail = "拍卖时间内无人出价，[%s]流拍。",
	Auction_EventNext = "，下一场拍卖将在60秒后开始，敬请等待。",
	Auction_EventEnd = "，本次拍卖已结束。",
	Auction_EventNextTip = "前一个竞拍品竞拍结束后，开始拍卖此商品！",
	Auction_EventPublicityTip = "该商品将作为第%s件商品进行拍卖",
	Auction_RecordMaxLog = "拍卖记录最多保存%s天，未领取的金额和道具最多保留%s天",
	Auction_RecordReceive = "还有%s条未领取",
	Auction_RecordBuySuccess = "成功竞拍由[c][FF8A00]%s[-][/c]〔%s〕提供的%s，花费{itemicon=151}%s",
	Auction_RecordSellSucess = "出售%s给[c][FF8A00]%s[-][/c]〔%s〕，扣税{itemicon=100}%s共赚取{itemicon=100}%s",
	Auction_RecordSellFail = "您的%s拍卖结果为流拍，拍卖行退回了道具",
	Auction_RecordOverTakePrice = "其他竞拍者超越了您对%s的出价，可取回出价{itemicon=151}%s",
	Auction_RecordSignUp = "已向拍卖行报名提交%s，请等待抽取，还有%s天%s小时%s分钟%s秒",
	Auction_RecordSignUpSuccess = "拍卖行抽取了您的%s为第%s号拍品，请等待拍卖结束",
	Auction_RecordSignUpFail = "已向拍卖行报名提交%s，未抽取到您的道具，请取回道具",
	Auction_RecordBuyNoPass = "交易异常，您竞拍的%s，价格{itemicon=151}%s，审核未通过，请取回",
	Auction_RecordSellNoPass = "交易异常，您竞拍的%s，价格{itemicon=100}%s，审核未通过，请取回",
	Auction_RecordTakeMoney = "领取金额",
	Auction_RecordTakeItem = "领取商品",
	Auction_RecordRetrieveMoney = "取回金额",
	Auction_RecordTook = "已领取",
	Auction_RecordVerifying = "审核中",
	Auction_RecordRetrieveItem = "取回道具",
	Auction_DontShowAgainTitle = "出价提示",
	Auction_DontShowAgainContent = "在当前竞价%s上加价[c][63cd4e]%s[-][/c]B格猫金币？\n此次总加价[c][63cd4e]%s[-][/c]B格猫金币。\n注：竞拍失败后返还B格猫金币。",
	Auction_DontShowAgain = "本次拍卖不再提示",
	Auction_ItemTip = "本拍品由[c][4059A8]%s[-][/c]提供",

	FunctionVisitNpc_AuctionDialog_OpenTip = "拍卖行将于%s开放。",
	FunctionVisitNpc_AuctionDialog_Month = "月",
	FunctionVisitNpc_AuctionDialog_Day = "日",
	FunctionVisitNpc_AuctionDialog_Hour = "点",

	RecipeData_DunHao = "、",

	--导师
	Tutor_Title = "导师",
	Tutor_Guide_FindStudent = "寻找学生",
	Tutor_Guide_AsTutor = "成为导师",
	Tutor_TutorApply = "希望能够成为你的导师",
	Tutor_StudentApply = "希望能够成为你的学生",
	Tutor_Chat_FindStudent = "寻找学生",
	Tutor_Chat_FindTutor = "寻找导师",
	Tutor_TaskTitle = "%s的冒险任务",
	Tutor_TaskProficiency = "冒险熟练度：[c][427BC1]%.1f%%[-][/c]",
	Tutor_TaskProgress = "[c][427BC1]%s/%s[-][/c]",
	Tutor_TaskFinish = "已完成",
	Tutor_TaskTake = "已领取",
	Tutor_Graduation = "Base等级达到%s级",
	Tutor_FindingStudent = "正在招募学生...",
	Tutor_FindingTutor = "正在寻找导师...",
	Tutor_ReceiveReward = "领取",
	Tutor_Graduate = "毕业",
	Tutor_GrowthTile = "成长奖励",
	Tutor_GrowthRewardTitle = "达成奖励",
	Tutor_GraduationTitle = "毕业条件",
	Tutor_GraduationRewardTtile = "毕业奖励",
	Tutor_MatchSelect = "请选择%s的性别",
	Tutor_Matching = "正在寻找%s···",
	Tutor_FoundMatch = "寻找成功",
	Tutor_Student = "学生",
	Tutor_TutorHint = "对方确认中，是否要成为他的导师",
	Tutor_StudentHint = "对方确认中，是否要成为他的学生",


	GvgLandInfoPopUp_NoGuildTip = "需要拥有公会",
	GvgLandInfoPopUp_OpenTip = "%s月%s日%s时开始公会战",
	GvgLandInfoPopUp_MyLandTip = "防守方建议从公会据点进入防守",
	GvgLandInfoPopUp_NoRuleTip = "-- 无人占领 --",
	GvgLandInfoPopUp_None = "无",
	GvgLandInfoPopUp_JoinGuild = "加入公会",
	GvgLandInfoPopUp_EnterArea = "进入据点",
	GvgLandInfoPopUp_JoinFight = "参加战斗",
	GvgLandInfoPopUp_HaveGuildTip = "您已有公会",

    --todo xde
    FaceBookGiftGetSuccess = "獎勵領取成功，請注意查收郵件~",
    FaceBookShareSuccess = "FaceBook分享成功",
    FaceBookShareFailed = "FaceBook分享失敗",
    FaceBookRewardHasNotUnlocked = "當前獎勵尚未解鎖！",
    FaceBookRewardHasRedeemed = "您已領取過當前獎勵！",
	ShopConfirmTitle = "确定要购买%s吗?（%s %s）",
	ShopConfirmDes = "[FF1616FF]﻿﻿구입하신 고양이 코인은 [메일]로 발송됩니다.\n [메일]을 확인해주세요[-]",
	ShopConfirmDes1 = "[6C6C6CFF]구매 후 7일 이내에는 청약철회가 가능합니다.\n상품을 사용하였거나, 즉시 적용되는 상품의 경우, 청약 철회 대상에서 제외됩니다. \n- 유료 재화부터 우선 소모됩니다 –[-]",
	ShopConfirmTitleMonthly = "月卡确定要购买%s吗？（%s元）",
	ShopConfirmBtnTxt = "[자세히보기]",
	ShopConfirmDesMonthly = "月卡优先消耗付费货币，购买后7日内可以退还。\n但如果使用了商品或发生使用，将无法作为退还对象。",
	ShopConfirmDesTxT = "﻿\n1. 구매일로부터 7일 이내에는 청약철회를 할 수 있습니다.\n  단, 다음의 경우에는 청약 철회가 제한될 수 있습니다. \n  1) 구매 후 즉시 사용이 시작되거나 즉시 적용되는 아이템을 구매하여 수령한 경우 \n  2) 개봉 행위를 사용으로 볼 수 있거나 개봉 시 효용이 결정되는 아이템의 경우 \n  3) 묶음형(패키지)으로 판매된 아이템의 일부가 사용되거나 적용된 경우 \n2. 청약철회는 게임 내 고객센터 또는 문의하기를 이용하여 접수할 수 있으며 접수일로부터 3영업일 이내에 결제 취소를 해드립니다. \n3. 미성년자가 법정대리인의 동의 없이 결제한 경우에는 미성년자 본인 또는 법정대리인은 결제를 취소할 수 있습니다.\n  위의 조건 외의 청약 철회 및 환불은 이용약관 및 운영 정책에 따라 조치됩니다.",
	SetViewTabAbout = "信息", -- setview 中的 “关于” 标签
	NoticeTitle = "알림",
	ConvertTitle = "卡普拉MVP兑换",
	IAPBoughtLimit = "抱歉，“%s”已達到本月購買上限！",
	ActivityProductLimit = "折扣活動已過期，無法購買！",
	STR_CONFIRM_EXIT_GAME = "確定退出遊戲？",
	NoticeTitle = "提示",
	Oversea_MVP_Complete = "达成",
	Oversea_MVP_Best = "[最高]",
	-- 服务器下发的debug信息
	Oversea_SVR_DEBUG1 = "没有找到该宠物",
	Oversea_SVR_DEBUG2 = "没有找到该宠物的配置",
	Oversea_SVR_DEBUG3 = "没有找到该宠物的实体npc",
	Oversea_SVR_DEBUG4 = "背包没了,炸炸炸",
	Oversea_SVR_DEBUG5 = "没有这个装备",
	Oversea_SVR_DEBUG6 = "这个装备不能装",
	Oversea_SVR_DEBUG7 = "皮肤没有变化",
	Oversea_SVR_DEBUG8 = "皮肤未解锁",
	Oversea_SVR_DEBUG9 = "测试log:未找到场景NPC",
	-- 华丽金属抢夺战文本
	Oversea_SVR_HLJS = "击倒玩家: ",
	Oversea_SVR_HLJS = "助攻:     ",
	Oversea_SVR_HLJS = "Combo:    ",
	Oversea_SVR_HLJS = "无畏者:   ",
	Oversea_SVR_HLJS = "救世主:   ",
	Oversea_SVR_HLJS = "伤害:     ",
	Oversea_SVR_HLJS = "有效治疗: ",
	Oversea_SVR_HLJS = " (全场最高 ",
	-- 职业特色 和 就职条件
	Oversea_Job_Speciality = "职业特色：",
	Oversea_Job_Condition = "就职条件：",
	Oversea_Job_Promote = "进阶",
	Oversea_Hard_Code_Server_1 = "找不到目标地图",
	Oversea_Hard_Code_Client_1 = "技能加点:",
	Oversea_Hard_Code_Client_2 = "核心占领度",
	Oversea_Hard_Code_Client_3 = "西部晶塔占领度",
	Oversea_Hard_Code_Client_4 = "东部晶塔占领度",
	Oversea_Hard_Code_Client_5 = "星盘:",
	Oversea_Hard_Code_Client_6 = "是否购买该职业？",
	Oversea_Hard_Code_Client_7 = "在这里没法购买职业",
	-- xx打洞
	Oversea_Hole_1 = "武器打洞",
	Oversea_Hole_2 = "副手打洞",
	Oversea_Hole_3 = "盔甲打洞",
	Oversea_Hole_4 = "靴子打洞",
	Oversea_Hole_5 = "披肩打洞",
	Oversea_Hole_6 = "头饰打洞",
	Oversea_Hole_7 = "饰品打洞",
	Oversea_Hole_8 = "饰品打洞",
	-- 新增翻译
	Oversea_Prefab_1 = "请点击”+“选择所需附魔的装备",
	-- 名动词区分
	Verb_Translation_1 = "装备v",

	--打赏积分卡
	QuotaCard_Desc="凡是打赏都可获得打赏积分：1 Zeny=1点打赏积分；1 B格猫金币=10,000点打赏积分；限定特典=500000点打赏积分。额外赠送部分不获得打赏积分。打赏获得其它道具也将根据您的打赏金额以同样的比例给您打赏积分。",
	QuotaCard_Detail="补充: %s\n余额: %s",
	QuotaCard_Surplus="剩余%s天",
	QuotaCard_SurplusRed="剩余[c][FF0000]%s[-][/c]天",
	QuotaCard_Overdue="已过期",
	QuotaCard_UseUp="已用完",
	QuotaCard_LogDesc_Charge="充值获得",
	QuotaCard_LogDesc_Give="赠送消耗",
	QuotaCard_LogDesc_Auction="拍卖消耗",
	QuotaCard_Lottery = "扭蛋赠送消耗",
	QuotaCard_GuildBox = "公会宝箱消耗",
	QuotaCard_WeddingDress = "赠送婚纱消耗",
	QuotaCard_BoothLock = "摆摊冻结",
	QuotaCard_BoothUnLock = "摆摊解冻",
	QuotaCard_BoothCost = "摆摊消耗",
	QuotaCard_ExchangeGiveLock = "赠送冻结",
	QuotaCard_ExchangeGiveUnLock = "赠送解冻",
	QuotaCard_ExchangeGiveCost = "赠送消耗",
	QuotaCard_ChargeLock = "积分冻结",
	QuotaCard_ChargeUnLock = "冻结解锁",
	QuotaCard_LogDesc_AuctionBack="拍卖失败返回",
	QuotaCard_Loading="加载中",
	QuotaCard_End="没有更多的信息了哦~",
	QuotaCard_Desc2="进行打赏可获得打赏积分",
	QuotaCard_QuotaTitle = "可用：%s",
	QuotaCard_LockTitle = "冻结：%s",
	QuotaCard_ChargeLockTip = "解锁剩余时间：%s小时",

	-- 神器
	ArtifactMake_Title = "公会材料（%s/%s）",
	ArtifactMake_FilterTitle = "所有神器",
	ArtifactMake_MakeBtnName = "制作",
	ArtifactMake_Using = "使用中",
	ArtifactMake_UnUsing = "空闲",
	ArtifactMake_LeftTime = "收回剩余时间%s",
	ArtifactMake_Dist="分配",
	ArtifactMake_Retrieve = "收回",
	ArtifactMake_CancleRetrieve ="取消收回",
	ArtifactMake_DisText="分配神器",
	ArtifactMake_NoData="当前没有可制作的神器",

	-- 公会宝箱
	GuildTreasure_GuildAssetType = "公会资产",
	GuildTreasure_GuildMemberType = "每位成员获得(±50%)",
	GuildTreasure_Tip = "开启后将有概率获得以下物品:",
	GuildTreasure_holdTreasureCount = "剩余个数:%s",
	GuildTreasure_GuildLimit = "剩余次数:%s",
	GuildTreasure_RewardPer = "%s/%s个华丽宝箱",
	GuildTreasure_RewardTitle = "%s的华丽宝箱奖励",
	GuildTreasure_RewardGet = "奖励已领取！",
	GuildTreasure_EmptyTip = "奖励尚未有人领取",
	GuildTreasure_GoBtn = "前往领取",
	GuildTreasure_FixedRewardTitle = "奖励详情",
	GuildTreasure_GuildTreaSure = "所需额度：%s/%s",
	GuildTreasure_ChatTip = "查看宝箱奖励",

	-- 公会设施
	GuildBuilding_RankDesc = "排名",
	GuildBuilding_NameDesc = "玩家名称",
	GuildBuilding_TotalDesc = "升级捐赠次数",
	GuildBuilding_RankName = "[%s]升级贡献榜",
	GuildBuilding_RankEmpty = "当前没有冒险者为设施贡献",
	GuildBuilding_TitleName="公会设施",
	GuildBuilding_Build = "建造",
	GuildBuilding_Levelup = "升级",
	GuildBuilding_isBuilding = "建造中...",
	GuildBuilding_isUpLevel = "升级中...",
	GuildBuilding_StartBuild="已开始%s",
	GuildBuilding_Process = "%s%%",
	GuildBuilding_Title = "%sLv.%s",
	GuildBuilding_Submit_Count = "今日还可提交%s/%s次",
	GuildBuilding_Submit_MatNum="%s/%s",
	GuildBuilding_Submit_Name = "%s(%s/%s)",
	GuildBuilding_FnDes="%s\n\n%s",
	GuildBuilding_TypeLevelUp = "%s升到%s级",
	GuildBuilding_LevelUpPreview = "                      下一等级",

	GuildBuilding_LevelUpPreview_CountDownTime = "活动倒计时：%s天%s时%s分",
	GuildBuilding_LevelUpPreview_SubmitInc = "设施升级进度提升%s%%",
	GuildBuilding_LevelUpPreview_RewardInc = "捐赠个人奖励提升%s%%",

	--快速购买
	QuickBuy_NotExist = "无商品",
	QuickBuy_Publicity = "公示中",
	QuickBuy_NotEnough = "商品不足",
	QuickBuy_Price = "价格    ",
	QuickBuy_TotalCost = "总花费： {itemicon=100} %s {itemicon=110} %s {itemicon=151} %s",
	QuickBuy_Own = "拥有： {itemicon=100} %s {itemicon=110} %s {itemicon=151} %s",
	
	--月卡到期提醒
	MouthCard_End = "当前到期时间：%s-%s-%s",
	MouthCard_None = "未拥有特典特权",

	--公会挑战任务
	GuildChallenge_RefreshTime = "下次刷新时间：%s天%s时%s分%s秒",
	GuildChallenge_Progress = "已挑战：%s/%s",
	SpringActivitySendText = "送上祝福",

	--结婚
	Wedding_EngageDate = "%s.%02d.%02d",
	Wedding_EngageDay = "%02d:00",
	Wedding_EngageDateWday = "%s (%s)",
	Wedding_EngageBookedDate = "%02d:00~%02d:00\n已预约",
	Wedding_EngageCheckDialog = "亲爱的冒险者，这是%s线普隆德拉大教堂近期的神圣仪式排期哦！",
	Wedding_EngageBookDateDialog = "亲爱的冒险者你好呀~看你们洋溢着满脸的幸福~是来挑选那个最重要的日子吧？来看看普隆德拉大教堂的神圣仪式档期吧~显示为【热门】的日子已预定过半，显示为【爆满】的日子已预定完毕哦！",
	Wedding_EngageBookDayDialog = "请选择神圣仪式的时间，从12:00~24:00之间每一小时为一场神圣仪式档期哦！",
	Wedding_EngageBookZone = "预约线路：%s线",
	Wedding_EngageBookDate = "预约时间：%s年%02d月%02d日\n                    %02d:00~%02d:00",
	Wedding_EngageBookCost = "消耗：{itemicon=%s}%s",
	Wedding_EngageBookTarget = "结婚对象：%s",
	Wedding_EngageHot = "热门",
	Wedding_EngageFull = "爆满",
	Wedding_ManualInfo = "%s.%02d.%02d %02d:00~%02d:00   [世界线 %s]普隆德拉大主教堂",
	Wedding_InviteTip = "已发出邀请（%s/%s）",
	Wedding_CharactorCoupleLabel = "婚",
	Wedding_CharNameTip = "%s[c][FF98B5FF](伴侣)[-][/c]",
	Wedding_SendDress = "非常期待你穿上这件礼服的样子呢！要一直这样幸福下去哦~~~",

	OricalCardInfoView_TitleName = "%s，下面是我为你精心准备的一套卡牌，做好准备了吗？",
	OricalCardInfoView_Diff_1 = "[7FCC1AFF]简单[-]",
	OricalCardInfoView_Diff_2 = "[FFC94EFF]一般[-]",
	OricalCardInfoView_Diff_3 = "[AF1F16FF]困难[-]",

	CardDecompose_Material = "%s+?",
	KFCShareURL = "http://party.xd.com/event/2018marb/ro/views/start.html?charid=%s&code=%s",

	--今日财经
	Finance_Ratio = "%.1f%%",
	Finance_DetailRatio = "%.1f%%",
	Finance_DayTip = "%s天前",
	Finance_TodayTip = "今天",
	Finance_TenThousand = "%d万",
	Finance_HundredsMillions = "%d亿",

	-- 今日推荐
	Servant_Recommend_Go = "GO",
	Servant_Recommend_Receive = "领取",
	Servant_Recommend_Received = "已领取",
	Servant_Recommend_HideTip = "隐藏已完成内容",
	Servant_Recommend_ShowTip = "显示已完成内容",

	MainviewMenu_ChuXinSheQu = "初心社区",
	MainviewMenu_HuoDong = "活动",
	MainviewMenu_TongRen = "同人",

	MainviewMenu_HouseKeeper = "执事",
	MVPFightInfoBord_LeftPerson = "当前人数:%s",
	MVPFightInfoBord_MvpLeftTime = "MVP剩余击杀次数:%s",
	MVPFightInfoBord_MiniLeftTime = "MINI剩余击杀次数:%s",
	MVPFightInfoBord_LeftTime = "剩余时间:%02d:%02d:%02d",
	MVPFightInfoBord_LeftMonster = "剩余魔物",
	MainviewGvgFinalPage_TimeDes = "决战时间",
	MainviewGvgFinalPage_Title = "水晶排名",

	GvgFinalFightTip_Title = "GVG信息",
	GvgFinalFightTip_TimeDes = "副本时间",
	GvgFinalFightTip_CoreDes = "核心占领度(归属方)",
	GvgFinalFightTip_WestDes = "西部晶塔占领度(归属方)",
	GvgFinalFightTip_EastDes = "东部晶塔占领度(归属方)",
	GvgFinalFightTip_MetalNumLabel = "总水晶数",
	GvgTowerStateNeutral = "中立",
	MiniMapNearby = "附近",
	MiniMapGVGInfo = "信息",

	DungeonCountDownView_AltmanRaidName = "地球裂隙",
	AltmanInfoBord_LeftTimeTip = "剩余时间：%02d:%02d",
	AltmanInfoBord_KillCountTip = "击败魔物：%s",

	-- 多职业存储
	MultiProfession_Joblv = "Job: [ff8a00]Lv.%s[-]",
	MultiProfession_Astro = "星盘: [ff8a00]%s/%s[-]",
	MultiProfession_Skill = "技能加点: [ff8a00]%s/%s[-]",
	MultiProfession_MonthCardTip = "激活月卡获得此栏位",
	MultiProfession_SaveDate = "%s.%02d.%02d",
	MultiProfession_SaveTime = "%02d:%02d",
	MultiProfession_SaveName = "存档%02d",
	MultiProfession_Info = "人物信息",

	-- MVP匹配
	MVPMatch_tip1 = "冒险者，在警惕其他冒险者们的同时,与你的战友一起参与MVP的争夺吧！",
	MVPMatch_tip2 = "[7e5018]MVP争夺战将在[-][1F74BF]%s[-][7e5018]开放，你和队友可以通过击杀MVP和MINI获得BOSS掉落以及其他材料、荣誉奖励。每次活动存在击杀上限，达到上限将无法继续赢取奖励。[-]",
	MVPMatch_JoinTeam = "加入",
	MVPMatch_InMatch = "匹配中",

	PetAdvance_BuyCaptureItem = "购买捕捉道具",
	PetAdvance_Compose = "融合",

	-- 舞台
	Stage_Photofilter_Pet = "宠物",
	Stage_Photofilter_Partner = "猎人的宝宝",
	Stage_Dialog_Pre = "来参加我们的变装舞会吧~只要%d%s，就可以在大家面前展示你的可爱了哟~",
	Stage_Dialog_StageInfo = "目前%s舞台使用者：%d人 ",
	Stage_Dialog_Sinlge = "单人换装",
	Stage_Dialog_Double = "双人换装",
	Stage_Dialog_Choose = "选择舞台",
	Stage_Name_A = "甜心国王",
	Stage_Name_B = "仲夏夜之梦",
	Stage_Name_C = "心跳嘉年华",
	Stage_WaitInfo = "目前舞台%s需要排队%d秒钟",
	Stage_TeamUp_Tip = "需两人组队时，队长访问才可进行双人换装哦。",
	Stage_Team_Tip = "只有队长可以进行此操作哦",

	--GVG决战
	GVGProtalDesc = "[7e5018]米德加尔特的考古学者们在最近的一次探险中，发现了疑似诸神之战后散落于王国的神之遗迹--[1f74bf]华丽水晶的原始核心[-]。哦据说这些核心是铸造神器的优秀材料哟……\n\n[1f74bf]每周日21:25[-]达成完美防守的公会将获得参与GVG决战的机会\n\nGVG决战由四方公会参与决出排名，并会获得首饰神器碎片奖励！[-]",
	GVGProtalLineUpNotice = "排队进入中，请耐心等待...（剩余约%s秒)",

	-- 追踪商店
	ExchangeShop_Title = "卡普拉公司的问候",
	ExchangeShop_Desc = "卡普拉公司向你致意，新加入的冒险者！卡普拉公司为了初心冒险者们能够尽快成长，现向全大陆的冒险者提供由卡普拉公司特别制造的秘密成长道具！",
	ExchangeShop_Free = "免费领取",
	ExchangeShop_Donate = "捐献材料",
	ExchangeShop_Exchange = "兑换金章",
	ExchangeShop_DonateProgress = "捐献进度:%s/%s",
	ExchangeShop_Reward = "可获得:        %s/%s",
	ExchangeShop_ChooseNum = "X%s=",
	ExchangeShop_RewardNum = "X%s",

	--语音授权
	ENABLE_MIC= "授权麦克风",
	DISABLE_MIC= "解除授权",

	ProfessionInfoViewMP_AddSkillPointTip = "技能加点:",
	ProfessionInfoViewMP_AstrolabeTip = "星盘:",
	ProfessionInfoViewMP_NilTip = "暂未有角色信息",
	ProfessionInfoViewMP_HintLabel = "可通过二转职业切换哦",
	ProfessionInfoViewMP_ProfessionInfoSpc = "职业特色：",
	ProfessionInfoViewMP_ChangeCondition = "就职条件：",

	-- 摆摊
	Booth_SignName = "%s招牌",
	Booth_Name = "%s的商店",
	Booth_Selling = "正在出售：%s/%s",
	Booth_Score = "积分：%s",
	Booth_ExchangeSellPriceRateTip = "推荐价格",
	Booth_IntroduceCount = "摆摊内数量：[c][1F74BF]%s[-][/c]",
	Booth_IntroduceBuyerCount = "已抢购的人数：[c][1F74BF]%s[-][/c]",
	Booth_IntroducePublicity = "[c][1F74BF]%s[-][/c]过于稀缺，已处于[c][CF1C0F]抢购期[-][/c]。",
	Booth_IntroduceWillPublicity = "[c][1F74BF]%s[-][/c]过于稀缺，上架会进入[c][CF1C0F]抢购期[-][/c]。",
	Booth_IntroducePublicityTip = "[c][6C6C6C]仅有处于公示期的摆摊物品才进入交易所展示[-][/c]",
	Booth_IntroducePublicitySellTip = "[c][6C6C6C]摆摊内公示期物品不可按原价上架[-][/c]",
	Booth_IntroducePublicityTime = "[c][1F74BF]%s[-][/c]的[c][CF1C0F]抢购期[-][/c]时间为[c][1F74BF]%s[-][/c]分钟。",
	Booth_IntroduceSendTip = "[c][6C6C6C]摆摊购买的物品无法赠送[-][/c]",
	Booth_IntroduceBuyTip = "[c][6C6C6C]购买摆摊物品将专享%d%%的优惠[-][/c]",
	Booth_IntroduceFrom = "来自：%s",
	Booth_ExchangeRecordMaxLog = "记录保存%s天，未领取的金额和道具保留%s天",
	Booth_ExchangeRecordNormalSellOverLap = "出售%s个%s给[c][FF8A00]%s[-][/c]〔%s〕等人，扣税%s共赚取%s",
	Booth_Maintenance = "摆摊维护中",

	ProfessionInfoViewMP_AddSkillPointTip = "技能加点:",
	ProfessionInfoViewMP_AstrolabeTip = "星盘:",
	ProfessionInfoViewMP_NilTip = "暂未有角色信息",
	ProfessionInfoViewMP_HintLabel = "可通过二转职业切换哦",
	ProfessionInfoViewMP_ProfessionInfoSpc = "职业特色：",
	ProfessionInfoViewMP_ChangeCondition = "就职条件：",

	PetAdvance_BuyCaptureItem = "购买捕捉道具",
	PetAdvance_Compose = "融合",

	--语音授权
	ENABLE_MIC= "授权麦克风",
	DISABLE_MIC= "解除授权",

	CollectSaleConfirmPopUp_SellDiscountDesc = "总价+%s%%，多得%sZeny",

	Push_title = "",
	Push_message = "你现在无法收到推送消息通知，请到系统-设置-通知-仙境传说中开启",
	Push_cancelButtonTitle = "取消",
	Push_otherButtonTitles = "确定",

	-- 任务手册
    QuestManual_GetPuzzleAward = "集齐%s块拼图",
    QuestManual_Unlock = "解锁%s",
    QuestManual_GetDaily = "收集%s(%s/%s)",
    QuestManual_TwoSpace = "　　",
    QuestManual_FormerQuest = " 前置任务:",
    QuestManual_Level = "[等级%s]",
    QuestManual_QuestName = "[%s]",
    QuestManual_Acceptable = "(可接取)",

	GuildInfoView_TabName1 = "信息",
	GuildInfoView_TabName2 = "成员",
	GuildInfoView_TabName3 = "信仰",
	GuildInfoView_TabName4 = "查找",
	GuildInfoView_TabName5 = "公会仓库",

	PlayerDetailView_EquipTabName = "装备",
	PlayerDetailView_AttriTabName = "属性",
	PlayerDetailView_FashionTabName = "外观",

	PackageView_BagTabName = "包包",
	PackageView_StrengthTabName = "强化",

	FriendMainView_FriendTabName = "好友",
	FriendMainView_TutorTabName = "导师",
	
	SetView_SystemTabName = "声音",
	SetView_EffectTabName = "效果",
	SetView_MsgPushTabName = "推送",

	RepositoryView_RepositoryTabName = "仓库",
	RepositoryView_CommonTabName = "通用仓库",

	StageView_EquipTabName = "装备",
	StageView_FashionTabName = "造型",

    VoiceString ={
        Team_MicPhoneHasAlreadyClosed = "组队频道麦克风已经静音",
        Guild_MicPhoneHasAlreadyClosed = "公会频道麦克风已经静音",
        Guild_MicPhoneHasAlreadyOpened = "公会频道麦克风已经开启",
        MicPhoneHasAlreadyClosed = "麦克风已静音",
        MicPhoneHasAlreadyOpened = "麦克风已开启",
		YouAreNotAuthorized = "你没有权限不能开麦",
		YouAreNotGuildAuthorized = "你还没有公会开麦权限哦",
		YouDontHaveGuild = "还没有工会不能进入",
		YouHaveAlreadyQuit = "你已退出实时语音",
	},
	MVP_WorldBoss_Tip = "存在被亡灵附身的巨型魔物！！",

	--女仆提升
	ServantImproveCellState_Look = "查看",
	ServantImproveCellState_Go = "出发",
	ServantImproveCellState_Get = "领取",
	ServantImproveCellState_Finish = "完成",
	ServantImproveCellState_Next = "下一章节",

	-- 装备合成
	EquipCompose_ChooseEquipValidTip = "当前装备等级不足",
	EquipCompose_ChooseEquipValidTip_Damage = "当前装备已破损",

	GuildFaithPage_FaithTabName = "女神殿",
	GuildFaithPage_AstroTabName = "星辰殿",

	ShopSale_BagTabName = "包包",
	ShopSale_FoodTabName = "料理",
	ShopSale_PetTabName = "宠物",
	ShopSale_TempTabName = "临时",

	--todo xde
	FaceBookShare = "將本遊戲分享給朋友，讓朋友和你一起遊戲！分享後可以獲得分享禮包：Zeny：50,000\n\n注意事項：每週禮包當週分享僅可獲得一次獎勵，需待下週完成分享後才可再次獲得獎勵";
	FaceBookShare1 = "只要去為我們的Facebook專頁點讚(Like)，當點讚數量到達一定數量的時候，就會全服派發大禮包哦！所以不要只自己點讚，也要多叫Facebook的朋友們幫忙哦！讚的數量越多，獎勵就越多哦！",
	FaceBookCellFormat = "%s，獲取獎勵",
	ChangeZoneError = "世界线范围为1-%s",
	ZoneStrError = "未知线路",
	ChangeLangDes = "确认切换当前游戏语言为%s?",
	CardDecomposeViewTitle = "请点击“+”选择需要分解的卡片",
	SkyWheelAcceptViewTitle = "真诚地接受",
	NotFindPrice = "未找到价格",
	GetPlatFormInfoError = "无法获取正确的通行证信息",
	ParseRecPlatListError = "解析补单数据出错",


	--todo xde
	ExchangeTimeoutError = "交易所查询繁忙中，请稍后再试",
	AuctionNext = "[c][563104FF]下一场将在[c][4580BD]%d[-][/c]秒后开始！[-][/c]",
    ChangeZone_VeryBusyNotice = "世界线已完全饱和，无法传送，请稍后再试",


	GuestExchangeForbid = "游客账号无法使用交易所",
	GuestSecurityTitle = "提示",
	GuestSecurityContent = "遊客帳號無法使用此功能\n是否要前往綁定賬號？ （綁定帳號需要退出遊戲操作，完成綁定後請重新登錄哦(ゝ∀･)）",
	GuestSecurityCancel = "取消",
	GuestSecurityConfirm = "確定"
}
