--md5:266c6dd954925a634b9f282096e35b36
Table_Class_WW = { 
	[14] = {id = 14, NameZh = '符文骑士', NameEn = 'RuneKnight', MaleBody = 9, FemaleBody = 10, Desc = '战士使用中重量级武器，敏捷度较低，但攻击是极强有力的。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 1, TypeBranch = 11, icon = 'icon_1_4', InitialAttr = {{name='Str',value=96},{name='Vit',value=72},{name='Luk',value=24},{name='Int',value=24},{name='Dex',value=48},{name='Agi',value=24}}, AddPointSolution = {31,32,33,34}, Explain = '近战、物理、攻守兼备', AdvancedTeacher = 1050, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Str=6}},
	[74] = {id = 74, NameZh = '皇家卫士', NameEn = 'RoyalGuard', MaleBody = 57, FemaleBody = 58, Desc = '侍奉神的战士，拥有强大的耐力和防御力，攻击手段也多样。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 1, TypeBranch = 12, icon = 'icon_7_4', InitialAttr = {{name='Str',value=72},{name='Vit',value=96},{name='Luk',value=24},{name='Int',value=72},{name='Dex',value=48},{name='Agi',value=24}}, AddPointSolution = {59,60,61}, Explain = '近战、守护、生存能力强', AdvancedTeacher = 1050, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Vit=6}},
	[24] = {id = 24, NameZh = '大法师', NameEn = 'Warlock', MaleBody = 17, FemaleBody = 18, Desc = '魔法师的体力防御较低，可使用魔法技能进行强大的法术攻击。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 2, TypeBranch = 21, icon = 'icon_2_4', InitialAttr = {{name='Str',value=12},{name='Vit',value=48},{name='Luk',value=24},{name='Int',value=96},{name='Dex',value=72},{name='Agi',value=12}}, AddPointSolution = {35,36,37}, Explain = '远程、魔法、范围伤害', AdvancedTeacher = 1051, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Int=6}},
	[84] = {id = 84, NameZh = '元素使', NameEn = 'Sorcerer', MaleBody = 61, FemaleBody = 62, Desc = '', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 2, TypeBranch = 22, icon = '', InitialAttr = {{name='Str',value=24},{name='Vit',value=36},{name='Luk',value=48},{name='Int',value=96},{name='Dex',value=96},{name='Agi',value=24}}, AddPointSolution = _EmptyTable, Explain = '', DamRandom = {1,1}, IsOpen = 0, ActionSuffixMap = _EmptyTable, UnlockAttr = _EmptyTable},
	[34] = {id = 34, NameZh = '十字切割者', NameEn = 'GuillotineCross', MaleBody = 25, FemaleBody = 26, Desc = '盗贼的防御低而敏捷高，善于快速移动暗杀，有较高的爆发。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 3, TypeBranch = 31, icon = 'icon_3_4', InitialAttr = {{name='Str',value=48},{name='Vit',value=24},{name='Luk',value=96},{name='Int',value=24},{name='Dex',value=48},{name='Agi',value=96}}, AddPointSolution = {46,47,48}, Explain = '近战、物理、高爆发', AdvancedTeacher = 1052, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = {Knife="KnifeAS"}, UnlockAttr = {Agi=6}},
	[94] = {id = 94, NameZh = '逐影', NameEn = 'ShadowChaser', MaleBody = 77, FemaleBody = 78, Desc = '', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 3, TypeBranch = 32, icon = 'icon_9_4', InitialAttr = {{name='Str',value=48},{name='Vit',value=24},{name='Luk',value=96},{name='Int',value=24},{name='Dex',value=48},{name='Agi',value=96}}, AddPointSolution = {52,53,54}, Explain = '偷袭、卸除、远近程兼备', AdvancedTeacher = 1052, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Luk=6}},
	[44] = {id = 44, NameZh = '游侠', NameEn = 'Ranger', MaleBody = 33, FemaleBody = 34, Desc = '弓箭手攻击灵活、移动迅速，能从较远的距离或高处攻击敌人。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 4, TypeBranch = 41, icon = 'icon_4_4', InitialAttr = {{name='Str',value=12},{name='Vit',value=24},{name='Luk',value=72},{name='Int',value=12},{name='Dex',value=96},{name='Agi',value=48}}, AddPointSolution = {38,39,40}, Explain = '超长远程、物理、单体高伤害', AdvancedTeacher = 1053, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Dex=6}},
	[104] = {id = 104, NameZh = '宫廷乐师', NameEn = 'Minstrel', MaleBody = 83, FemaleBody = 74, Desc = '', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 4, TypeBranch = 42, icon = '', InitialAttr = {{name='Str',value=24},{name='Vit',value=48},{name='Luk',value=48},{name='Int',value=24},{name='Dex',value=96},{name='Agi',value=96}}, AddPointSolution = _EmptyTable, Explain = '', DamRandom = {1,1}, IsOpen = 0, ActionSuffixMap = _EmptyTable, UnlockAttr = _EmptyTable},
	[114] = {id = 114, NameZh = '漫游舞者', NameEn = 'Wanderer', MaleBody = 83, FemaleBody = 84, Desc = '', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 4, TypeBranch = 43, icon = '', InitialAttr = {{name='Str',value=24},{name='Vit',value=48},{name='Luk',value=48},{name='Int',value=24},{name='Dex',value=96},{name='Agi',value=96}}, AddPointSolution = _EmptyTable, Explain = '', DamRandom = {1,1}, IsOpen = 0, ActionSuffixMap = _EmptyTable, UnlockAttr = _EmptyTable},
	[54] = {id = 54, NameZh = '大主教', NameEn = 'Archbishop', MaleBody = 41, FemaleBody = 42, Desc = '服事有治愈及治疗能力，拥有很强的力量对付不死系的敌人。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 5, TypeBranch = 51, icon = 'icon_5_4', InitialAttr = {{name='Str',value=24},{name='Vit',value=60},{name='Luk',value=20},{name='Int',value=96},{name='Dex',value=48},{name='Agi',value=12}}, AddPointSolution = {41,42,43}, Explain = '远程、魔法、治疗、辅助', AdvancedTeacher = 1054, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Vit=6}},
	[124] = {id = 124, NameZh = '修罗', NameEn = 'Shura', MaleBody = 64, FemaleBody = 65, Desc = '极限修炼肉体的圣职者，拥有超绝的爆发力。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 5, TypeBranch = 52, icon = 'icon_12_4', InitialAttr = {{name='Str',value=24},{name='Vit',value=72},{name='Luk',value=24},{name='Int',value=96},{name='Dex',value=48},{name='Agi',value=24}}, AddPointSolution = {49,50,51}, Explain = '近战、辅助、爆发', AdvancedTeacher = 1054, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Int=6}},
	[64] = {id = 64, NameZh = '机匠', NameEn = 'Mechanic', MaleBody = 49, FemaleBody = 50, Desc = '拥有基本的攻击力及一般的能力。', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 6, TypeBranch = 61, icon = 'icon_6_4', InitialAttr = {{name='Str',value=96},{name='Vit',value=72},{name='Luk',value=24},{name='Int',value=24},{name='Dex',value=72},{name='Agi',value=48}}, AddPointSolution = {44,45}, Explain = '战斗、辅助、交易大师', AdvancedTeacher = 1055, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Luk=6}},
	[134] = {id = 134, NameZh = '基因学者', NameEn = 'Genetic', MaleBody = 71, FemaleBody = 72, Desc = '', Skill = _EmptyTable, MaxJobLevel = 200, AdvancedOccupation = _EmptyTable, AdvanceClass = _EmptyTable, Type = 6, TypeBranch = 62, icon = 'icon_13_4', InitialAttr = {{name='Str',value=72},{name='Vit',value=96},{name='Luk',value=24},{name='Int',value=72},{name='Dex',value=48},{name='Agi',value=24}}, AddPointSolution = {55,56,57,58}, Explain = '药剂、装备破坏、生命体', AdvancedTeacher = 1055, DamRandom = {1,1}, IsOpen = 1, ActionSuffixMap = _EmptyTable, UnlockAttr = {Str=6}},
}

Table_Class_WW_fields = { "id","NameZh","NameEn","MaleBody","FemaleBody","Desc","Skill","MaxJobLevel","MaxPeak","AdvancedOccupation","AdvanceClass","Type","TypeBranch","icon","InitialAttr","AddPointSolution","Explain","AdvancedTeacher","DamRandom","IsOpen","ActionSuffixMap","UnlockAttr",}
return Table_Class_WW