--md5:5d0ab1a452ae969084200ff8fe4bcfd6
Table_RoleData = { 
	[1] = {id = 1, PropName = '角色ID', VarName = 'CharID', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[2] = {id = 2, PropName = '角色名字', VarName = 'CharName', IsPercent = 0, IsClientPercent = 0, RuneName = '', }, 
	[3] = {id = 3, PropName = '性别', VarName = 'Sex', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[4] = {id = 4, PropName = '职业', VarName = 'Class', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', }, 
	[5] = {id = 5, PropName = '人物等级', VarName = 'BaseLv', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', }, 
	[6] = {id = 6, PropName = '经验', VarName = 'Exp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[7] = {id = 7, PropName = '职业等级', VarName = 'JobLv', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', }, 
	[8] = {id = 8, PropName = '职业经验', VarName = 'JobExp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', }, 
	[100] = {id = 100, PropName = '力量', VarName = 'Str', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Str', BaseTag = 9, }, 
	[101] = {id = 101, PropName = '智力', VarName = 'Int', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Int', BaseTag = 17, }, 
	[102] = {id = 102, PropName = '敏捷', VarName = 'Agi', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Agi', BaseTag = 33, }, 
	[103] = {id = 103, PropName = '灵巧', VarName = 'Dex', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Dex', BaseTag = 65, }, 
	[104] = {id = 104, PropName = '体质', VarName = 'Vit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Vit', BaseTag = 129, }, 
	[105] = {id = 105, PropName = '幸运', VarName = 'Luk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Luk', BaseTag = 257, }, 
	[200] = {id = 200, PropName = '物理攻击', VarName = 'Atk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Atk', CombatTag = 257, }, 
	[201] = {id = 201, PropName = '物理攻击%', VarName = 'AtkPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Atk', CombatTag = 257, }, 
	[202] = {id = 202, PropName = '物理防御', VarName = 'Def', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Def', CombatTag = 258, }, 
	[203] = {id = 203, PropName = '物理防御%', VarName = 'DefPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Def', CombatTag = 258, }, 
	[204] = {id = 204, PropName = '魔法攻击', VarName = 'MAtk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Matk', CombatTag = 513, }, 
	[205] = {id = 205, PropName = '魔法攻击%', VarName = 'MAtkPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Matk', CombatTag = 513, }, 
	[206] = {id = 206, PropName = '魔法防御', VarName = 'MDef', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Mdef', CombatTag = 514, }, 
	[207] = {id = 207, PropName = '魔法防御%', VarName = 'MDefPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Mdef', CombatTag = 514, }, 
	[208] = {id = 208, PropName = 'MaxHp', VarName = 'MaxHp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Hp', BaseTag = 512, CombatTag = 4, }, 
	[209] = {id = 209, PropName = 'MaxHp%', VarName = 'MaxHpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Hp', BaseTag = 512, CombatTag = 4, }, 
	[210] = {id = 210, PropName = 'MaxSp', VarName = 'MaxSp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Sp', BaseTag = 1024, CombatTag = 4, }, 
	[211] = {id = 211, PropName = 'MaxSp%', VarName = 'MaxSpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Sp', BaseTag = 1024, CombatTag = 4, }, 
	[212] = {id = 212, PropName = 'Hp', VarName = 'Hp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[213] = {id = 213, PropName = 'Sp', VarName = 'Sp', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[214] = {id = 214, PropName = '命中', VarName = 'Hit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Hit', CombatTag = 65537, }, 
	[215] = {id = 215, PropName = '闪避', VarName = 'Flee', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Flee', CombatTag = 549755813890, }, 
	[216] = {id = 216, PropName = '暴击', VarName = 'Cri', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Cri', CombatTag = 16385, }, 
	[217] = {id = 217, PropName = '暴击防护', VarName = 'CriRes', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '暴击防护', CombatTag = 32770, }, 
	[218] = {id = 218, PropName = '暴伤%', VarName = 'CriDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'CriDam', CombatTag = 16385, }, 
	[219] = {id = 219, PropName = '暴伤减免%', VarName = 'CriDefPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '暴伤减免', CombatTag = 32770, }, 
	[220] = {id = 220, PropName = '攻击速度', VarName = 'AtkSpd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'Aspd', CombatTag = 8193, }, 
	[221] = {id = 221, PropName = '移动速度', VarName = 'MoveSpd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'Speed', CombatTag = 4194308, }, 
	[222] = {id = 222, PropName = '吟唱减免', VarName = 'CastSpd', IsPercent = 1, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 131076, }, 
	[223] = {id = 223, PropName = 'Hp恢复', VarName = 'RestoreSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Hp回复', BaseTag = 512, CombatTag = 262148, }, 
	[224] = {id = 224, PropName = 'Sp恢复', VarName = 'SpRestoreSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = 'Sp回复', BaseTag = 1024, CombatTag = 262148, }, 
	[225] = {id = 225, PropName = 'Hp恢复药剂', VarName = 'ItemRestoreSpd', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 512, CombatTag = 262148, }, 
	[226] = {id = 226, PropName = 'Sp恢复药剂', VarName = 'ItemSpRestoreSpd', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 1024, CombatTag = 262148, }, 
	[227] = {id = 227, PropName = 'Hp%恢复', VarName = 'RestoreSpdPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Hp回复', BaseTag = 512, CombatTag = 262148, }, 
	[228] = {id = 228, PropName = 'Sp%恢复', VarName = 'SpRestoreSpdPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Sp回复', BaseTag = 1024, CombatTag = 262148, }, 
	[229] = {id = 229, PropName = '暴击%', VarName = 'CriPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'Cri', CombatTag = 16385, }, 
	[300] = {id = 300, PropName = '精炼物攻', VarName = 'Refine', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '精炼Atk', BaseTag = 32768, CombatTag = 257, }, 
	[301] = {id = 301, PropName = '精炼魔攻', VarName = 'MRefine', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '精炼Matk', BaseTag = 32768, CombatTag = 513, }, 
	[302] = {id = 302, PropName = '移动速度%', VarName = 'MoveSpdPer', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'Speed', CombatTag = 4194308, }, 
	[303] = {id = 303, PropName = '装备攻速', VarName = 'EquipASPD', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'EquipAspd', CombatTag = 8193, }, 
	[304] = {id = 304, PropName = '技能攻速', VarName = 'SkillASPD', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = 'SkillAspd', CombatTag = 8193, }, 
	[305] = {id = 305, PropName = '命中补正', VarName = 'HitPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[306] = {id = 306, PropName = '回避补正', VarName = 'FleePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[307] = {id = 307, PropName = '力量补正', VarName = 'StrPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[308] = {id = 308, PropName = '智力补正', VarName = 'IntPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[309] = {id = 309, PropName = '敏捷补正', VarName = 'AgiPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[310] = {id = 310, PropName = '灵巧补正', VarName = 'DexPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[311] = {id = 311, PropName = '体质补正', VarName = 'VitPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[312] = {id = 312, PropName = '幸运补正', VarName = 'LukPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[400] = {id = 400, PropName = '物理攻击', VarName = 'ShowAtk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 257, }, 
	[401] = {id = 401, PropName = '物理防御', VarName = 'ShowDef', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 258, }, 
	[402] = {id = 402, PropName = '魔法攻击', VarName = 'ShowMAtk', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 513, }, 
	[403] = {id = 403, PropName = '魔法防御', VarName = 'ShowMDef', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 514, }, 
	[404] = {id = 404, PropName = 'MaxHp', VarName = 'ShowMaxHp', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[405] = {id = 405, PropName = 'MaxSp', VarName = 'ShowMaxSp', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[406] = {id = 406, PropName = '命中', VarName = 'ShowHit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 65537, }, 
	[407] = {id = 407, PropName = '闪避', VarName = 'ShowFlee', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 549755813890, }, 
	[408] = {id = 408, PropName = '暴击', VarName = 'ShowCri', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16385, }, 
	[409] = {id = 409, PropName = '抗暴', VarName = 'ShowCriRes', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 32770, }, 
	[410] = {id = 410, PropName = '攻击速度', VarName = 'ShowAtkSpd', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 8193, }, 
	[411] = {id = 411, PropName = '移动速度', VarName = 'ShowMoveSpd', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 4194308, }, 
	[412] = {id = 412, PropName = '吟唱速度', VarName = 'ShowCastSpd', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 131076, }, 
	[413] = {id = 413, PropName = '恢复速度', VarName = 'ShowRestoreSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 262148, }, 
	[414] = {id = 414, PropName = '物伤减免', VarName = 'DamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[415] = {id = 415, PropName = '魔伤减免', VarName = 'MDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[416] = {id = 416, PropName = '忽视物防', VarName = 'IgnoreDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4353, }, 
	[417] = {id = 417, PropName = '忽视魔防', VarName = 'IgnoreMDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4609, }, 
	[418] = {id = 418, PropName = '物伤反弹', VarName = 'DamRebound', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8388868, }, 
	[419] = {id = 419, PropName = '魔伤反弹', VarName = 'MDamRebound', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8389124, }, 
	[420] = {id = 420, PropName = '物伤加成', VarName = 'DamIncrease', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2305, }, 
	[421] = {id = 421, PropName = '魔伤加成', VarName = 'MDamIncrease', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2561, }, 
	[422] = {id = 422, PropName = '伤害吸血比例', VarName = 'Vampiric', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[423] = {id = 423, PropName = '受伤害吸血比例', VarName = 'BeVampiric', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[424] = {id = 424, PropName = '伤害减免', VarName = 'HarmImmune', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, }, 
	[425] = {id = 425, PropName = '真实伤害', VarName = 'RealDamage', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554435, }, 
	[426] = {id = 426, PropName = '范围伤害', VarName = 'RangeDam', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 129, }, 
	[427] = {id = 427, PropName = '近战物理伤害减免', VarName = 'ShortRangeDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1314, }, 
	[428] = {id = 428, PropName = '远程物理伤害减免', VarName = 'LongRangeDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1298, }, 
	[429] = {id = 429, PropName = '远程魔法伤害减免', VarName = 'LongRangeMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1554, }, 
	[430] = {id = 430, PropName = '忽视乘算物防', VarName = 'IgnoreEquipDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[431] = {id = 431, PropName = '无视体型攻击百分比', VarName = 'ShapeAtkPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[432] = {id = 432, PropName = '物理穿刺', VarName = 'DamSpike', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4353, }, 
	[433] = {id = 433, PropName = '魔法穿刺', VarName = 'MDamSpike', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4609, }, 
	[434] = {id = 434, PropName = '精炼物免', VarName = 'RefineDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 32768, CombatTag = 1, }, 
	[435] = {id = 435, PropName = '精炼魔免', VarName = 'RefineMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 32768, CombatTag = 1, }, 
	[436] = {id = 436, PropName = '能量外套物伤减免', VarName = 'EnergyDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[437] = {id = 437, PropName = '钢铁之心物伤减免', VarName = 'SteelDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[438] = {id = 438, PropName = '钢铁之心魔伤减免', VarName = 'SteelMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[439] = {id = 439, PropName = '舍命庇护物伤减免', VarName = 'ProtectDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[440] = {id = 440, PropName = '舍命庇护魔伤减免', VarName = 'ProtectMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[441] = {id = 441, PropName = '销声匿迹物伤减免', VarName = 'HideDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[442] = {id = 442, PropName = '销声匿迹魔伤减免', VarName = 'HideMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[443] = {id = 443, PropName = '龙鳞饼物伤减免', VarName = 'DragonDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[444] = {id = 444, PropName = '龙鳞饼魔伤减免', VarName = 'DragonMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[445] = {id = 445, PropName = '物理普攻真实伤害', VarName = 'NormalRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554689, }, 
	[446] = {id = 446, PropName = '魔法普攻真实伤害', VarName = 'NormalMRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554945, }, 
	[447] = {id = 447, PropName = '物理技能真实伤害', VarName = 'SkillRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554697, }, 
	[448] = {id = 448, PropName = '魔法技能真实伤害', VarName = 'SkillMRealDam', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 33554953, }, 
	[449] = {id = 449, PropName = '普攻攻击力', VarName = 'NormalAtk', IsPercent = 0, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1, }, 
	[450] = {id = 450, PropName = '普攻伤害加成', VarName = 'NormalAtkDam', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, }, 
	[451] = {id = 451, PropName = '普攻伤害减免', VarName = 'NormalAtkRes', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1025, }, 
	[452] = {id = 452, PropName = '技能伤害加成', VarName = 'SkillDam', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, }, 
	[453] = {id = 453, PropName = '技能伤害减免', VarName = 'SkillRes', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1025, }, 
	[454] = {id = 454, PropName = '疾风步魔伤减免', VarName = 'WindMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[455] = {id = 455, PropName = '濒死物伤减免', VarName = 'DeadDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1282, }, 
	[456] = {id = 456, PropName = '濒死魔伤减免', VarName = 'DeadMDamReduc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1538, }, 
	[500] = {id = 500, PropName = '计算物理伤害', VarName = 'CalcDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 257, }, 
	[501] = {id = 501, PropName = '计算物理暴击伤害', VarName = 'CalcCriDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 16641, }, 
	[502] = {id = 502, PropName = '计算魔法伤害', VarName = 'CalcMDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 513, }, 
	[503] = {id = 503, PropName = '计算魔法暴击伤害', VarName = 'CalcCriMDamage', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 16897, }, 
	[504] = {id = 504, PropName = '计算命中率', VarName = 'CalcHit', IsPercent = 1, Default = 1, IsClientPercent = 1, RuneName = '', CombatTag = 65537, }, 
	[505] = {id = 505, PropName = '计算暴击率', VarName = 'CalcCri', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 16385, }, 
	[506] = {id = 506, PropName = '计算攻击速度', VarName = 'CalAspd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = '', CombatTag = 8193, }, 
	[507] = {id = 507, PropName = '计算移动速度', VarName = 'CalcMoveSpd', IsPercent = 1, Default = 1000, IsClientPercent = 1, RuneName = '', CombatTag = 4194308, }, 
	[508] = {id = 508, PropName = '计算吟唱速度', VarName = 'CalcCastSpd', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 131076, }, 
	[509] = {id = 509, PropName = '吟唱时间修正', VarName = 'CTChange', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 131076, }, 
	[510] = {id = 510, PropName = '吟唱时间修正%', VarName = 'CTChangePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 131076, }, 
	[511] = {id = 511, PropName = '冷却时间修正', VarName = 'CDChange', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 524292, }, 
	[512] = {id = 512, PropName = '冷却时间修正%', VarName = 'CDChangePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 524292, }, 
	[513] = {id = 513, PropName = '净化值变动', VarName = 'Purify', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[514] = {id = 514, PropName = '净化值', VarName = 'PurifyMax', IsPercent = 0, Default = 1000, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[515] = {id = 515, PropName = 'SP消耗修正', VarName = 'SpCost', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[516] = {id = 516, PropName = 'SP消耗修正%', VarName = 'SpCostPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[517] = {id = 517, PropName = '攻击距离修正', VarName = 'AtkDistance', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 1, }, 
	[518] = {id = 518, PropName = '攻击距离修正%', VarName = 'AtkDistancePer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1, }, 
	[519] = {id = 519, PropName = '固定吟唱时间修正', VarName = 'CTFixed', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', CombatTag = 131076, }, 
	[520] = {id = 520, PropName = '固定吟唱时间%修正', VarName = 'CTFixedPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 131076, }, 
	[521] = {id = 521, PropName = '售卖优惠', VarName = 'SellDiscount', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[522] = {id = 522, PropName = '购买折扣', VarName = 'BuyDiscount', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[523] = {id = 523, PropName = 'HP消耗修正', VarName = 'HpCost', IsPercent = 0, Default = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[524] = {id = 524, PropName = 'HP消耗修正%', VarName = 'HpCostPer', IsPercent = 1, Default = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[533] = {id = 533, PropName = '背包格子', VarName = 'CartNum', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[534] = {id = 534, PropName = '技能延迟', VarName = 'DelayCDChange', IsPercent = 0, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[535] = {id = 535, PropName = '技能延迟%', VarName = 'DelayCDChangePer', IsPercent = 1, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[536] = {id = 536, PropName = '持续引导时间', VarName = 'DChange', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[537] = {id = 537, PropName = '持续引导时间%', VarName = 'DChangePer', IsPercent = 1, Default = 0, IsClientPercent = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[600] = {id = 600, PropName = '无法使用技能', VarName = 'NoSkill', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 1073741828, }, 
	[601] = {id = 601, PropName = '无法做任何动作', VarName = 'NoAct', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[602] = {id = 602, PropName = '无法移动', VarName = 'NoMove', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 68719476740, }, 
	[603] = {id = 603, PropName = '不会硬直', VarName = 'NoStiff', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[604] = {id = 604, PropName = '不会攻击', VarName = 'NoAttack', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[605] = {id = 605, PropName = '恐惧逃跑', VarName = 'FearRun', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 536870916, }, 
	[606] = {id = 606, PropName = '隐匿', VarName = 'Hiding', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 134217728, }, 
	[607] = {id = 607, PropName = '强制攻击', VarName = 'Taunt', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[608] = {id = 608, PropName = '冻结', VarName = 'Freeze', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 2147483652, }, 
	[609] = {id = 609, PropName = '不会位移', VarName = 'NoEffectMove', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 68719476740, }, 
	[610] = {id = 610, PropName = '状态效果', VarName = 'StateEffect', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[611] = {id = 611, PropName = '属性效果', VarName = 'AttrEffect', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[612] = {id = 612, PropName = '不会被攻击(无敌)', VarName = 'NoAttacked', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 67108868, }, 
	[613] = {id = 613, PropName = '冒险技能效果', VarName = 'AttrFunction', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 8, }, 
	[614] = {id = 614, PropName = '属性效果', VarName = 'AttrEffect2', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[615] = {id = 615, PropName = '功能禁止', VarName = 'FuncLimit', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[700] = {id = 700, PropName = '攻击属性转换', VarName = 'AtkAttr', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 268435460, }, 
	[701] = {id = 701, PropName = '防御属性转换', VarName = 'DefAttr', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 268435460, }, 
	[702] = {id = 702, PropName = '对风属性魔物增伤%', VarName = 'WindDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 262146},
	[703] = {id = 703, PropName = '对地属性魔物增伤%', VarName = 'EarthDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 2097154},
	[704] = {id = 704, PropName = '对水属性魔物增伤%', VarName = 'WaterDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 1048578},
	[705] = {id = 705, PropName = '对火属性魔物增伤%', VarName = 'FireDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 524290},
	[706] = {id = 706, PropName = '对无属性魔物增伤%', VarName = 'NeutralDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 131074},
	[707] = {id = 707, PropName = '对圣属性魔物增伤%', VarName = 'HolyDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 4194306},
	[708] = {id = 708, PropName = '对暗属性魔物增伤%', VarName = 'ShadowDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 8388610},
	[709] = {id = 709, PropName = '对念属性魔物增伤%', VarName = 'GhostDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 16777218},
	[710] = {id = 710, PropName = '对不死属性魔物增伤%', VarName = 'UndeadDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 67108866},
	[711] = {id = 711, PropName = '对毒属性魔物增伤%', VarName = 'PoisonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 33554434},
	[712] = {id = 712, PropName = '对风属性伤害减免%', VarName = 'BeWindDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 262146},
	[713] = {id = 713, PropName = '对地属性伤害减免%', VarName = 'BeEarthDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 2097154},
	[714] = {id = 714, PropName = '对水属性伤害减免%', VarName = 'BeWaterDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 1048578},
	[715] = {id = 715, PropName = '对火属性伤害减免%', VarName = 'BeFireDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 524290},
	[716] = {id = 716, PropName = '对无属性伤害减免%', VarName = 'BeNeutralDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 131074},
	[717] = {id = 717, PropName = '对圣属性伤害减免%', VarName = 'BeHolyDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 4194306},
	[718] = {id = 718, PropName = '对暗属性伤害减免%', VarName = 'BeShadowDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 8388610},
	[719] = {id = 719, PropName = '对念属性伤害减免%', VarName = 'BeGhostDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 16777218},
	[720] = {id = 720, PropName = '对不死属性伤害减免%', VarName = 'BeUndeadDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 268435458},
	[721] = {id = 721, PropName = '对毒属性伤害减免%', VarName = 'BePoisonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 33554434},
	[722] = {id = 722, PropName = '风属性攻击', VarName = 'WindAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WindAtk', CombatTag = 1, AdjTag = 262146},
	[723] = {id = 723, PropName = '地属性攻击', VarName = 'EarthAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'EarthAtk', CombatTag = 1, AdjTag = 2097154},
	[724] = {id = 724, PropName = '火属性攻击', VarName = 'FireAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'FireAtk', CombatTag = 1, AdjTag = 524290},
	[725] = {id = 725, PropName = '水属性攻击', VarName = 'WaterAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WaterAtk', CombatTag = 1, AdjTag = 1048578},
	[726] = {id = 726, PropName = '无属性攻击', VarName = 'NeutralAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'NeutralAtk', CombatTag = 1, AdjTag = 131074},
	[727] = {id = 727, PropName = '圣属性攻击', VarName = 'HolyAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'HolyAtk', CombatTag = 1, AdjTag = 4194306},
	[728] = {id = 728, PropName = '暗属性攻击', VarName = 'DarkAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'DarkAtk', CombatTag = 1, AdjTag = 8388610},
	[729] = {id = 729, PropName = '风属性防御', VarName = 'WindDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WindDef', CombatTag = 2, AdjTag = 262146},
	[730] = {id = 730, PropName = '地属性防御', VarName = 'EarthDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'EarthDef', CombatTag = 2, AdjTag = 2097154},
	[731] = {id = 731, PropName = '火属性防御', VarName = 'FireDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'FireDef', CombatTag = 2, AdjTag = 524290},
	[732] = {id = 732, PropName = '水属性防御', VarName = 'WaterDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'WaterDef', CombatTag = 2, AdjTag = 1048578},
	[733] = {id = 733, PropName = '无属性防御', VarName = 'NeutralDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'NeutralDef', CombatTag = 2, AdjTag = 131074},
	[734] = {id = 734, PropName = '圣属性防御', VarName = 'HolyDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'HolyDef', CombatTag = 2, AdjTag = 4194306},
	[735] = {id = 735, PropName = '暗属性防御', VarName = 'DarkDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'DarkDef', CombatTag = 2, AdjTag = 8388610},
	[736] = {id = 736, PropName = '念属性攻击', VarName = 'GhostAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'GhostAtk', CombatTag = 1, AdjTag = 16777218},
	[737] = {id = 737, PropName = '不死属性攻击', VarName = 'UndeadAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'UndeadAtk', CombatTag = 1, AdjTag = 268435458},
	[738] = {id = 738, PropName = '毒属性攻击', VarName = 'PoisoningAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = 'PoisoningAtk', CombatTag = 1, AdjTag = 33554434},
	[800] = {id = 800, PropName = '对动物增伤%', VarName = 'BruteDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 1025},
	[801] = {id = 801, PropName = '对人形增伤%', VarName = 'DemiHumanDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 2049},
	[802] = {id = 802, PropName = '对恶魔增伤%', VarName = 'DemonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 513},
	[803] = {id = 803, PropName = '对植物增伤%', VarName = 'PlantDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 16385},
	[804] = {id = 804, PropName = '对不死增伤%', VarName = 'DeadLessDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 4097},
	[805] = {id = 805, PropName = '对无形增伤%', VarName = 'FormlessDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 8193},
	[806] = {id = 806, PropName = '对鱼贝增伤%', VarName = 'FishDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 32769},
	[807] = {id = 807, PropName = '对天使增伤%', VarName = 'AngelDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 134217729},
	[808] = {id = 808, PropName = '对昆虫增伤%', VarName = 'InsectDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 65537},
	[809] = {id = 809, PropName = '对龙族增伤%', VarName = 'DragonDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 67108865},
	[810] = {id = 810, PropName = '对动物减伤%', VarName = 'BruteResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 1025},
	[811] = {id = 811, PropName = '对人形减伤%', VarName = 'DemiHumanResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 2049},
	[812] = {id = 812, PropName = '对恶魔减伤%', VarName = 'DemonResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 513},
	[813] = {id = 813, PropName = '对植物减伤%', VarName = 'PlantResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 16385},
	[814] = {id = 814, PropName = '对不死减伤%', VarName = 'DeadLessResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 4097},
	[815] = {id = 815, PropName = '对无形减伤%', VarName = 'FormlessResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 8193},
	[816] = {id = 816, PropName = '对鱼贝减伤%', VarName = 'FishResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 32769},
	[817] = {id = 817, PropName = '对天使减伤%', VarName = 'AngelResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 134217729},
	[818] = {id = 818, PropName = '对昆虫减伤%', VarName = 'InsectResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 65537},
	[819] = {id = 819, PropName = '对龙族减伤%', VarName = 'DragonResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 67108865},
	[900] = {id = 900, PropName = '对小体型增伤%', VarName = 'SmallDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 32},
	[901] = {id = 901, PropName = '对小体型减伤%', VarName = 'SmallResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 32},
	[902] = {id = 902, PropName = '对中体型增伤%', VarName = 'MidDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 64},
	[903] = {id = 903, PropName = '对中体型减伤%', VarName = 'MidResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 64},
	[904] = {id = 904, PropName = '对大体型增伤%', VarName = 'BigDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2049, AdjTag = 128},
	[905] = {id = 905, PropName = '对大体型减伤%', VarName = 'BigResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1026, AdjTag = 128},
	[906] = {id = 906, PropName = '对BOSS增伤%', VarName = 'BossDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 4096, CombatTag = 2049, }, 
	[907] = {id = 907, PropName = '对BOSS减伤%', VarName = 'BossResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 4096, CombatTag = 1026, }, 
	[908] = {id = 908, PropName = '对非BOSS魔物增伤%', VarName = 'MonsterDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 2048, CombatTag = 2049, }, 
	[909] = {id = 909, PropName = '对非BOSS魔物减伤%', VarName = 'MonsterResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 2048, CombatTag = 1026, }, 
	[910] = {id = 910, PropName = '对玩家增伤%', VarName = 'NpcDamPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2113, }, 
	[911] = {id = 911, PropName = '对玩家减伤%', VarName = 'NpcResPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1090, }, 
	[1000] = {id = 1000, PropName = '沉默攻击', VarName = 'SilenceAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1073741828, }, 
	[1001] = {id = 1001, PropName = '沉默抵抗', VarName = 'SilenceDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1073741828, }, 
	[1002] = {id = 1002, PropName = '冰冻攻击', VarName = 'FreezeAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2147483652, }, 
	[1003] = {id = 1003, PropName = '冰冻抵抗', VarName = 'FreezeDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2147483652, }, 
	[1004] = {id = 1004, PropName = '石化攻击', VarName = 'StoneAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4294967300, }, 
	[1005] = {id = 1005, PropName = '石化抵抗', VarName = 'StoneDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4294967300, }, 
	[1006] = {id = 1006, PropName = '晕眩攻击', VarName = 'StunAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8589934596, }, 
	[1007] = {id = 1007, PropName = '晕眩抵抗', VarName = 'StunDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8589934596, }, 
	[1008] = {id = 1008, PropName = '灼烧攻击', VarName = 'BlindAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 17179869188, }, 
	[1009] = {id = 1009, PropName = '灼烧抵抗', VarName = 'BlindDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 17179869188, }, 
	[1010] = {id = 1010, PropName = '中毒攻击', VarName = 'PoisonAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 34359738372, }, 
	[1011] = {id = 1011, PropName = '中毒抵抗', VarName = 'PoisonDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 34359738372, }, 
	[1012] = {id = 1012, PropName = '定身攻击', VarName = 'SlowAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 68719476740, }, 
	[1013] = {id = 1013, PropName = '定身抵抗', VarName = 'SlowDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 68719476740, }, 
	[1014] = {id = 1014, PropName = '恐惧攻击', VarName = 'ChaosAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 536870916, }, 
	[1015] = {id = 1015, PropName = '恐惧抵抗', VarName = 'ChaosDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 536870916, }, 
	[1016] = {id = 1016, PropName = '诅咒攻击', VarName = 'CurseAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 0, }, 
	[1017] = {id = 1017, PropName = '诅咒抵抗', VarName = 'CurseDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 137438953476, }, 
	[1018] = {id = 1018, PropName = '异常攻击', VarName = 'StateAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4, }, 
	[1019] = {id = 1019, PropName = '异常抵抗', VarName = 'StateDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 4, }, 
	[1020] = {id = 1020, PropName = '反射异常', VarName = 'StateReflect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 8388612, }, 
	[1021] = {id = 1021, PropName = '异常效果延长', VarName = 'StateTimeEnc', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1022] = {id = 1022, PropName = '被异常时间缩短', VarName = 'BeStateTimeDec', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1023] = {id = 1023, PropName = '异常效果抵抗', VarName = 'StateAbnorResist', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1024] = {id = 1024, PropName = '变身ID', VarName = 'TransformID', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[1025] = {id = 1025, PropName = '睡眠攻击', VarName = 'SleepAtk', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1099511627780, }, 
	[1026] = {id = 1026, PropName = '睡眠抵抗', VarName = 'SleepDef', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 1099511627780, }, 
	[1100] = {id = 1100, PropName = '武器破坏', VarName = 'WeaponBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1101] = {id = 1101, PropName = '铠甲破坏', VarName = 'EquipBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1102] = {id = 1102, PropName = '头饰破坏', VarName = 'HeadBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1103] = {id = 1103, PropName = '盾牌破坏', VarName = 'ShieldBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1104] = {id = 1104, PropName = '战靴破坏', VarName = 'ShoesBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1105] = {id = 1105, PropName = '披风破坏', VarName = 'RobeBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1106] = {id = 1106, PropName = '装饰品破坏', VarName = 'AccessoryBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1107] = {id = 1107, PropName = '武器保护', VarName = 'WeaponProtect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1108] = {id = 1108, PropName = '防具保护', VarName = 'EquipProtect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1109] = {id = 1109, PropName = '饰品保护', VarName = 'AccessoryProtect', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1110] = {id = 1110, PropName = '受治疗加成', VarName = 'BeHealEncPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 274877906948, }, 
	[1111] = {id = 1111, PropName = '治疗加成', VarName = 'HealEncPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 274877906948, }, 
	[1112] = {id = 1112, PropName = '自然恢复力增加%', VarName = 'AutoHealEncPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 262148, }, 
	[1113] = {id = 1113, PropName = '生命吸收概率', VarName = 'HpSuckRate', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 16777220, }, 
	[1114] = {id = 1114, PropName = '生命吸收%', VarName = 'HpSuckPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 16777220, }, 
	[1115] = {id = 1115, PropName = '生命吸收', VarName = 'HpSuck', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16777220, }, 
	[1116] = {id = 1116, PropName = '装备破坏', VarName = 'EquipBrake', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 2097156, }, 
	[1200] = {id = 1200, PropName = '伤害吸收数量', VarName = 'DamAbsorb', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16777220, }, 
	[1201] = {id = 1201, PropName = '伤害吸收次数', VarName = 'DamAbsorbTime', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', CombatTag = 16777220, }, 
	[1202] = {id = 1202, PropName = '能量冲击', VarName = 'PowerShock', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1203] = {id = 1203, PropName = '能量吸收', VarName = 'PowerAbsorb', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', CombatTag = 16777220, }, 
	[1204] = {id = 1204, PropName = '打断施法', VarName = 'CastBreak', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1205] = {id = 1205, PropName = '防打断', VarName = 'CastBreakRes', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1206] = {id = 1206, PropName = '体型修正', VarName = 'SizeCorrection', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', AdjTag = 4},
	[1207] = {id = 1207, PropName = '技能等级', VarName = 'Slv', IsPercent = 0, Default = 1, IsClientPercent = 0, RuneName = '', CombatTag = 8, }, 
	[1208] = {id = 1208, PropName = '瞬间死亡', VarName = 'DeadSoon', IsPercent = 0, Default = 0, IsClientPercent = 0, RuneName = '', AdjTag = 4},
	[1209] = {id = 1209, PropName = 'HP热量', VarName = 'SaveHp', IsPercent = 0, Default = 0, RuneName = '', BaseTag = 512, CombatTag = 4, }, 
	[1210] = {id = 1210, PropName = 'SP热量', VarName = 'SaveSp', IsPercent = 0, Default = 0, RuneName = '', BaseTag = 1024, CombatTag = 4, }, 
	[1211] = {id = 1211, PropName = '修身高度', VarName = 'SlimHeight', IsPercent = 0, Default = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[1212] = {id = 1212, PropName = '修身体重', VarName = 'SlimWeight', IsPercent = 0, Default = 0, SyncFloat = 1, RuneName = '', AdjTag = 4},
	[1213] = {id = 1213, PropName = '击杀魔物Base经验', VarName = 'BaseExpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 8194, AdjTag = 4},
	[1214] = {id = 1214, PropName = '击杀魔物Job经验', VarName = 'JobExpPer', IsPercent = 1, Default = 0, IsClientPercent = 1, RuneName = '', BaseTag = 8196, AdjTag = 4},
}

Table_RoleData_fields = { "id","PropName","VarName","IsPercent","Default","IsClientPercent","SyncFloat","RuneName","BaseTag","CombatTag","AdjTag",}
return Table_RoleData