Table_Skill_JP = {
  [50050001] = {
    id = 50050001,
    NameZh = "\230\137\147\229\183\165\232\190\190\228\186\186",
    Level = 1,
    Class = 500,
    Icon = "skill_50050001",
    Cost = 1,
    Contidion = {riskid = 1005},
    Desc = {
      {
        id = 50050000,
        params = {}
      }
    },
    SkillType = "Passive",
    Camps = "",
    TargetFilter = _EmptyTable,
    SkillCost = _EmptyTable,
    StrengthenCost = _EmptyTable,
    PreCondition = _EmptyTable,
    AutoCondition = _EmptyTable,
    Lead_Type = _EmptyTable,
    Logic = "",
    Logic_Param = _EmptyTable,
    Damage = _EmptyTable,
    DamTime = _EmptyTable,
    HitEffects = _EmptyTable,
    AttackEffects = _EmptyTable,
    Buff = _EmptyTable,
    Pvp_buff = _EmptyTable,
    EndAct = "",
    CastAct = "",
    AttackAct = "",
    E_Cast = "",
    E_Attack = "",
    E_Fire = "",
    E_Hit = "",
    E_Miss = "",
    E_CastLock = "",
    SE_cast = "",
    SE_attack = "",
    SE_fire = "",
    SE_hit = "",
    SE_miss = "",
    SE_bg = ""
  },
  [50051001] = {
    id = 50051001,
    NameZh = "\230\137\147\229\183\165\229\164\167\229\184\136",
    Level = 1,
    Class = 500,
    Icon = "skill_50051001",
    Cost = 1,
    Contidion = {riskid = 1007},
    Desc = {
      {
        id = 50050000,
        params = {}
      }
    },
    SkillType = "Passive",
    Camps = "",
    TargetFilter = _EmptyTable,
    SkillCost = _EmptyTable,
    StrengthenCost = _EmptyTable,
    PreCondition = _EmptyTable,
    AutoCondition = _EmptyTable,
    Lead_Type = _EmptyTable,
    Logic = "",
    Logic_Param = _EmptyTable,
    Damage = _EmptyTable,
    DamTime = _EmptyTable,
    HitEffects = _EmptyTable,
    AttackEffects = _EmptyTable,
    Buff = _EmptyTable,
    Pvp_buff = _EmptyTable,
    EndAct = "",
    CastAct = "",
    AttackAct = "",
    E_Cast = "",
    E_Attack = "",
    E_Fire = "",
    E_Hit = "",
    E_Miss = "",
    E_CastLock = "",
    SE_cast = "",
    SE_attack = "",
    SE_fire = "",
    SE_hit = "",
    SE_miss = "",
    SE_bg = ""
  },
  [50053001] = {
    id = 50053001,
    NameZh = "\230\151\182\231\169\186\230\150\173\232\163\130",
    Level = 1,
    Class = 500,
    Icon = "skill_50053001",
    Cost = 1,
    Contidion = {riskid = 1006},
    Desc = {
      {
        id = 50053000,
        params = {}
      }
    },
    SkillType = "Passive",
    Camps = "",
    TargetFilter = _EmptyTable,
    SkillCost = _EmptyTable,
    StrengthenCost = _EmptyTable,
    PreCondition = _EmptyTable,
    AutoCondition = _EmptyTable,
    Lead_Type = _EmptyTable,
    Logic = "",
    Logic_Param = _EmptyTable,
    Damage = _EmptyTable,
    DamTime = _EmptyTable,
    HitEffects = _EmptyTable,
    AttackEffects = _EmptyTable,
    Buff = _EmptyTable,
    Pvp_buff = _EmptyTable,
    EndAct = "",
    CastAct = "",
    AttackAct = "",
    E_Cast = "",
    E_Attack = "",
    E_Fire = "",
    E_Hit = "",
    E_Miss = "",
    E_CastLock = "",
    SE_cast = "",
    SE_attack = "",
    SE_fire = "",
    SE_hit = "",
    SE_miss = "",
    SE_bg = ""
  },
  [50058001] = {
    id = 50058001,
    NameZh = "\230\152\159\230\156\136\228\185\139\231\186\166",
    Level = 1,
    Class = 500,
    Icon = "skill_50058001",
    Cost = 1,
    Contidion = _EmptyTable,
    Desc = {
      {
        id = 50058000,
        params = {}
      }
    },
    SkillType = "Buff",
    Camps = "Friend",
    TargetFilter = _EmptyTable,
    Launch_Range = 0,
    Fire_EP = 3,
    Target_EP = 3,
    Attack_EP = 3,
    SkillCost = _EmptyTable,
    StrengthenCost = _EmptyTable,
    PreCondition = _EmptyTable,
    AutoCondition = {
      {type = 2}
    },
    AutoCondition_Groove = 1,
    Lead_Type = _EmptyTable,
    Logic = "SkillNone",
    Logic_Param = {
      GM = {type = "servant", option = 7}
    },
    Damage = _EmptyTable,
    DamTime = _EmptyTable,
    HitEffects = _EmptyTable,
    AttackEffects = _EmptyTable,
    Buff = _EmptyTable,
    Pvp_buff = _EmptyTable,
    EndAct = "",
    CastAct = "",
    AttackAct = "use_skill",
    E_Cast = "",
    E_Attack = "",
    E_Fire = "",
    E_Hit = "",
    E_Miss = "",
    E_CastLock = "",
    SE_cast = "",
    SE_attack = "",
    SE_fire = "",
    SE_hit = "",
    SE_miss = "",
    SE_bg = ""
  }
}
Table_Skill_JP_fields = {
  "id",
  "NameZh",
  "Share",
  "Level",
  "Class",
  "Icon",
  "Cost",
  "Contidion",
  "NextID",
  "NextBreakID",
  "PeakLevel",
  "NextNewID",
  "Desc",
  "RollType",
  "SkillHit",
  "Launch_Type",
  "SkillType",
  "Camps",
  "TargetFilter",
  "Launch_Range",
  "Fire_EP",
  "Target_EP",
  "Attack_EP",
  "CD",
  "FixCD",
  "SkillCost",
  "StrengthenCost",
  "DelayCD",
  "PreCondition",
  "AutoCondition",
  "NoTargetAutoCast",
  "AutoCondition_Groove",
  "Lead_Type",
  "Logic",
  "Logic_Param",
  "Damage",
  "DamTime",
  "HitEffects",
  "AttackEffects",
  "SuperUse",
  "SuperUseEffect",
  "NoHpBreak",
  "BuffBreakLimit",
  "Buff",
  "Pvp_buff",
  "ForbidUse",
  "AttackStatus",
  "EndAct",
  "CastAct",
  "AttackAct",
  "E_Cast",
  "E_Attack",
  "E_Attack_On",
  "E_Fire",
  "E_Hit",
  "E_Miss",
  "E_CastLock",
  "CastLock_EP",
  "SE_cast",
  "SE_attack",
  "SE_fire",
  "SE_hit",
  "SE_miss",
  "SE_bg"
}
return Table_Skill_JP
