local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("ActivityCmd_pb")
ACTIVITYPARAM = protobuf.EnumDescriptor()
ACTIVITYPARAM_ACTIVITYPARAM_ACT_START_ENUM = protobuf.EnumValueDescriptor()
ACTIVITYPARAM_ACTIVITYPARAM_BCAT_UFOPOS_ENUM = protobuf.EnumValueDescriptor()
ACTIVITYPARAM_ACTIVITYPARAM_PROGRESS_NTF_ENUM = protobuf.EnumValueDescriptor()
ACTIVITYPARAM_ACTIVITYPARAM_ACT_STOP_ENUM = protobuf.EnumValueDescriptor()
ACTIVITYPARAM_ACTIVITYPARAM_GLOBAL_ACT_START_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE = protobuf.EnumDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_MIN_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_AUGURY_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_QUEST_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_DONATE_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_FUBEN_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_NOVICE_WELFARE_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_NORMAL_REFINE_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_DISCOUNT_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_RECALL_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_SPRING_LOTTERY_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_WEDDING_SERVICE_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_FOOD_RECIPE_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_COUNT_DOWN_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_REWARD_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_DISCOUNT_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_COUNT_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_BARRAGE_FRAME_FREE_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_IMAGE_RAID_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_WORLD_LABEL_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_ALTMAN_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_MENROCO_ENUM = protobuf.EnumValueDescriptor()
GLOBALACTIVITYTYPE_GACTIVITY_MAX_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS = protobuf.EnumDescriptor()
EACTPROGRESS_EACTPROGRESS_NONE_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_1_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_2_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_3_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_4_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_5_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_6_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_7_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_FAIL_ENUM = protobuf.EnumValueDescriptor()
EACTPROGRESS_EACTPROGRESS_SUCCESS_ENUM = protobuf.EnumValueDescriptor()
STARTACTCMD = protobuf.Descriptor()
STARTACTCMD_CMD_FIELD = protobuf.FieldDescriptor()
STARTACTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
STARTACTCMD_ID_FIELD = protobuf.FieldDescriptor()
STARTACTCMD_MAPID_FIELD = protobuf.FieldDescriptor()
STARTACTCMD_STARTTIME_FIELD = protobuf.FieldDescriptor()
STARTACTCMD_ENDTIME_FIELD = protobuf.FieldDescriptor()
STARTACTCMD_PATH_FIELD = protobuf.FieldDescriptor()
STARTACTCMD_UNSHOWMAP_FIELD = protobuf.FieldDescriptor()
STOPACTCMD = protobuf.Descriptor()
STOPACTCMD_CMD_FIELD = protobuf.FieldDescriptor()
STOPACTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
STOPACTCMD_ID_FIELD = protobuf.FieldDescriptor()
BCATUFOPOSACTCMD = protobuf.Descriptor()
BCATUFOPOSACTCMD_CMD_FIELD = protobuf.FieldDescriptor()
BCATUFOPOSACTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BCATUFOPOSACTCMD_POS_FIELD = protobuf.FieldDescriptor()
ACTPROGRESSNTFCMD = protobuf.Descriptor()
ACTPROGRESSNTFCMD_CMD_FIELD = protobuf.FieldDescriptor()
ACTPROGRESSNTFCMD_PARAM_FIELD = protobuf.FieldDescriptor()
ACTPROGRESSNTFCMD_ID_FIELD = protobuf.FieldDescriptor()
ACTPROGRESSNTFCMD_PROGRESS_FIELD = protobuf.FieldDescriptor()
ACTPROGRESSNTFCMD_ENDTIME_FIELD = protobuf.FieldDescriptor()
ACTPROGRESSNTFCMD_STARTTIME_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD = protobuf.Descriptor()
STARTGLOBALACTCMD_CMD_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_ID_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_TYPE_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_PARAMS_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_STARTTIME_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_ENDTIME_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_OPEN_FIELD = protobuf.FieldDescriptor()
STARTGLOBALACTCMD_COUNT_FIELD = protobuf.FieldDescriptor()
ACTIVITYPROGRESS = protobuf.Descriptor()
ACTIVITYPROGRESS_ACTID_FIELD = protobuf.FieldDescriptor()
ACTIVITYPROGRESS_PROGRESS_FIELD = protobuf.FieldDescriptor()
ACTIVITYPROGRESS_STARTTIME_FIELD = protobuf.FieldDescriptor()
ACTIVITYPROGRESS_ENDTIME_FIELD = protobuf.FieldDescriptor()
ACTIVITYPARAM_ACTIVITYPARAM_ACT_START_ENUM.name = "ACTIVITYPARAM_ACT_START"
ACTIVITYPARAM_ACTIVITYPARAM_ACT_START_ENUM.index = 0
ACTIVITYPARAM_ACTIVITYPARAM_ACT_START_ENUM.number = 1
ACTIVITYPARAM_ACTIVITYPARAM_BCAT_UFOPOS_ENUM.name = "ACTIVITYPARAM_BCAT_UFOPOS"
ACTIVITYPARAM_ACTIVITYPARAM_BCAT_UFOPOS_ENUM.index = 1
ACTIVITYPARAM_ACTIVITYPARAM_BCAT_UFOPOS_ENUM.number = 2
ACTIVITYPARAM_ACTIVITYPARAM_PROGRESS_NTF_ENUM.name = "ACTIVITYPARAM_PROGRESS_NTF"
ACTIVITYPARAM_ACTIVITYPARAM_PROGRESS_NTF_ENUM.index = 2
ACTIVITYPARAM_ACTIVITYPARAM_PROGRESS_NTF_ENUM.number = 3
ACTIVITYPARAM_ACTIVITYPARAM_ACT_STOP_ENUM.name = "ACTIVITYPARAM_ACT_STOP"
ACTIVITYPARAM_ACTIVITYPARAM_ACT_STOP_ENUM.index = 3
ACTIVITYPARAM_ACTIVITYPARAM_ACT_STOP_ENUM.number = 4
ACTIVITYPARAM_ACTIVITYPARAM_GLOBAL_ACT_START_ENUM.name = "ACTIVITYPARAM_GLOBAL_ACT_START"
ACTIVITYPARAM_ACTIVITYPARAM_GLOBAL_ACT_START_ENUM.index = 4
ACTIVITYPARAM_ACTIVITYPARAM_GLOBAL_ACT_START_ENUM.number = 5
ACTIVITYPARAM.name = "ActivityParam"
ACTIVITYPARAM.full_name = ".Cmd.ActivityParam"
ACTIVITYPARAM.values = {
  ACTIVITYPARAM_ACTIVITYPARAM_ACT_START_ENUM,
  ACTIVITYPARAM_ACTIVITYPARAM_BCAT_UFOPOS_ENUM,
  ACTIVITYPARAM_ACTIVITYPARAM_PROGRESS_NTF_ENUM,
  ACTIVITYPARAM_ACTIVITYPARAM_ACT_STOP_ENUM,
  ACTIVITYPARAM_ACTIVITYPARAM_GLOBAL_ACT_START_ENUM
}
GLOBALACTIVITYTYPE_GACTIVITY_MIN_ENUM.name = "GACTIVITY_MIN"
GLOBALACTIVITYTYPE_GACTIVITY_MIN_ENUM.index = 0
GLOBALACTIVITYTYPE_GACTIVITY_MIN_ENUM.number = 0
GLOBALACTIVITYTYPE_GACTIVITY_AUGURY_ENUM.name = "GACTIVITY_AUGURY"
GLOBALACTIVITYTYPE_GACTIVITY_AUGURY_ENUM.index = 1
GLOBALACTIVITYTYPE_GACTIVITY_AUGURY_ENUM.number = 14
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_QUEST_ENUM.name = "GACTIVITY_GUILD_QUEST"
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_QUEST_ENUM.index = 2
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_QUEST_ENUM.number = 15
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_DONATE_ENUM.name = "GACTIVITY_GUILD_DONATE"
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_DONATE_ENUM.index = 3
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_DONATE_ENUM.number = 16
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_FUBEN_ENUM.name = "GACTIVITY_GUILD_FUBEN"
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_FUBEN_ENUM.index = 4
GLOBALACTIVITYTYPE_GACTIVITY_GUILD_FUBEN_ENUM.number = 17
GLOBALACTIVITYTYPE_GACTIVITY_NOVICE_WELFARE_ENUM.name = "GACTIVITY_NOVICE_WELFARE"
GLOBALACTIVITYTYPE_GACTIVITY_NOVICE_WELFARE_ENUM.index = 5
GLOBALACTIVITYTYPE_GACTIVITY_NOVICE_WELFARE_ENUM.number = 18
GLOBALACTIVITYTYPE_GACTIVITY_NORMAL_REFINE_ENUM.name = "GACTIVITY_NORMAL_REFINE"
GLOBALACTIVITYTYPE_GACTIVITY_NORMAL_REFINE_ENUM.index = 6
GLOBALACTIVITYTYPE_GACTIVITY_NORMAL_REFINE_ENUM.number = 20
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_ENUM.name = "GACTIVITY_SAFE_REFINE"
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_ENUM.index = 7
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_ENUM.number = 21
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_DISCOUNT_ENUM.name = "GACTIVITY_SAFE_REFINE_DISCOUNT"
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_DISCOUNT_ENUM.index = 8
GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_DISCOUNT_ENUM.number = 22
GLOBALACTIVITYTYPE_GACTIVITY_RECALL_ENUM.name = "GACTIVITY_RECALL"
GLOBALACTIVITYTYPE_GACTIVITY_RECALL_ENUM.index = 9
GLOBALACTIVITYTYPE_GACTIVITY_RECALL_ENUM.number = 23
GLOBALACTIVITYTYPE_GACTIVITY_SPRING_LOTTERY_ENUM.name = "GACTIVITY_SPRING_LOTTERY"
GLOBALACTIVITYTYPE_GACTIVITY_SPRING_LOTTERY_ENUM.index = 10
GLOBALACTIVITYTYPE_GACTIVITY_SPRING_LOTTERY_ENUM.number = 24
GLOBALACTIVITYTYPE_GACTIVITY_WEDDING_SERVICE_ENUM.name = "GACTIVITY_WEDDING_SERVICE"
GLOBALACTIVITYTYPE_GACTIVITY_WEDDING_SERVICE_ENUM.index = 11
GLOBALACTIVITYTYPE_GACTIVITY_WEDDING_SERVICE_ENUM.number = 26
GLOBALACTIVITYTYPE_GACTIVITY_FOOD_RECIPE_ENUM.name = "GACTIVITY_FOOD_RECIPE"
GLOBALACTIVITYTYPE_GACTIVITY_FOOD_RECIPE_ENUM.index = 12
GLOBALACTIVITYTYPE_GACTIVITY_FOOD_RECIPE_ENUM.number = 27
GLOBALACTIVITYTYPE_GACTIVITY_COUNT_DOWN_ENUM.name = "GACTIVITY_COUNT_DOWN"
GLOBALACTIVITYTYPE_GACTIVITY_COUNT_DOWN_ENUM.index = 13
GLOBALACTIVITYTYPE_GACTIVITY_COUNT_DOWN_ENUM.number = 28
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_REWARD_ENUM.name = "GACTIVITY_CHARGE_EXTRA_REWARD"
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_REWARD_ENUM.index = 14
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_REWARD_ENUM.number = 30
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_DISCOUNT_ENUM.name = "GACTIVITY_CHARGE_DISCOUNT"
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_DISCOUNT_ENUM.index = 15
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_DISCOUNT_ENUM.number = 31
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_COUNT_ENUM.name = "GACTIVITY_CHARGE_EXTRA_COUNT"
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_COUNT_ENUM.index = 16
GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_COUNT_ENUM.number = 32
GLOBALACTIVITYTYPE_GACTIVITY_BARRAGE_FRAME_FREE_ENUM.name = "GACTIVITY_BARRAGE_FRAME_FREE"
GLOBALACTIVITYTYPE_GACTIVITY_BARRAGE_FRAME_FREE_ENUM.index = 17
GLOBALACTIVITYTYPE_GACTIVITY_BARRAGE_FRAME_FREE_ENUM.number = 33
GLOBALACTIVITYTYPE_GACTIVITY_IMAGE_RAID_ENUM.name = "GACTIVITY_IMAGE_RAID"
GLOBALACTIVITYTYPE_GACTIVITY_IMAGE_RAID_ENUM.index = 18
GLOBALACTIVITYTYPE_GACTIVITY_IMAGE_RAID_ENUM.number = 34
GLOBALACTIVITYTYPE_GACTIVITY_WORLD_LABEL_ENUM.name = "GACTIVITY_WORLD_LABEL"
GLOBALACTIVITYTYPE_GACTIVITY_WORLD_LABEL_ENUM.index = 19
GLOBALACTIVITYTYPE_GACTIVITY_WORLD_LABEL_ENUM.number = 60
GLOBALACTIVITYTYPE_GACTIVITY_ALTMAN_ENUM.name = "GACTIVITY_ALTMAN"
GLOBALACTIVITYTYPE_GACTIVITY_ALTMAN_ENUM.index = 20
GLOBALACTIVITYTYPE_GACTIVITY_ALTMAN_ENUM.number = 101
GLOBALACTIVITYTYPE_GACTIVITY_MENROCO_ENUM.name = "GACTIVITY_MENROCO"
GLOBALACTIVITYTYPE_GACTIVITY_MENROCO_ENUM.index = 21
GLOBALACTIVITYTYPE_GACTIVITY_MENROCO_ENUM.number = 1001
GLOBALACTIVITYTYPE_GACTIVITY_MAX_ENUM.name = "GACTIVITY_MAX"
GLOBALACTIVITYTYPE_GACTIVITY_MAX_ENUM.index = 22
GLOBALACTIVITYTYPE_GACTIVITY_MAX_ENUM.number = 1002
GLOBALACTIVITYTYPE.name = "GlobalActivityType"
GLOBALACTIVITYTYPE.full_name = ".Cmd.GlobalActivityType"
GLOBALACTIVITYTYPE.values = {
  GLOBALACTIVITYTYPE_GACTIVITY_MIN_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_AUGURY_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_GUILD_QUEST_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_GUILD_DONATE_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_GUILD_FUBEN_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_NOVICE_WELFARE_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_NORMAL_REFINE_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_SAFE_REFINE_DISCOUNT_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_RECALL_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_SPRING_LOTTERY_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_WEDDING_SERVICE_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_FOOD_RECIPE_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_COUNT_DOWN_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_REWARD_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_DISCOUNT_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_CHARGE_EXTRA_COUNT_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_BARRAGE_FRAME_FREE_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_IMAGE_RAID_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_WORLD_LABEL_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_ALTMAN_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_MENROCO_ENUM,
  GLOBALACTIVITYTYPE_GACTIVITY_MAX_ENUM
}
EACTPROGRESS_EACTPROGRESS_NONE_ENUM.name = "EACTPROGRESS_NONE"
EACTPROGRESS_EACTPROGRESS_NONE_ENUM.index = 0
EACTPROGRESS_EACTPROGRESS_NONE_ENUM.number = 0
EACTPROGRESS_EACTPROGRESS_1_ENUM.name = "EACTPROGRESS_1"
EACTPROGRESS_EACTPROGRESS_1_ENUM.index = 1
EACTPROGRESS_EACTPROGRESS_1_ENUM.number = 1
EACTPROGRESS_EACTPROGRESS_2_ENUM.name = "EACTPROGRESS_2"
EACTPROGRESS_EACTPROGRESS_2_ENUM.index = 2
EACTPROGRESS_EACTPROGRESS_2_ENUM.number = 2
EACTPROGRESS_EACTPROGRESS_3_ENUM.name = "EACTPROGRESS_3"
EACTPROGRESS_EACTPROGRESS_3_ENUM.index = 3
EACTPROGRESS_EACTPROGRESS_3_ENUM.number = 3
EACTPROGRESS_EACTPROGRESS_4_ENUM.name = "EACTPROGRESS_4"
EACTPROGRESS_EACTPROGRESS_4_ENUM.index = 4
EACTPROGRESS_EACTPROGRESS_4_ENUM.number = 4
EACTPROGRESS_EACTPROGRESS_5_ENUM.name = "EACTPROGRESS_5"
EACTPROGRESS_EACTPROGRESS_5_ENUM.index = 5
EACTPROGRESS_EACTPROGRESS_5_ENUM.number = 5
EACTPROGRESS_EACTPROGRESS_6_ENUM.name = "EACTPROGRESS_6"
EACTPROGRESS_EACTPROGRESS_6_ENUM.index = 6
EACTPROGRESS_EACTPROGRESS_6_ENUM.number = 6
EACTPROGRESS_EACTPROGRESS_7_ENUM.name = "EACTPROGRESS_7"
EACTPROGRESS_EACTPROGRESS_7_ENUM.index = 7
EACTPROGRESS_EACTPROGRESS_7_ENUM.number = 7
EACTPROGRESS_EACTPROGRESS_FAIL_ENUM.name = "EACTPROGRESS_FAIL"
EACTPROGRESS_EACTPROGRESS_FAIL_ENUM.index = 8
EACTPROGRESS_EACTPROGRESS_FAIL_ENUM.number = 100
EACTPROGRESS_EACTPROGRESS_SUCCESS_ENUM.name = "EACTPROGRESS_SUCCESS"
EACTPROGRESS_EACTPROGRESS_SUCCESS_ENUM.index = 9
EACTPROGRESS_EACTPROGRESS_SUCCESS_ENUM.number = 101
EACTPROGRESS.name = "EActProgress"
EACTPROGRESS.full_name = ".Cmd.EActProgress"
EACTPROGRESS.values = {
  EACTPROGRESS_EACTPROGRESS_NONE_ENUM,
  EACTPROGRESS_EACTPROGRESS_1_ENUM,
  EACTPROGRESS_EACTPROGRESS_2_ENUM,
  EACTPROGRESS_EACTPROGRESS_3_ENUM,
  EACTPROGRESS_EACTPROGRESS_4_ENUM,
  EACTPROGRESS_EACTPROGRESS_5_ENUM,
  EACTPROGRESS_EACTPROGRESS_6_ENUM,
  EACTPROGRESS_EACTPROGRESS_7_ENUM,
  EACTPROGRESS_EACTPROGRESS_FAIL_ENUM,
  EACTPROGRESS_EACTPROGRESS_SUCCESS_ENUM
}
STARTACTCMD_CMD_FIELD.name = "cmd"
STARTACTCMD_CMD_FIELD.full_name = ".Cmd.StartActCmd.cmd"
STARTACTCMD_CMD_FIELD.number = 1
STARTACTCMD_CMD_FIELD.index = 0
STARTACTCMD_CMD_FIELD.label = 1
STARTACTCMD_CMD_FIELD.has_default_value = true
STARTACTCMD_CMD_FIELD.default_value = 60
STARTACTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
STARTACTCMD_CMD_FIELD.type = 14
STARTACTCMD_CMD_FIELD.cpp_type = 8
STARTACTCMD_PARAM_FIELD.name = "param"
STARTACTCMD_PARAM_FIELD.full_name = ".Cmd.StartActCmd.param"
STARTACTCMD_PARAM_FIELD.number = 2
STARTACTCMD_PARAM_FIELD.index = 1
STARTACTCMD_PARAM_FIELD.label = 1
STARTACTCMD_PARAM_FIELD.has_default_value = true
STARTACTCMD_PARAM_FIELD.default_value = 1
STARTACTCMD_PARAM_FIELD.enum_type = ACTIVITYPARAM
STARTACTCMD_PARAM_FIELD.type = 14
STARTACTCMD_PARAM_FIELD.cpp_type = 8
STARTACTCMD_ID_FIELD.name = "id"
STARTACTCMD_ID_FIELD.full_name = ".Cmd.StartActCmd.id"
STARTACTCMD_ID_FIELD.number = 3
STARTACTCMD_ID_FIELD.index = 2
STARTACTCMD_ID_FIELD.label = 1
STARTACTCMD_ID_FIELD.has_default_value = false
STARTACTCMD_ID_FIELD.default_value = 0
STARTACTCMD_ID_FIELD.type = 13
STARTACTCMD_ID_FIELD.cpp_type = 3
STARTACTCMD_MAPID_FIELD.name = "mapid"
STARTACTCMD_MAPID_FIELD.full_name = ".Cmd.StartActCmd.mapid"
STARTACTCMD_MAPID_FIELD.number = 4
STARTACTCMD_MAPID_FIELD.index = 3
STARTACTCMD_MAPID_FIELD.label = 1
STARTACTCMD_MAPID_FIELD.has_default_value = true
STARTACTCMD_MAPID_FIELD.default_value = 0
STARTACTCMD_MAPID_FIELD.type = 13
STARTACTCMD_MAPID_FIELD.cpp_type = 3
STARTACTCMD_STARTTIME_FIELD.name = "starttime"
STARTACTCMD_STARTTIME_FIELD.full_name = ".Cmd.StartActCmd.starttime"
STARTACTCMD_STARTTIME_FIELD.number = 5
STARTACTCMD_STARTTIME_FIELD.index = 4
STARTACTCMD_STARTTIME_FIELD.label = 1
STARTACTCMD_STARTTIME_FIELD.has_default_value = true
STARTACTCMD_STARTTIME_FIELD.default_value = 0
STARTACTCMD_STARTTIME_FIELD.type = 13
STARTACTCMD_STARTTIME_FIELD.cpp_type = 3
STARTACTCMD_ENDTIME_FIELD.name = "endtime"
STARTACTCMD_ENDTIME_FIELD.full_name = ".Cmd.StartActCmd.endtime"
STARTACTCMD_ENDTIME_FIELD.number = 6
STARTACTCMD_ENDTIME_FIELD.index = 5
STARTACTCMD_ENDTIME_FIELD.label = 1
STARTACTCMD_ENDTIME_FIELD.has_default_value = true
STARTACTCMD_ENDTIME_FIELD.default_value = 0
STARTACTCMD_ENDTIME_FIELD.type = 13
STARTACTCMD_ENDTIME_FIELD.cpp_type = 3
STARTACTCMD_PATH_FIELD.name = "path"
STARTACTCMD_PATH_FIELD.full_name = ".Cmd.StartActCmd.path"
STARTACTCMD_PATH_FIELD.number = 7
STARTACTCMD_PATH_FIELD.index = 6
STARTACTCMD_PATH_FIELD.label = 1
STARTACTCMD_PATH_FIELD.has_default_value = false
STARTACTCMD_PATH_FIELD.default_value = 0
STARTACTCMD_PATH_FIELD.type = 13
STARTACTCMD_PATH_FIELD.cpp_type = 3
STARTACTCMD_UNSHOWMAP_FIELD.name = "unshowmap"
STARTACTCMD_UNSHOWMAP_FIELD.full_name = ".Cmd.StartActCmd.unshowmap"
STARTACTCMD_UNSHOWMAP_FIELD.number = 8
STARTACTCMD_UNSHOWMAP_FIELD.index = 7
STARTACTCMD_UNSHOWMAP_FIELD.label = 3
STARTACTCMD_UNSHOWMAP_FIELD.has_default_value = false
STARTACTCMD_UNSHOWMAP_FIELD.default_value = {}
STARTACTCMD_UNSHOWMAP_FIELD.type = 13
STARTACTCMD_UNSHOWMAP_FIELD.cpp_type = 3
STARTACTCMD.name = "StartActCmd"
STARTACTCMD.full_name = ".Cmd.StartActCmd"
STARTACTCMD.nested_types = {}
STARTACTCMD.enum_types = {}
STARTACTCMD.fields = {
  STARTACTCMD_CMD_FIELD,
  STARTACTCMD_PARAM_FIELD,
  STARTACTCMD_ID_FIELD,
  STARTACTCMD_MAPID_FIELD,
  STARTACTCMD_STARTTIME_FIELD,
  STARTACTCMD_ENDTIME_FIELD,
  STARTACTCMD_PATH_FIELD,
  STARTACTCMD_UNSHOWMAP_FIELD
}
STARTACTCMD.is_extendable = false
STARTACTCMD.extensions = {}
STOPACTCMD_CMD_FIELD.name = "cmd"
STOPACTCMD_CMD_FIELD.full_name = ".Cmd.StopActCmd.cmd"
STOPACTCMD_CMD_FIELD.number = 1
STOPACTCMD_CMD_FIELD.index = 0
STOPACTCMD_CMD_FIELD.label = 1
STOPACTCMD_CMD_FIELD.has_default_value = true
STOPACTCMD_CMD_FIELD.default_value = 60
STOPACTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
STOPACTCMD_CMD_FIELD.type = 14
STOPACTCMD_CMD_FIELD.cpp_type = 8
STOPACTCMD_PARAM_FIELD.name = "param"
STOPACTCMD_PARAM_FIELD.full_name = ".Cmd.StopActCmd.param"
STOPACTCMD_PARAM_FIELD.number = 2
STOPACTCMD_PARAM_FIELD.index = 1
STOPACTCMD_PARAM_FIELD.label = 1
STOPACTCMD_PARAM_FIELD.has_default_value = true
STOPACTCMD_PARAM_FIELD.default_value = 4
STOPACTCMD_PARAM_FIELD.enum_type = ACTIVITYPARAM
STOPACTCMD_PARAM_FIELD.type = 14
STOPACTCMD_PARAM_FIELD.cpp_type = 8
STOPACTCMD_ID_FIELD.name = "id"
STOPACTCMD_ID_FIELD.full_name = ".Cmd.StopActCmd.id"
STOPACTCMD_ID_FIELD.number = 3
STOPACTCMD_ID_FIELD.index = 2
STOPACTCMD_ID_FIELD.label = 1
STOPACTCMD_ID_FIELD.has_default_value = false
STOPACTCMD_ID_FIELD.default_value = 0
STOPACTCMD_ID_FIELD.type = 13
STOPACTCMD_ID_FIELD.cpp_type = 3
STOPACTCMD.name = "StopActCmd"
STOPACTCMD.full_name = ".Cmd.StopActCmd"
STOPACTCMD.nested_types = {}
STOPACTCMD.enum_types = {}
STOPACTCMD.fields = {
  STOPACTCMD_CMD_FIELD,
  STOPACTCMD_PARAM_FIELD,
  STOPACTCMD_ID_FIELD
}
STOPACTCMD.is_extendable = false
STOPACTCMD.extensions = {}
BCATUFOPOSACTCMD_CMD_FIELD.name = "cmd"
BCATUFOPOSACTCMD_CMD_FIELD.full_name = ".Cmd.BCatUFOPosActCmd.cmd"
BCATUFOPOSACTCMD_CMD_FIELD.number = 1
BCATUFOPOSACTCMD_CMD_FIELD.index = 0
BCATUFOPOSACTCMD_CMD_FIELD.label = 1
BCATUFOPOSACTCMD_CMD_FIELD.has_default_value = true
BCATUFOPOSACTCMD_CMD_FIELD.default_value = 60
BCATUFOPOSACTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BCATUFOPOSACTCMD_CMD_FIELD.type = 14
BCATUFOPOSACTCMD_CMD_FIELD.cpp_type = 8
BCATUFOPOSACTCMD_PARAM_FIELD.name = "param"
BCATUFOPOSACTCMD_PARAM_FIELD.full_name = ".Cmd.BCatUFOPosActCmd.param"
BCATUFOPOSACTCMD_PARAM_FIELD.number = 2
BCATUFOPOSACTCMD_PARAM_FIELD.index = 1
BCATUFOPOSACTCMD_PARAM_FIELD.label = 1
BCATUFOPOSACTCMD_PARAM_FIELD.has_default_value = true
BCATUFOPOSACTCMD_PARAM_FIELD.default_value = 2
BCATUFOPOSACTCMD_PARAM_FIELD.enum_type = ACTIVITYPARAM
BCATUFOPOSACTCMD_PARAM_FIELD.type = 14
BCATUFOPOSACTCMD_PARAM_FIELD.cpp_type = 8
BCATUFOPOSACTCMD_POS_FIELD.name = "pos"
BCATUFOPOSACTCMD_POS_FIELD.full_name = ".Cmd.BCatUFOPosActCmd.pos"
BCATUFOPOSACTCMD_POS_FIELD.number = 3
BCATUFOPOSACTCMD_POS_FIELD.index = 2
BCATUFOPOSACTCMD_POS_FIELD.label = 1
BCATUFOPOSACTCMD_POS_FIELD.has_default_value = false
BCATUFOPOSACTCMD_POS_FIELD.default_value = nil
BCATUFOPOSACTCMD_POS_FIELD.message_type = ProtoCommon_pb.SCENEPOS
BCATUFOPOSACTCMD_POS_FIELD.type = 11
BCATUFOPOSACTCMD_POS_FIELD.cpp_type = 10
BCATUFOPOSACTCMD.name = "BCatUFOPosActCmd"
BCATUFOPOSACTCMD.full_name = ".Cmd.BCatUFOPosActCmd"
BCATUFOPOSACTCMD.nested_types = {}
BCATUFOPOSACTCMD.enum_types = {}
BCATUFOPOSACTCMD.fields = {
  BCATUFOPOSACTCMD_CMD_FIELD,
  BCATUFOPOSACTCMD_PARAM_FIELD,
  BCATUFOPOSACTCMD_POS_FIELD
}
BCATUFOPOSACTCMD.is_extendable = false
BCATUFOPOSACTCMD.extensions = {}
ACTPROGRESSNTFCMD_CMD_FIELD.name = "cmd"
ACTPROGRESSNTFCMD_CMD_FIELD.full_name = ".Cmd.ActProgressNtfCmd.cmd"
ACTPROGRESSNTFCMD_CMD_FIELD.number = 1
ACTPROGRESSNTFCMD_CMD_FIELD.index = 0
ACTPROGRESSNTFCMD_CMD_FIELD.label = 1
ACTPROGRESSNTFCMD_CMD_FIELD.has_default_value = true
ACTPROGRESSNTFCMD_CMD_FIELD.default_value = 60
ACTPROGRESSNTFCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTPROGRESSNTFCMD_CMD_FIELD.type = 14
ACTPROGRESSNTFCMD_CMD_FIELD.cpp_type = 8
ACTPROGRESSNTFCMD_PARAM_FIELD.name = "param"
ACTPROGRESSNTFCMD_PARAM_FIELD.full_name = ".Cmd.ActProgressNtfCmd.param"
ACTPROGRESSNTFCMD_PARAM_FIELD.number = 2
ACTPROGRESSNTFCMD_PARAM_FIELD.index = 1
ACTPROGRESSNTFCMD_PARAM_FIELD.label = 1
ACTPROGRESSNTFCMD_PARAM_FIELD.has_default_value = true
ACTPROGRESSNTFCMD_PARAM_FIELD.default_value = 3
ACTPROGRESSNTFCMD_PARAM_FIELD.enum_type = ACTIVITYPARAM
ACTPROGRESSNTFCMD_PARAM_FIELD.type = 14
ACTPROGRESSNTFCMD_PARAM_FIELD.cpp_type = 8
ACTPROGRESSNTFCMD_ID_FIELD.name = "id"
ACTPROGRESSNTFCMD_ID_FIELD.full_name = ".Cmd.ActProgressNtfCmd.id"
ACTPROGRESSNTFCMD_ID_FIELD.number = 3
ACTPROGRESSNTFCMD_ID_FIELD.index = 2
ACTPROGRESSNTFCMD_ID_FIELD.label = 1
ACTPROGRESSNTFCMD_ID_FIELD.has_default_value = false
ACTPROGRESSNTFCMD_ID_FIELD.default_value = 0
ACTPROGRESSNTFCMD_ID_FIELD.type = 13
ACTPROGRESSNTFCMD_ID_FIELD.cpp_type = 3
ACTPROGRESSNTFCMD_PROGRESS_FIELD.name = "progress"
ACTPROGRESSNTFCMD_PROGRESS_FIELD.full_name = ".Cmd.ActProgressNtfCmd.progress"
ACTPROGRESSNTFCMD_PROGRESS_FIELD.number = 4
ACTPROGRESSNTFCMD_PROGRESS_FIELD.index = 3
ACTPROGRESSNTFCMD_PROGRESS_FIELD.label = 1
ACTPROGRESSNTFCMD_PROGRESS_FIELD.has_default_value = false
ACTPROGRESSNTFCMD_PROGRESS_FIELD.default_value = nil
ACTPROGRESSNTFCMD_PROGRESS_FIELD.enum_type = EACTPROGRESS
ACTPROGRESSNTFCMD_PROGRESS_FIELD.type = 14
ACTPROGRESSNTFCMD_PROGRESS_FIELD.cpp_type = 8
ACTPROGRESSNTFCMD_ENDTIME_FIELD.name = "endtime"
ACTPROGRESSNTFCMD_ENDTIME_FIELD.full_name = ".Cmd.ActProgressNtfCmd.endtime"
ACTPROGRESSNTFCMD_ENDTIME_FIELD.number = 5
ACTPROGRESSNTFCMD_ENDTIME_FIELD.index = 4
ACTPROGRESSNTFCMD_ENDTIME_FIELD.label = 1
ACTPROGRESSNTFCMD_ENDTIME_FIELD.has_default_value = false
ACTPROGRESSNTFCMD_ENDTIME_FIELD.default_value = 0
ACTPROGRESSNTFCMD_ENDTIME_FIELD.type = 13
ACTPROGRESSNTFCMD_ENDTIME_FIELD.cpp_type = 3
ACTPROGRESSNTFCMD_STARTTIME_FIELD.name = "starttime"
ACTPROGRESSNTFCMD_STARTTIME_FIELD.full_name = ".Cmd.ActProgressNtfCmd.starttime"
ACTPROGRESSNTFCMD_STARTTIME_FIELD.number = 6
ACTPROGRESSNTFCMD_STARTTIME_FIELD.index = 5
ACTPROGRESSNTFCMD_STARTTIME_FIELD.label = 1
ACTPROGRESSNTFCMD_STARTTIME_FIELD.has_default_value = false
ACTPROGRESSNTFCMD_STARTTIME_FIELD.default_value = 0
ACTPROGRESSNTFCMD_STARTTIME_FIELD.type = 13
ACTPROGRESSNTFCMD_STARTTIME_FIELD.cpp_type = 3
ACTPROGRESSNTFCMD.name = "ActProgressNtfCmd"
ACTPROGRESSNTFCMD.full_name = ".Cmd.ActProgressNtfCmd"
ACTPROGRESSNTFCMD.nested_types = {}
ACTPROGRESSNTFCMD.enum_types = {}
ACTPROGRESSNTFCMD.fields = {
  ACTPROGRESSNTFCMD_CMD_FIELD,
  ACTPROGRESSNTFCMD_PARAM_FIELD,
  ACTPROGRESSNTFCMD_ID_FIELD,
  ACTPROGRESSNTFCMD_PROGRESS_FIELD,
  ACTPROGRESSNTFCMD_ENDTIME_FIELD,
  ACTPROGRESSNTFCMD_STARTTIME_FIELD
}
ACTPROGRESSNTFCMD.is_extendable = false
ACTPROGRESSNTFCMD.extensions = {}
STARTGLOBALACTCMD_CMD_FIELD.name = "cmd"
STARTGLOBALACTCMD_CMD_FIELD.full_name = ".Cmd.StartGlobalActCmd.cmd"
STARTGLOBALACTCMD_CMD_FIELD.number = 1
STARTGLOBALACTCMD_CMD_FIELD.index = 0
STARTGLOBALACTCMD_CMD_FIELD.label = 1
STARTGLOBALACTCMD_CMD_FIELD.has_default_value = true
STARTGLOBALACTCMD_CMD_FIELD.default_value = 60
STARTGLOBALACTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
STARTGLOBALACTCMD_CMD_FIELD.type = 14
STARTGLOBALACTCMD_CMD_FIELD.cpp_type = 8
STARTGLOBALACTCMD_PARAM_FIELD.name = "param"
STARTGLOBALACTCMD_PARAM_FIELD.full_name = ".Cmd.StartGlobalActCmd.param"
STARTGLOBALACTCMD_PARAM_FIELD.number = 2
STARTGLOBALACTCMD_PARAM_FIELD.index = 1
STARTGLOBALACTCMD_PARAM_FIELD.label = 1
STARTGLOBALACTCMD_PARAM_FIELD.has_default_value = true
STARTGLOBALACTCMD_PARAM_FIELD.default_value = 5
STARTGLOBALACTCMD_PARAM_FIELD.enum_type = ACTIVITYPARAM
STARTGLOBALACTCMD_PARAM_FIELD.type = 14
STARTGLOBALACTCMD_PARAM_FIELD.cpp_type = 8
STARTGLOBALACTCMD_ID_FIELD.name = "id"
STARTGLOBALACTCMD_ID_FIELD.full_name = ".Cmd.StartGlobalActCmd.id"
STARTGLOBALACTCMD_ID_FIELD.number = 3
STARTGLOBALACTCMD_ID_FIELD.index = 2
STARTGLOBALACTCMD_ID_FIELD.label = 1
STARTGLOBALACTCMD_ID_FIELD.has_default_value = false
STARTGLOBALACTCMD_ID_FIELD.default_value = 0
STARTGLOBALACTCMD_ID_FIELD.type = 13
STARTGLOBALACTCMD_ID_FIELD.cpp_type = 3
STARTGLOBALACTCMD_TYPE_FIELD.name = "type"
STARTGLOBALACTCMD_TYPE_FIELD.full_name = ".Cmd.StartGlobalActCmd.type"
STARTGLOBALACTCMD_TYPE_FIELD.number = 4
STARTGLOBALACTCMD_TYPE_FIELD.index = 3
STARTGLOBALACTCMD_TYPE_FIELD.label = 1
STARTGLOBALACTCMD_TYPE_FIELD.has_default_value = false
STARTGLOBALACTCMD_TYPE_FIELD.default_value = nil
STARTGLOBALACTCMD_TYPE_FIELD.enum_type = GLOBALACTIVITYTYPE
STARTGLOBALACTCMD_TYPE_FIELD.type = 14
STARTGLOBALACTCMD_TYPE_FIELD.cpp_type = 8
STARTGLOBALACTCMD_PARAMS_FIELD.name = "params"
STARTGLOBALACTCMD_PARAMS_FIELD.full_name = ".Cmd.StartGlobalActCmd.params"
STARTGLOBALACTCMD_PARAMS_FIELD.number = 5
STARTGLOBALACTCMD_PARAMS_FIELD.index = 4
STARTGLOBALACTCMD_PARAMS_FIELD.label = 3
STARTGLOBALACTCMD_PARAMS_FIELD.has_default_value = false
STARTGLOBALACTCMD_PARAMS_FIELD.default_value = {}
STARTGLOBALACTCMD_PARAMS_FIELD.type = 13
STARTGLOBALACTCMD_PARAMS_FIELD.cpp_type = 3
STARTGLOBALACTCMD_STARTTIME_FIELD.name = "starttime"
STARTGLOBALACTCMD_STARTTIME_FIELD.full_name = ".Cmd.StartGlobalActCmd.starttime"
STARTGLOBALACTCMD_STARTTIME_FIELD.number = 6
STARTGLOBALACTCMD_STARTTIME_FIELD.index = 5
STARTGLOBALACTCMD_STARTTIME_FIELD.label = 1
STARTGLOBALACTCMD_STARTTIME_FIELD.has_default_value = false
STARTGLOBALACTCMD_STARTTIME_FIELD.default_value = 0
STARTGLOBALACTCMD_STARTTIME_FIELD.type = 13
STARTGLOBALACTCMD_STARTTIME_FIELD.cpp_type = 3
STARTGLOBALACTCMD_ENDTIME_FIELD.name = "endtime"
STARTGLOBALACTCMD_ENDTIME_FIELD.full_name = ".Cmd.StartGlobalActCmd.endtime"
STARTGLOBALACTCMD_ENDTIME_FIELD.number = 7
STARTGLOBALACTCMD_ENDTIME_FIELD.index = 6
STARTGLOBALACTCMD_ENDTIME_FIELD.label = 1
STARTGLOBALACTCMD_ENDTIME_FIELD.has_default_value = false
STARTGLOBALACTCMD_ENDTIME_FIELD.default_value = 0
STARTGLOBALACTCMD_ENDTIME_FIELD.type = 13
STARTGLOBALACTCMD_ENDTIME_FIELD.cpp_type = 3
STARTGLOBALACTCMD_OPEN_FIELD.name = "open"
STARTGLOBALACTCMD_OPEN_FIELD.full_name = ".Cmd.StartGlobalActCmd.open"
STARTGLOBALACTCMD_OPEN_FIELD.number = 8
STARTGLOBALACTCMD_OPEN_FIELD.index = 7
STARTGLOBALACTCMD_OPEN_FIELD.label = 1
STARTGLOBALACTCMD_OPEN_FIELD.has_default_value = false
STARTGLOBALACTCMD_OPEN_FIELD.default_value = false
STARTGLOBALACTCMD_OPEN_FIELD.type = 8
STARTGLOBALACTCMD_OPEN_FIELD.cpp_type = 7
STARTGLOBALACTCMD_COUNT_FIELD.name = "count"
STARTGLOBALACTCMD_COUNT_FIELD.full_name = ".Cmd.StartGlobalActCmd.count"
STARTGLOBALACTCMD_COUNT_FIELD.number = 9
STARTGLOBALACTCMD_COUNT_FIELD.index = 8
STARTGLOBALACTCMD_COUNT_FIELD.label = 1
STARTGLOBALACTCMD_COUNT_FIELD.has_default_value = false
STARTGLOBALACTCMD_COUNT_FIELD.default_value = 0
STARTGLOBALACTCMD_COUNT_FIELD.type = 13
STARTGLOBALACTCMD_COUNT_FIELD.cpp_type = 3
STARTGLOBALACTCMD.name = "StartGlobalActCmd"
STARTGLOBALACTCMD.full_name = ".Cmd.StartGlobalActCmd"
STARTGLOBALACTCMD.nested_types = {}
STARTGLOBALACTCMD.enum_types = {}
STARTGLOBALACTCMD.fields = {
  STARTGLOBALACTCMD_CMD_FIELD,
  STARTGLOBALACTCMD_PARAM_FIELD,
  STARTGLOBALACTCMD_ID_FIELD,
  STARTGLOBALACTCMD_TYPE_FIELD,
  STARTGLOBALACTCMD_PARAMS_FIELD,
  STARTGLOBALACTCMD_STARTTIME_FIELD,
  STARTGLOBALACTCMD_ENDTIME_FIELD,
  STARTGLOBALACTCMD_OPEN_FIELD,
  STARTGLOBALACTCMD_COUNT_FIELD
}
STARTGLOBALACTCMD.is_extendable = false
STARTGLOBALACTCMD.extensions = {}
ACTIVITYPROGRESS_ACTID_FIELD.name = "actid"
ACTIVITYPROGRESS_ACTID_FIELD.full_name = ".Cmd.ActivityProgress.actid"
ACTIVITYPROGRESS_ACTID_FIELD.number = 1
ACTIVITYPROGRESS_ACTID_FIELD.index = 0
ACTIVITYPROGRESS_ACTID_FIELD.label = 1
ACTIVITYPROGRESS_ACTID_FIELD.has_default_value = false
ACTIVITYPROGRESS_ACTID_FIELD.default_value = 0
ACTIVITYPROGRESS_ACTID_FIELD.type = 13
ACTIVITYPROGRESS_ACTID_FIELD.cpp_type = 3
ACTIVITYPROGRESS_PROGRESS_FIELD.name = "progress"
ACTIVITYPROGRESS_PROGRESS_FIELD.full_name = ".Cmd.ActivityProgress.progress"
ACTIVITYPROGRESS_PROGRESS_FIELD.number = 2
ACTIVITYPROGRESS_PROGRESS_FIELD.index = 1
ACTIVITYPROGRESS_PROGRESS_FIELD.label = 1
ACTIVITYPROGRESS_PROGRESS_FIELD.has_default_value = false
ACTIVITYPROGRESS_PROGRESS_FIELD.default_value = 0
ACTIVITYPROGRESS_PROGRESS_FIELD.type = 13
ACTIVITYPROGRESS_PROGRESS_FIELD.cpp_type = 3
ACTIVITYPROGRESS_STARTTIME_FIELD.name = "starttime"
ACTIVITYPROGRESS_STARTTIME_FIELD.full_name = ".Cmd.ActivityProgress.starttime"
ACTIVITYPROGRESS_STARTTIME_FIELD.number = 3
ACTIVITYPROGRESS_STARTTIME_FIELD.index = 2
ACTIVITYPROGRESS_STARTTIME_FIELD.label = 1
ACTIVITYPROGRESS_STARTTIME_FIELD.has_default_value = false
ACTIVITYPROGRESS_STARTTIME_FIELD.default_value = 0
ACTIVITYPROGRESS_STARTTIME_FIELD.type = 13
ACTIVITYPROGRESS_STARTTIME_FIELD.cpp_type = 3
ACTIVITYPROGRESS_ENDTIME_FIELD.name = "endtime"
ACTIVITYPROGRESS_ENDTIME_FIELD.full_name = ".Cmd.ActivityProgress.endtime"
ACTIVITYPROGRESS_ENDTIME_FIELD.number = 4
ACTIVITYPROGRESS_ENDTIME_FIELD.index = 3
ACTIVITYPROGRESS_ENDTIME_FIELD.label = 1
ACTIVITYPROGRESS_ENDTIME_FIELD.has_default_value = false
ACTIVITYPROGRESS_ENDTIME_FIELD.default_value = 0
ACTIVITYPROGRESS_ENDTIME_FIELD.type = 13
ACTIVITYPROGRESS_ENDTIME_FIELD.cpp_type = 3
ACTIVITYPROGRESS.name = "ActivityProgress"
ACTIVITYPROGRESS.full_name = ".Cmd.ActivityProgress"
ACTIVITYPROGRESS.nested_types = {}
ACTIVITYPROGRESS.enum_types = {}
ACTIVITYPROGRESS.fields = {
  ACTIVITYPROGRESS_ACTID_FIELD,
  ACTIVITYPROGRESS_PROGRESS_FIELD,
  ACTIVITYPROGRESS_STARTTIME_FIELD,
  ACTIVITYPROGRESS_ENDTIME_FIELD
}
ACTIVITYPROGRESS.is_extendable = false
ACTIVITYPROGRESS.extensions = {}
ACTIVITYPARAM_ACT_START = 1
ACTIVITYPARAM_ACT_STOP = 4
ACTIVITYPARAM_BCAT_UFOPOS = 2
ACTIVITYPARAM_GLOBAL_ACT_START = 5
ACTIVITYPARAM_PROGRESS_NTF = 3
ActProgressNtfCmd = protobuf.Message(ACTPROGRESSNTFCMD)
ActivityProgress = protobuf.Message(ACTIVITYPROGRESS)
BCatUFOPosActCmd = protobuf.Message(BCATUFOPOSACTCMD)
EACTPROGRESS_1 = 1
EACTPROGRESS_2 = 2
EACTPROGRESS_3 = 3
EACTPROGRESS_4 = 4
EACTPROGRESS_5 = 5
EACTPROGRESS_6 = 6
EACTPROGRESS_7 = 7
EACTPROGRESS_FAIL = 100
EACTPROGRESS_NONE = 0
EACTPROGRESS_SUCCESS = 101
GACTIVITY_ALTMAN = 101
GACTIVITY_AUGURY = 14
GACTIVITY_BARRAGE_FRAME_FREE = 33
GACTIVITY_CHARGE_DISCOUNT = 31
GACTIVITY_CHARGE_EXTRA_COUNT = 32
GACTIVITY_CHARGE_EXTRA_REWARD = 30
GACTIVITY_COUNT_DOWN = 28
GACTIVITY_FOOD_RECIPE = 27
GACTIVITY_GUILD_DONATE = 16
GACTIVITY_GUILD_FUBEN = 17
GACTIVITY_GUILD_QUEST = 15
GACTIVITY_IMAGE_RAID = 34
GACTIVITY_MAX = 1002
GACTIVITY_MENROCO = 1001
GACTIVITY_MIN = 0
GACTIVITY_NORMAL_REFINE = 20
GACTIVITY_NOVICE_WELFARE = 18
GACTIVITY_RECALL = 23
GACTIVITY_SAFE_REFINE = 21
GACTIVITY_SAFE_REFINE_DISCOUNT = 22
GACTIVITY_SPRING_LOTTERY = 24
GACTIVITY_WEDDING_SERVICE = 26
GACTIVITY_WORLD_LABEL = 60
StartActCmd = protobuf.Message(STARTACTCMD)
StartGlobalActCmd = protobuf.Message(STARTGLOBALACTCMD)
StopActCmd = protobuf.Message(STOPACTCMD)
