local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("BossCmd_pb")
BOSSPARAM = protobuf.EnumDescriptor()
BOSSPARAM_BOSS_LIST_USER_CMD_ENUM = protobuf.EnumValueDescriptor()
BOSSPARAM_BOSS_POS_USER_CMD_ENUM = protobuf.EnumValueDescriptor()
BOSSPARAM_BOSS_KILL_USER_CMD_ENUM = protobuf.EnumValueDescriptor()
BOSSPARAM_BOSS_USER_INFO_CMD_ENUM = protobuf.EnumValueDescriptor()
BOSSPARAM_BOSS_WORLD_NTF_ENUM = protobuf.EnumValueDescriptor()
BOSSPARAM_BOSS_STEP_SYNC_ENUM = protobuf.EnumValueDescriptor()
EBOSSREFRESHSTATE = protobuf.EnumDescriptor()
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MIN_ENUM = protobuf.EnumValueDescriptor()
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_APPEARED_ENUM = protobuf.EnumValueDescriptor()
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_UPCOMING_ENUM = protobuf.EnumValueDescriptor()
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_SHORT_ENUM = protobuf.EnumValueDescriptor()
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_LONG_ENUM = protobuf.EnumValueDescriptor()
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MAX_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP = protobuf.EnumDescriptor()
EBOSSSTEP_EBOSSSTEP_MIN_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_VISIT_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_SUMMON_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_CLEAR_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_BOSS_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_END_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_LIMIT_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_DIALOG_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_STATUS_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_WAIT_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_KILL_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_WORLD_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_SHOW_ENUM = protobuf.EnumValueDescriptor()
EBOSSSTEP_EBOSSSTEP_MAX_ENUM = protobuf.EnumValueDescriptor()
BOSSINFOITEM = protobuf.Descriptor()
BOSSINFOITEM_ID_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_REFRESHTIME_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_DIETIME_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_SUMMONTIME_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_MAPID_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_SETTIME_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_LV_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_REFRESHSTATE_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_LASTKILLER_FIELD = protobuf.FieldDescriptor()
BOSSINFOITEM_CHARID_FIELD = protobuf.FieldDescriptor()
BOSSLISTUSERCMD = protobuf.Descriptor()
BOSSLISTUSERCMD_CMD_FIELD = protobuf.FieldDescriptor()
BOSSLISTUSERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BOSSLISTUSERCMD_BOSSLIST_FIELD = protobuf.FieldDescriptor()
BOSSLISTUSERCMD_MINILIST_FIELD = protobuf.FieldDescriptor()
BOSSLISTUSERCMD_DEADLIST_FIELD = protobuf.FieldDescriptor()
BOSSPOSUSERCMD = protobuf.Descriptor()
BOSSPOSUSERCMD_CMD_FIELD = protobuf.FieldDescriptor()
BOSSPOSUSERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
BOSSPOSUSERCMD_POS_FIELD = protobuf.FieldDescriptor()
KILLBOSSUSERCMD = protobuf.Descriptor()
KILLBOSSUSERCMD_CMD_FIELD = protobuf.FieldDescriptor()
KILLBOSSUSERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
KILLBOSSUSERCMD_USERID_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA = protobuf.Descriptor()
BOSSKILLERDATA_CHARID_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_PORTRAIT_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_BASELEVEL_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_HAIR_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_HAIRCOLOR_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_BODY_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_HEAD_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_FACE_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_MOUTH_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_EYE_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_BLINK_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_PROFESSION_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_GENDER_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_NAME_FIELD = protobuf.FieldDescriptor()
BOSSKILLERDATA_GUILDNAME_FIELD = protobuf.FieldDescriptor()
QUERYKILLERINFOBOSSCMD = protobuf.Descriptor()
QUERYKILLERINFOBOSSCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYKILLERINFOBOSSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYKILLERINFOBOSSCMD_CHARID_FIELD = protobuf.FieldDescriptor()
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD = protobuf.FieldDescriptor()
WORLDBOSSNTF = protobuf.Descriptor()
WORLDBOSSNTF_CMD_FIELD = protobuf.FieldDescriptor()
WORLDBOSSNTF_PARAM_FIELD = protobuf.FieldDescriptor()
WORLDBOSSNTF_NPCID_FIELD = protobuf.FieldDescriptor()
WORLDBOSSNTF_MAPID_FIELD = protobuf.FieldDescriptor()
WORLDBOSSNTF_TIME_FIELD = protobuf.FieldDescriptor()
WORLDBOSSNTF_OPEN_FIELD = protobuf.FieldDescriptor()
STEPSYNCBOSSCMD = protobuf.Descriptor()
STEPSYNCBOSSCMD_CMD_FIELD = protobuf.FieldDescriptor()
STEPSYNCBOSSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
STEPSYNCBOSSCMD_ACTID_FIELD = protobuf.FieldDescriptor()
STEPSYNCBOSSCMD_STEP_FIELD = protobuf.FieldDescriptor()
STEPSYNCBOSSCMD_PARAMS_FIELD = protobuf.FieldDescriptor()
BOSSPARAM_BOSS_LIST_USER_CMD_ENUM.name = "BOSS_LIST_USER_CMD"
BOSSPARAM_BOSS_LIST_USER_CMD_ENUM.index = 0
BOSSPARAM_BOSS_LIST_USER_CMD_ENUM.number = 1
BOSSPARAM_BOSS_POS_USER_CMD_ENUM.name = "BOSS_POS_USER_CMD"
BOSSPARAM_BOSS_POS_USER_CMD_ENUM.index = 1
BOSSPARAM_BOSS_POS_USER_CMD_ENUM.number = 2
BOSSPARAM_BOSS_KILL_USER_CMD_ENUM.name = "BOSS_KILL_USER_CMD"
BOSSPARAM_BOSS_KILL_USER_CMD_ENUM.index = 2
BOSSPARAM_BOSS_KILL_USER_CMD_ENUM.number = 3
BOSSPARAM_BOSS_USER_INFO_CMD_ENUM.name = "BOSS_USER_INFO_CMD"
BOSSPARAM_BOSS_USER_INFO_CMD_ENUM.index = 3
BOSSPARAM_BOSS_USER_INFO_CMD_ENUM.number = 4
BOSSPARAM_BOSS_WORLD_NTF_ENUM.name = "BOSS_WORLD_NTF"
BOSSPARAM_BOSS_WORLD_NTF_ENUM.index = 4
BOSSPARAM_BOSS_WORLD_NTF_ENUM.number = 5
BOSSPARAM_BOSS_STEP_SYNC_ENUM.name = "BOSS_STEP_SYNC"
BOSSPARAM_BOSS_STEP_SYNC_ENUM.index = 5
BOSSPARAM_BOSS_STEP_SYNC_ENUM.number = 6
BOSSPARAM.name = "BossParam"
BOSSPARAM.full_name = ".Cmd.BossParam"
BOSSPARAM.values = {
  BOSSPARAM_BOSS_LIST_USER_CMD_ENUM,
  BOSSPARAM_BOSS_POS_USER_CMD_ENUM,
  BOSSPARAM_BOSS_KILL_USER_CMD_ENUM,
  BOSSPARAM_BOSS_USER_INFO_CMD_ENUM,
  BOSSPARAM_BOSS_WORLD_NTF_ENUM,
  BOSSPARAM_BOSS_STEP_SYNC_ENUM
}
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MIN_ENUM.name = "EBOSSREFRESHSTATE_MIN"
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MIN_ENUM.index = 0
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MIN_ENUM.number = 0
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_APPEARED_ENUM.name = "EBOSSREFRESHSTATE_APPEARED"
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_APPEARED_ENUM.index = 1
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_APPEARED_ENUM.number = 1
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_UPCOMING_ENUM.name = "EBOSSREFRESHSTATE_UPCOMING"
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_UPCOMING_ENUM.index = 2
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_UPCOMING_ENUM.number = 2
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_SHORT_ENUM.name = "EBOSSREFRESHSTATE_SHORT"
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_SHORT_ENUM.index = 3
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_SHORT_ENUM.number = 3
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_LONG_ENUM.name = "EBOSSREFRESHSTATE_LONG"
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_LONG_ENUM.index = 4
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_LONG_ENUM.number = 4
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MAX_ENUM.name = "EBOSSREFRESHSTATE_MAX"
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MAX_ENUM.index = 5
EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MAX_ENUM.number = 5
EBOSSREFRESHSTATE.name = "EBossRefreshState"
EBOSSREFRESHSTATE.full_name = ".Cmd.EBossRefreshState"
EBOSSREFRESHSTATE.values = {
  EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MIN_ENUM,
  EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_APPEARED_ENUM,
  EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_UPCOMING_ENUM,
  EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_SHORT_ENUM,
  EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_LONG_ENUM,
  EBOSSREFRESHSTATE_EBOSSREFRESHSTATE_MAX_ENUM
}
EBOSSSTEP_EBOSSSTEP_MIN_ENUM.name = "EBOSSSTEP_MIN"
EBOSSSTEP_EBOSSSTEP_MIN_ENUM.index = 0
EBOSSSTEP_EBOSSSTEP_MIN_ENUM.number = 0
EBOSSSTEP_EBOSSSTEP_VISIT_ENUM.name = "EBOSSSTEP_VISIT"
EBOSSSTEP_EBOSSSTEP_VISIT_ENUM.index = 1
EBOSSSTEP_EBOSSSTEP_VISIT_ENUM.number = 1
EBOSSSTEP_EBOSSSTEP_SUMMON_ENUM.name = "EBOSSSTEP_SUMMON"
EBOSSSTEP_EBOSSSTEP_SUMMON_ENUM.index = 2
EBOSSSTEP_EBOSSSTEP_SUMMON_ENUM.number = 2
EBOSSSTEP_EBOSSSTEP_CLEAR_ENUM.name = "EBOSSSTEP_CLEAR"
EBOSSSTEP_EBOSSSTEP_CLEAR_ENUM.index = 3
EBOSSSTEP_EBOSSSTEP_CLEAR_ENUM.number = 3
EBOSSSTEP_EBOSSSTEP_BOSS_ENUM.name = "EBOSSSTEP_BOSS"
EBOSSSTEP_EBOSSSTEP_BOSS_ENUM.index = 4
EBOSSSTEP_EBOSSSTEP_BOSS_ENUM.number = 4
EBOSSSTEP_EBOSSSTEP_END_ENUM.name = "EBOSSSTEP_END"
EBOSSSTEP_EBOSSSTEP_END_ENUM.index = 5
EBOSSSTEP_EBOSSSTEP_END_ENUM.number = 5
EBOSSSTEP_EBOSSSTEP_LIMIT_ENUM.name = "EBOSSSTEP_LIMIT"
EBOSSSTEP_EBOSSSTEP_LIMIT_ENUM.index = 6
EBOSSSTEP_EBOSSSTEP_LIMIT_ENUM.number = 7
EBOSSSTEP_EBOSSSTEP_DIALOG_ENUM.name = "EBOSSSTEP_DIALOG"
EBOSSSTEP_EBOSSSTEP_DIALOG_ENUM.index = 7
EBOSSSTEP_EBOSSSTEP_DIALOG_ENUM.number = 8
EBOSSSTEP_EBOSSSTEP_STATUS_ENUM.name = "EBOSSSTEP_STATUS"
EBOSSSTEP_EBOSSSTEP_STATUS_ENUM.index = 8
EBOSSSTEP_EBOSSSTEP_STATUS_ENUM.number = 9
EBOSSSTEP_EBOSSSTEP_WAIT_ENUM.name = "EBOSSSTEP_WAIT"
EBOSSSTEP_EBOSSSTEP_WAIT_ENUM.index = 9
EBOSSSTEP_EBOSSSTEP_WAIT_ENUM.number = 10
EBOSSSTEP_EBOSSSTEP_KILL_ENUM.name = "EBOSSSTEP_KILL"
EBOSSSTEP_EBOSSSTEP_KILL_ENUM.index = 10
EBOSSSTEP_EBOSSSTEP_KILL_ENUM.number = 11
EBOSSSTEP_EBOSSSTEP_WORLD_ENUM.name = "EBOSSSTEP_WORLD"
EBOSSSTEP_EBOSSSTEP_WORLD_ENUM.index = 11
EBOSSSTEP_EBOSSSTEP_WORLD_ENUM.number = 12
EBOSSSTEP_EBOSSSTEP_SHOW_ENUM.name = "EBOSSSTEP_SHOW"
EBOSSSTEP_EBOSSSTEP_SHOW_ENUM.index = 12
EBOSSSTEP_EBOSSSTEP_SHOW_ENUM.number = 13
EBOSSSTEP_EBOSSSTEP_MAX_ENUM.name = "EBOSSSTEP_MAX"
EBOSSSTEP_EBOSSSTEP_MAX_ENUM.index = 13
EBOSSSTEP_EBOSSSTEP_MAX_ENUM.number = 14
EBOSSSTEP.name = "EBossStep"
EBOSSSTEP.full_name = ".Cmd.EBossStep"
EBOSSSTEP.values = {
  EBOSSSTEP_EBOSSSTEP_MIN_ENUM,
  EBOSSSTEP_EBOSSSTEP_VISIT_ENUM,
  EBOSSSTEP_EBOSSSTEP_SUMMON_ENUM,
  EBOSSSTEP_EBOSSSTEP_CLEAR_ENUM,
  EBOSSSTEP_EBOSSSTEP_BOSS_ENUM,
  EBOSSSTEP_EBOSSSTEP_END_ENUM,
  EBOSSSTEP_EBOSSSTEP_LIMIT_ENUM,
  EBOSSSTEP_EBOSSSTEP_DIALOG_ENUM,
  EBOSSSTEP_EBOSSSTEP_STATUS_ENUM,
  EBOSSSTEP_EBOSSSTEP_WAIT_ENUM,
  EBOSSSTEP_EBOSSSTEP_KILL_ENUM,
  EBOSSSTEP_EBOSSSTEP_WORLD_ENUM,
  EBOSSSTEP_EBOSSSTEP_SHOW_ENUM,
  EBOSSSTEP_EBOSSSTEP_MAX_ENUM
}
BOSSINFOITEM_ID_FIELD.name = "id"
BOSSINFOITEM_ID_FIELD.full_name = ".Cmd.BossInfoItem.id"
BOSSINFOITEM_ID_FIELD.number = 1
BOSSINFOITEM_ID_FIELD.index = 0
BOSSINFOITEM_ID_FIELD.label = 1
BOSSINFOITEM_ID_FIELD.has_default_value = false
BOSSINFOITEM_ID_FIELD.default_value = 0
BOSSINFOITEM_ID_FIELD.type = 13
BOSSINFOITEM_ID_FIELD.cpp_type = 3
BOSSINFOITEM_REFRESHTIME_FIELD.name = "refreshTime"
BOSSINFOITEM_REFRESHTIME_FIELD.full_name = ".Cmd.BossInfoItem.refreshTime"
BOSSINFOITEM_REFRESHTIME_FIELD.number = 2
BOSSINFOITEM_REFRESHTIME_FIELD.index = 1
BOSSINFOITEM_REFRESHTIME_FIELD.label = 1
BOSSINFOITEM_REFRESHTIME_FIELD.has_default_value = true
BOSSINFOITEM_REFRESHTIME_FIELD.default_value = 0
BOSSINFOITEM_REFRESHTIME_FIELD.type = 13
BOSSINFOITEM_REFRESHTIME_FIELD.cpp_type = 3
BOSSINFOITEM_DIETIME_FIELD.name = "dietime"
BOSSINFOITEM_DIETIME_FIELD.full_name = ".Cmd.BossInfoItem.dietime"
BOSSINFOITEM_DIETIME_FIELD.number = 9
BOSSINFOITEM_DIETIME_FIELD.index = 2
BOSSINFOITEM_DIETIME_FIELD.label = 1
BOSSINFOITEM_DIETIME_FIELD.has_default_value = true
BOSSINFOITEM_DIETIME_FIELD.default_value = 0
BOSSINFOITEM_DIETIME_FIELD.type = 13
BOSSINFOITEM_DIETIME_FIELD.cpp_type = 3
BOSSINFOITEM_SUMMONTIME_FIELD.name = "summontime"
BOSSINFOITEM_SUMMONTIME_FIELD.full_name = ".Cmd.BossInfoItem.summontime"
BOSSINFOITEM_SUMMONTIME_FIELD.number = 10
BOSSINFOITEM_SUMMONTIME_FIELD.index = 3
BOSSINFOITEM_SUMMONTIME_FIELD.label = 1
BOSSINFOITEM_SUMMONTIME_FIELD.has_default_value = true
BOSSINFOITEM_SUMMONTIME_FIELD.default_value = 0
BOSSINFOITEM_SUMMONTIME_FIELD.type = 13
BOSSINFOITEM_SUMMONTIME_FIELD.cpp_type = 3
BOSSINFOITEM_MAPID_FIELD.name = "mapid"
BOSSINFOITEM_MAPID_FIELD.full_name = ".Cmd.BossInfoItem.mapid"
BOSSINFOITEM_MAPID_FIELD.number = 4
BOSSINFOITEM_MAPID_FIELD.index = 4
BOSSINFOITEM_MAPID_FIELD.label = 1
BOSSINFOITEM_MAPID_FIELD.has_default_value = false
BOSSINFOITEM_MAPID_FIELD.default_value = 0
BOSSINFOITEM_MAPID_FIELD.type = 13
BOSSINFOITEM_MAPID_FIELD.cpp_type = 3
BOSSINFOITEM_SETTIME_FIELD.name = "settime"
BOSSINFOITEM_SETTIME_FIELD.full_name = ".Cmd.BossInfoItem.settime"
BOSSINFOITEM_SETTIME_FIELD.number = 7
BOSSINFOITEM_SETTIME_FIELD.index = 5
BOSSINFOITEM_SETTIME_FIELD.label = 1
BOSSINFOITEM_SETTIME_FIELD.has_default_value = true
BOSSINFOITEM_SETTIME_FIELD.default_value = 0
BOSSINFOITEM_SETTIME_FIELD.type = 13
BOSSINFOITEM_SETTIME_FIELD.cpp_type = 3
BOSSINFOITEM_LV_FIELD.name = "lv"
BOSSINFOITEM_LV_FIELD.full_name = ".Cmd.BossInfoItem.lv"
BOSSINFOITEM_LV_FIELD.number = 8
BOSSINFOITEM_LV_FIELD.index = 6
BOSSINFOITEM_LV_FIELD.label = 1
BOSSINFOITEM_LV_FIELD.has_default_value = true
BOSSINFOITEM_LV_FIELD.default_value = 0
BOSSINFOITEM_LV_FIELD.type = 13
BOSSINFOITEM_LV_FIELD.cpp_type = 3
BOSSINFOITEM_REFRESHSTATE_FIELD.name = "refreshstate"
BOSSINFOITEM_REFRESHSTATE_FIELD.full_name = ".Cmd.BossInfoItem.refreshstate"
BOSSINFOITEM_REFRESHSTATE_FIELD.number = 5
BOSSINFOITEM_REFRESHSTATE_FIELD.index = 7
BOSSINFOITEM_REFRESHSTATE_FIELD.label = 1
BOSSINFOITEM_REFRESHSTATE_FIELD.has_default_value = true
BOSSINFOITEM_REFRESHSTATE_FIELD.default_value = 0
BOSSINFOITEM_REFRESHSTATE_FIELD.enum_type = EBOSSREFRESHSTATE
BOSSINFOITEM_REFRESHSTATE_FIELD.type = 14
BOSSINFOITEM_REFRESHSTATE_FIELD.cpp_type = 8
BOSSINFOITEM_LASTKILLER_FIELD.name = "lastKiller"
BOSSINFOITEM_LASTKILLER_FIELD.full_name = ".Cmd.BossInfoItem.lastKiller"
BOSSINFOITEM_LASTKILLER_FIELD.number = 3
BOSSINFOITEM_LASTKILLER_FIELD.index = 8
BOSSINFOITEM_LASTKILLER_FIELD.label = 1
BOSSINFOITEM_LASTKILLER_FIELD.has_default_value = false
BOSSINFOITEM_LASTKILLER_FIELD.default_value = ""
BOSSINFOITEM_LASTKILLER_FIELD.type = 9
BOSSINFOITEM_LASTKILLER_FIELD.cpp_type = 9
BOSSINFOITEM_CHARID_FIELD.name = "charid"
BOSSINFOITEM_CHARID_FIELD.full_name = ".Cmd.BossInfoItem.charid"
BOSSINFOITEM_CHARID_FIELD.number = 6
BOSSINFOITEM_CHARID_FIELD.index = 9
BOSSINFOITEM_CHARID_FIELD.label = 1
BOSSINFOITEM_CHARID_FIELD.has_default_value = true
BOSSINFOITEM_CHARID_FIELD.default_value = 0
BOSSINFOITEM_CHARID_FIELD.type = 4
BOSSINFOITEM_CHARID_FIELD.cpp_type = 4
BOSSINFOITEM.name = "BossInfoItem"
BOSSINFOITEM.full_name = ".Cmd.BossInfoItem"
BOSSINFOITEM.nested_types = {}
BOSSINFOITEM.enum_types = {}
BOSSINFOITEM.fields = {
  BOSSINFOITEM_ID_FIELD,
  BOSSINFOITEM_REFRESHTIME_FIELD,
  BOSSINFOITEM_DIETIME_FIELD,
  BOSSINFOITEM_SUMMONTIME_FIELD,
  BOSSINFOITEM_MAPID_FIELD,
  BOSSINFOITEM_SETTIME_FIELD,
  BOSSINFOITEM_LV_FIELD,
  BOSSINFOITEM_REFRESHSTATE_FIELD,
  BOSSINFOITEM_LASTKILLER_FIELD,
  BOSSINFOITEM_CHARID_FIELD
}
BOSSINFOITEM.is_extendable = false
BOSSINFOITEM.extensions = {}
BOSSLISTUSERCMD_CMD_FIELD.name = "cmd"
BOSSLISTUSERCMD_CMD_FIELD.full_name = ".Cmd.BossListUserCmd.cmd"
BOSSLISTUSERCMD_CMD_FIELD.number = 1
BOSSLISTUSERCMD_CMD_FIELD.index = 0
BOSSLISTUSERCMD_CMD_FIELD.label = 1
BOSSLISTUSERCMD_CMD_FIELD.has_default_value = true
BOSSLISTUSERCMD_CMD_FIELD.default_value = 15
BOSSLISTUSERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BOSSLISTUSERCMD_CMD_FIELD.type = 14
BOSSLISTUSERCMD_CMD_FIELD.cpp_type = 8
BOSSLISTUSERCMD_PARAM_FIELD.name = "param"
BOSSLISTUSERCMD_PARAM_FIELD.full_name = ".Cmd.BossListUserCmd.param"
BOSSLISTUSERCMD_PARAM_FIELD.number = 2
BOSSLISTUSERCMD_PARAM_FIELD.index = 1
BOSSLISTUSERCMD_PARAM_FIELD.label = 1
BOSSLISTUSERCMD_PARAM_FIELD.has_default_value = true
BOSSLISTUSERCMD_PARAM_FIELD.default_value = 1
BOSSLISTUSERCMD_PARAM_FIELD.enum_type = BOSSPARAM
BOSSLISTUSERCMD_PARAM_FIELD.type = 14
BOSSLISTUSERCMD_PARAM_FIELD.cpp_type = 8
BOSSLISTUSERCMD_BOSSLIST_FIELD.name = "bosslist"
BOSSLISTUSERCMD_BOSSLIST_FIELD.full_name = ".Cmd.BossListUserCmd.bosslist"
BOSSLISTUSERCMD_BOSSLIST_FIELD.number = 3
BOSSLISTUSERCMD_BOSSLIST_FIELD.index = 2
BOSSLISTUSERCMD_BOSSLIST_FIELD.label = 3
BOSSLISTUSERCMD_BOSSLIST_FIELD.has_default_value = false
BOSSLISTUSERCMD_BOSSLIST_FIELD.default_value = {}
BOSSLISTUSERCMD_BOSSLIST_FIELD.message_type = BOSSINFOITEM
BOSSLISTUSERCMD_BOSSLIST_FIELD.type = 11
BOSSLISTUSERCMD_BOSSLIST_FIELD.cpp_type = 10
BOSSLISTUSERCMD_MINILIST_FIELD.name = "minilist"
BOSSLISTUSERCMD_MINILIST_FIELD.full_name = ".Cmd.BossListUserCmd.minilist"
BOSSLISTUSERCMD_MINILIST_FIELD.number = 4
BOSSLISTUSERCMD_MINILIST_FIELD.index = 3
BOSSLISTUSERCMD_MINILIST_FIELD.label = 3
BOSSLISTUSERCMD_MINILIST_FIELD.has_default_value = false
BOSSLISTUSERCMD_MINILIST_FIELD.default_value = {}
BOSSLISTUSERCMD_MINILIST_FIELD.message_type = BOSSINFOITEM
BOSSLISTUSERCMD_MINILIST_FIELD.type = 11
BOSSLISTUSERCMD_MINILIST_FIELD.cpp_type = 10
BOSSLISTUSERCMD_DEADLIST_FIELD.name = "deadlist"
BOSSLISTUSERCMD_DEADLIST_FIELD.full_name = ".Cmd.BossListUserCmd.deadlist"
BOSSLISTUSERCMD_DEADLIST_FIELD.number = 5
BOSSLISTUSERCMD_DEADLIST_FIELD.index = 4
BOSSLISTUSERCMD_DEADLIST_FIELD.label = 3
BOSSLISTUSERCMD_DEADLIST_FIELD.has_default_value = false
BOSSLISTUSERCMD_DEADLIST_FIELD.default_value = {}
BOSSLISTUSERCMD_DEADLIST_FIELD.message_type = BOSSINFOITEM
BOSSLISTUSERCMD_DEADLIST_FIELD.type = 11
BOSSLISTUSERCMD_DEADLIST_FIELD.cpp_type = 10
BOSSLISTUSERCMD.name = "BossListUserCmd"
BOSSLISTUSERCMD.full_name = ".Cmd.BossListUserCmd"
BOSSLISTUSERCMD.nested_types = {}
BOSSLISTUSERCMD.enum_types = {}
BOSSLISTUSERCMD.fields = {
  BOSSLISTUSERCMD_CMD_FIELD,
  BOSSLISTUSERCMD_PARAM_FIELD,
  BOSSLISTUSERCMD_BOSSLIST_FIELD,
  BOSSLISTUSERCMD_MINILIST_FIELD,
  BOSSLISTUSERCMD_DEADLIST_FIELD
}
BOSSLISTUSERCMD.is_extendable = false
BOSSLISTUSERCMD.extensions = {}
BOSSPOSUSERCMD_CMD_FIELD.name = "cmd"
BOSSPOSUSERCMD_CMD_FIELD.full_name = ".Cmd.BossPosUserCmd.cmd"
BOSSPOSUSERCMD_CMD_FIELD.number = 1
BOSSPOSUSERCMD_CMD_FIELD.index = 0
BOSSPOSUSERCMD_CMD_FIELD.label = 1
BOSSPOSUSERCMD_CMD_FIELD.has_default_value = true
BOSSPOSUSERCMD_CMD_FIELD.default_value = 15
BOSSPOSUSERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BOSSPOSUSERCMD_CMD_FIELD.type = 14
BOSSPOSUSERCMD_CMD_FIELD.cpp_type = 8
BOSSPOSUSERCMD_PARAM_FIELD.name = "param"
BOSSPOSUSERCMD_PARAM_FIELD.full_name = ".Cmd.BossPosUserCmd.param"
BOSSPOSUSERCMD_PARAM_FIELD.number = 2
BOSSPOSUSERCMD_PARAM_FIELD.index = 1
BOSSPOSUSERCMD_PARAM_FIELD.label = 1
BOSSPOSUSERCMD_PARAM_FIELD.has_default_value = true
BOSSPOSUSERCMD_PARAM_FIELD.default_value = 2
BOSSPOSUSERCMD_PARAM_FIELD.enum_type = BOSSPARAM
BOSSPOSUSERCMD_PARAM_FIELD.type = 14
BOSSPOSUSERCMD_PARAM_FIELD.cpp_type = 8
BOSSPOSUSERCMD_POS_FIELD.name = "pos"
BOSSPOSUSERCMD_POS_FIELD.full_name = ".Cmd.BossPosUserCmd.pos"
BOSSPOSUSERCMD_POS_FIELD.number = 3
BOSSPOSUSERCMD_POS_FIELD.index = 2
BOSSPOSUSERCMD_POS_FIELD.label = 1
BOSSPOSUSERCMD_POS_FIELD.has_default_value = false
BOSSPOSUSERCMD_POS_FIELD.default_value = nil
BOSSPOSUSERCMD_POS_FIELD.message_type = ProtoCommon_pb.SCENEPOS
BOSSPOSUSERCMD_POS_FIELD.type = 11
BOSSPOSUSERCMD_POS_FIELD.cpp_type = 10
BOSSPOSUSERCMD.name = "BossPosUserCmd"
BOSSPOSUSERCMD.full_name = ".Cmd.BossPosUserCmd"
BOSSPOSUSERCMD.nested_types = {}
BOSSPOSUSERCMD.enum_types = {}
BOSSPOSUSERCMD.fields = {
  BOSSPOSUSERCMD_CMD_FIELD,
  BOSSPOSUSERCMD_PARAM_FIELD,
  BOSSPOSUSERCMD_POS_FIELD
}
BOSSPOSUSERCMD.is_extendable = false
BOSSPOSUSERCMD.extensions = {}
KILLBOSSUSERCMD_CMD_FIELD.name = "cmd"
KILLBOSSUSERCMD_CMD_FIELD.full_name = ".Cmd.KillBossUserCmd.cmd"
KILLBOSSUSERCMD_CMD_FIELD.number = 1
KILLBOSSUSERCMD_CMD_FIELD.index = 0
KILLBOSSUSERCMD_CMD_FIELD.label = 1
KILLBOSSUSERCMD_CMD_FIELD.has_default_value = true
KILLBOSSUSERCMD_CMD_FIELD.default_value = 15
KILLBOSSUSERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
KILLBOSSUSERCMD_CMD_FIELD.type = 14
KILLBOSSUSERCMD_CMD_FIELD.cpp_type = 8
KILLBOSSUSERCMD_PARAM_FIELD.name = "param"
KILLBOSSUSERCMD_PARAM_FIELD.full_name = ".Cmd.KillBossUserCmd.param"
KILLBOSSUSERCMD_PARAM_FIELD.number = 2
KILLBOSSUSERCMD_PARAM_FIELD.index = 1
KILLBOSSUSERCMD_PARAM_FIELD.label = 1
KILLBOSSUSERCMD_PARAM_FIELD.has_default_value = true
KILLBOSSUSERCMD_PARAM_FIELD.default_value = 3
KILLBOSSUSERCMD_PARAM_FIELD.enum_type = BOSSPARAM
KILLBOSSUSERCMD_PARAM_FIELD.type = 14
KILLBOSSUSERCMD_PARAM_FIELD.cpp_type = 8
KILLBOSSUSERCMD_USERID_FIELD.name = "userid"
KILLBOSSUSERCMD_USERID_FIELD.full_name = ".Cmd.KillBossUserCmd.userid"
KILLBOSSUSERCMD_USERID_FIELD.number = 3
KILLBOSSUSERCMD_USERID_FIELD.index = 2
KILLBOSSUSERCMD_USERID_FIELD.label = 1
KILLBOSSUSERCMD_USERID_FIELD.has_default_value = true
KILLBOSSUSERCMD_USERID_FIELD.default_value = 0
KILLBOSSUSERCMD_USERID_FIELD.type = 4
KILLBOSSUSERCMD_USERID_FIELD.cpp_type = 4
KILLBOSSUSERCMD.name = "KillBossUserCmd"
KILLBOSSUSERCMD.full_name = ".Cmd.KillBossUserCmd"
KILLBOSSUSERCMD.nested_types = {}
KILLBOSSUSERCMD.enum_types = {}
KILLBOSSUSERCMD.fields = {
  KILLBOSSUSERCMD_CMD_FIELD,
  KILLBOSSUSERCMD_PARAM_FIELD,
  KILLBOSSUSERCMD_USERID_FIELD
}
KILLBOSSUSERCMD.is_extendable = false
KILLBOSSUSERCMD.extensions = {}
BOSSKILLERDATA_CHARID_FIELD.name = "charid"
BOSSKILLERDATA_CHARID_FIELD.full_name = ".Cmd.BossKillerData.charid"
BOSSKILLERDATA_CHARID_FIELD.number = 1
BOSSKILLERDATA_CHARID_FIELD.index = 0
BOSSKILLERDATA_CHARID_FIELD.label = 1
BOSSKILLERDATA_CHARID_FIELD.has_default_value = true
BOSSKILLERDATA_CHARID_FIELD.default_value = 0
BOSSKILLERDATA_CHARID_FIELD.type = 4
BOSSKILLERDATA_CHARID_FIELD.cpp_type = 4
BOSSKILLERDATA_PORTRAIT_FIELD.name = "portrait"
BOSSKILLERDATA_PORTRAIT_FIELD.full_name = ".Cmd.BossKillerData.portrait"
BOSSKILLERDATA_PORTRAIT_FIELD.number = 2
BOSSKILLERDATA_PORTRAIT_FIELD.index = 1
BOSSKILLERDATA_PORTRAIT_FIELD.label = 1
BOSSKILLERDATA_PORTRAIT_FIELD.has_default_value = false
BOSSKILLERDATA_PORTRAIT_FIELD.default_value = 0
BOSSKILLERDATA_PORTRAIT_FIELD.type = 13
BOSSKILLERDATA_PORTRAIT_FIELD.cpp_type = 3
BOSSKILLERDATA_BASELEVEL_FIELD.name = "baselevel"
BOSSKILLERDATA_BASELEVEL_FIELD.full_name = ".Cmd.BossKillerData.baselevel"
BOSSKILLERDATA_BASELEVEL_FIELD.number = 4
BOSSKILLERDATA_BASELEVEL_FIELD.index = 2
BOSSKILLERDATA_BASELEVEL_FIELD.label = 1
BOSSKILLERDATA_BASELEVEL_FIELD.has_default_value = false
BOSSKILLERDATA_BASELEVEL_FIELD.default_value = 0
BOSSKILLERDATA_BASELEVEL_FIELD.type = 13
BOSSKILLERDATA_BASELEVEL_FIELD.cpp_type = 3
BOSSKILLERDATA_HAIR_FIELD.name = "hair"
BOSSKILLERDATA_HAIR_FIELD.full_name = ".Cmd.BossKillerData.hair"
BOSSKILLERDATA_HAIR_FIELD.number = 5
BOSSKILLERDATA_HAIR_FIELD.index = 3
BOSSKILLERDATA_HAIR_FIELD.label = 1
BOSSKILLERDATA_HAIR_FIELD.has_default_value = false
BOSSKILLERDATA_HAIR_FIELD.default_value = 0
BOSSKILLERDATA_HAIR_FIELD.type = 13
BOSSKILLERDATA_HAIR_FIELD.cpp_type = 3
BOSSKILLERDATA_HAIRCOLOR_FIELD.name = "haircolor"
BOSSKILLERDATA_HAIRCOLOR_FIELD.full_name = ".Cmd.BossKillerData.haircolor"
BOSSKILLERDATA_HAIRCOLOR_FIELD.number = 6
BOSSKILLERDATA_HAIRCOLOR_FIELD.index = 4
BOSSKILLERDATA_HAIRCOLOR_FIELD.label = 1
BOSSKILLERDATA_HAIRCOLOR_FIELD.has_default_value = false
BOSSKILLERDATA_HAIRCOLOR_FIELD.default_value = 0
BOSSKILLERDATA_HAIRCOLOR_FIELD.type = 13
BOSSKILLERDATA_HAIRCOLOR_FIELD.cpp_type = 3
BOSSKILLERDATA_BODY_FIELD.name = "body"
BOSSKILLERDATA_BODY_FIELD.full_name = ".Cmd.BossKillerData.body"
BOSSKILLERDATA_BODY_FIELD.number = 7
BOSSKILLERDATA_BODY_FIELD.index = 5
BOSSKILLERDATA_BODY_FIELD.label = 1
BOSSKILLERDATA_BODY_FIELD.has_default_value = false
BOSSKILLERDATA_BODY_FIELD.default_value = 0
BOSSKILLERDATA_BODY_FIELD.type = 13
BOSSKILLERDATA_BODY_FIELD.cpp_type = 3
BOSSKILLERDATA_HEAD_FIELD.name = "head"
BOSSKILLERDATA_HEAD_FIELD.full_name = ".Cmd.BossKillerData.head"
BOSSKILLERDATA_HEAD_FIELD.number = 8
BOSSKILLERDATA_HEAD_FIELD.index = 6
BOSSKILLERDATA_HEAD_FIELD.label = 1
BOSSKILLERDATA_HEAD_FIELD.has_default_value = false
BOSSKILLERDATA_HEAD_FIELD.default_value = 0
BOSSKILLERDATA_HEAD_FIELD.type = 13
BOSSKILLERDATA_HEAD_FIELD.cpp_type = 3
BOSSKILLERDATA_FACE_FIELD.name = "face"
BOSSKILLERDATA_FACE_FIELD.full_name = ".Cmd.BossKillerData.face"
BOSSKILLERDATA_FACE_FIELD.number = 9
BOSSKILLERDATA_FACE_FIELD.index = 7
BOSSKILLERDATA_FACE_FIELD.label = 1
BOSSKILLERDATA_FACE_FIELD.has_default_value = false
BOSSKILLERDATA_FACE_FIELD.default_value = 0
BOSSKILLERDATA_FACE_FIELD.type = 13
BOSSKILLERDATA_FACE_FIELD.cpp_type = 3
BOSSKILLERDATA_MOUTH_FIELD.name = "mouth"
BOSSKILLERDATA_MOUTH_FIELD.full_name = ".Cmd.BossKillerData.mouth"
BOSSKILLERDATA_MOUTH_FIELD.number = 10
BOSSKILLERDATA_MOUTH_FIELD.index = 8
BOSSKILLERDATA_MOUTH_FIELD.label = 1
BOSSKILLERDATA_MOUTH_FIELD.has_default_value = false
BOSSKILLERDATA_MOUTH_FIELD.default_value = 0
BOSSKILLERDATA_MOUTH_FIELD.type = 13
BOSSKILLERDATA_MOUTH_FIELD.cpp_type = 3
BOSSKILLERDATA_EYE_FIELD.name = "eye"
BOSSKILLERDATA_EYE_FIELD.full_name = ".Cmd.BossKillerData.eye"
BOSSKILLERDATA_EYE_FIELD.number = 11
BOSSKILLERDATA_EYE_FIELD.index = 9
BOSSKILLERDATA_EYE_FIELD.label = 1
BOSSKILLERDATA_EYE_FIELD.has_default_value = false
BOSSKILLERDATA_EYE_FIELD.default_value = 0
BOSSKILLERDATA_EYE_FIELD.type = 13
BOSSKILLERDATA_EYE_FIELD.cpp_type = 3
BOSSKILLERDATA_BLINK_FIELD.name = "blink"
BOSSKILLERDATA_BLINK_FIELD.full_name = ".Cmd.BossKillerData.blink"
BOSSKILLERDATA_BLINK_FIELD.number = 12
BOSSKILLERDATA_BLINK_FIELD.index = 10
BOSSKILLERDATA_BLINK_FIELD.label = 1
BOSSKILLERDATA_BLINK_FIELD.has_default_value = false
BOSSKILLERDATA_BLINK_FIELD.default_value = 0
BOSSKILLERDATA_BLINK_FIELD.type = 13
BOSSKILLERDATA_BLINK_FIELD.cpp_type = 3
BOSSKILLERDATA_PROFESSION_FIELD.name = "profession"
BOSSKILLERDATA_PROFESSION_FIELD.full_name = ".Cmd.BossKillerData.profession"
BOSSKILLERDATA_PROFESSION_FIELD.number = 13
BOSSKILLERDATA_PROFESSION_FIELD.index = 11
BOSSKILLERDATA_PROFESSION_FIELD.label = 1
BOSSKILLERDATA_PROFESSION_FIELD.has_default_value = false
BOSSKILLERDATA_PROFESSION_FIELD.default_value = nil
BOSSKILLERDATA_PROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
BOSSKILLERDATA_PROFESSION_FIELD.type = 14
BOSSKILLERDATA_PROFESSION_FIELD.cpp_type = 8
BOSSKILLERDATA_GENDER_FIELD.name = "gender"
BOSSKILLERDATA_GENDER_FIELD.full_name = ".Cmd.BossKillerData.gender"
BOSSKILLERDATA_GENDER_FIELD.number = 14
BOSSKILLERDATA_GENDER_FIELD.index = 12
BOSSKILLERDATA_GENDER_FIELD.label = 1
BOSSKILLERDATA_GENDER_FIELD.has_default_value = false
BOSSKILLERDATA_GENDER_FIELD.default_value = nil
BOSSKILLERDATA_GENDER_FIELD.enum_type = PROTOCOMMON_PB_EGENDER
BOSSKILLERDATA_GENDER_FIELD.type = 14
BOSSKILLERDATA_GENDER_FIELD.cpp_type = 8
BOSSKILLERDATA_NAME_FIELD.name = "name"
BOSSKILLERDATA_NAME_FIELD.full_name = ".Cmd.BossKillerData.name"
BOSSKILLERDATA_NAME_FIELD.number = 15
BOSSKILLERDATA_NAME_FIELD.index = 13
BOSSKILLERDATA_NAME_FIELD.label = 1
BOSSKILLERDATA_NAME_FIELD.has_default_value = false
BOSSKILLERDATA_NAME_FIELD.default_value = ""
BOSSKILLERDATA_NAME_FIELD.type = 9
BOSSKILLERDATA_NAME_FIELD.cpp_type = 9
BOSSKILLERDATA_GUILDNAME_FIELD.name = "guildname"
BOSSKILLERDATA_GUILDNAME_FIELD.full_name = ".Cmd.BossKillerData.guildname"
BOSSKILLERDATA_GUILDNAME_FIELD.number = 16
BOSSKILLERDATA_GUILDNAME_FIELD.index = 14
BOSSKILLERDATA_GUILDNAME_FIELD.label = 1
BOSSKILLERDATA_GUILDNAME_FIELD.has_default_value = false
BOSSKILLERDATA_GUILDNAME_FIELD.default_value = ""
BOSSKILLERDATA_GUILDNAME_FIELD.type = 9
BOSSKILLERDATA_GUILDNAME_FIELD.cpp_type = 9
BOSSKILLERDATA.name = "BossKillerData"
BOSSKILLERDATA.full_name = ".Cmd.BossKillerData"
BOSSKILLERDATA.nested_types = {}
BOSSKILLERDATA.enum_types = {}
BOSSKILLERDATA.fields = {
  BOSSKILLERDATA_CHARID_FIELD,
  BOSSKILLERDATA_PORTRAIT_FIELD,
  BOSSKILLERDATA_BASELEVEL_FIELD,
  BOSSKILLERDATA_HAIR_FIELD,
  BOSSKILLERDATA_HAIRCOLOR_FIELD,
  BOSSKILLERDATA_BODY_FIELD,
  BOSSKILLERDATA_HEAD_FIELD,
  BOSSKILLERDATA_FACE_FIELD,
  BOSSKILLERDATA_MOUTH_FIELD,
  BOSSKILLERDATA_EYE_FIELD,
  BOSSKILLERDATA_BLINK_FIELD,
  BOSSKILLERDATA_PROFESSION_FIELD,
  BOSSKILLERDATA_GENDER_FIELD,
  BOSSKILLERDATA_NAME_FIELD,
  BOSSKILLERDATA_GUILDNAME_FIELD
}
BOSSKILLERDATA.is_extendable = false
BOSSKILLERDATA.extensions = {}
QUERYKILLERINFOBOSSCMD_CMD_FIELD.name = "cmd"
QUERYKILLERINFOBOSSCMD_CMD_FIELD.full_name = ".Cmd.QueryKillerInfoBossCmd.cmd"
QUERYKILLERINFOBOSSCMD_CMD_FIELD.number = 1
QUERYKILLERINFOBOSSCMD_CMD_FIELD.index = 0
QUERYKILLERINFOBOSSCMD_CMD_FIELD.label = 1
QUERYKILLERINFOBOSSCMD_CMD_FIELD.has_default_value = true
QUERYKILLERINFOBOSSCMD_CMD_FIELD.default_value = 15
QUERYKILLERINFOBOSSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYKILLERINFOBOSSCMD_CMD_FIELD.type = 14
QUERYKILLERINFOBOSSCMD_CMD_FIELD.cpp_type = 8
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.name = "param"
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.full_name = ".Cmd.QueryKillerInfoBossCmd.param"
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.number = 2
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.index = 1
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.label = 1
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.has_default_value = true
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.default_value = 4
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.enum_type = BOSSPARAM
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.type = 14
QUERYKILLERINFOBOSSCMD_PARAM_FIELD.cpp_type = 8
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.name = "charid"
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.full_name = ".Cmd.QueryKillerInfoBossCmd.charid"
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.number = 3
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.index = 2
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.label = 1
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.has_default_value = false
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.default_value = 0
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.type = 4
QUERYKILLERINFOBOSSCMD_CHARID_FIELD.cpp_type = 4
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.name = "userdata"
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.full_name = ".Cmd.QueryKillerInfoBossCmd.userdata"
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.number = 4
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.index = 3
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.label = 1
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.has_default_value = false
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.default_value = nil
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.message_type = BOSSKILLERDATA
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.type = 11
QUERYKILLERINFOBOSSCMD_USERDATA_FIELD.cpp_type = 10
QUERYKILLERINFOBOSSCMD.name = "QueryKillerInfoBossCmd"
QUERYKILLERINFOBOSSCMD.full_name = ".Cmd.QueryKillerInfoBossCmd"
QUERYKILLERINFOBOSSCMD.nested_types = {}
QUERYKILLERINFOBOSSCMD.enum_types = {}
QUERYKILLERINFOBOSSCMD.fields = {
  QUERYKILLERINFOBOSSCMD_CMD_FIELD,
  QUERYKILLERINFOBOSSCMD_PARAM_FIELD,
  QUERYKILLERINFOBOSSCMD_CHARID_FIELD,
  QUERYKILLERINFOBOSSCMD_USERDATA_FIELD
}
QUERYKILLERINFOBOSSCMD.is_extendable = false
QUERYKILLERINFOBOSSCMD.extensions = {}
WORLDBOSSNTF_CMD_FIELD.name = "cmd"
WORLDBOSSNTF_CMD_FIELD.full_name = ".Cmd.WorldBossNtf.cmd"
WORLDBOSSNTF_CMD_FIELD.number = 1
WORLDBOSSNTF_CMD_FIELD.index = 0
WORLDBOSSNTF_CMD_FIELD.label = 1
WORLDBOSSNTF_CMD_FIELD.has_default_value = true
WORLDBOSSNTF_CMD_FIELD.default_value = 15
WORLDBOSSNTF_CMD_FIELD.enum_type = XCMD_PB_COMMAND
WORLDBOSSNTF_CMD_FIELD.type = 14
WORLDBOSSNTF_CMD_FIELD.cpp_type = 8
WORLDBOSSNTF_PARAM_FIELD.name = "param"
WORLDBOSSNTF_PARAM_FIELD.full_name = ".Cmd.WorldBossNtf.param"
WORLDBOSSNTF_PARAM_FIELD.number = 2
WORLDBOSSNTF_PARAM_FIELD.index = 1
WORLDBOSSNTF_PARAM_FIELD.label = 1
WORLDBOSSNTF_PARAM_FIELD.has_default_value = true
WORLDBOSSNTF_PARAM_FIELD.default_value = 5
WORLDBOSSNTF_PARAM_FIELD.enum_type = BOSSPARAM
WORLDBOSSNTF_PARAM_FIELD.type = 14
WORLDBOSSNTF_PARAM_FIELD.cpp_type = 8
WORLDBOSSNTF_NPCID_FIELD.name = "npcid"
WORLDBOSSNTF_NPCID_FIELD.full_name = ".Cmd.WorldBossNtf.npcid"
WORLDBOSSNTF_NPCID_FIELD.number = 3
WORLDBOSSNTF_NPCID_FIELD.index = 2
WORLDBOSSNTF_NPCID_FIELD.label = 1
WORLDBOSSNTF_NPCID_FIELD.has_default_value = true
WORLDBOSSNTF_NPCID_FIELD.default_value = 0
WORLDBOSSNTF_NPCID_FIELD.type = 13
WORLDBOSSNTF_NPCID_FIELD.cpp_type = 3
WORLDBOSSNTF_MAPID_FIELD.name = "mapid"
WORLDBOSSNTF_MAPID_FIELD.full_name = ".Cmd.WorldBossNtf.mapid"
WORLDBOSSNTF_MAPID_FIELD.number = 4
WORLDBOSSNTF_MAPID_FIELD.index = 3
WORLDBOSSNTF_MAPID_FIELD.label = 1
WORLDBOSSNTF_MAPID_FIELD.has_default_value = true
WORLDBOSSNTF_MAPID_FIELD.default_value = 0
WORLDBOSSNTF_MAPID_FIELD.type = 13
WORLDBOSSNTF_MAPID_FIELD.cpp_type = 3
WORLDBOSSNTF_TIME_FIELD.name = "time"
WORLDBOSSNTF_TIME_FIELD.full_name = ".Cmd.WorldBossNtf.time"
WORLDBOSSNTF_TIME_FIELD.number = 5
WORLDBOSSNTF_TIME_FIELD.index = 4
WORLDBOSSNTF_TIME_FIELD.label = 1
WORLDBOSSNTF_TIME_FIELD.has_default_value = true
WORLDBOSSNTF_TIME_FIELD.default_value = 0
WORLDBOSSNTF_TIME_FIELD.type = 13
WORLDBOSSNTF_TIME_FIELD.cpp_type = 3
WORLDBOSSNTF_OPEN_FIELD.name = "open"
WORLDBOSSNTF_OPEN_FIELD.full_name = ".Cmd.WorldBossNtf.open"
WORLDBOSSNTF_OPEN_FIELD.number = 6
WORLDBOSSNTF_OPEN_FIELD.index = 5
WORLDBOSSNTF_OPEN_FIELD.label = 1
WORLDBOSSNTF_OPEN_FIELD.has_default_value = true
WORLDBOSSNTF_OPEN_FIELD.default_value = false
WORLDBOSSNTF_OPEN_FIELD.type = 8
WORLDBOSSNTF_OPEN_FIELD.cpp_type = 7
WORLDBOSSNTF.name = "WorldBossNtf"
WORLDBOSSNTF.full_name = ".Cmd.WorldBossNtf"
WORLDBOSSNTF.nested_types = {}
WORLDBOSSNTF.enum_types = {}
WORLDBOSSNTF.fields = {
  WORLDBOSSNTF_CMD_FIELD,
  WORLDBOSSNTF_PARAM_FIELD,
  WORLDBOSSNTF_NPCID_FIELD,
  WORLDBOSSNTF_MAPID_FIELD,
  WORLDBOSSNTF_TIME_FIELD,
  WORLDBOSSNTF_OPEN_FIELD
}
WORLDBOSSNTF.is_extendable = false
WORLDBOSSNTF.extensions = {}
STEPSYNCBOSSCMD_CMD_FIELD.name = "cmd"
STEPSYNCBOSSCMD_CMD_FIELD.full_name = ".Cmd.StepSyncBossCmd.cmd"
STEPSYNCBOSSCMD_CMD_FIELD.number = 1
STEPSYNCBOSSCMD_CMD_FIELD.index = 0
STEPSYNCBOSSCMD_CMD_FIELD.label = 1
STEPSYNCBOSSCMD_CMD_FIELD.has_default_value = true
STEPSYNCBOSSCMD_CMD_FIELD.default_value = 15
STEPSYNCBOSSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
STEPSYNCBOSSCMD_CMD_FIELD.type = 14
STEPSYNCBOSSCMD_CMD_FIELD.cpp_type = 8
STEPSYNCBOSSCMD_PARAM_FIELD.name = "param"
STEPSYNCBOSSCMD_PARAM_FIELD.full_name = ".Cmd.StepSyncBossCmd.param"
STEPSYNCBOSSCMD_PARAM_FIELD.number = 2
STEPSYNCBOSSCMD_PARAM_FIELD.index = 1
STEPSYNCBOSSCMD_PARAM_FIELD.label = 1
STEPSYNCBOSSCMD_PARAM_FIELD.has_default_value = true
STEPSYNCBOSSCMD_PARAM_FIELD.default_value = 6
STEPSYNCBOSSCMD_PARAM_FIELD.enum_type = BOSSPARAM
STEPSYNCBOSSCMD_PARAM_FIELD.type = 14
STEPSYNCBOSSCMD_PARAM_FIELD.cpp_type = 8
STEPSYNCBOSSCMD_ACTID_FIELD.name = "actid"
STEPSYNCBOSSCMD_ACTID_FIELD.full_name = ".Cmd.StepSyncBossCmd.actid"
STEPSYNCBOSSCMD_ACTID_FIELD.number = 3
STEPSYNCBOSSCMD_ACTID_FIELD.index = 2
STEPSYNCBOSSCMD_ACTID_FIELD.label = 1
STEPSYNCBOSSCMD_ACTID_FIELD.has_default_value = true
STEPSYNCBOSSCMD_ACTID_FIELD.default_value = 0
STEPSYNCBOSSCMD_ACTID_FIELD.type = 13
STEPSYNCBOSSCMD_ACTID_FIELD.cpp_type = 3
STEPSYNCBOSSCMD_STEP_FIELD.name = "step"
STEPSYNCBOSSCMD_STEP_FIELD.full_name = ".Cmd.StepSyncBossCmd.step"
STEPSYNCBOSSCMD_STEP_FIELD.number = 4
STEPSYNCBOSSCMD_STEP_FIELD.index = 3
STEPSYNCBOSSCMD_STEP_FIELD.label = 1
STEPSYNCBOSSCMD_STEP_FIELD.has_default_value = true
STEPSYNCBOSSCMD_STEP_FIELD.default_value = 0
STEPSYNCBOSSCMD_STEP_FIELD.enum_type = EBOSSSTEP
STEPSYNCBOSSCMD_STEP_FIELD.type = 14
STEPSYNCBOSSCMD_STEP_FIELD.cpp_type = 8
STEPSYNCBOSSCMD_PARAMS_FIELD.name = "params"
STEPSYNCBOSSCMD_PARAMS_FIELD.full_name = ".Cmd.StepSyncBossCmd.params"
STEPSYNCBOSSCMD_PARAMS_FIELD.number = 5
STEPSYNCBOSSCMD_PARAMS_FIELD.index = 4
STEPSYNCBOSSCMD_PARAMS_FIELD.label = 1
STEPSYNCBOSSCMD_PARAMS_FIELD.has_default_value = false
STEPSYNCBOSSCMD_PARAMS_FIELD.default_value = nil
STEPSYNCBOSSCMD_PARAMS_FIELD.message_type = ProtoCommon_pb.CONFIGPARAM
STEPSYNCBOSSCMD_PARAMS_FIELD.type = 11
STEPSYNCBOSSCMD_PARAMS_FIELD.cpp_type = 10
STEPSYNCBOSSCMD.name = "StepSyncBossCmd"
STEPSYNCBOSSCMD.full_name = ".Cmd.StepSyncBossCmd"
STEPSYNCBOSSCMD.nested_types = {}
STEPSYNCBOSSCMD.enum_types = {}
STEPSYNCBOSSCMD.fields = {
  STEPSYNCBOSSCMD_CMD_FIELD,
  STEPSYNCBOSSCMD_PARAM_FIELD,
  STEPSYNCBOSSCMD_ACTID_FIELD,
  STEPSYNCBOSSCMD_STEP_FIELD,
  STEPSYNCBOSSCMD_PARAMS_FIELD
}
STEPSYNCBOSSCMD.is_extendable = false
STEPSYNCBOSSCMD.extensions = {}
BOSS_KILL_USER_CMD = 3
BOSS_LIST_USER_CMD = 1
BOSS_POS_USER_CMD = 2
BOSS_STEP_SYNC = 6
BOSS_USER_INFO_CMD = 4
BOSS_WORLD_NTF = 5
BossInfoItem = protobuf.Message(BOSSINFOITEM)
BossKillerData = protobuf.Message(BOSSKILLERDATA)
BossListUserCmd = protobuf.Message(BOSSLISTUSERCMD)
BossPosUserCmd = protobuf.Message(BOSSPOSUSERCMD)
EBOSSREFRESHSTATE_APPEARED = 1
EBOSSREFRESHSTATE_LONG = 4
EBOSSREFRESHSTATE_MAX = 5
EBOSSREFRESHSTATE_MIN = 0
EBOSSREFRESHSTATE_SHORT = 3
EBOSSREFRESHSTATE_UPCOMING = 2
EBOSSSTEP_BOSS = 4
EBOSSSTEP_CLEAR = 3
EBOSSSTEP_DIALOG = 8
EBOSSSTEP_END = 5
EBOSSSTEP_KILL = 11
EBOSSSTEP_LIMIT = 7
EBOSSSTEP_MAX = 14
EBOSSSTEP_MIN = 0
EBOSSSTEP_SHOW = 13
EBOSSSTEP_STATUS = 9
EBOSSSTEP_SUMMON = 2
EBOSSSTEP_VISIT = 1
EBOSSSTEP_WAIT = 10
EBOSSSTEP_WORLD = 12
KillBossUserCmd = protobuf.Message(KILLBOSSUSERCMD)
QueryKillerInfoBossCmd = protobuf.Message(QUERYKILLERINFOBOSSCMD)
StepSyncBossCmd = protobuf.Message(STEPSYNCBOSSCMD)
WorldBossNtf = protobuf.Message(WORLDBOSSNTF)
