local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ChatCmd_pb")
local ChatCmd_pb = ChatCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("InteractCmd_pb")
INTERACTPARAM = protobuf.EnumDescriptor()
INTERACTPARAM_INTERPARAM_ADD_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_DEL_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_CONFIRM_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_CANCEL_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_ADD_MOVE_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_DEL_MOVE_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_CONFIRM_MOVE_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_CANCEL_MOVE_MOUNT_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_SYNC_TRAIN_STATUS_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_UPDATE_TRAIN_STATE_ENUM = protobuf.EnumValueDescriptor()
INTERACTPARAM_INTERPARAM_UPDATE_POS_ENUM = protobuf.EnumValueDescriptor()
ETRAINMOVESTATE = protobuf.EnumDescriptor()
ETRAINMOVESTATE_ETRAIN_MIN_ENUM = protobuf.EnumValueDescriptor()
ETRAINMOVESTATE_ETRAIN_STOP_OPEN_ENUM = protobuf.EnumValueDescriptor()
ETRAINMOVESTATE_ETRAIN_STOP_CLOSE_ENUM = protobuf.EnumValueDescriptor()
ETRAINMOVESTATE_ETRAIN_MOVE_ENUM = protobuf.EnumValueDescriptor()
ADDMOUNTINTERCMD = protobuf.Descriptor()
ADDMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
ADDMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
ADDMOUNTINTERCMD_NPCGUID_FIELD = protobuf.FieldDescriptor()
ADDMOUNTINTERCMD_MOUNTID_FIELD = protobuf.FieldDescriptor()
ADDMOUNTINTERCMD_CHARID_FIELD = protobuf.FieldDescriptor()
DELMOUNTINTERCMD = protobuf.Descriptor()
DELMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
DELMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
DELMOUNTINTERCMD_NPCGUID_FIELD = protobuf.FieldDescriptor()
DELMOUNTINTERCMD_CHARID_FIELD = protobuf.FieldDescriptor()
CONFIRMMOUNTINTERCMD = protobuf.Descriptor()
CONFIRMMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
CONFIRMMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD = protobuf.FieldDescriptor()
CANCELMOUNTINTERCMD = protobuf.Descriptor()
CANCELMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
CANCELMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
CANCELMOUNTINTERCMD_NPCGUID_FIELD = protobuf.FieldDescriptor()
TRAINUSERINFO = protobuf.Descriptor()
TRAINUSERINFO_USER_FIELD = protobuf.FieldDescriptor()
TRAINUSERINFO_MOUNTID_FIELD = protobuf.FieldDescriptor()
ADDMOVEMOUNTINTERCMD = protobuf.Descriptor()
ADDMOVEMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
ADDMOVEMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
ADDMOVEMOUNTINTERCMD_NPCID_FIELD = protobuf.FieldDescriptor()
ADDMOVEMOUNTINTERCMD_USER_FIELD = protobuf.FieldDescriptor()
DELMOVEMOUNTINTERCMD = protobuf.Descriptor()
DELMOVEMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
DELMOVEMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
DELMOVEMOUNTINTERCMD_NPCID_FIELD = protobuf.FieldDescriptor()
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD = protobuf.FieldDescriptor()
CONFIRMMOVEMOUNTINTERCMD = protobuf.Descriptor()
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD = protobuf.FieldDescriptor()
CANCELMOVEMOUNTINTERCMD = protobuf.Descriptor()
CANCELMOVEMOUNTINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD = protobuf.FieldDescriptor()
UPDATETRAINSTATEINTERCMD = protobuf.Descriptor()
UPDATETRAINSTATEINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
UPDATETRAINSTATEINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
UPDATETRAINSTATEINTERCMD_NPCID_FIELD = protobuf.FieldDescriptor()
UPDATETRAINSTATEINTERCMD_STATE_FIELD = protobuf.FieldDescriptor()
TRAINUSERSYNCINTERCMD = protobuf.Descriptor()
TRAINUSERSYNCINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
TRAINUSERSYNCINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TRAINUSERSYNCINTERCMD_STATE_FIELD = protobuf.FieldDescriptor()
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD = protobuf.FieldDescriptor()
TRAINUSERSYNCINTERCMD_USERS_FIELD = protobuf.FieldDescriptor()
TRAINUSERSYNCINTERCMD_NPCID_FIELD = protobuf.FieldDescriptor()
POSUPDATEINTERCMD = protobuf.Descriptor()
POSUPDATEINTERCMD_CMD_FIELD = protobuf.FieldDescriptor()
POSUPDATEINTERCMD_PARAM_FIELD = protobuf.FieldDescriptor()
POSUPDATEINTERCMD_POS_FIELD = protobuf.FieldDescriptor()
INTERACTPARAM_INTERPARAM_ADD_MOUNT_ENUM.name = "INTERPARAM_ADD_MOUNT"
INTERACTPARAM_INTERPARAM_ADD_MOUNT_ENUM.index = 0
INTERACTPARAM_INTERPARAM_ADD_MOUNT_ENUM.number = 1
INTERACTPARAM_INTERPARAM_DEL_MOUNT_ENUM.name = "INTERPARAM_DEL_MOUNT"
INTERACTPARAM_INTERPARAM_DEL_MOUNT_ENUM.index = 1
INTERACTPARAM_INTERPARAM_DEL_MOUNT_ENUM.number = 2
INTERACTPARAM_INTERPARAM_CONFIRM_MOUNT_ENUM.name = "INTERPARAM_CONFIRM_MOUNT"
INTERACTPARAM_INTERPARAM_CONFIRM_MOUNT_ENUM.index = 2
INTERACTPARAM_INTERPARAM_CONFIRM_MOUNT_ENUM.number = 3
INTERACTPARAM_INTERPARAM_CANCEL_MOUNT_ENUM.name = "INTERPARAM_CANCEL_MOUNT"
INTERACTPARAM_INTERPARAM_CANCEL_MOUNT_ENUM.index = 3
INTERACTPARAM_INTERPARAM_CANCEL_MOUNT_ENUM.number = 4
INTERACTPARAM_INTERPARAM_ADD_MOVE_MOUNT_ENUM.name = "INTERPARAM_ADD_MOVE_MOUNT"
INTERACTPARAM_INTERPARAM_ADD_MOVE_MOUNT_ENUM.index = 4
INTERACTPARAM_INTERPARAM_ADD_MOVE_MOUNT_ENUM.number = 5
INTERACTPARAM_INTERPARAM_DEL_MOVE_MOUNT_ENUM.name = "INTERPARAM_DEL_MOVE_MOUNT"
INTERACTPARAM_INTERPARAM_DEL_MOVE_MOUNT_ENUM.index = 5
INTERACTPARAM_INTERPARAM_DEL_MOVE_MOUNT_ENUM.number = 6
INTERACTPARAM_INTERPARAM_CONFIRM_MOVE_MOUNT_ENUM.name = "INTERPARAM_CONFIRM_MOVE_MOUNT"
INTERACTPARAM_INTERPARAM_CONFIRM_MOVE_MOUNT_ENUM.index = 6
INTERACTPARAM_INTERPARAM_CONFIRM_MOVE_MOUNT_ENUM.number = 7
INTERACTPARAM_INTERPARAM_CANCEL_MOVE_MOUNT_ENUM.name = "INTERPARAM_CANCEL_MOVE_MOUNT"
INTERACTPARAM_INTERPARAM_CANCEL_MOVE_MOUNT_ENUM.index = 7
INTERACTPARAM_INTERPARAM_CANCEL_MOVE_MOUNT_ENUM.number = 8
INTERACTPARAM_INTERPARAM_SYNC_TRAIN_STATUS_ENUM.name = "INTERPARAM_SYNC_TRAIN_STATUS"
INTERACTPARAM_INTERPARAM_SYNC_TRAIN_STATUS_ENUM.index = 8
INTERACTPARAM_INTERPARAM_SYNC_TRAIN_STATUS_ENUM.number = 9
INTERACTPARAM_INTERPARAM_UPDATE_TRAIN_STATE_ENUM.name = "INTERPARAM_UPDATE_TRAIN_STATE"
INTERACTPARAM_INTERPARAM_UPDATE_TRAIN_STATE_ENUM.index = 9
INTERACTPARAM_INTERPARAM_UPDATE_TRAIN_STATE_ENUM.number = 10
INTERACTPARAM_INTERPARAM_UPDATE_POS_ENUM.name = "INTERPARAM_UPDATE_POS"
INTERACTPARAM_INTERPARAM_UPDATE_POS_ENUM.index = 10
INTERACTPARAM_INTERPARAM_UPDATE_POS_ENUM.number = 11
INTERACTPARAM.name = "InteractParam"
INTERACTPARAM.full_name = ".Cmd.InteractParam"
INTERACTPARAM.values = {
  INTERACTPARAM_INTERPARAM_ADD_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_DEL_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_CONFIRM_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_CANCEL_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_ADD_MOVE_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_DEL_MOVE_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_CONFIRM_MOVE_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_CANCEL_MOVE_MOUNT_ENUM,
  INTERACTPARAM_INTERPARAM_SYNC_TRAIN_STATUS_ENUM,
  INTERACTPARAM_INTERPARAM_UPDATE_TRAIN_STATE_ENUM,
  INTERACTPARAM_INTERPARAM_UPDATE_POS_ENUM
}
ETRAINMOVESTATE_ETRAIN_MIN_ENUM.name = "ETRAIN_MIN"
ETRAINMOVESTATE_ETRAIN_MIN_ENUM.index = 0
ETRAINMOVESTATE_ETRAIN_MIN_ENUM.number = 0
ETRAINMOVESTATE_ETRAIN_STOP_OPEN_ENUM.name = "ETRAIN_STOP_OPEN"
ETRAINMOVESTATE_ETRAIN_STOP_OPEN_ENUM.index = 1
ETRAINMOVESTATE_ETRAIN_STOP_OPEN_ENUM.number = 1
ETRAINMOVESTATE_ETRAIN_STOP_CLOSE_ENUM.name = "ETRAIN_STOP_CLOSE"
ETRAINMOVESTATE_ETRAIN_STOP_CLOSE_ENUM.index = 2
ETRAINMOVESTATE_ETRAIN_STOP_CLOSE_ENUM.number = 2
ETRAINMOVESTATE_ETRAIN_MOVE_ENUM.name = "ETRAIN_MOVE"
ETRAINMOVESTATE_ETRAIN_MOVE_ENUM.index = 3
ETRAINMOVESTATE_ETRAIN_MOVE_ENUM.number = 3
ETRAINMOVESTATE.name = "ETrainMoveState"
ETRAINMOVESTATE.full_name = ".Cmd.ETrainMoveState"
ETRAINMOVESTATE.values = {
  ETRAINMOVESTATE_ETRAIN_MIN_ENUM,
  ETRAINMOVESTATE_ETRAIN_STOP_OPEN_ENUM,
  ETRAINMOVESTATE_ETRAIN_STOP_CLOSE_ENUM,
  ETRAINMOVESTATE_ETRAIN_MOVE_ENUM
}
ADDMOUNTINTERCMD_CMD_FIELD.name = "cmd"
ADDMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.AddMountInterCmd.cmd"
ADDMOUNTINTERCMD_CMD_FIELD.number = 1
ADDMOUNTINTERCMD_CMD_FIELD.index = 0
ADDMOUNTINTERCMD_CMD_FIELD.label = 1
ADDMOUNTINTERCMD_CMD_FIELD.has_default_value = true
ADDMOUNTINTERCMD_CMD_FIELD.default_value = 217
ADDMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ADDMOUNTINTERCMD_CMD_FIELD.type = 14
ADDMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
ADDMOUNTINTERCMD_PARAM_FIELD.name = "param"
ADDMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.AddMountInterCmd.param"
ADDMOUNTINTERCMD_PARAM_FIELD.number = 2
ADDMOUNTINTERCMD_PARAM_FIELD.index = 1
ADDMOUNTINTERCMD_PARAM_FIELD.label = 1
ADDMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
ADDMOUNTINTERCMD_PARAM_FIELD.default_value = 1
ADDMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
ADDMOUNTINTERCMD_PARAM_FIELD.type = 14
ADDMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
ADDMOUNTINTERCMD_NPCGUID_FIELD.name = "npcguid"
ADDMOUNTINTERCMD_NPCGUID_FIELD.full_name = ".Cmd.AddMountInterCmd.npcguid"
ADDMOUNTINTERCMD_NPCGUID_FIELD.number = 3
ADDMOUNTINTERCMD_NPCGUID_FIELD.index = 2
ADDMOUNTINTERCMD_NPCGUID_FIELD.label = 1
ADDMOUNTINTERCMD_NPCGUID_FIELD.has_default_value = false
ADDMOUNTINTERCMD_NPCGUID_FIELD.default_value = 0
ADDMOUNTINTERCMD_NPCGUID_FIELD.type = 4
ADDMOUNTINTERCMD_NPCGUID_FIELD.cpp_type = 4
ADDMOUNTINTERCMD_MOUNTID_FIELD.name = "mountid"
ADDMOUNTINTERCMD_MOUNTID_FIELD.full_name = ".Cmd.AddMountInterCmd.mountid"
ADDMOUNTINTERCMD_MOUNTID_FIELD.number = 4
ADDMOUNTINTERCMD_MOUNTID_FIELD.index = 3
ADDMOUNTINTERCMD_MOUNTID_FIELD.label = 1
ADDMOUNTINTERCMD_MOUNTID_FIELD.has_default_value = false
ADDMOUNTINTERCMD_MOUNTID_FIELD.default_value = 0
ADDMOUNTINTERCMD_MOUNTID_FIELD.type = 13
ADDMOUNTINTERCMD_MOUNTID_FIELD.cpp_type = 3
ADDMOUNTINTERCMD_CHARID_FIELD.name = "charid"
ADDMOUNTINTERCMD_CHARID_FIELD.full_name = ".Cmd.AddMountInterCmd.charid"
ADDMOUNTINTERCMD_CHARID_FIELD.number = 5
ADDMOUNTINTERCMD_CHARID_FIELD.index = 4
ADDMOUNTINTERCMD_CHARID_FIELD.label = 1
ADDMOUNTINTERCMD_CHARID_FIELD.has_default_value = false
ADDMOUNTINTERCMD_CHARID_FIELD.default_value = 0
ADDMOUNTINTERCMD_CHARID_FIELD.type = 4
ADDMOUNTINTERCMD_CHARID_FIELD.cpp_type = 4
ADDMOUNTINTERCMD.name = "AddMountInterCmd"
ADDMOUNTINTERCMD.full_name = ".Cmd.AddMountInterCmd"
ADDMOUNTINTERCMD.nested_types = {}
ADDMOUNTINTERCMD.enum_types = {}
ADDMOUNTINTERCMD.fields = {
  ADDMOUNTINTERCMD_CMD_FIELD,
  ADDMOUNTINTERCMD_PARAM_FIELD,
  ADDMOUNTINTERCMD_NPCGUID_FIELD,
  ADDMOUNTINTERCMD_MOUNTID_FIELD,
  ADDMOUNTINTERCMD_CHARID_FIELD
}
ADDMOUNTINTERCMD.is_extendable = false
ADDMOUNTINTERCMD.extensions = {}
DELMOUNTINTERCMD_CMD_FIELD.name = "cmd"
DELMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.DelMountInterCmd.cmd"
DELMOUNTINTERCMD_CMD_FIELD.number = 1
DELMOUNTINTERCMD_CMD_FIELD.index = 0
DELMOUNTINTERCMD_CMD_FIELD.label = 1
DELMOUNTINTERCMD_CMD_FIELD.has_default_value = true
DELMOUNTINTERCMD_CMD_FIELD.default_value = 217
DELMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
DELMOUNTINTERCMD_CMD_FIELD.type = 14
DELMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
DELMOUNTINTERCMD_PARAM_FIELD.name = "param"
DELMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.DelMountInterCmd.param"
DELMOUNTINTERCMD_PARAM_FIELD.number = 2
DELMOUNTINTERCMD_PARAM_FIELD.index = 1
DELMOUNTINTERCMD_PARAM_FIELD.label = 1
DELMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
DELMOUNTINTERCMD_PARAM_FIELD.default_value = 2
DELMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
DELMOUNTINTERCMD_PARAM_FIELD.type = 14
DELMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
DELMOUNTINTERCMD_NPCGUID_FIELD.name = "npcguid"
DELMOUNTINTERCMD_NPCGUID_FIELD.full_name = ".Cmd.DelMountInterCmd.npcguid"
DELMOUNTINTERCMD_NPCGUID_FIELD.number = 3
DELMOUNTINTERCMD_NPCGUID_FIELD.index = 2
DELMOUNTINTERCMD_NPCGUID_FIELD.label = 1
DELMOUNTINTERCMD_NPCGUID_FIELD.has_default_value = false
DELMOUNTINTERCMD_NPCGUID_FIELD.default_value = 0
DELMOUNTINTERCMD_NPCGUID_FIELD.type = 4
DELMOUNTINTERCMD_NPCGUID_FIELD.cpp_type = 4
DELMOUNTINTERCMD_CHARID_FIELD.name = "charid"
DELMOUNTINTERCMD_CHARID_FIELD.full_name = ".Cmd.DelMountInterCmd.charid"
DELMOUNTINTERCMD_CHARID_FIELD.number = 4
DELMOUNTINTERCMD_CHARID_FIELD.index = 3
DELMOUNTINTERCMD_CHARID_FIELD.label = 1
DELMOUNTINTERCMD_CHARID_FIELD.has_default_value = false
DELMOUNTINTERCMD_CHARID_FIELD.default_value = 0
DELMOUNTINTERCMD_CHARID_FIELD.type = 4
DELMOUNTINTERCMD_CHARID_FIELD.cpp_type = 4
DELMOUNTINTERCMD.name = "DelMountInterCmd"
DELMOUNTINTERCMD.full_name = ".Cmd.DelMountInterCmd"
DELMOUNTINTERCMD.nested_types = {}
DELMOUNTINTERCMD.enum_types = {}
DELMOUNTINTERCMD.fields = {
  DELMOUNTINTERCMD_CMD_FIELD,
  DELMOUNTINTERCMD_PARAM_FIELD,
  DELMOUNTINTERCMD_NPCGUID_FIELD,
  DELMOUNTINTERCMD_CHARID_FIELD
}
DELMOUNTINTERCMD.is_extendable = false
DELMOUNTINTERCMD.extensions = {}
CONFIRMMOUNTINTERCMD_CMD_FIELD.name = "cmd"
CONFIRMMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.ConfirmMountInterCmd.cmd"
CONFIRMMOUNTINTERCMD_CMD_FIELD.number = 1
CONFIRMMOUNTINTERCMD_CMD_FIELD.index = 0
CONFIRMMOUNTINTERCMD_CMD_FIELD.label = 1
CONFIRMMOUNTINTERCMD_CMD_FIELD.has_default_value = true
CONFIRMMOUNTINTERCMD_CMD_FIELD.default_value = 217
CONFIRMMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CONFIRMMOUNTINTERCMD_CMD_FIELD.type = 14
CONFIRMMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
CONFIRMMOUNTINTERCMD_PARAM_FIELD.name = "param"
CONFIRMMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.ConfirmMountInterCmd.param"
CONFIRMMOUNTINTERCMD_PARAM_FIELD.number = 2
CONFIRMMOUNTINTERCMD_PARAM_FIELD.index = 1
CONFIRMMOUNTINTERCMD_PARAM_FIELD.label = 1
CONFIRMMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
CONFIRMMOUNTINTERCMD_PARAM_FIELD.default_value = 3
CONFIRMMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
CONFIRMMOUNTINTERCMD_PARAM_FIELD.type = 14
CONFIRMMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.name = "npcguid"
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.full_name = ".Cmd.ConfirmMountInterCmd.npcguid"
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.number = 3
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.index = 2
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.label = 1
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.has_default_value = false
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.default_value = 0
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.type = 4
CONFIRMMOUNTINTERCMD_NPCGUID_FIELD.cpp_type = 4
CONFIRMMOUNTINTERCMD.name = "ConfirmMountInterCmd"
CONFIRMMOUNTINTERCMD.full_name = ".Cmd.ConfirmMountInterCmd"
CONFIRMMOUNTINTERCMD.nested_types = {}
CONFIRMMOUNTINTERCMD.enum_types = {}
CONFIRMMOUNTINTERCMD.fields = {
  CONFIRMMOUNTINTERCMD_CMD_FIELD,
  CONFIRMMOUNTINTERCMD_PARAM_FIELD,
  CONFIRMMOUNTINTERCMD_NPCGUID_FIELD
}
CONFIRMMOUNTINTERCMD.is_extendable = false
CONFIRMMOUNTINTERCMD.extensions = {}
CANCELMOUNTINTERCMD_CMD_FIELD.name = "cmd"
CANCELMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.CancelMountInterCmd.cmd"
CANCELMOUNTINTERCMD_CMD_FIELD.number = 1
CANCELMOUNTINTERCMD_CMD_FIELD.index = 0
CANCELMOUNTINTERCMD_CMD_FIELD.label = 1
CANCELMOUNTINTERCMD_CMD_FIELD.has_default_value = true
CANCELMOUNTINTERCMD_CMD_FIELD.default_value = 217
CANCELMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CANCELMOUNTINTERCMD_CMD_FIELD.type = 14
CANCELMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
CANCELMOUNTINTERCMD_PARAM_FIELD.name = "param"
CANCELMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.CancelMountInterCmd.param"
CANCELMOUNTINTERCMD_PARAM_FIELD.number = 2
CANCELMOUNTINTERCMD_PARAM_FIELD.index = 1
CANCELMOUNTINTERCMD_PARAM_FIELD.label = 1
CANCELMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
CANCELMOUNTINTERCMD_PARAM_FIELD.default_value = 4
CANCELMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
CANCELMOUNTINTERCMD_PARAM_FIELD.type = 14
CANCELMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
CANCELMOUNTINTERCMD_NPCGUID_FIELD.name = "npcguid"
CANCELMOUNTINTERCMD_NPCGUID_FIELD.full_name = ".Cmd.CancelMountInterCmd.npcguid"
CANCELMOUNTINTERCMD_NPCGUID_FIELD.number = 3
CANCELMOUNTINTERCMD_NPCGUID_FIELD.index = 2
CANCELMOUNTINTERCMD_NPCGUID_FIELD.label = 1
CANCELMOUNTINTERCMD_NPCGUID_FIELD.has_default_value = false
CANCELMOUNTINTERCMD_NPCGUID_FIELD.default_value = 0
CANCELMOUNTINTERCMD_NPCGUID_FIELD.type = 4
CANCELMOUNTINTERCMD_NPCGUID_FIELD.cpp_type = 4
CANCELMOUNTINTERCMD.name = "CancelMountInterCmd"
CANCELMOUNTINTERCMD.full_name = ".Cmd.CancelMountInterCmd"
CANCELMOUNTINTERCMD.nested_types = {}
CANCELMOUNTINTERCMD.enum_types = {}
CANCELMOUNTINTERCMD.fields = {
  CANCELMOUNTINTERCMD_CMD_FIELD,
  CANCELMOUNTINTERCMD_PARAM_FIELD,
  CANCELMOUNTINTERCMD_NPCGUID_FIELD
}
CANCELMOUNTINTERCMD.is_extendable = false
CANCELMOUNTINTERCMD.extensions = {}
TRAINUSERINFO_USER_FIELD.name = "user"
TRAINUSERINFO_USER_FIELD.full_name = ".Cmd.TrainUserInfo.user"
TRAINUSERINFO_USER_FIELD.number = 1
TRAINUSERINFO_USER_FIELD.index = 0
TRAINUSERINFO_USER_FIELD.label = 1
TRAINUSERINFO_USER_FIELD.has_default_value = false
TRAINUSERINFO_USER_FIELD.default_value = nil
TRAINUSERINFO_USER_FIELD.message_type = ChatCmd_pb.QUERYUSERINFO
TRAINUSERINFO_USER_FIELD.type = 11
TRAINUSERINFO_USER_FIELD.cpp_type = 10
TRAINUSERINFO_MOUNTID_FIELD.name = "mountid"
TRAINUSERINFO_MOUNTID_FIELD.full_name = ".Cmd.TrainUserInfo.mountid"
TRAINUSERINFO_MOUNTID_FIELD.number = 2
TRAINUSERINFO_MOUNTID_FIELD.index = 1
TRAINUSERINFO_MOUNTID_FIELD.label = 1
TRAINUSERINFO_MOUNTID_FIELD.has_default_value = false
TRAINUSERINFO_MOUNTID_FIELD.default_value = 0
TRAINUSERINFO_MOUNTID_FIELD.type = 13
TRAINUSERINFO_MOUNTID_FIELD.cpp_type = 3
TRAINUSERINFO.name = "TrainUserInfo"
TRAINUSERINFO.full_name = ".Cmd.TrainUserInfo"
TRAINUSERINFO.nested_types = {}
TRAINUSERINFO.enum_types = {}
TRAINUSERINFO.fields = {
  TRAINUSERINFO_USER_FIELD,
  TRAINUSERINFO_MOUNTID_FIELD
}
TRAINUSERINFO.is_extendable = false
TRAINUSERINFO.extensions = {}
ADDMOVEMOUNTINTERCMD_CMD_FIELD.name = "cmd"
ADDMOVEMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.AddMoveMountInterCmd.cmd"
ADDMOVEMOUNTINTERCMD_CMD_FIELD.number = 1
ADDMOVEMOUNTINTERCMD_CMD_FIELD.index = 0
ADDMOVEMOUNTINTERCMD_CMD_FIELD.label = 1
ADDMOVEMOUNTINTERCMD_CMD_FIELD.has_default_value = true
ADDMOVEMOUNTINTERCMD_CMD_FIELD.default_value = 217
ADDMOVEMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ADDMOVEMOUNTINTERCMD_CMD_FIELD.type = 14
ADDMOVEMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.name = "param"
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.AddMoveMountInterCmd.param"
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.number = 2
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.index = 1
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.label = 1
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.default_value = 5
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.type = 14
ADDMOVEMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.name = "npcid"
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.full_name = ".Cmd.AddMoveMountInterCmd.npcid"
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.number = 3
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.index = 2
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.label = 1
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.has_default_value = false
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.default_value = 0
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.type = 13
ADDMOVEMOUNTINTERCMD_NPCID_FIELD.cpp_type = 3
ADDMOVEMOUNTINTERCMD_USER_FIELD.name = "user"
ADDMOVEMOUNTINTERCMD_USER_FIELD.full_name = ".Cmd.AddMoveMountInterCmd.user"
ADDMOVEMOUNTINTERCMD_USER_FIELD.number = 4
ADDMOVEMOUNTINTERCMD_USER_FIELD.index = 3
ADDMOVEMOUNTINTERCMD_USER_FIELD.label = 1
ADDMOVEMOUNTINTERCMD_USER_FIELD.has_default_value = false
ADDMOVEMOUNTINTERCMD_USER_FIELD.default_value = nil
ADDMOVEMOUNTINTERCMD_USER_FIELD.message_type = TRAINUSERINFO
ADDMOVEMOUNTINTERCMD_USER_FIELD.type = 11
ADDMOVEMOUNTINTERCMD_USER_FIELD.cpp_type = 10
ADDMOVEMOUNTINTERCMD.name = "AddMoveMountInterCmd"
ADDMOVEMOUNTINTERCMD.full_name = ".Cmd.AddMoveMountInterCmd"
ADDMOVEMOUNTINTERCMD.nested_types = {}
ADDMOVEMOUNTINTERCMD.enum_types = {}
ADDMOVEMOUNTINTERCMD.fields = {
  ADDMOVEMOUNTINTERCMD_CMD_FIELD,
  ADDMOVEMOUNTINTERCMD_PARAM_FIELD,
  ADDMOVEMOUNTINTERCMD_NPCID_FIELD,
  ADDMOVEMOUNTINTERCMD_USER_FIELD
}
ADDMOVEMOUNTINTERCMD.is_extendable = false
ADDMOVEMOUNTINTERCMD.extensions = {}
DELMOVEMOUNTINTERCMD_CMD_FIELD.name = "cmd"
DELMOVEMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.DelMoveMountInterCmd.cmd"
DELMOVEMOUNTINTERCMD_CMD_FIELD.number = 1
DELMOVEMOUNTINTERCMD_CMD_FIELD.index = 0
DELMOVEMOUNTINTERCMD_CMD_FIELD.label = 1
DELMOVEMOUNTINTERCMD_CMD_FIELD.has_default_value = true
DELMOVEMOUNTINTERCMD_CMD_FIELD.default_value = 217
DELMOVEMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
DELMOVEMOUNTINTERCMD_CMD_FIELD.type = 14
DELMOVEMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
DELMOVEMOUNTINTERCMD_PARAM_FIELD.name = "param"
DELMOVEMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.DelMoveMountInterCmd.param"
DELMOVEMOUNTINTERCMD_PARAM_FIELD.number = 2
DELMOVEMOUNTINTERCMD_PARAM_FIELD.index = 1
DELMOVEMOUNTINTERCMD_PARAM_FIELD.label = 1
DELMOVEMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
DELMOVEMOUNTINTERCMD_PARAM_FIELD.default_value = 6
DELMOVEMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
DELMOVEMOUNTINTERCMD_PARAM_FIELD.type = 14
DELMOVEMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
DELMOVEMOUNTINTERCMD_NPCID_FIELD.name = "npcid"
DELMOVEMOUNTINTERCMD_NPCID_FIELD.full_name = ".Cmd.DelMoveMountInterCmd.npcid"
DELMOVEMOUNTINTERCMD_NPCID_FIELD.number = 3
DELMOVEMOUNTINTERCMD_NPCID_FIELD.index = 2
DELMOVEMOUNTINTERCMD_NPCID_FIELD.label = 1
DELMOVEMOUNTINTERCMD_NPCID_FIELD.has_default_value = false
DELMOVEMOUNTINTERCMD_NPCID_FIELD.default_value = 0
DELMOVEMOUNTINTERCMD_NPCID_FIELD.type = 13
DELMOVEMOUNTINTERCMD_NPCID_FIELD.cpp_type = 3
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.name = "charids"
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.full_name = ".Cmd.DelMoveMountInterCmd.charids"
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.number = 4
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.index = 3
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.label = 3
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.has_default_value = false
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.default_value = {}
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.type = 4
DELMOVEMOUNTINTERCMD_CHARIDS_FIELD.cpp_type = 4
DELMOVEMOUNTINTERCMD.name = "DelMoveMountInterCmd"
DELMOVEMOUNTINTERCMD.full_name = ".Cmd.DelMoveMountInterCmd"
DELMOVEMOUNTINTERCMD.nested_types = {}
DELMOVEMOUNTINTERCMD.enum_types = {}
DELMOVEMOUNTINTERCMD.fields = {
  DELMOVEMOUNTINTERCMD_CMD_FIELD,
  DELMOVEMOUNTINTERCMD_PARAM_FIELD,
  DELMOVEMOUNTINTERCMD_NPCID_FIELD,
  DELMOVEMOUNTINTERCMD_CHARIDS_FIELD
}
DELMOVEMOUNTINTERCMD.is_extendable = false
DELMOVEMOUNTINTERCMD.extensions = {}
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.name = "cmd"
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.ConfirmMoveMountInterCmd.cmd"
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.number = 1
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.index = 0
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.label = 1
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.has_default_value = true
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.default_value = 217
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.type = 14
CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.name = "param"
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.ConfirmMoveMountInterCmd.param"
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.number = 2
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.index = 1
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.label = 1
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.default_value = 7
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.type = 14
CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.name = "npcid"
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.full_name = ".Cmd.ConfirmMoveMountInterCmd.npcid"
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.number = 3
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.index = 2
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.label = 1
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.has_default_value = false
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.default_value = 0
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.type = 13
CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD.cpp_type = 3
CONFIRMMOVEMOUNTINTERCMD.name = "ConfirmMoveMountInterCmd"
CONFIRMMOVEMOUNTINTERCMD.full_name = ".Cmd.ConfirmMoveMountInterCmd"
CONFIRMMOVEMOUNTINTERCMD.nested_types = {}
CONFIRMMOVEMOUNTINTERCMD.enum_types = {}
CONFIRMMOVEMOUNTINTERCMD.fields = {
  CONFIRMMOVEMOUNTINTERCMD_CMD_FIELD,
  CONFIRMMOVEMOUNTINTERCMD_PARAM_FIELD,
  CONFIRMMOVEMOUNTINTERCMD_NPCID_FIELD
}
CONFIRMMOVEMOUNTINTERCMD.is_extendable = false
CONFIRMMOVEMOUNTINTERCMD.extensions = {}
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.name = "cmd"
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.full_name = ".Cmd.CancelMoveMountInterCmd.cmd"
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.number = 1
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.index = 0
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.label = 1
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.has_default_value = true
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.default_value = 217
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.type = 14
CANCELMOVEMOUNTINTERCMD_CMD_FIELD.cpp_type = 8
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.name = "param"
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.full_name = ".Cmd.CancelMoveMountInterCmd.param"
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.number = 2
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.index = 1
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.label = 1
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.has_default_value = true
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.default_value = 8
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.type = 14
CANCELMOVEMOUNTINTERCMD_PARAM_FIELD.cpp_type = 8
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.name = "npcid"
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.full_name = ".Cmd.CancelMoveMountInterCmd.npcid"
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.number = 3
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.index = 2
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.label = 1
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.has_default_value = false
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.default_value = 0
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.type = 13
CANCELMOVEMOUNTINTERCMD_NPCID_FIELD.cpp_type = 3
CANCELMOVEMOUNTINTERCMD.name = "CancelMoveMountInterCmd"
CANCELMOVEMOUNTINTERCMD.full_name = ".Cmd.CancelMoveMountInterCmd"
CANCELMOVEMOUNTINTERCMD.nested_types = {}
CANCELMOVEMOUNTINTERCMD.enum_types = {}
CANCELMOVEMOUNTINTERCMD.fields = {
  CANCELMOVEMOUNTINTERCMD_CMD_FIELD,
  CANCELMOVEMOUNTINTERCMD_PARAM_FIELD,
  CANCELMOVEMOUNTINTERCMD_NPCID_FIELD
}
CANCELMOVEMOUNTINTERCMD.is_extendable = false
CANCELMOVEMOUNTINTERCMD.extensions = {}
UPDATETRAINSTATEINTERCMD_CMD_FIELD.name = "cmd"
UPDATETRAINSTATEINTERCMD_CMD_FIELD.full_name = ".Cmd.UpdateTrainStateInterCmd.cmd"
UPDATETRAINSTATEINTERCMD_CMD_FIELD.number = 1
UPDATETRAINSTATEINTERCMD_CMD_FIELD.index = 0
UPDATETRAINSTATEINTERCMD_CMD_FIELD.label = 1
UPDATETRAINSTATEINTERCMD_CMD_FIELD.has_default_value = true
UPDATETRAINSTATEINTERCMD_CMD_FIELD.default_value = 217
UPDATETRAINSTATEINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
UPDATETRAINSTATEINTERCMD_CMD_FIELD.type = 14
UPDATETRAINSTATEINTERCMD_CMD_FIELD.cpp_type = 8
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.name = "param"
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.full_name = ".Cmd.UpdateTrainStateInterCmd.param"
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.number = 2
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.index = 1
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.label = 1
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.has_default_value = true
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.default_value = 10
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.type = 14
UPDATETRAINSTATEINTERCMD_PARAM_FIELD.cpp_type = 8
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.name = "npcid"
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.full_name = ".Cmd.UpdateTrainStateInterCmd.npcid"
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.number = 3
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.index = 2
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.label = 1
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.has_default_value = false
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.default_value = 0
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.type = 13
UPDATETRAINSTATEINTERCMD_NPCID_FIELD.cpp_type = 3
UPDATETRAINSTATEINTERCMD_STATE_FIELD.name = "state"
UPDATETRAINSTATEINTERCMD_STATE_FIELD.full_name = ".Cmd.UpdateTrainStateInterCmd.state"
UPDATETRAINSTATEINTERCMD_STATE_FIELD.number = 4
UPDATETRAINSTATEINTERCMD_STATE_FIELD.index = 3
UPDATETRAINSTATEINTERCMD_STATE_FIELD.label = 1
UPDATETRAINSTATEINTERCMD_STATE_FIELD.has_default_value = false
UPDATETRAINSTATEINTERCMD_STATE_FIELD.default_value = nil
UPDATETRAINSTATEINTERCMD_STATE_FIELD.enum_type = ETRAINMOVESTATE
UPDATETRAINSTATEINTERCMD_STATE_FIELD.type = 14
UPDATETRAINSTATEINTERCMD_STATE_FIELD.cpp_type = 8
UPDATETRAINSTATEINTERCMD.name = "UpdateTrainStateInterCmd"
UPDATETRAINSTATEINTERCMD.full_name = ".Cmd.UpdateTrainStateInterCmd"
UPDATETRAINSTATEINTERCMD.nested_types = {}
UPDATETRAINSTATEINTERCMD.enum_types = {}
UPDATETRAINSTATEINTERCMD.fields = {
  UPDATETRAINSTATEINTERCMD_CMD_FIELD,
  UPDATETRAINSTATEINTERCMD_PARAM_FIELD,
  UPDATETRAINSTATEINTERCMD_NPCID_FIELD,
  UPDATETRAINSTATEINTERCMD_STATE_FIELD
}
UPDATETRAINSTATEINTERCMD.is_extendable = false
UPDATETRAINSTATEINTERCMD.extensions = {}
TRAINUSERSYNCINTERCMD_CMD_FIELD.name = "cmd"
TRAINUSERSYNCINTERCMD_CMD_FIELD.full_name = ".Cmd.TrainUserSyncInterCmd.cmd"
TRAINUSERSYNCINTERCMD_CMD_FIELD.number = 1
TRAINUSERSYNCINTERCMD_CMD_FIELD.index = 0
TRAINUSERSYNCINTERCMD_CMD_FIELD.label = 1
TRAINUSERSYNCINTERCMD_CMD_FIELD.has_default_value = true
TRAINUSERSYNCINTERCMD_CMD_FIELD.default_value = 217
TRAINUSERSYNCINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TRAINUSERSYNCINTERCMD_CMD_FIELD.type = 14
TRAINUSERSYNCINTERCMD_CMD_FIELD.cpp_type = 8
TRAINUSERSYNCINTERCMD_PARAM_FIELD.name = "param"
TRAINUSERSYNCINTERCMD_PARAM_FIELD.full_name = ".Cmd.TrainUserSyncInterCmd.param"
TRAINUSERSYNCINTERCMD_PARAM_FIELD.number = 2
TRAINUSERSYNCINTERCMD_PARAM_FIELD.index = 1
TRAINUSERSYNCINTERCMD_PARAM_FIELD.label = 1
TRAINUSERSYNCINTERCMD_PARAM_FIELD.has_default_value = true
TRAINUSERSYNCINTERCMD_PARAM_FIELD.default_value = 9
TRAINUSERSYNCINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
TRAINUSERSYNCINTERCMD_PARAM_FIELD.type = 14
TRAINUSERSYNCINTERCMD_PARAM_FIELD.cpp_type = 8
TRAINUSERSYNCINTERCMD_STATE_FIELD.name = "state"
TRAINUSERSYNCINTERCMD_STATE_FIELD.full_name = ".Cmd.TrainUserSyncInterCmd.state"
TRAINUSERSYNCINTERCMD_STATE_FIELD.number = 3
TRAINUSERSYNCINTERCMD_STATE_FIELD.index = 2
TRAINUSERSYNCINTERCMD_STATE_FIELD.label = 1
TRAINUSERSYNCINTERCMD_STATE_FIELD.has_default_value = false
TRAINUSERSYNCINTERCMD_STATE_FIELD.default_value = nil
TRAINUSERSYNCINTERCMD_STATE_FIELD.enum_type = ETRAINMOVESTATE
TRAINUSERSYNCINTERCMD_STATE_FIELD.type = 14
TRAINUSERSYNCINTERCMD_STATE_FIELD.cpp_type = 8
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.name = "arrivetime"
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.full_name = ".Cmd.TrainUserSyncInterCmd.arrivetime"
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.number = 4
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.index = 3
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.label = 1
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.has_default_value = false
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.default_value = 0
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.type = 13
TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD.cpp_type = 3
TRAINUSERSYNCINTERCMD_USERS_FIELD.name = "users"
TRAINUSERSYNCINTERCMD_USERS_FIELD.full_name = ".Cmd.TrainUserSyncInterCmd.users"
TRAINUSERSYNCINTERCMD_USERS_FIELD.number = 5
TRAINUSERSYNCINTERCMD_USERS_FIELD.index = 4
TRAINUSERSYNCINTERCMD_USERS_FIELD.label = 3
TRAINUSERSYNCINTERCMD_USERS_FIELD.has_default_value = false
TRAINUSERSYNCINTERCMD_USERS_FIELD.default_value = {}
TRAINUSERSYNCINTERCMD_USERS_FIELD.message_type = TRAINUSERINFO
TRAINUSERSYNCINTERCMD_USERS_FIELD.type = 11
TRAINUSERSYNCINTERCMD_USERS_FIELD.cpp_type = 10
TRAINUSERSYNCINTERCMD_NPCID_FIELD.name = "npcid"
TRAINUSERSYNCINTERCMD_NPCID_FIELD.full_name = ".Cmd.TrainUserSyncInterCmd.npcid"
TRAINUSERSYNCINTERCMD_NPCID_FIELD.number = 6
TRAINUSERSYNCINTERCMD_NPCID_FIELD.index = 5
TRAINUSERSYNCINTERCMD_NPCID_FIELD.label = 1
TRAINUSERSYNCINTERCMD_NPCID_FIELD.has_default_value = false
TRAINUSERSYNCINTERCMD_NPCID_FIELD.default_value = 0
TRAINUSERSYNCINTERCMD_NPCID_FIELD.type = 13
TRAINUSERSYNCINTERCMD_NPCID_FIELD.cpp_type = 3
TRAINUSERSYNCINTERCMD.name = "TrainUserSyncInterCmd"
TRAINUSERSYNCINTERCMD.full_name = ".Cmd.TrainUserSyncInterCmd"
TRAINUSERSYNCINTERCMD.nested_types = {}
TRAINUSERSYNCINTERCMD.enum_types = {}
TRAINUSERSYNCINTERCMD.fields = {
  TRAINUSERSYNCINTERCMD_CMD_FIELD,
  TRAINUSERSYNCINTERCMD_PARAM_FIELD,
  TRAINUSERSYNCINTERCMD_STATE_FIELD,
  TRAINUSERSYNCINTERCMD_ARRIVETIME_FIELD,
  TRAINUSERSYNCINTERCMD_USERS_FIELD,
  TRAINUSERSYNCINTERCMD_NPCID_FIELD
}
TRAINUSERSYNCINTERCMD.is_extendable = false
TRAINUSERSYNCINTERCMD.extensions = {}
POSUPDATEINTERCMD_CMD_FIELD.name = "cmd"
POSUPDATEINTERCMD_CMD_FIELD.full_name = ".Cmd.PosUpdateInterCmd.cmd"
POSUPDATEINTERCMD_CMD_FIELD.number = 1
POSUPDATEINTERCMD_CMD_FIELD.index = 0
POSUPDATEINTERCMD_CMD_FIELD.label = 1
POSUPDATEINTERCMD_CMD_FIELD.has_default_value = true
POSUPDATEINTERCMD_CMD_FIELD.default_value = 217
POSUPDATEINTERCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
POSUPDATEINTERCMD_CMD_FIELD.type = 14
POSUPDATEINTERCMD_CMD_FIELD.cpp_type = 8
POSUPDATEINTERCMD_PARAM_FIELD.name = "param"
POSUPDATEINTERCMD_PARAM_FIELD.full_name = ".Cmd.PosUpdateInterCmd.param"
POSUPDATEINTERCMD_PARAM_FIELD.number = 2
POSUPDATEINTERCMD_PARAM_FIELD.index = 1
POSUPDATEINTERCMD_PARAM_FIELD.label = 1
POSUPDATEINTERCMD_PARAM_FIELD.has_default_value = true
POSUPDATEINTERCMD_PARAM_FIELD.default_value = 11
POSUPDATEINTERCMD_PARAM_FIELD.enum_type = INTERACTPARAM
POSUPDATEINTERCMD_PARAM_FIELD.type = 14
POSUPDATEINTERCMD_PARAM_FIELD.cpp_type = 8
POSUPDATEINTERCMD_POS_FIELD.name = "pos"
POSUPDATEINTERCMD_POS_FIELD.full_name = ".Cmd.PosUpdateInterCmd.pos"
POSUPDATEINTERCMD_POS_FIELD.number = 3
POSUPDATEINTERCMD_POS_FIELD.index = 2
POSUPDATEINTERCMD_POS_FIELD.label = 1
POSUPDATEINTERCMD_POS_FIELD.has_default_value = false
POSUPDATEINTERCMD_POS_FIELD.default_value = nil
POSUPDATEINTERCMD_POS_FIELD.message_type = ProtoCommon_pb.SCENEPOS
POSUPDATEINTERCMD_POS_FIELD.type = 11
POSUPDATEINTERCMD_POS_FIELD.cpp_type = 10
POSUPDATEINTERCMD.name = "PosUpdateInterCmd"
POSUPDATEINTERCMD.full_name = ".Cmd.PosUpdateInterCmd"
POSUPDATEINTERCMD.nested_types = {}
POSUPDATEINTERCMD.enum_types = {}
POSUPDATEINTERCMD.fields = {
  POSUPDATEINTERCMD_CMD_FIELD,
  POSUPDATEINTERCMD_PARAM_FIELD,
  POSUPDATEINTERCMD_POS_FIELD
}
POSUPDATEINTERCMD.is_extendable = false
POSUPDATEINTERCMD.extensions = {}
AddMountInterCmd = protobuf.Message(ADDMOUNTINTERCMD)
AddMoveMountInterCmd = protobuf.Message(ADDMOVEMOUNTINTERCMD)
CancelMountInterCmd = protobuf.Message(CANCELMOUNTINTERCMD)
CancelMoveMountInterCmd = protobuf.Message(CANCELMOVEMOUNTINTERCMD)
ConfirmMountInterCmd = protobuf.Message(CONFIRMMOUNTINTERCMD)
ConfirmMoveMountInterCmd = protobuf.Message(CONFIRMMOVEMOUNTINTERCMD)
DelMountInterCmd = protobuf.Message(DELMOUNTINTERCMD)
DelMoveMountInterCmd = protobuf.Message(DELMOVEMOUNTINTERCMD)
ETRAIN_MIN = 0
ETRAIN_MOVE = 3
ETRAIN_STOP_CLOSE = 2
ETRAIN_STOP_OPEN = 1
INTERPARAM_ADD_MOUNT = 1
INTERPARAM_ADD_MOVE_MOUNT = 5
INTERPARAM_CANCEL_MOUNT = 4
INTERPARAM_CANCEL_MOVE_MOUNT = 8
INTERPARAM_CONFIRM_MOUNT = 3
INTERPARAM_CONFIRM_MOVE_MOUNT = 7
INTERPARAM_DEL_MOUNT = 2
INTERPARAM_DEL_MOVE_MOUNT = 6
INTERPARAM_SYNC_TRAIN_STATUS = 9
INTERPARAM_UPDATE_POS = 11
INTERPARAM_UPDATE_TRAIN_STATE = 10
PosUpdateInterCmd = protobuf.Message(POSUPDATEINTERCMD)
TrainUserInfo = protobuf.Message(TRAINUSERINFO)
TrainUserSyncInterCmd = protobuf.Message(TRAINUSERSYNCINTERCMD)
UpdateTrainStateInterCmd = protobuf.Message(UPDATETRAINSTATEINTERCMD)
