local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("OverseasTaiwanCmd_pb")
OVERSEASTAIWANPARAM = protobuf.EnumDescriptor()
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_REDEEM_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASSCENEPARAM = protobuf.EnumDescriptor()
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_UPLOAD_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_PREFIX_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASSCENEPARAM_OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_ADD_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_USE_CMD_ENUM = protobuf.EnumValueDescriptor()
OVERSEASGOEITEMADDTYPE = protobuf.EnumDescriptor()
OVERSEASGOEITEMADDTYPE_ENUM_GOE_ITEM_ADD_TYPE_LOTTERY_ENUM = protobuf.EnumValueDescriptor()
OVERSEASGOEITEMUSETYPE = protobuf.EnumDescriptor()
OVERSEASGOEITEMUSETYPE_ENUM_GOE_ITEM_USE_TYPE_LOTTERY_ENUM = protobuf.EnumValueDescriptor()
OVERSEASPHOTOGALLERYTYPE = protobuf.EnumDescriptor()
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MIN_ENUM = protobuf.EnumValueDescriptor()
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_SCENERY_ENUM = protobuf.EnumValueDescriptor()
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_PHOTO_ENUM = protobuf.EnumValueDescriptor()
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_GUILDICON_ENUM = protobuf.EnumValueDescriptor()
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_WEDDING_ENUM = protobuf.EnumValueDescriptor()
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MAX_ENUM = protobuf.EnumValueDescriptor()
TAIWANFBLIKEUSERREDEEMERROR = protobuf.EnumDescriptor()
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR_ENUM = protobuf.EnumValueDescriptor()
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED_ENUM = protobuf.EnumValueDescriptor()
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED_ENUM = protobuf.EnumValueDescriptor()
TAIWANFACEBOOKSHAREREDEEMERROR = protobuf.EnumDescriptor()
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS_ENUM = protobuf.EnumValueDescriptor()
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED_ENUM = protobuf.EnumValueDescriptor()
TAIWANFBLIKEPRIZEITEM = protobuf.Descriptor()
TAIWANFBLIKEPRIZEITEM_ID_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEPROGRESSCMD = protobuf.Descriptor()
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEUSERREDEEMCMD = protobuf.Descriptor()
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD = protobuf.FieldDescriptor()
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADFIELD = protobuf.Descriptor()
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADCMD = protobuf.Descriptor()
OVERSEASPHOTOUPLOADCMD_CMD_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOUPLOADCMD_PATH_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOPATHPREFIXCMD = protobuf.Descriptor()
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD = protobuf.FieldDescriptor()
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD = protobuf.FieldDescriptor()
TAIWANFBSHAREPROGRESSCMD = protobuf.Descriptor()
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD = protobuf.FieldDescriptor()
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD = protobuf.FieldDescriptor()
TAIWANFBSHAREREDEEMCMD = protobuf.Descriptor()
TAIWANFBSHAREREDEEMCMD_CMD_FIELD = protobuf.FieldDescriptor()
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
TAIWANFBSHAREREDEEMCMD_ERR_FIELD = protobuf.FieldDescriptor()
OVERSEASCHARGELIMITGETCHARGECMD = protobuf.Descriptor()
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD = protobuf.FieldDescriptor()
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD = protobuf.FieldDescriptor()
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD = protobuf.Descriptor()
OVERSEASGOEITEMADDCMD_CMD_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_PARAM_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_UID_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_CONTENT_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_PID_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_NUM_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_AMT_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_PTYPE_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_NOTE_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMADDCMD_DATE_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD = protobuf.Descriptor()
OVERSEASGOEITEMUSECMD_CMD_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_PARAM_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_UID_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_CONTENT_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_PID_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_NUM_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_NUMF_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_UTYPE_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_NOTE_FIELD = protobuf.FieldDescriptor()
OVERSEASGOEITEMUSECMD_DATE_FIELD = protobuf.FieldDescriptor()
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD_ENUM.name = "TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD"
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD_ENUM.index = 0
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD_ENUM.number = 1
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD_ENUM.name = "TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD"
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD_ENUM.index = 1
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD_ENUM.number = 2
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD_ENUM.name = "TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD"
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD_ENUM.index = 2
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD_ENUM.number = 10
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_REDEEM_CMD_ENUM.name = "TAIWAN_FACEBOOK_SHARE_REDEEM_CMD"
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_REDEEM_CMD_ENUM.index = 3
OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_REDEEM_CMD_ENUM.number = 11
OVERSEASTAIWANPARAM.name = "OverseasTaiwanParam"
OVERSEASTAIWANPARAM.full_name = ".Cmd.OverseasTaiwanParam"
OVERSEASTAIWANPARAM.values = {
  OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD_ENUM,
  OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD_ENUM,
  OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD_ENUM,
  OVERSEASTAIWANPARAM_TAIWAN_FACEBOOK_SHARE_REDEEM_CMD_ENUM
}
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_UPLOAD_CMD_ENUM.name = "OVERSEAS_PHOTO_UPLOAD_CMD"
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_UPLOAD_CMD_ENUM.index = 0
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_UPLOAD_CMD_ENUM.number = 1
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_PREFIX_CMD_ENUM.name = "OVERSEAS_PHOTO_PREFIX_CMD"
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_PREFIX_CMD_ENUM.index = 1
OVERSEASSCENEPARAM_OVERSEAS_PHOTO_PREFIX_CMD_ENUM.number = 2
OVERSEASSCENEPARAM_OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD_ENUM.name = "OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD"
OVERSEASSCENEPARAM_OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD_ENUM.index = 2
OVERSEASSCENEPARAM_OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD_ENUM.number = 11
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_ADD_CMD_ENUM.name = "OVERSEAS_GOE_ITEM_ADD_CMD"
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_ADD_CMD_ENUM.index = 3
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_ADD_CMD_ENUM.number = 21
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_USE_CMD_ENUM.name = "OVERSEAS_GOE_ITEM_USE_CMD"
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_USE_CMD_ENUM.index = 4
OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_USE_CMD_ENUM.number = 22
OVERSEASSCENEPARAM.name = "OverseasSceneParam"
OVERSEASSCENEPARAM.full_name = ".Cmd.OverseasSceneParam"
OVERSEASSCENEPARAM.values = {
  OVERSEASSCENEPARAM_OVERSEAS_PHOTO_UPLOAD_CMD_ENUM,
  OVERSEASSCENEPARAM_OVERSEAS_PHOTO_PREFIX_CMD_ENUM,
  OVERSEASSCENEPARAM_OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD_ENUM,
  OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_ADD_CMD_ENUM,
  OVERSEASSCENEPARAM_OVERSEAS_GOE_ITEM_USE_CMD_ENUM
}
OVERSEASGOEITEMADDTYPE_ENUM_GOE_ITEM_ADD_TYPE_LOTTERY_ENUM.name = "ENUM_GOE_ITEM_ADD_TYPE_LOTTERY"
OVERSEASGOEITEMADDTYPE_ENUM_GOE_ITEM_ADD_TYPE_LOTTERY_ENUM.index = 0
OVERSEASGOEITEMADDTYPE_ENUM_GOE_ITEM_ADD_TYPE_LOTTERY_ENUM.number = 1
OVERSEASGOEITEMADDTYPE.name = "OverseasGoeItemAddType"
OVERSEASGOEITEMADDTYPE.full_name = ".Cmd.OverseasGoeItemAddType"
OVERSEASGOEITEMADDTYPE.values = {
  OVERSEASGOEITEMADDTYPE_ENUM_GOE_ITEM_ADD_TYPE_LOTTERY_ENUM
}
OVERSEASGOEITEMUSETYPE_ENUM_GOE_ITEM_USE_TYPE_LOTTERY_ENUM.name = "ENUM_GOE_ITEM_USE_TYPE_LOTTERY"
OVERSEASGOEITEMUSETYPE_ENUM_GOE_ITEM_USE_TYPE_LOTTERY_ENUM.index = 0
OVERSEASGOEITEMUSETYPE_ENUM_GOE_ITEM_USE_TYPE_LOTTERY_ENUM.number = 1
OVERSEASGOEITEMUSETYPE.name = "OverseasGoeItemUseType"
OVERSEASGOEITEMUSETYPE.full_name = ".Cmd.OverseasGoeItemUseType"
OVERSEASGOEITEMUSETYPE.values = {
  OVERSEASGOEITEMUSETYPE_ENUM_GOE_ITEM_USE_TYPE_LOTTERY_ENUM
}
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MIN_ENUM.name = "ENUM_GALLERY_TYPE_MIN"
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MIN_ENUM.index = 0
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MIN_ENUM.number = 0
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_SCENERY_ENUM.name = "ENUM_GALLERY_TYPE_SCENERY"
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_SCENERY_ENUM.index = 1
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_SCENERY_ENUM.number = 1
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_PHOTO_ENUM.name = "ENUM_GALLERY_TYPE_PHOTO"
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_PHOTO_ENUM.index = 2
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_PHOTO_ENUM.number = 2
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_GUILDICON_ENUM.name = "ENUM_GALLERY_TYPE_GUILDICON"
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_GUILDICON_ENUM.index = 3
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_GUILDICON_ENUM.number = 3
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_WEDDING_ENUM.name = "ENUM_GALLERY_TYPE_WEDDING"
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_WEDDING_ENUM.index = 4
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_WEDDING_ENUM.number = 4
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MAX_ENUM.name = "ENUM_GALLERY_TYPE_MAX"
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MAX_ENUM.index = 5
OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MAX_ENUM.number = 5
OVERSEASPHOTOGALLERYTYPE.name = "OverseasPhotoGalleryType"
OVERSEASPHOTOGALLERYTYPE.full_name = ".Cmd.OverseasPhotoGalleryType"
OVERSEASPHOTOGALLERYTYPE.values = {
  OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MIN_ENUM,
  OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_SCENERY_ENUM,
  OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_PHOTO_ENUM,
  OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_GUILDICON_ENUM,
  OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_WEDDING_ENUM,
  OVERSEASPHOTOGALLERYTYPE_ENUM_GALLERY_TYPE_MAX_ENUM
}
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR_ENUM.name = "TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR"
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR_ENUM.index = 0
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR_ENUM.number = 0
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED_ENUM.name = "TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED"
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED_ENUM.index = 1
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED_ENUM.number = 1
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED_ENUM.name = "TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED"
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED_ENUM.index = 2
TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED_ENUM.number = 2
TAIWANFBLIKEUSERREDEEMERROR.name = "TaiwanFbLikeUserRedeemError"
TAIWANFBLIKEUSERREDEEMERROR.full_name = ".Cmd.TaiwanFbLikeUserRedeemError"
TAIWANFBLIKEUSERREDEEMERROR.values = {
  TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR_ENUM,
  TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED_ENUM,
  TAIWANFBLIKEUSERREDEEMERROR_TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED_ENUM
}
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS_ENUM.name = "TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS"
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS_ENUM.index = 0
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS_ENUM.number = 0
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED_ENUM.name = "TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED"
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED_ENUM.index = 1
TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED_ENUM.number = 1
TAIWANFACEBOOKSHAREREDEEMERROR.name = "TaiwanFaceBookShareRedeemError"
TAIWANFACEBOOKSHAREREDEEMERROR.full_name = ".Cmd.TaiwanFaceBookShareRedeemError"
TAIWANFACEBOOKSHAREREDEEMERROR.values = {
  TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS_ENUM,
  TAIWANFACEBOOKSHAREREDEEMERROR_TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED_ENUM
}
TAIWANFBLIKEPRIZEITEM_ID_FIELD.name = "id"
TAIWANFBLIKEPRIZEITEM_ID_FIELD.full_name = ".Cmd.TaiwanFbLikePrizeItem.id"
TAIWANFBLIKEPRIZEITEM_ID_FIELD.number = 1
TAIWANFBLIKEPRIZEITEM_ID_FIELD.index = 0
TAIWANFBLIKEPRIZEITEM_ID_FIELD.label = 1
TAIWANFBLIKEPRIZEITEM_ID_FIELD.has_default_value = false
TAIWANFBLIKEPRIZEITEM_ID_FIELD.default_value = 0
TAIWANFBLIKEPRIZEITEM_ID_FIELD.type = 13
TAIWANFBLIKEPRIZEITEM_ID_FIELD.cpp_type = 3
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.name = "isUnlocked"
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.full_name = ".Cmd.TaiwanFbLikePrizeItem.isUnlocked"
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.number = 2
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.index = 1
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.label = 1
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.has_default_value = true
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.default_value = false
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.type = 8
TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD.cpp_type = 7
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.name = "userRedeemed"
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.full_name = ".Cmd.TaiwanFbLikePrizeItem.userRedeemed"
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.number = 3
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.index = 2
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.label = 1
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.has_default_value = true
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.default_value = false
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.type = 8
TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD.cpp_type = 7
TAIWANFBLIKEPRIZEITEM.name = "TaiwanFbLikePrizeItem"
TAIWANFBLIKEPRIZEITEM.full_name = ".Cmd.TaiwanFbLikePrizeItem"
TAIWANFBLIKEPRIZEITEM.nested_types = {}
TAIWANFBLIKEPRIZEITEM.enum_types = {}
TAIWANFBLIKEPRIZEITEM.fields = {
  TAIWANFBLIKEPRIZEITEM_ID_FIELD,
  TAIWANFBLIKEPRIZEITEM_ISUNLOCKED_FIELD,
  TAIWANFBLIKEPRIZEITEM_USERREDEEMED_FIELD
}
TAIWANFBLIKEPRIZEITEM.is_extendable = false
TAIWANFBLIKEPRIZEITEM.extensions = {}
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.name = "cmd"
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.full_name = ".Cmd.TaiwanFbLikeProgressCmd.cmd"
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.number = 1
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.index = 0
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.label = 1
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.has_default_value = true
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.default_value = 80
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.type = 14
TAIWANFBLIKEPROGRESSCMD_CMD_FIELD.cpp_type = 8
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.name = "param"
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.full_name = ".Cmd.TaiwanFbLikeProgressCmd.param"
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.number = 2
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.index = 1
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.label = 1
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.has_default_value = true
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.default_value = 1
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.enum_type = OVERSEASTAIWANPARAM
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.type = 14
TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD.cpp_type = 8
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.name = "totalLikes"
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.full_name = ".Cmd.TaiwanFbLikeProgressCmd.totalLikes"
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.number = 3
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.index = 2
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.label = 1
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.has_default_value = false
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.default_value = 0
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.type = 13
TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD.cpp_type = 3
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.name = "prizeList"
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.full_name = ".Cmd.TaiwanFbLikeProgressCmd.prizeList"
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.number = 4
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.index = 3
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.label = 3
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.has_default_value = false
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.default_value = {}
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.message_type = TAIWANFBLIKEPRIZEITEM
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.type = 11
TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD.cpp_type = 10
TAIWANFBLIKEPROGRESSCMD.name = "TaiwanFbLikeProgressCmd"
TAIWANFBLIKEPROGRESSCMD.full_name = ".Cmd.TaiwanFbLikeProgressCmd"
TAIWANFBLIKEPROGRESSCMD.nested_types = {}
TAIWANFBLIKEPROGRESSCMD.enum_types = {}
TAIWANFBLIKEPROGRESSCMD.fields = {
  TAIWANFBLIKEPROGRESSCMD_CMD_FIELD,
  TAIWANFBLIKEPROGRESSCMD_PARAM_FIELD,
  TAIWANFBLIKEPROGRESSCMD_TOTALLIKES_FIELD,
  TAIWANFBLIKEPROGRESSCMD_PRIZELIST_FIELD
}
TAIWANFBLIKEPROGRESSCMD.is_extendable = false
TAIWANFBLIKEPROGRESSCMD.extensions = {}
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.name = "cmd"
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.full_name = ".Cmd.TaiwanFbLikeUserRedeemCmd.cmd"
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.number = 1
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.index = 0
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.label = 1
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.has_default_value = true
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.default_value = 80
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.type = 14
TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD.cpp_type = 8
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.name = "param"
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.full_name = ".Cmd.TaiwanFbLikeUserRedeemCmd.param"
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.number = 2
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.index = 1
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.label = 1
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.has_default_value = true
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.default_value = 2
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.enum_type = OVERSEASTAIWANPARAM
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.type = 14
TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD.cpp_type = 8
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.name = "prizeId"
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.full_name = ".Cmd.TaiwanFbLikeUserRedeemCmd.prizeId"
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.number = 3
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.index = 2
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.label = 2
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.has_default_value = false
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.default_value = 0
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.type = 13
TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD.cpp_type = 3
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.name = "err"
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.full_name = ".Cmd.TaiwanFbLikeUserRedeemCmd.err"
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.number = 4
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.index = 3
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.label = 1
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.has_default_value = true
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.default_value = 0
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.enum_type = TAIWANFBLIKEUSERREDEEMERROR
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.type = 14
TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD.cpp_type = 8
TAIWANFBLIKEUSERREDEEMCMD.name = "TaiwanFbLikeUserRedeemCmd"
TAIWANFBLIKEUSERREDEEMCMD.full_name = ".Cmd.TaiwanFbLikeUserRedeemCmd"
TAIWANFBLIKEUSERREDEEMCMD.nested_types = {}
TAIWANFBLIKEUSERREDEEMCMD.enum_types = {}
TAIWANFBLIKEUSERREDEEMCMD.fields = {
  TAIWANFBLIKEUSERREDEEMCMD_CMD_FIELD,
  TAIWANFBLIKEUSERREDEEMCMD_PARAM_FIELD,
  TAIWANFBLIKEUSERREDEEMCMD_PRIZEID_FIELD,
  TAIWANFBLIKEUSERREDEEMCMD_ERR_FIELD
}
TAIWANFBLIKEUSERREDEEMCMD.is_extendable = false
TAIWANFBLIKEUSERREDEEMCMD.extensions = {}
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.name = "name"
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.full_name = ".Cmd.OverseasPhotoUploadField.name"
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.number = 1
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.index = 0
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.label = 2
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.has_default_value = false
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.default_value = ""
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.type = 9
OVERSEASPHOTOUPLOADFIELD_NAME_FIELD.cpp_type = 9
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.name = "value"
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.full_name = ".Cmd.OverseasPhotoUploadField.value"
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.number = 2
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.index = 1
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.label = 2
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.has_default_value = false
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.default_value = ""
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.type = 9
OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD.cpp_type = 9
OVERSEASPHOTOUPLOADFIELD.name = "OverseasPhotoUploadField"
OVERSEASPHOTOUPLOADFIELD.full_name = ".Cmd.OverseasPhotoUploadField"
OVERSEASPHOTOUPLOADFIELD.nested_types = {}
OVERSEASPHOTOUPLOADFIELD.enum_types = {}
OVERSEASPHOTOUPLOADFIELD.fields = {
  OVERSEASPHOTOUPLOADFIELD_NAME_FIELD,
  OVERSEASPHOTOUPLOADFIELD_VALUE_FIELD
}
OVERSEASPHOTOUPLOADFIELD.is_extendable = false
OVERSEASPHOTOUPLOADFIELD.extensions = {}
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.name = "cmd"
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.full_name = ".Cmd.OverseasPhotoUploadCmd.cmd"
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.number = 1
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.index = 0
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.label = 1
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.has_default_value = true
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.default_value = 81
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.type = 14
OVERSEASPHOTOUPLOADCMD_CMD_FIELD.cpp_type = 8
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.name = "param"
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.full_name = ".Cmd.OverseasPhotoUploadCmd.param"
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.number = 2
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.index = 1
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.label = 1
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.has_default_value = true
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.default_value = 1
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.enum_type = OVERSEASSCENEPARAM
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.type = 14
OVERSEASPHOTOUPLOADCMD_PARAM_FIELD.cpp_type = 8
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.name = "type"
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.full_name = ".Cmd.OverseasPhotoUploadCmd.type"
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.number = 3
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.index = 2
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.label = 2
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.has_default_value = false
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.default_value = nil
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.enum_type = OVERSEASPHOTOGALLERYTYPE
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.type = 14
OVERSEASPHOTOUPLOADCMD_TYPE_FIELD.cpp_type = 8
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.name = "photoId"
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.full_name = ".Cmd.OverseasPhotoUploadCmd.photoId"
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.number = 4
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.index = 3
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.label = 2
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.has_default_value = false
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.default_value = 0
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.type = 13
OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD.cpp_type = 3
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.name = "fields"
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.full_name = ".Cmd.OverseasPhotoUploadCmd.fields"
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.number = 6
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.index = 4
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.label = 3
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.has_default_value = false
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.default_value = {}
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.message_type = OVERSEASPHOTOUPLOADFIELD
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.type = 11
OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD.cpp_type = 10
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.name = "path"
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.full_name = ".Cmd.OverseasPhotoUploadCmd.path"
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.number = 5
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.index = 5
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.label = 1
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.has_default_value = false
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.default_value = ""
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.type = 9
OVERSEASPHOTOUPLOADCMD_PATH_FIELD.cpp_type = 9
OVERSEASPHOTOUPLOADCMD.name = "OverseasPhotoUploadCmd"
OVERSEASPHOTOUPLOADCMD.full_name = ".Cmd.OverseasPhotoUploadCmd"
OVERSEASPHOTOUPLOADCMD.nested_types = {}
OVERSEASPHOTOUPLOADCMD.enum_types = {}
OVERSEASPHOTOUPLOADCMD.fields = {
  OVERSEASPHOTOUPLOADCMD_CMD_FIELD,
  OVERSEASPHOTOUPLOADCMD_PARAM_FIELD,
  OVERSEASPHOTOUPLOADCMD_TYPE_FIELD,
  OVERSEASPHOTOUPLOADCMD_PHOTOID_FIELD,
  OVERSEASPHOTOUPLOADCMD_FIELDS_FIELD,
  OVERSEASPHOTOUPLOADCMD_PATH_FIELD
}
OVERSEASPHOTOUPLOADCMD.is_extendable = false
OVERSEASPHOTOUPLOADCMD.extensions = {}
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.name = "cmd"
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.full_name = ".Cmd.OverseasPhotoPathPrefixCmd.cmd"
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.number = 1
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.index = 0
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.label = 1
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.has_default_value = true
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.default_value = 81
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.type = 14
OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD.cpp_type = 8
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.name = "param"
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.full_name = ".Cmd.OverseasPhotoPathPrefixCmd.param"
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.number = 2
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.index = 1
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.label = 1
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.has_default_value = true
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.default_value = 2
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.enum_type = OVERSEASSCENEPARAM
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.type = 14
OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD.cpp_type = 8
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.name = "type"
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.full_name = ".Cmd.OverseasPhotoPathPrefixCmd.type"
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.number = 3
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.index = 2
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.label = 2
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.has_default_value = false
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.default_value = nil
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.enum_type = OVERSEASPHOTOGALLERYTYPE
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.type = 14
OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD.cpp_type = 8
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.name = "path"
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.full_name = ".Cmd.OverseasPhotoPathPrefixCmd.path"
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.number = 4
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.index = 3
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.label = 1
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.has_default_value = false
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.default_value = ""
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.type = 9
OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD.cpp_type = 9
OVERSEASPHOTOPATHPREFIXCMD.name = "OverseasPhotoPathPrefixCmd"
OVERSEASPHOTOPATHPREFIXCMD.full_name = ".Cmd.OverseasPhotoPathPrefixCmd"
OVERSEASPHOTOPATHPREFIXCMD.nested_types = {}
OVERSEASPHOTOPATHPREFIXCMD.enum_types = {}
OVERSEASPHOTOPATHPREFIXCMD.fields = {
  OVERSEASPHOTOPATHPREFIXCMD_CMD_FIELD,
  OVERSEASPHOTOPATHPREFIXCMD_PARAM_FIELD,
  OVERSEASPHOTOPATHPREFIXCMD_TYPE_FIELD,
  OVERSEASPHOTOPATHPREFIXCMD_PATH_FIELD
}
OVERSEASPHOTOPATHPREFIXCMD.is_extendable = false
OVERSEASPHOTOPATHPREFIXCMD.extensions = {}
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.name = "cmd"
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.full_name = ".Cmd.TaiwanFbShareProgressCmd.cmd"
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.number = 1
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.index = 0
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.label = 1
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.has_default_value = true
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.default_value = 80
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.type = 14
TAIWANFBSHAREPROGRESSCMD_CMD_FIELD.cpp_type = 8
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.name = "param"
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.full_name = ".Cmd.TaiwanFbShareProgressCmd.param"
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.number = 2
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.index = 1
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.label = 1
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.has_default_value = true
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.default_value = 10
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.enum_type = OVERSEASTAIWANPARAM
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.type = 14
TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD.cpp_type = 8
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.name = "canShare"
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.full_name = ".Cmd.TaiwanFbShareProgressCmd.canShare"
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.number = 3
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.index = 2
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.label = 1
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.has_default_value = false
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.default_value = false
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.type = 8
TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD.cpp_type = 7
TAIWANFBSHAREPROGRESSCMD.name = "TaiwanFbShareProgressCmd"
TAIWANFBSHAREPROGRESSCMD.full_name = ".Cmd.TaiwanFbShareProgressCmd"
TAIWANFBSHAREPROGRESSCMD.nested_types = {}
TAIWANFBSHAREPROGRESSCMD.enum_types = {}
TAIWANFBSHAREPROGRESSCMD.fields = {
  TAIWANFBSHAREPROGRESSCMD_CMD_FIELD,
  TAIWANFBSHAREPROGRESSCMD_PARAM_FIELD,
  TAIWANFBSHAREPROGRESSCMD_CANSHARE_FIELD
}
TAIWANFBSHAREPROGRESSCMD.is_extendable = false
TAIWANFBSHAREPROGRESSCMD.extensions = {}
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.name = "cmd"
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.full_name = ".Cmd.TaiwanFbShareRedeemCmd.cmd"
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.number = 1
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.index = 0
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.label = 1
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.has_default_value = true
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.default_value = 80
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.type = 14
TAIWANFBSHAREREDEEMCMD_CMD_FIELD.cpp_type = 8
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.name = "param"
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.full_name = ".Cmd.TaiwanFbShareRedeemCmd.param"
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.number = 2
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.index = 1
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.label = 1
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.has_default_value = true
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.default_value = 11
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.enum_type = OVERSEASTAIWANPARAM
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.type = 14
TAIWANFBSHAREREDEEMCMD_PARAM_FIELD.cpp_type = 8
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.name = "err"
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.full_name = ".Cmd.TaiwanFbShareRedeemCmd.err"
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.number = 3
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.index = 2
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.label = 1
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.has_default_value = true
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.default_value = 0
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.enum_type = TAIWANFACEBOOKSHAREREDEEMERROR
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.type = 14
TAIWANFBSHAREREDEEMCMD_ERR_FIELD.cpp_type = 8
TAIWANFBSHAREREDEEMCMD.name = "TaiwanFbShareRedeemCmd"
TAIWANFBSHAREREDEEMCMD.full_name = ".Cmd.TaiwanFbShareRedeemCmd"
TAIWANFBSHAREREDEEMCMD.nested_types = {}
TAIWANFBSHAREREDEEMCMD.enum_types = {}
TAIWANFBSHAREREDEEMCMD.fields = {
  TAIWANFBSHAREREDEEMCMD_CMD_FIELD,
  TAIWANFBSHAREREDEEMCMD_PARAM_FIELD,
  TAIWANFBSHAREREDEEMCMD_ERR_FIELD
}
TAIWANFBSHAREREDEEMCMD.is_extendable = false
TAIWANFBSHAREREDEEMCMD.extensions = {}
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.name = "cmd"
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.full_name = ".Cmd.OverseasChargeLimitGetChargeCmd.cmd"
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.number = 1
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.index = 0
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.label = 1
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.has_default_value = true
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.default_value = 81
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.type = 14
OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD.cpp_type = 8
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.name = "param"
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.full_name = ".Cmd.OverseasChargeLimitGetChargeCmd.param"
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.number = 2
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.index = 1
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.label = 1
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.has_default_value = true
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.default_value = 11
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.enum_type = OVERSEASSCENEPARAM
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.type = 14
OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD.cpp_type = 8
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.name = "charge"
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.full_name = ".Cmd.OverseasChargeLimitGetChargeCmd.charge"
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.number = 3
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.index = 2
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.label = 1
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.has_default_value = false
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.default_value = 0
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.type = 13
OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD.cpp_type = 3
OVERSEASCHARGELIMITGETCHARGECMD.name = "OverseasChargeLimitGetChargeCmd"
OVERSEASCHARGELIMITGETCHARGECMD.full_name = ".Cmd.OverseasChargeLimitGetChargeCmd"
OVERSEASCHARGELIMITGETCHARGECMD.nested_types = {}
OVERSEASCHARGELIMITGETCHARGECMD.enum_types = {}
OVERSEASCHARGELIMITGETCHARGECMD.fields = {
  OVERSEASCHARGELIMITGETCHARGECMD_CMD_FIELD,
  OVERSEASCHARGELIMITGETCHARGECMD_PARAM_FIELD,
  OVERSEASCHARGELIMITGETCHARGECMD_CHARGE_FIELD
}
OVERSEASCHARGELIMITGETCHARGECMD.is_extendable = false
OVERSEASCHARGELIMITGETCHARGECMD.extensions = {}
OVERSEASGOEITEMADDCMD_CMD_FIELD.name = "cmd"
OVERSEASGOEITEMADDCMD_CMD_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.cmd"
OVERSEASGOEITEMADDCMD_CMD_FIELD.number = 1
OVERSEASGOEITEMADDCMD_CMD_FIELD.index = 0
OVERSEASGOEITEMADDCMD_CMD_FIELD.label = 1
OVERSEASGOEITEMADDCMD_CMD_FIELD.has_default_value = true
OVERSEASGOEITEMADDCMD_CMD_FIELD.default_value = 81
OVERSEASGOEITEMADDCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OVERSEASGOEITEMADDCMD_CMD_FIELD.type = 14
OVERSEASGOEITEMADDCMD_CMD_FIELD.cpp_type = 8
OVERSEASGOEITEMADDCMD_PARAM_FIELD.name = "param"
OVERSEASGOEITEMADDCMD_PARAM_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.param"
OVERSEASGOEITEMADDCMD_PARAM_FIELD.number = 2
OVERSEASGOEITEMADDCMD_PARAM_FIELD.index = 1
OVERSEASGOEITEMADDCMD_PARAM_FIELD.label = 1
OVERSEASGOEITEMADDCMD_PARAM_FIELD.has_default_value = true
OVERSEASGOEITEMADDCMD_PARAM_FIELD.default_value = 21
OVERSEASGOEITEMADDCMD_PARAM_FIELD.enum_type = OVERSEASSCENEPARAM
OVERSEASGOEITEMADDCMD_PARAM_FIELD.type = 14
OVERSEASGOEITEMADDCMD_PARAM_FIELD.cpp_type = 8
OVERSEASGOEITEMADDCMD_UID_FIELD.name = "uid"
OVERSEASGOEITEMADDCMD_UID_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.uid"
OVERSEASGOEITEMADDCMD_UID_FIELD.number = 3
OVERSEASGOEITEMADDCMD_UID_FIELD.index = 2
OVERSEASGOEITEMADDCMD_UID_FIELD.label = 1
OVERSEASGOEITEMADDCMD_UID_FIELD.has_default_value = false
OVERSEASGOEITEMADDCMD_UID_FIELD.default_value = ""
OVERSEASGOEITEMADDCMD_UID_FIELD.type = 9
OVERSEASGOEITEMADDCMD_UID_FIELD.cpp_type = 9
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.name = "content"
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.content"
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.number = 4
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.index = 3
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.label = 1
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.has_default_value = true
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.default_value = "ROM"
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.type = 9
OVERSEASGOEITEMADDCMD_CONTENT_FIELD.cpp_type = 9
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.name = "platform"
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.platform"
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.number = 5
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.index = 4
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.label = 1
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.has_default_value = true
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.default_value = 0
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.type = 13
OVERSEASGOEITEMADDCMD_PLATFORM_FIELD.cpp_type = 3
OVERSEASGOEITEMADDCMD_PID_FIELD.name = "pid"
OVERSEASGOEITEMADDCMD_PID_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.pid"
OVERSEASGOEITEMADDCMD_PID_FIELD.number = 6
OVERSEASGOEITEMADDCMD_PID_FIELD.index = 5
OVERSEASGOEITEMADDCMD_PID_FIELD.label = 1
OVERSEASGOEITEMADDCMD_PID_FIELD.has_default_value = false
OVERSEASGOEITEMADDCMD_PID_FIELD.default_value = 0
OVERSEASGOEITEMADDCMD_PID_FIELD.type = 13
OVERSEASGOEITEMADDCMD_PID_FIELD.cpp_type = 3
OVERSEASGOEITEMADDCMD_NUM_FIELD.name = "num"
OVERSEASGOEITEMADDCMD_NUM_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.num"
OVERSEASGOEITEMADDCMD_NUM_FIELD.number = 7
OVERSEASGOEITEMADDCMD_NUM_FIELD.index = 6
OVERSEASGOEITEMADDCMD_NUM_FIELD.label = 1
OVERSEASGOEITEMADDCMD_NUM_FIELD.has_default_value = false
OVERSEASGOEITEMADDCMD_NUM_FIELD.default_value = 0
OVERSEASGOEITEMADDCMD_NUM_FIELD.type = 13
OVERSEASGOEITEMADDCMD_NUM_FIELD.cpp_type = 3
OVERSEASGOEITEMADDCMD_AMT_FIELD.name = "amt"
OVERSEASGOEITEMADDCMD_AMT_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.amt"
OVERSEASGOEITEMADDCMD_AMT_FIELD.number = 8
OVERSEASGOEITEMADDCMD_AMT_FIELD.index = 7
OVERSEASGOEITEMADDCMD_AMT_FIELD.label = 1
OVERSEASGOEITEMADDCMD_AMT_FIELD.has_default_value = true
OVERSEASGOEITEMADDCMD_AMT_FIELD.default_value = 0
OVERSEASGOEITEMADDCMD_AMT_FIELD.type = 13
OVERSEASGOEITEMADDCMD_AMT_FIELD.cpp_type = 3
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.name = "ptype"
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.ptype"
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.number = 9
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.index = 8
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.label = 1
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.has_default_value = false
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.default_value = 0
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.type = 13
OVERSEASGOEITEMADDCMD_PTYPE_FIELD.cpp_type = 3
OVERSEASGOEITEMADDCMD_NOTE_FIELD.name = "note"
OVERSEASGOEITEMADDCMD_NOTE_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.note"
OVERSEASGOEITEMADDCMD_NOTE_FIELD.number = 10
OVERSEASGOEITEMADDCMD_NOTE_FIELD.index = 9
OVERSEASGOEITEMADDCMD_NOTE_FIELD.label = 1
OVERSEASGOEITEMADDCMD_NOTE_FIELD.has_default_value = false
OVERSEASGOEITEMADDCMD_NOTE_FIELD.default_value = ""
OVERSEASGOEITEMADDCMD_NOTE_FIELD.type = 9
OVERSEASGOEITEMADDCMD_NOTE_FIELD.cpp_type = 9
OVERSEASGOEITEMADDCMD_DATE_FIELD.name = "date"
OVERSEASGOEITEMADDCMD_DATE_FIELD.full_name = ".Cmd.OverseasGoeItemAddCmd.date"
OVERSEASGOEITEMADDCMD_DATE_FIELD.number = 11
OVERSEASGOEITEMADDCMD_DATE_FIELD.index = 10
OVERSEASGOEITEMADDCMD_DATE_FIELD.label = 1
OVERSEASGOEITEMADDCMD_DATE_FIELD.has_default_value = false
OVERSEASGOEITEMADDCMD_DATE_FIELD.default_value = 0
OVERSEASGOEITEMADDCMD_DATE_FIELD.type = 4
OVERSEASGOEITEMADDCMD_DATE_FIELD.cpp_type = 4
OVERSEASGOEITEMADDCMD.name = "OverseasGoeItemAddCmd"
OVERSEASGOEITEMADDCMD.full_name = ".Cmd.OverseasGoeItemAddCmd"
OVERSEASGOEITEMADDCMD.nested_types = {}
OVERSEASGOEITEMADDCMD.enum_types = {}
OVERSEASGOEITEMADDCMD.fields = {
  OVERSEASGOEITEMADDCMD_CMD_FIELD,
  OVERSEASGOEITEMADDCMD_PARAM_FIELD,
  OVERSEASGOEITEMADDCMD_UID_FIELD,
  OVERSEASGOEITEMADDCMD_CONTENT_FIELD,
  OVERSEASGOEITEMADDCMD_PLATFORM_FIELD,
  OVERSEASGOEITEMADDCMD_PID_FIELD,
  OVERSEASGOEITEMADDCMD_NUM_FIELD,
  OVERSEASGOEITEMADDCMD_AMT_FIELD,
  OVERSEASGOEITEMADDCMD_PTYPE_FIELD,
  OVERSEASGOEITEMADDCMD_NOTE_FIELD,
  OVERSEASGOEITEMADDCMD_DATE_FIELD
}
OVERSEASGOEITEMADDCMD.is_extendable = false
OVERSEASGOEITEMADDCMD.extensions = {}
OVERSEASGOEITEMUSECMD_CMD_FIELD.name = "cmd"
OVERSEASGOEITEMUSECMD_CMD_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.cmd"
OVERSEASGOEITEMUSECMD_CMD_FIELD.number = 1
OVERSEASGOEITEMUSECMD_CMD_FIELD.index = 0
OVERSEASGOEITEMUSECMD_CMD_FIELD.label = 1
OVERSEASGOEITEMUSECMD_CMD_FIELD.has_default_value = true
OVERSEASGOEITEMUSECMD_CMD_FIELD.default_value = 81
OVERSEASGOEITEMUSECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OVERSEASGOEITEMUSECMD_CMD_FIELD.type = 14
OVERSEASGOEITEMUSECMD_CMD_FIELD.cpp_type = 8
OVERSEASGOEITEMUSECMD_PARAM_FIELD.name = "param"
OVERSEASGOEITEMUSECMD_PARAM_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.param"
OVERSEASGOEITEMUSECMD_PARAM_FIELD.number = 2
OVERSEASGOEITEMUSECMD_PARAM_FIELD.index = 1
OVERSEASGOEITEMUSECMD_PARAM_FIELD.label = 1
OVERSEASGOEITEMUSECMD_PARAM_FIELD.has_default_value = true
OVERSEASGOEITEMUSECMD_PARAM_FIELD.default_value = 22
OVERSEASGOEITEMUSECMD_PARAM_FIELD.enum_type = OVERSEASSCENEPARAM
OVERSEASGOEITEMUSECMD_PARAM_FIELD.type = 14
OVERSEASGOEITEMUSECMD_PARAM_FIELD.cpp_type = 8
OVERSEASGOEITEMUSECMD_UID_FIELD.name = "uid"
OVERSEASGOEITEMUSECMD_UID_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.uid"
OVERSEASGOEITEMUSECMD_UID_FIELD.number = 3
OVERSEASGOEITEMUSECMD_UID_FIELD.index = 2
OVERSEASGOEITEMUSECMD_UID_FIELD.label = 1
OVERSEASGOEITEMUSECMD_UID_FIELD.has_default_value = false
OVERSEASGOEITEMUSECMD_UID_FIELD.default_value = ""
OVERSEASGOEITEMUSECMD_UID_FIELD.type = 9
OVERSEASGOEITEMUSECMD_UID_FIELD.cpp_type = 9
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.name = "content"
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.content"
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.number = 4
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.index = 3
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.label = 1
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.has_default_value = true
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.default_value = "ROM"
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.type = 9
OVERSEASGOEITEMUSECMD_CONTENT_FIELD.cpp_type = 9
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.name = "platform"
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.platform"
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.number = 5
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.index = 4
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.label = 1
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.has_default_value = true
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.default_value = 0
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.type = 13
OVERSEASGOEITEMUSECMD_PLATFORM_FIELD.cpp_type = 3
OVERSEASGOEITEMUSECMD_PID_FIELD.name = "pid"
OVERSEASGOEITEMUSECMD_PID_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.pid"
OVERSEASGOEITEMUSECMD_PID_FIELD.number = 6
OVERSEASGOEITEMUSECMD_PID_FIELD.index = 5
OVERSEASGOEITEMUSECMD_PID_FIELD.label = 1
OVERSEASGOEITEMUSECMD_PID_FIELD.has_default_value = false
OVERSEASGOEITEMUSECMD_PID_FIELD.default_value = 0
OVERSEASGOEITEMUSECMD_PID_FIELD.type = 13
OVERSEASGOEITEMUSECMD_PID_FIELD.cpp_type = 3
OVERSEASGOEITEMUSECMD_NUM_FIELD.name = "num"
OVERSEASGOEITEMUSECMD_NUM_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.num"
OVERSEASGOEITEMUSECMD_NUM_FIELD.number = 7
OVERSEASGOEITEMUSECMD_NUM_FIELD.index = 6
OVERSEASGOEITEMUSECMD_NUM_FIELD.label = 1
OVERSEASGOEITEMUSECMD_NUM_FIELD.has_default_value = false
OVERSEASGOEITEMUSECMD_NUM_FIELD.default_value = 0
OVERSEASGOEITEMUSECMD_NUM_FIELD.type = 13
OVERSEASGOEITEMUSECMD_NUM_FIELD.cpp_type = 3
OVERSEASGOEITEMUSECMD_NUMF_FIELD.name = "numf"
OVERSEASGOEITEMUSECMD_NUMF_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.numf"
OVERSEASGOEITEMUSECMD_NUMF_FIELD.number = 8
OVERSEASGOEITEMUSECMD_NUMF_FIELD.index = 7
OVERSEASGOEITEMUSECMD_NUMF_FIELD.label = 1
OVERSEASGOEITEMUSECMD_NUMF_FIELD.has_default_value = false
OVERSEASGOEITEMUSECMD_NUMF_FIELD.default_value = 0
OVERSEASGOEITEMUSECMD_NUMF_FIELD.type = 13
OVERSEASGOEITEMUSECMD_NUMF_FIELD.cpp_type = 3
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.name = "utype"
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.utype"
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.number = 9
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.index = 8
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.label = 1
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.has_default_value = true
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.default_value = 0
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.type = 13
OVERSEASGOEITEMUSECMD_UTYPE_FIELD.cpp_type = 3
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.name = "acquiree"
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.acquiree"
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.number = 10
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.index = 9
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.label = 1
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.has_default_value = false
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.default_value = ""
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.type = 9
OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD.cpp_type = 9
OVERSEASGOEITEMUSECMD_NOTE_FIELD.name = "note"
OVERSEASGOEITEMUSECMD_NOTE_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.note"
OVERSEASGOEITEMUSECMD_NOTE_FIELD.number = 11
OVERSEASGOEITEMUSECMD_NOTE_FIELD.index = 10
OVERSEASGOEITEMUSECMD_NOTE_FIELD.label = 1
OVERSEASGOEITEMUSECMD_NOTE_FIELD.has_default_value = false
OVERSEASGOEITEMUSECMD_NOTE_FIELD.default_value = ""
OVERSEASGOEITEMUSECMD_NOTE_FIELD.type = 9
OVERSEASGOEITEMUSECMD_NOTE_FIELD.cpp_type = 9
OVERSEASGOEITEMUSECMD_DATE_FIELD.name = "date"
OVERSEASGOEITEMUSECMD_DATE_FIELD.full_name = ".Cmd.OverseasGoeItemUseCmd.date"
OVERSEASGOEITEMUSECMD_DATE_FIELD.number = 12
OVERSEASGOEITEMUSECMD_DATE_FIELD.index = 11
OVERSEASGOEITEMUSECMD_DATE_FIELD.label = 1
OVERSEASGOEITEMUSECMD_DATE_FIELD.has_default_value = false
OVERSEASGOEITEMUSECMD_DATE_FIELD.default_value = 0
OVERSEASGOEITEMUSECMD_DATE_FIELD.type = 4
OVERSEASGOEITEMUSECMD_DATE_FIELD.cpp_type = 4
OVERSEASGOEITEMUSECMD.name = "OverseasGoeItemUseCmd"
OVERSEASGOEITEMUSECMD.full_name = ".Cmd.OverseasGoeItemUseCmd"
OVERSEASGOEITEMUSECMD.nested_types = {}
OVERSEASGOEITEMUSECMD.enum_types = {}
OVERSEASGOEITEMUSECMD.fields = {
  OVERSEASGOEITEMUSECMD_CMD_FIELD,
  OVERSEASGOEITEMUSECMD_PARAM_FIELD,
  OVERSEASGOEITEMUSECMD_UID_FIELD,
  OVERSEASGOEITEMUSECMD_CONTENT_FIELD,
  OVERSEASGOEITEMUSECMD_PLATFORM_FIELD,
  OVERSEASGOEITEMUSECMD_PID_FIELD,
  OVERSEASGOEITEMUSECMD_NUM_FIELD,
  OVERSEASGOEITEMUSECMD_NUMF_FIELD,
  OVERSEASGOEITEMUSECMD_UTYPE_FIELD,
  OVERSEASGOEITEMUSECMD_ACQUIREE_FIELD,
  OVERSEASGOEITEMUSECMD_NOTE_FIELD,
  OVERSEASGOEITEMUSECMD_DATE_FIELD
}
OVERSEASGOEITEMUSECMD.is_extendable = false
OVERSEASGOEITEMUSECMD.extensions = {}
ENUM_GALLERY_TYPE_GUILDICON = 3
ENUM_GALLERY_TYPE_MAX = 5
ENUM_GALLERY_TYPE_MIN = 0
ENUM_GALLERY_TYPE_PHOTO = 2
ENUM_GALLERY_TYPE_SCENERY = 1
ENUM_GALLERY_TYPE_WEDDING = 4
ENUM_GOE_ITEM_ADD_TYPE_LOTTERY = 1
ENUM_GOE_ITEM_USE_TYPE_LOTTERY = 1
OVERSEAS_CHARGE_LIMIT_GET_CHARGE_CMD = 11
OVERSEAS_GOE_ITEM_ADD_CMD = 21
OVERSEAS_GOE_ITEM_USE_CMD = 22
OVERSEAS_PHOTO_PREFIX_CMD = 2
OVERSEAS_PHOTO_UPLOAD_CMD = 1
OverseasChargeLimitGetChargeCmd = protobuf.Message(OVERSEASCHARGELIMITGETCHARGECMD)
OverseasGoeItemAddCmd = protobuf.Message(OVERSEASGOEITEMADDCMD)
OverseasGoeItemUseCmd = protobuf.Message(OVERSEASGOEITEMUSECMD)
OverseasPhotoPathPrefixCmd = protobuf.Message(OVERSEASPHOTOPATHPREFIXCMD)
OverseasPhotoUploadCmd = protobuf.Message(OVERSEASPHOTOUPLOADCMD)
OverseasPhotoUploadField = protobuf.Message(OVERSEASPHOTOUPLOADFIELD)
TAIWAN_FACEBOOK_LIKE_TOTAL_PROGRESS_CMD = 1
TAIWAN_FACEBOOK_LIKE_USER_REDEEM_CMD = 2
TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NOT_UNLOCKED = 1
TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_NO_ERROR = 0
TAIWAN_FACEBOOK_LIKE_USER_REDEEM_ERROR_USER_REDEEMED = 2
TAIWAN_FACEBOOK_SHARE_PROGRESS_CMD = 10
TAIWAN_FACEBOOK_SHARE_REDEEM_CMD = 11
TAIWAN_FACEBOOK_SHARE_REDEEM_ERROR_SHARED = 1
TAIWAN_FACEBOOK_SHARE_REDEEM_SUCCESS = 0
TaiwanFbLikePrizeItem = protobuf.Message(TAIWANFBLIKEPRIZEITEM)
TaiwanFbLikeProgressCmd = protobuf.Message(TAIWANFBLIKEPROGRESSCMD)
TaiwanFbLikeUserRedeemCmd = protobuf.Message(TAIWANFBLIKEUSERREDEEMCMD)
TaiwanFbShareProgressCmd = protobuf.Message(TAIWANFBSHAREPROGRESSCMD)
TaiwanFbShareRedeemCmd = protobuf.Message(TAIWANFBSHAREREDEEMCMD)
