local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
module("PuzzleCmd_pb")
PUZZLEPARAM = protobuf.EnumDescriptor()
PUZZLEPARAM_PUZZLEPARAM_QUERYACTLIST_ENUM = protobuf.EnumValueDescriptor()
PUZZLEPARAM_PUZZLEPARAM_ITEMNTF_ENUM = protobuf.EnumValueDescriptor()
PUZZLEPARAM_PUZZLEPARAM_ACTIVIEPUZZLE_ENUM = protobuf.EnumValueDescriptor()
EPUZZLESTATE = protobuf.EnumDescriptor()
EPUZZLESTATE_EPUZZLESTATE_MIN_ENUM = protobuf.EnumValueDescriptor()
EPUZZLESTATE_EPUZZLESTATE_UNACTIVE_ENUM = protobuf.EnumValueDescriptor()
EPUZZLESTATE_EPUZZLESTATE_CANACTIVE_ENUM = protobuf.EnumValueDescriptor()
EPUZZLESTATE_EPUZZLESTATE_ACTIVE_ENUM = protobuf.EnumValueDescriptor()
EPUZZLESTATE_EPUZZLESTATE_MAX_ENUM = protobuf.EnumValueDescriptor()
PUZZLEITEM = protobuf.Descriptor()
PUZZLEITEM_ACTID_FIELD = protobuf.FieldDescriptor()
PUZZLEITEM_PUZZLED_FIELD = protobuf.FieldDescriptor()
PUZZLEITEM_PROCESS_FIELD = protobuf.FieldDescriptor()
PUZZLEITEM_STATE_FIELD = protobuf.FieldDescriptor()
ACTITEM = protobuf.Descriptor()
ACTITEM_ACTID_FIELD = protobuf.FieldDescriptor()
ACTITEM_ITEMS_FIELD = protobuf.FieldDescriptor()
QUERYACTPUZZLECMD = protobuf.Descriptor()
QUERYACTPUZZLECMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYACTPUZZLECMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYACTPUZZLECMD_ACTITEM_FIELD = protobuf.FieldDescriptor()
PUZZLEITEMNTF = protobuf.Descriptor()
PUZZLEITEMNTF_CMD_FIELD = protobuf.FieldDescriptor()
PUZZLEITEMNTF_PARAM_FIELD = protobuf.FieldDescriptor()
PUZZLEITEMNTF_ITEMS_FIELD = protobuf.FieldDescriptor()
ACTIVEPUZZLECMD = protobuf.Descriptor()
ACTIVEPUZZLECMD_CMD_FIELD = protobuf.FieldDescriptor()
ACTIVEPUZZLECMD_PARAM_FIELD = protobuf.FieldDescriptor()
ACTIVEPUZZLECMD_ACTID_FIELD = protobuf.FieldDescriptor()
ACTIVEPUZZLECMD_PUZZLEID_FIELD = protobuf.FieldDescriptor()
PUZZLEPARAM_PUZZLEPARAM_QUERYACTLIST_ENUM.name = "PUZZLEPARAM_QUERYACTLIST"
PUZZLEPARAM_PUZZLEPARAM_QUERYACTLIST_ENUM.index = 0
PUZZLEPARAM_PUZZLEPARAM_QUERYACTLIST_ENUM.number = 1
PUZZLEPARAM_PUZZLEPARAM_ITEMNTF_ENUM.name = "PUZZLEPARAM_ITEMNTF"
PUZZLEPARAM_PUZZLEPARAM_ITEMNTF_ENUM.index = 1
PUZZLEPARAM_PUZZLEPARAM_ITEMNTF_ENUM.number = 3
PUZZLEPARAM_PUZZLEPARAM_ACTIVIEPUZZLE_ENUM.name = "PUZZLEPARAM_ACTIVIEPUZZLE"
PUZZLEPARAM_PUZZLEPARAM_ACTIVIEPUZZLE_ENUM.index = 2
PUZZLEPARAM_PUZZLEPARAM_ACTIVIEPUZZLE_ENUM.number = 4
PUZZLEPARAM.name = "PuzzleParam"
PUZZLEPARAM.full_name = ".Cmd.PuzzleParam"
PUZZLEPARAM.values = {
  PUZZLEPARAM_PUZZLEPARAM_QUERYACTLIST_ENUM,
  PUZZLEPARAM_PUZZLEPARAM_ITEMNTF_ENUM,
  PUZZLEPARAM_PUZZLEPARAM_ACTIVIEPUZZLE_ENUM
}
EPUZZLESTATE_EPUZZLESTATE_MIN_ENUM.name = "EPUZZLESTATE_MIN"
EPUZZLESTATE_EPUZZLESTATE_MIN_ENUM.index = 0
EPUZZLESTATE_EPUZZLESTATE_MIN_ENUM.number = 0
EPUZZLESTATE_EPUZZLESTATE_UNACTIVE_ENUM.name = "EPUZZLESTATE_UNACTIVE"
EPUZZLESTATE_EPUZZLESTATE_UNACTIVE_ENUM.index = 1
EPUZZLESTATE_EPUZZLESTATE_UNACTIVE_ENUM.number = 1
EPUZZLESTATE_EPUZZLESTATE_CANACTIVE_ENUM.name = "EPUZZLESTATE_CANACTIVE"
EPUZZLESTATE_EPUZZLESTATE_CANACTIVE_ENUM.index = 2
EPUZZLESTATE_EPUZZLESTATE_CANACTIVE_ENUM.number = 2
EPUZZLESTATE_EPUZZLESTATE_ACTIVE_ENUM.name = "EPUZZLESTATE_ACTIVE"
EPUZZLESTATE_EPUZZLESTATE_ACTIVE_ENUM.index = 3
EPUZZLESTATE_EPUZZLESTATE_ACTIVE_ENUM.number = 3
EPUZZLESTATE_EPUZZLESTATE_MAX_ENUM.name = "EPUZZLESTATE_MAX"
EPUZZLESTATE_EPUZZLESTATE_MAX_ENUM.index = 4
EPUZZLESTATE_EPUZZLESTATE_MAX_ENUM.number = 4
EPUZZLESTATE.name = "EPuzzleState"
EPUZZLESTATE.full_name = ".Cmd.EPuzzleState"
EPUZZLESTATE.values = {
  EPUZZLESTATE_EPUZZLESTATE_MIN_ENUM,
  EPUZZLESTATE_EPUZZLESTATE_UNACTIVE_ENUM,
  EPUZZLESTATE_EPUZZLESTATE_CANACTIVE_ENUM,
  EPUZZLESTATE_EPUZZLESTATE_ACTIVE_ENUM,
  EPUZZLESTATE_EPUZZLESTATE_MAX_ENUM
}
PUZZLEITEM_ACTID_FIELD.name = "actid"
PUZZLEITEM_ACTID_FIELD.full_name = ".Cmd.PuzzleItem.actid"
PUZZLEITEM_ACTID_FIELD.number = 1
PUZZLEITEM_ACTID_FIELD.index = 0
PUZZLEITEM_ACTID_FIELD.label = 1
PUZZLEITEM_ACTID_FIELD.has_default_value = true
PUZZLEITEM_ACTID_FIELD.default_value = 0
PUZZLEITEM_ACTID_FIELD.type = 13
PUZZLEITEM_ACTID_FIELD.cpp_type = 3
PUZZLEITEM_PUZZLED_FIELD.name = "puzzled"
PUZZLEITEM_PUZZLED_FIELD.full_name = ".Cmd.PuzzleItem.puzzled"
PUZZLEITEM_PUZZLED_FIELD.number = 2
PUZZLEITEM_PUZZLED_FIELD.index = 1
PUZZLEITEM_PUZZLED_FIELD.label = 1
PUZZLEITEM_PUZZLED_FIELD.has_default_value = true
PUZZLEITEM_PUZZLED_FIELD.default_value = 0
PUZZLEITEM_PUZZLED_FIELD.type = 13
PUZZLEITEM_PUZZLED_FIELD.cpp_type = 3
PUZZLEITEM_PROCESS_FIELD.name = "process"
PUZZLEITEM_PROCESS_FIELD.full_name = ".Cmd.PuzzleItem.process"
PUZZLEITEM_PROCESS_FIELD.number = 3
PUZZLEITEM_PROCESS_FIELD.index = 2
PUZZLEITEM_PROCESS_FIELD.label = 1
PUZZLEITEM_PROCESS_FIELD.has_default_value = true
PUZZLEITEM_PROCESS_FIELD.default_value = 0
PUZZLEITEM_PROCESS_FIELD.type = 13
PUZZLEITEM_PROCESS_FIELD.cpp_type = 3
PUZZLEITEM_STATE_FIELD.name = "state"
PUZZLEITEM_STATE_FIELD.full_name = ".Cmd.PuzzleItem.state"
PUZZLEITEM_STATE_FIELD.number = 4
PUZZLEITEM_STATE_FIELD.index = 3
PUZZLEITEM_STATE_FIELD.label = 1
PUZZLEITEM_STATE_FIELD.has_default_value = true
PUZZLEITEM_STATE_FIELD.default_value = 0
PUZZLEITEM_STATE_FIELD.enum_type = EPUZZLESTATE
PUZZLEITEM_STATE_FIELD.type = 14
PUZZLEITEM_STATE_FIELD.cpp_type = 8
PUZZLEITEM.name = "PuzzleItem"
PUZZLEITEM.full_name = ".Cmd.PuzzleItem"
PUZZLEITEM.nested_types = {}
PUZZLEITEM.enum_types = {}
PUZZLEITEM.fields = {
  PUZZLEITEM_ACTID_FIELD,
  PUZZLEITEM_PUZZLED_FIELD,
  PUZZLEITEM_PROCESS_FIELD,
  PUZZLEITEM_STATE_FIELD
}
PUZZLEITEM.is_extendable = false
PUZZLEITEM.extensions = {}
ACTITEM_ACTID_FIELD.name = "actid"
ACTITEM_ACTID_FIELD.full_name = ".Cmd.ActItem.actid"
ACTITEM_ACTID_FIELD.number = 1
ACTITEM_ACTID_FIELD.index = 0
ACTITEM_ACTID_FIELD.label = 1
ACTITEM_ACTID_FIELD.has_default_value = true
ACTITEM_ACTID_FIELD.default_value = 0
ACTITEM_ACTID_FIELD.type = 13
ACTITEM_ACTID_FIELD.cpp_type = 3
ACTITEM_ITEMS_FIELD.name = "items"
ACTITEM_ITEMS_FIELD.full_name = ".Cmd.ActItem.items"
ACTITEM_ITEMS_FIELD.number = 2
ACTITEM_ITEMS_FIELD.index = 1
ACTITEM_ITEMS_FIELD.label = 3
ACTITEM_ITEMS_FIELD.has_default_value = false
ACTITEM_ITEMS_FIELD.default_value = {}
ACTITEM_ITEMS_FIELD.message_type = PUZZLEITEM
ACTITEM_ITEMS_FIELD.type = 11
ACTITEM_ITEMS_FIELD.cpp_type = 10
ACTITEM.name = "ActItem"
ACTITEM.full_name = ".Cmd.ActItem"
ACTITEM.nested_types = {}
ACTITEM.enum_types = {}
ACTITEM.fields = {
  ACTITEM_ACTID_FIELD,
  ACTITEM_ITEMS_FIELD
}
ACTITEM.is_extendable = false
ACTITEM.extensions = {}
QUERYACTPUZZLECMD_CMD_FIELD.name = "cmd"
QUERYACTPUZZLECMD_CMD_FIELD.full_name = ".Cmd.QueryActPuzzleCmd.cmd"
QUERYACTPUZZLECMD_CMD_FIELD.number = 1
QUERYACTPUZZLECMD_CMD_FIELD.index = 0
QUERYACTPUZZLECMD_CMD_FIELD.label = 1
QUERYACTPUZZLECMD_CMD_FIELD.has_default_value = true
QUERYACTPUZZLECMD_CMD_FIELD.default_value = 68
QUERYACTPUZZLECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYACTPUZZLECMD_CMD_FIELD.type = 14
QUERYACTPUZZLECMD_CMD_FIELD.cpp_type = 8
QUERYACTPUZZLECMD_PARAM_FIELD.name = "param"
QUERYACTPUZZLECMD_PARAM_FIELD.full_name = ".Cmd.QueryActPuzzleCmd.param"
QUERYACTPUZZLECMD_PARAM_FIELD.number = 2
QUERYACTPUZZLECMD_PARAM_FIELD.index = 1
QUERYACTPUZZLECMD_PARAM_FIELD.label = 1
QUERYACTPUZZLECMD_PARAM_FIELD.has_default_value = true
QUERYACTPUZZLECMD_PARAM_FIELD.default_value = 1
QUERYACTPUZZLECMD_PARAM_FIELD.enum_type = PUZZLEPARAM
QUERYACTPUZZLECMD_PARAM_FIELD.type = 14
QUERYACTPUZZLECMD_PARAM_FIELD.cpp_type = 8
QUERYACTPUZZLECMD_ACTITEM_FIELD.name = "actitem"
QUERYACTPUZZLECMD_ACTITEM_FIELD.full_name = ".Cmd.QueryActPuzzleCmd.actitem"
QUERYACTPUZZLECMD_ACTITEM_FIELD.number = 3
QUERYACTPUZZLECMD_ACTITEM_FIELD.index = 2
QUERYACTPUZZLECMD_ACTITEM_FIELD.label = 3
QUERYACTPUZZLECMD_ACTITEM_FIELD.has_default_value = false
QUERYACTPUZZLECMD_ACTITEM_FIELD.default_value = {}
QUERYACTPUZZLECMD_ACTITEM_FIELD.message_type = ACTITEM
QUERYACTPUZZLECMD_ACTITEM_FIELD.type = 11
QUERYACTPUZZLECMD_ACTITEM_FIELD.cpp_type = 10
QUERYACTPUZZLECMD.name = "QueryActPuzzleCmd"
QUERYACTPUZZLECMD.full_name = ".Cmd.QueryActPuzzleCmd"
QUERYACTPUZZLECMD.nested_types = {}
QUERYACTPUZZLECMD.enum_types = {}
QUERYACTPUZZLECMD.fields = {
  QUERYACTPUZZLECMD_CMD_FIELD,
  QUERYACTPUZZLECMD_PARAM_FIELD,
  QUERYACTPUZZLECMD_ACTITEM_FIELD
}
QUERYACTPUZZLECMD.is_extendable = false
QUERYACTPUZZLECMD.extensions = {}
PUZZLEITEMNTF_CMD_FIELD.name = "cmd"
PUZZLEITEMNTF_CMD_FIELD.full_name = ".Cmd.PuzzleItemNtf.cmd"
PUZZLEITEMNTF_CMD_FIELD.number = 1
PUZZLEITEMNTF_CMD_FIELD.index = 0
PUZZLEITEMNTF_CMD_FIELD.label = 1
PUZZLEITEMNTF_CMD_FIELD.has_default_value = true
PUZZLEITEMNTF_CMD_FIELD.default_value = 68
PUZZLEITEMNTF_CMD_FIELD.enum_type = XCMD_PB_COMMAND
PUZZLEITEMNTF_CMD_FIELD.type = 14
PUZZLEITEMNTF_CMD_FIELD.cpp_type = 8
PUZZLEITEMNTF_PARAM_FIELD.name = "param"
PUZZLEITEMNTF_PARAM_FIELD.full_name = ".Cmd.PuzzleItemNtf.param"
PUZZLEITEMNTF_PARAM_FIELD.number = 2
PUZZLEITEMNTF_PARAM_FIELD.index = 1
PUZZLEITEMNTF_PARAM_FIELD.label = 1
PUZZLEITEMNTF_PARAM_FIELD.has_default_value = true
PUZZLEITEMNTF_PARAM_FIELD.default_value = 3
PUZZLEITEMNTF_PARAM_FIELD.enum_type = PUZZLEPARAM
PUZZLEITEMNTF_PARAM_FIELD.type = 14
PUZZLEITEMNTF_PARAM_FIELD.cpp_type = 8
PUZZLEITEMNTF_ITEMS_FIELD.name = "items"
PUZZLEITEMNTF_ITEMS_FIELD.full_name = ".Cmd.PuzzleItemNtf.items"
PUZZLEITEMNTF_ITEMS_FIELD.number = 3
PUZZLEITEMNTF_ITEMS_FIELD.index = 2
PUZZLEITEMNTF_ITEMS_FIELD.label = 3
PUZZLEITEMNTF_ITEMS_FIELD.has_default_value = false
PUZZLEITEMNTF_ITEMS_FIELD.default_value = {}
PUZZLEITEMNTF_ITEMS_FIELD.message_type = PUZZLEITEM
PUZZLEITEMNTF_ITEMS_FIELD.type = 11
PUZZLEITEMNTF_ITEMS_FIELD.cpp_type = 10
PUZZLEITEMNTF.name = "PuzzleItemNtf"
PUZZLEITEMNTF.full_name = ".Cmd.PuzzleItemNtf"
PUZZLEITEMNTF.nested_types = {}
PUZZLEITEMNTF.enum_types = {}
PUZZLEITEMNTF.fields = {
  PUZZLEITEMNTF_CMD_FIELD,
  PUZZLEITEMNTF_PARAM_FIELD,
  PUZZLEITEMNTF_ITEMS_FIELD
}
PUZZLEITEMNTF.is_extendable = false
PUZZLEITEMNTF.extensions = {}
ACTIVEPUZZLECMD_CMD_FIELD.name = "cmd"
ACTIVEPUZZLECMD_CMD_FIELD.full_name = ".Cmd.ActivePuzzleCmd.cmd"
ACTIVEPUZZLECMD_CMD_FIELD.number = 1
ACTIVEPUZZLECMD_CMD_FIELD.index = 0
ACTIVEPUZZLECMD_CMD_FIELD.label = 1
ACTIVEPUZZLECMD_CMD_FIELD.has_default_value = true
ACTIVEPUZZLECMD_CMD_FIELD.default_value = 68
ACTIVEPUZZLECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
ACTIVEPUZZLECMD_CMD_FIELD.type = 14
ACTIVEPUZZLECMD_CMD_FIELD.cpp_type = 8
ACTIVEPUZZLECMD_PARAM_FIELD.name = "param"
ACTIVEPUZZLECMD_PARAM_FIELD.full_name = ".Cmd.ActivePuzzleCmd.param"
ACTIVEPUZZLECMD_PARAM_FIELD.number = 2
ACTIVEPUZZLECMD_PARAM_FIELD.index = 1
ACTIVEPUZZLECMD_PARAM_FIELD.label = 1
ACTIVEPUZZLECMD_PARAM_FIELD.has_default_value = true
ACTIVEPUZZLECMD_PARAM_FIELD.default_value = 4
ACTIVEPUZZLECMD_PARAM_FIELD.enum_type = PUZZLEPARAM
ACTIVEPUZZLECMD_PARAM_FIELD.type = 14
ACTIVEPUZZLECMD_PARAM_FIELD.cpp_type = 8
ACTIVEPUZZLECMD_ACTID_FIELD.name = "actid"
ACTIVEPUZZLECMD_ACTID_FIELD.full_name = ".Cmd.ActivePuzzleCmd.actid"
ACTIVEPUZZLECMD_ACTID_FIELD.number = 3
ACTIVEPUZZLECMD_ACTID_FIELD.index = 2
ACTIVEPUZZLECMD_ACTID_FIELD.label = 1
ACTIVEPUZZLECMD_ACTID_FIELD.has_default_value = true
ACTIVEPUZZLECMD_ACTID_FIELD.default_value = 0
ACTIVEPUZZLECMD_ACTID_FIELD.type = 13
ACTIVEPUZZLECMD_ACTID_FIELD.cpp_type = 3
ACTIVEPUZZLECMD_PUZZLEID_FIELD.name = "puzzleid"
ACTIVEPUZZLECMD_PUZZLEID_FIELD.full_name = ".Cmd.ActivePuzzleCmd.puzzleid"
ACTIVEPUZZLECMD_PUZZLEID_FIELD.number = 4
ACTIVEPUZZLECMD_PUZZLEID_FIELD.index = 3
ACTIVEPUZZLECMD_PUZZLEID_FIELD.label = 1
ACTIVEPUZZLECMD_PUZZLEID_FIELD.has_default_value = true
ACTIVEPUZZLECMD_PUZZLEID_FIELD.default_value = 0
ACTIVEPUZZLECMD_PUZZLEID_FIELD.type = 13
ACTIVEPUZZLECMD_PUZZLEID_FIELD.cpp_type = 3
ACTIVEPUZZLECMD.name = "ActivePuzzleCmd"
ACTIVEPUZZLECMD.full_name = ".Cmd.ActivePuzzleCmd"
ACTIVEPUZZLECMD.nested_types = {}
ACTIVEPUZZLECMD.enum_types = {}
ACTIVEPUZZLECMD.fields = {
  ACTIVEPUZZLECMD_CMD_FIELD,
  ACTIVEPUZZLECMD_PARAM_FIELD,
  ACTIVEPUZZLECMD_ACTID_FIELD,
  ACTIVEPUZZLECMD_PUZZLEID_FIELD
}
ACTIVEPUZZLECMD.is_extendable = false
ACTIVEPUZZLECMD.extensions = {}
ActItem = protobuf.Message(ACTITEM)
ActivePuzzleCmd = protobuf.Message(ACTIVEPUZZLECMD)
EPUZZLESTATE_ACTIVE = 3
EPUZZLESTATE_CANACTIVE = 2
EPUZZLESTATE_MAX = 4
EPUZZLESTATE_MIN = 0
EPUZZLESTATE_UNACTIVE = 1
PUZZLEPARAM_ACTIVIEPUZZLE = 4
PUZZLEPARAM_ITEMNTF = 3
PUZZLEPARAM_QUERYACTLIST = 1
PuzzleItem = protobuf.Message(PUZZLEITEM)
PuzzleItemNtf = protobuf.Message(PUZZLEITEMNTF)
QueryActPuzzleCmd = protobuf.Message(QUERYACTPUZZLECMD)
