local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
module("SessionShop_pb")
SHOPPARAM = protobuf.EnumDescriptor()
SHOPPARAM_SHOPPARAM_BUYITEM_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_QUERY_SHOP_CONFIG_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_QUICKBUY_SHOP_CONFIG_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_QUERY_SHOP_SOLD_COUNT_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_UPDATE_DATA_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_UPDATE_SHOP_CONFIG_CMD_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_UPDATE_EXCHANGESHOP_DATA_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_EXCHANGEITEM_CMD_ENUM = protobuf.EnumValueDescriptor()
SHOPPARAM_SHOPPARAM_RESET_EXCHANGESHOP_DATA_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE = protobuf.EnumDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MIN_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ONE_ONLY_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ALWAYS_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_WEEK_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_MONTH_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_WEEK_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_MONTH_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_GUILD_MATERIAL_MAXCOUNT_ENUM = protobuf.EnumValueDescriptor()
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MAX_ENUM = protobuf.EnumValueDescriptor()
ESHOPLOCKTYPE = protobuf.EnumDescriptor()
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MIN_ENUM = protobuf.EnumValueDescriptor()
ESHOPLOCKTYPE_ESHOPLOCKTYPE_QUEST_ENUM = protobuf.EnumValueDescriptor()
ESHOPLOCKTYPE_ESHOPLOCKTYPE_GUILDBUILDING_ENUM = protobuf.EnumValueDescriptor()
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MAX_ENUM = protobuf.EnumValueDescriptor()
ESHOPSOURCE = protobuf.EnumDescriptor()
ESHOPSOURCE_ESHOPSOURCE_USER_ENUM = protobuf.EnumValueDescriptor()
ESHOPSOURCE_ESHOPSOURCE_GUILD_ENUM = protobuf.EnumValueDescriptor()
ESHOPSOURCE_ESHOPSOURCE_USER_GUILD_ENUM = protobuf.EnumValueDescriptor()
EPRESENTTYPE = protobuf.EnumDescriptor()
EPRESENTTYPE_EPRESENTTYPE_NORMAL_ENUM = protobuf.EnumValueDescriptor()
EPRESENTTYPE_EPRESENTTYPE_LOCK_ENUM = protobuf.EnumValueDescriptor()
EEXCHANGESTATUSTYPE = protobuf.EnumDescriptor()
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_OK_ENUM = protobuf.EnumValueDescriptor()
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_EMPTY_ENUM = protobuf.EnumValueDescriptor()
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_DELAY_ENUM = protobuf.EnumValueDescriptor()
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_UNLOOK_ENUM = protobuf.EnumValueDescriptor()
PRESENTATION = protobuf.Descriptor()
PRESENTATION_PRESENTTYPE_FIELD = protobuf.FieldDescriptor()
PRESENTATION_MSGID_FIELD = protobuf.FieldDescriptor()
PRESENTATION_MENUID_FIELD = protobuf.FieldDescriptor()
SHOPITEM = protobuf.Descriptor()
SHOPITEM_ID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_LV_FIELD = protobuf.FieldDescriptor()
SHOPITEM_MONEYID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_MONEYCOUNT_FIELD = protobuf.FieldDescriptor()
SHOPITEM_MONEYID2_FIELD = protobuf.FieldDescriptor()
SHOPITEM_MONEYCOUNT2_FIELD = protobuf.FieldDescriptor()
SHOPITEM_STARTTIME_FIELD = protobuf.FieldDescriptor()
SHOPITEM_ENDTIME_FIELD = protobuf.FieldDescriptor()
SHOPITEM_DISCOUNT_FIELD = protobuf.FieldDescriptor()
SHOPITEM_MAXCOUNT_FIELD = protobuf.FieldDescriptor()
SHOPITEM_SHOPID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_SCREEN_FIELD = protobuf.FieldDescriptor()
SHOPITEM_ITEMID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_SKILLID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_HAIRCOLORID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_NUM_FIELD = protobuf.FieldDescriptor()
SHOPITEM_MENUID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_SHOPTYPE_FIELD = protobuf.FieldDescriptor()
SHOPITEM_PROFESSION_FIELD = protobuf.FieldDescriptor()
SHOPITEM_LIMITTYPE_FIELD = protobuf.FieldDescriptor()
SHOPITEM_DES_FIELD = protobuf.FieldDescriptor()
SHOPITEM_LEVDES_FIELD = protobuf.FieldDescriptor()
SHOPITEM_BUSINESS_FIELD = protobuf.FieldDescriptor()
SHOPITEM_PRECOST_FIELD = protobuf.FieldDescriptor()
SHOPITEM_DISPLAY_FIELD = protobuf.FieldDescriptor()
SHOPITEM_SHOPORDER_FIELD = protobuf.FieldDescriptor()
SHOPITEM_IFMSG_FIELD = protobuf.FieldDescriptor()
SHOPITEM_ADDDATE_FIELD = protobuf.FieldDescriptor()
SHOPITEM_REMOVEDATE_FIELD = protobuf.FieldDescriptor()
SHOPITEM_SOURCE_FIELD = protobuf.FieldDescriptor()
SHOPITEM_LOCKTYPE_FIELD = protobuf.FieldDescriptor()
SHOPITEM_LOCKARG_FIELD = protobuf.FieldDescriptor()
SHOPITEM_DISCOUNTMAX_FIELD = protobuf.FieldDescriptor()
SHOPITEM_ACTDISCOUNT_FIELD = protobuf.FieldDescriptor()
SHOPITEM_PRODUCENUM_FIELD = protobuf.FieldDescriptor()
SHOPITEM_NEXTGOODSID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_CLOTHCOLORID_FIELD = protobuf.FieldDescriptor()
SHOPITEM_CLOTHCOLORIDS_FIELD = protobuf.FieldDescriptor()
SHOPITEM_ITEMTYPE_FIELD = protobuf.FieldDescriptor()
SHOPITEM_PRESENTATION_FIELD = protobuf.FieldDescriptor()
SHOPITEM_TABID_FIELD = protobuf.FieldDescriptor()
BUYSHOPITEM = protobuf.Descriptor()
BUYSHOPITEM_CMD_FIELD = protobuf.FieldDescriptor()
BUYSHOPITEM_PARAM_FIELD = protobuf.FieldDescriptor()
BUYSHOPITEM_ID_FIELD = protobuf.FieldDescriptor()
BUYSHOPITEM_COUNT_FIELD = protobuf.FieldDescriptor()
BUYSHOPITEM_PRICE_FIELD = protobuf.FieldDescriptor()
BUYSHOPITEM_PRICE2_FIELD = protobuf.FieldDescriptor()
BUYSHOPITEM_SUCCESS_FIELD = protobuf.FieldDescriptor()
QUERYSHOPCONFIGCMD = protobuf.Descriptor()
QUERYSHOPCONFIGCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYSHOPCONFIGCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYSHOPCONFIGCMD_TYPE_FIELD = protobuf.FieldDescriptor()
QUERYSHOPCONFIGCMD_SHOPID_FIELD = protobuf.FieldDescriptor()
QUERYSHOPCONFIGCMD_GOODS_FIELD = protobuf.FieldDescriptor()
QUERYSHOPCONFIGCMD_SCREEN_FIELD = protobuf.FieldDescriptor()
QUERYSHOPCONFIGCMD_TAB_FIELD = protobuf.FieldDescriptor()
QUERYQUICKBUYCONFIGCMD = protobuf.Descriptor()
QUERYQUICKBUYCONFIGCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD = protobuf.FieldDescriptor()
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD = protobuf.FieldDescriptor()
SHOPSOLDITEM = protobuf.Descriptor()
SHOPSOLDITEM_ID_FIELD = protobuf.FieldDescriptor()
SHOPSOLDITEM_COUNT_FIELD = protobuf.FieldDescriptor()
SHOPSOLDITEM_SHOPID_FIELD = protobuf.FieldDescriptor()
SHOPSOLDITEM_TYPE_FIELD = protobuf.FieldDescriptor()
QUERYSHOPSOLDCOUNTCMD = protobuf.Descriptor()
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD = protobuf.FieldDescriptor()
SHOPDATAUPDATECMD = protobuf.Descriptor()
SHOPDATAUPDATECMD_CMD_FIELD = protobuf.FieldDescriptor()
SHOPDATAUPDATECMD_PARAM_FIELD = protobuf.FieldDescriptor()
SHOPDATAUPDATECMD_TYPE_FIELD = protobuf.FieldDescriptor()
SHOPDATAUPDATECMD_SHOPID_FIELD = protobuf.FieldDescriptor()
UPDATESHOPCONFIGCMD = protobuf.Descriptor()
UPDATESHOPCONFIGCMD_CMD_FIELD = protobuf.FieldDescriptor()
UPDATESHOPCONFIGCMD_PARAM_FIELD = protobuf.FieldDescriptor()
UPDATESHOPCONFIGCMD_TYPE_FIELD = protobuf.FieldDescriptor()
UPDATESHOPCONFIGCMD_SHOPID_FIELD = protobuf.FieldDescriptor()
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD = protobuf.FieldDescriptor()
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEM = protobuf.Descriptor()
EXCHANGESHOPITEM_ID_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEM_STATUS_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEM_PROGRESS_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEM_LEFT_TIME_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEM_DELAY_TIME_FIELD = protobuf.FieldDescriptor()
UPDATEEXCHANGESHOPDATA = protobuf.Descriptor()
UPDATEEXCHANGESHOPDATA_CMD_FIELD = protobuf.FieldDescriptor()
UPDATEEXCHANGESHOPDATA_PARAM_FIELD = protobuf.FieldDescriptor()
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD = protobuf.FieldDescriptor()
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD = protobuf.FieldDescriptor()
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD = protobuf.FieldDescriptor()
UPDATEEXCHANGESHOPDATA_RESET_FIELD = protobuf.FieldDescriptor()
EXCHANGEITEMINFO = protobuf.Descriptor()
EXCHANGEITEMINFO_ID_FIELD = protobuf.FieldDescriptor()
EXCHANGEITEMINFO_NUM_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEMCMD = protobuf.Descriptor()
EXCHANGESHOPITEMCMD_CMD_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEMCMD_PARAM_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEMCMD_ID_FIELD = protobuf.FieldDescriptor()
EXCHANGESHOPITEMCMD_ITEMS_FIELD = protobuf.FieldDescriptor()
RESETEXCHANGESHOPDATASHOPCMD = protobuf.Descriptor()
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD = protobuf.FieldDescriptor()
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD = protobuf.FieldDescriptor()
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD = protobuf.FieldDescriptor()
SHOPPARAM_SHOPPARAM_BUYITEM_ENUM.name = "SHOPPARAM_BUYITEM"
SHOPPARAM_SHOPPARAM_BUYITEM_ENUM.index = 0
SHOPPARAM_SHOPPARAM_BUYITEM_ENUM.number = 1
SHOPPARAM_SHOPPARAM_QUERY_SHOP_CONFIG_ENUM.name = "SHOPPARAM_QUERY_SHOP_CONFIG"
SHOPPARAM_SHOPPARAM_QUERY_SHOP_CONFIG_ENUM.index = 1
SHOPPARAM_SHOPPARAM_QUERY_SHOP_CONFIG_ENUM.number = 2
SHOPPARAM_SHOPPARAM_QUICKBUY_SHOP_CONFIG_ENUM.name = "SHOPPARAM_QUICKBUY_SHOP_CONFIG"
SHOPPARAM_SHOPPARAM_QUICKBUY_SHOP_CONFIG_ENUM.index = 2
SHOPPARAM_SHOPPARAM_QUICKBUY_SHOP_CONFIG_ENUM.number = 3
SHOPPARAM_SHOPPARAM_QUERY_SHOP_SOLD_COUNT_ENUM.name = "SHOPPARAM_QUERY_SHOP_SOLD_COUNT"
SHOPPARAM_SHOPPARAM_QUERY_SHOP_SOLD_COUNT_ENUM.index = 3
SHOPPARAM_SHOPPARAM_QUERY_SHOP_SOLD_COUNT_ENUM.number = 4
SHOPPARAM_SHOPPARAM_UPDATE_DATA_ENUM.name = "SHOPPARAM_UPDATE_DATA"
SHOPPARAM_SHOPPARAM_UPDATE_DATA_ENUM.index = 4
SHOPPARAM_SHOPPARAM_UPDATE_DATA_ENUM.number = 5
SHOPPARAM_SHOPPARAM_UPDATE_SHOP_CONFIG_CMD_ENUM.name = "SHOPPARAM_UPDATE_SHOP_CONFIG_CMD"
SHOPPARAM_SHOPPARAM_UPDATE_SHOP_CONFIG_CMD_ENUM.index = 5
SHOPPARAM_SHOPPARAM_UPDATE_SHOP_CONFIG_CMD_ENUM.number = 6
SHOPPARAM_SHOPPARAM_UPDATE_EXCHANGESHOP_DATA_ENUM.name = "SHOPPARAM_UPDATE_EXCHANGESHOP_DATA"
SHOPPARAM_SHOPPARAM_UPDATE_EXCHANGESHOP_DATA_ENUM.index = 6
SHOPPARAM_SHOPPARAM_UPDATE_EXCHANGESHOP_DATA_ENUM.number = 7
SHOPPARAM_SHOPPARAM_EXCHANGEITEM_CMD_ENUM.name = "SHOPPARAM_EXCHANGEITEM_CMD"
SHOPPARAM_SHOPPARAM_EXCHANGEITEM_CMD_ENUM.index = 7
SHOPPARAM_SHOPPARAM_EXCHANGEITEM_CMD_ENUM.number = 8
SHOPPARAM_SHOPPARAM_RESET_EXCHANGESHOP_DATA_ENUM.name = "SHOPPARAM_RESET_EXCHANGESHOP_DATA"
SHOPPARAM_SHOPPARAM_RESET_EXCHANGESHOP_DATA_ENUM.index = 8
SHOPPARAM_SHOPPARAM_RESET_EXCHANGESHOP_DATA_ENUM.number = 9
SHOPPARAM.name = "ShopParam"
SHOPPARAM.full_name = ".Cmd.ShopParam"
SHOPPARAM.values = {
  SHOPPARAM_SHOPPARAM_BUYITEM_ENUM,
  SHOPPARAM_SHOPPARAM_QUERY_SHOP_CONFIG_ENUM,
  SHOPPARAM_SHOPPARAM_QUICKBUY_SHOP_CONFIG_ENUM,
  SHOPPARAM_SHOPPARAM_QUERY_SHOP_SOLD_COUNT_ENUM,
  SHOPPARAM_SHOPPARAM_UPDATE_DATA_ENUM,
  SHOPPARAM_SHOPPARAM_UPDATE_SHOP_CONFIG_CMD_ENUM,
  SHOPPARAM_SHOPPARAM_UPDATE_EXCHANGESHOP_DATA_ENUM,
  SHOPPARAM_SHOPPARAM_EXCHANGEITEM_CMD_ENUM,
  SHOPPARAM_SHOPPARAM_RESET_EXCHANGESHOP_DATA_ENUM
}
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MIN_ENUM.name = "ESHOPLIMITTYPE_MIN"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MIN_ENUM.index = 0
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MIN_ENUM.number = 0
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_ENUM.name = "ESHOPLIMITTYPE_USER"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_ENUM.index = 1
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_ENUM.number = 1
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ONE_ONLY_ENUM.name = "ESHOPLIMITTYPE_ONE_ONLY"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ONE_ONLY_ENUM.index = 2
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ONE_ONLY_ENUM.number = 2
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ENUM.name = "ESHOPLIMITTYPE_ACC_USER"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ENUM.index = 3
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ENUM.number = 4
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ALWAYS_ENUM.name = "ESHOPLIMITTYPE_ACC_USER_ALWAYS"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ALWAYS_ENUM.index = 4
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ALWAYS_ENUM.number = 8
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_WEEK_ENUM.name = "ESHOPLIMITTYPE_USER_WEEK"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_WEEK_ENUM.index = 5
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_WEEK_ENUM.number = 16
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_MONTH_ENUM.name = "ESHOPLIMITTYPE_USER_MONTH"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_MONTH_ENUM.index = 6
ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_MONTH_ENUM.number = 32
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_WEEK_ENUM.name = "ESHOPLIMITTYPE_ACC_WEEK"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_WEEK_ENUM.index = 7
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_WEEK_ENUM.number = 64
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_MONTH_ENUM.name = "ESHOPLIMITTYPE_ACC_MONTH"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_MONTH_ENUM.index = 8
ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_MONTH_ENUM.number = 128
ESHOPLIMITTYPE_ESHOPLIMITTYPE_GUILD_MATERIAL_MAXCOUNT_ENUM.name = "ESHOPLIMITTYPE_GUILD_MATERIAL_MAXCOUNT"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_GUILD_MATERIAL_MAXCOUNT_ENUM.index = 9
ESHOPLIMITTYPE_ESHOPLIMITTYPE_GUILD_MATERIAL_MAXCOUNT_ENUM.number = 256
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MAX_ENUM.name = "ESHOPLIMITTYPE_MAX"
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MAX_ENUM.index = 10
ESHOPLIMITTYPE_ESHOPLIMITTYPE_MAX_ENUM.number = 512
ESHOPLIMITTYPE.name = "EShopLimitType"
ESHOPLIMITTYPE.full_name = ".Cmd.EShopLimitType"
ESHOPLIMITTYPE.values = {
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_MIN_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_ONE_ONLY_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_USER_ALWAYS_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_WEEK_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_USER_MONTH_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_WEEK_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_ACC_MONTH_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_GUILD_MATERIAL_MAXCOUNT_ENUM,
  ESHOPLIMITTYPE_ESHOPLIMITTYPE_MAX_ENUM
}
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MIN_ENUM.name = "ESHOPLOCKTYPE_MIN"
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MIN_ENUM.index = 0
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MIN_ENUM.number = 0
ESHOPLOCKTYPE_ESHOPLOCKTYPE_QUEST_ENUM.name = "ESHOPLOCKTYPE_QUEST"
ESHOPLOCKTYPE_ESHOPLOCKTYPE_QUEST_ENUM.index = 1
ESHOPLOCKTYPE_ESHOPLOCKTYPE_QUEST_ENUM.number = 1
ESHOPLOCKTYPE_ESHOPLOCKTYPE_GUILDBUILDING_ENUM.name = "ESHOPLOCKTYPE_GUILDBUILDING"
ESHOPLOCKTYPE_ESHOPLOCKTYPE_GUILDBUILDING_ENUM.index = 2
ESHOPLOCKTYPE_ESHOPLOCKTYPE_GUILDBUILDING_ENUM.number = 2
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MAX_ENUM.name = "ESHOPLOCKTYPE_MAX"
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MAX_ENUM.index = 3
ESHOPLOCKTYPE_ESHOPLOCKTYPE_MAX_ENUM.number = 3
ESHOPLOCKTYPE.name = "EShopLockType"
ESHOPLOCKTYPE.full_name = ".Cmd.EShopLockType"
ESHOPLOCKTYPE.values = {
  ESHOPLOCKTYPE_ESHOPLOCKTYPE_MIN_ENUM,
  ESHOPLOCKTYPE_ESHOPLOCKTYPE_QUEST_ENUM,
  ESHOPLOCKTYPE_ESHOPLOCKTYPE_GUILDBUILDING_ENUM,
  ESHOPLOCKTYPE_ESHOPLOCKTYPE_MAX_ENUM
}
ESHOPSOURCE_ESHOPSOURCE_USER_ENUM.name = "ESHOPSOURCE_USER"
ESHOPSOURCE_ESHOPSOURCE_USER_ENUM.index = 0
ESHOPSOURCE_ESHOPSOURCE_USER_ENUM.number = 0
ESHOPSOURCE_ESHOPSOURCE_GUILD_ENUM.name = "ESHOPSOURCE_GUILD"
ESHOPSOURCE_ESHOPSOURCE_GUILD_ENUM.index = 1
ESHOPSOURCE_ESHOPSOURCE_GUILD_ENUM.number = 1
ESHOPSOURCE_ESHOPSOURCE_USER_GUILD_ENUM.name = "ESHOPSOURCE_USER_GUILD"
ESHOPSOURCE_ESHOPSOURCE_USER_GUILD_ENUM.index = 2
ESHOPSOURCE_ESHOPSOURCE_USER_GUILD_ENUM.number = 2
ESHOPSOURCE.name = "EShopSource"
ESHOPSOURCE.full_name = ".Cmd.EShopSource"
ESHOPSOURCE.values = {
  ESHOPSOURCE_ESHOPSOURCE_USER_ENUM,
  ESHOPSOURCE_ESHOPSOURCE_GUILD_ENUM,
  ESHOPSOURCE_ESHOPSOURCE_USER_GUILD_ENUM
}
EPRESENTTYPE_EPRESENTTYPE_NORMAL_ENUM.name = "EPRESENTTYPE_NORMAL"
EPRESENTTYPE_EPRESENTTYPE_NORMAL_ENUM.index = 0
EPRESENTTYPE_EPRESENTTYPE_NORMAL_ENUM.number = 0
EPRESENTTYPE_EPRESENTTYPE_LOCK_ENUM.name = "EPRESENTTYPE_LOCK"
EPRESENTTYPE_EPRESENTTYPE_LOCK_ENUM.index = 1
EPRESENTTYPE_EPRESENTTYPE_LOCK_ENUM.number = 1
EPRESENTTYPE.name = "EPresentType"
EPRESENTTYPE.full_name = ".Cmd.EPresentType"
EPRESENTTYPE.values = {
  EPRESENTTYPE_EPRESENTTYPE_NORMAL_ENUM,
  EPRESENTTYPE_EPRESENTTYPE_LOCK_ENUM
}
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_OK_ENUM.name = "EEXCHANGESTATUSTYPE_OK"
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_OK_ENUM.index = 0
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_OK_ENUM.number = 1
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_EMPTY_ENUM.name = "EEXCHANGESTATUSTYPE_EMPTY"
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_EMPTY_ENUM.index = 1
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_EMPTY_ENUM.number = 2
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_DELAY_ENUM.name = "EEXCHANGESTATUSTYPE_DELAY"
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_DELAY_ENUM.index = 2
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_DELAY_ENUM.number = 3
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_UNLOOK_ENUM.name = "EEXCHANGESTATUSTYPE_UNLOOK"
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_UNLOOK_ENUM.index = 3
EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_UNLOOK_ENUM.number = 4
EEXCHANGESTATUSTYPE.name = "EExchangeStatusType"
EEXCHANGESTATUSTYPE.full_name = ".Cmd.EExchangeStatusType"
EEXCHANGESTATUSTYPE.values = {
  EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_OK_ENUM,
  EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_EMPTY_ENUM,
  EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_DELAY_ENUM,
  EEXCHANGESTATUSTYPE_EEXCHANGESTATUSTYPE_UNLOOK_ENUM
}
PRESENTATION_PRESENTTYPE_FIELD.name = "presenttype"
PRESENTATION_PRESENTTYPE_FIELD.full_name = ".Cmd.Presentation.presenttype"
PRESENTATION_PRESENTTYPE_FIELD.number = 1
PRESENTATION_PRESENTTYPE_FIELD.index = 0
PRESENTATION_PRESENTTYPE_FIELD.label = 1
PRESENTATION_PRESENTTYPE_FIELD.has_default_value = true
PRESENTATION_PRESENTTYPE_FIELD.default_value = 0
PRESENTATION_PRESENTTYPE_FIELD.enum_type = EPRESENTTYPE
PRESENTATION_PRESENTTYPE_FIELD.type = 14
PRESENTATION_PRESENTTYPE_FIELD.cpp_type = 8
PRESENTATION_MSGID_FIELD.name = "msgid"
PRESENTATION_MSGID_FIELD.full_name = ".Cmd.Presentation.msgid"
PRESENTATION_MSGID_FIELD.number = 2
PRESENTATION_MSGID_FIELD.index = 1
PRESENTATION_MSGID_FIELD.label = 1
PRESENTATION_MSGID_FIELD.has_default_value = true
PRESENTATION_MSGID_FIELD.default_value = 0
PRESENTATION_MSGID_FIELD.type = 13
PRESENTATION_MSGID_FIELD.cpp_type = 3
PRESENTATION_MENUID_FIELD.name = "menuid"
PRESENTATION_MENUID_FIELD.full_name = ".Cmd.Presentation.menuid"
PRESENTATION_MENUID_FIELD.number = 3
PRESENTATION_MENUID_FIELD.index = 2
PRESENTATION_MENUID_FIELD.label = 3
PRESENTATION_MENUID_FIELD.has_default_value = false
PRESENTATION_MENUID_FIELD.default_value = {}
PRESENTATION_MENUID_FIELD.type = 13
PRESENTATION_MENUID_FIELD.cpp_type = 3
PRESENTATION.name = "Presentation"
PRESENTATION.full_name = ".Cmd.Presentation"
PRESENTATION.nested_types = {}
PRESENTATION.enum_types = {}
PRESENTATION.fields = {
  PRESENTATION_PRESENTTYPE_FIELD,
  PRESENTATION_MSGID_FIELD,
  PRESENTATION_MENUID_FIELD
}
PRESENTATION.is_extendable = false
PRESENTATION.extensions = {}
SHOPITEM_ID_FIELD.name = "id"
SHOPITEM_ID_FIELD.full_name = ".Cmd.ShopItem.id"
SHOPITEM_ID_FIELD.number = 1
SHOPITEM_ID_FIELD.index = 0
SHOPITEM_ID_FIELD.label = 1
SHOPITEM_ID_FIELD.has_default_value = true
SHOPITEM_ID_FIELD.default_value = 0
SHOPITEM_ID_FIELD.type = 13
SHOPITEM_ID_FIELD.cpp_type = 3
SHOPITEM_LV_FIELD.name = "lv"
SHOPITEM_LV_FIELD.full_name = ".Cmd.ShopItem.lv"
SHOPITEM_LV_FIELD.number = 2
SHOPITEM_LV_FIELD.index = 1
SHOPITEM_LV_FIELD.label = 1
SHOPITEM_LV_FIELD.has_default_value = true
SHOPITEM_LV_FIELD.default_value = 0
SHOPITEM_LV_FIELD.type = 13
SHOPITEM_LV_FIELD.cpp_type = 3
SHOPITEM_MONEYID_FIELD.name = "moneyid"
SHOPITEM_MONEYID_FIELD.full_name = ".Cmd.ShopItem.moneyid"
SHOPITEM_MONEYID_FIELD.number = 3
SHOPITEM_MONEYID_FIELD.index = 2
SHOPITEM_MONEYID_FIELD.label = 1
SHOPITEM_MONEYID_FIELD.has_default_value = true
SHOPITEM_MONEYID_FIELD.default_value = 0
SHOPITEM_MONEYID_FIELD.type = 13
SHOPITEM_MONEYID_FIELD.cpp_type = 3
SHOPITEM_MONEYCOUNT_FIELD.name = "moneycount"
SHOPITEM_MONEYCOUNT_FIELD.full_name = ".Cmd.ShopItem.moneycount"
SHOPITEM_MONEYCOUNT_FIELD.number = 4
SHOPITEM_MONEYCOUNT_FIELD.index = 3
SHOPITEM_MONEYCOUNT_FIELD.label = 1
SHOPITEM_MONEYCOUNT_FIELD.has_default_value = true
SHOPITEM_MONEYCOUNT_FIELD.default_value = 0
SHOPITEM_MONEYCOUNT_FIELD.type = 13
SHOPITEM_MONEYCOUNT_FIELD.cpp_type = 3
SHOPITEM_MONEYID2_FIELD.name = "moneyid2"
SHOPITEM_MONEYID2_FIELD.full_name = ".Cmd.ShopItem.moneyid2"
SHOPITEM_MONEYID2_FIELD.number = 5
SHOPITEM_MONEYID2_FIELD.index = 4
SHOPITEM_MONEYID2_FIELD.label = 1
SHOPITEM_MONEYID2_FIELD.has_default_value = false
SHOPITEM_MONEYID2_FIELD.default_value = 0
SHOPITEM_MONEYID2_FIELD.type = 13
SHOPITEM_MONEYID2_FIELD.cpp_type = 3
SHOPITEM_MONEYCOUNT2_FIELD.name = "moneycount2"
SHOPITEM_MONEYCOUNT2_FIELD.full_name = ".Cmd.ShopItem.moneycount2"
SHOPITEM_MONEYCOUNT2_FIELD.number = 6
SHOPITEM_MONEYCOUNT2_FIELD.index = 5
SHOPITEM_MONEYCOUNT2_FIELD.label = 1
SHOPITEM_MONEYCOUNT2_FIELD.has_default_value = false
SHOPITEM_MONEYCOUNT2_FIELD.default_value = 0
SHOPITEM_MONEYCOUNT2_FIELD.type = 13
SHOPITEM_MONEYCOUNT2_FIELD.cpp_type = 3
SHOPITEM_STARTTIME_FIELD.name = "starttime"
SHOPITEM_STARTTIME_FIELD.full_name = ".Cmd.ShopItem.starttime"
SHOPITEM_STARTTIME_FIELD.number = 7
SHOPITEM_STARTTIME_FIELD.index = 6
SHOPITEM_STARTTIME_FIELD.label = 1
SHOPITEM_STARTTIME_FIELD.has_default_value = true
SHOPITEM_STARTTIME_FIELD.default_value = 0
SHOPITEM_STARTTIME_FIELD.type = 13
SHOPITEM_STARTTIME_FIELD.cpp_type = 3
SHOPITEM_ENDTIME_FIELD.name = "endtime"
SHOPITEM_ENDTIME_FIELD.full_name = ".Cmd.ShopItem.endtime"
SHOPITEM_ENDTIME_FIELD.number = 8
SHOPITEM_ENDTIME_FIELD.index = 7
SHOPITEM_ENDTIME_FIELD.label = 1
SHOPITEM_ENDTIME_FIELD.has_default_value = true
SHOPITEM_ENDTIME_FIELD.default_value = 0
SHOPITEM_ENDTIME_FIELD.type = 13
SHOPITEM_ENDTIME_FIELD.cpp_type = 3
SHOPITEM_DISCOUNT_FIELD.name = "discount"
SHOPITEM_DISCOUNT_FIELD.full_name = ".Cmd.ShopItem.discount"
SHOPITEM_DISCOUNT_FIELD.number = 9
SHOPITEM_DISCOUNT_FIELD.index = 8
SHOPITEM_DISCOUNT_FIELD.label = 1
SHOPITEM_DISCOUNT_FIELD.has_default_value = true
SHOPITEM_DISCOUNT_FIELD.default_value = 0
SHOPITEM_DISCOUNT_FIELD.type = 13
SHOPITEM_DISCOUNT_FIELD.cpp_type = 3
SHOPITEM_MAXCOUNT_FIELD.name = "maxcount"
SHOPITEM_MAXCOUNT_FIELD.full_name = ".Cmd.ShopItem.maxcount"
SHOPITEM_MAXCOUNT_FIELD.number = 10
SHOPITEM_MAXCOUNT_FIELD.index = 9
SHOPITEM_MAXCOUNT_FIELD.label = 1
SHOPITEM_MAXCOUNT_FIELD.has_default_value = true
SHOPITEM_MAXCOUNT_FIELD.default_value = 0
SHOPITEM_MAXCOUNT_FIELD.type = 13
SHOPITEM_MAXCOUNT_FIELD.cpp_type = 3
SHOPITEM_SHOPID_FIELD.name = "shopid"
SHOPITEM_SHOPID_FIELD.full_name = ".Cmd.ShopItem.shopid"
SHOPITEM_SHOPID_FIELD.number = 11
SHOPITEM_SHOPID_FIELD.index = 10
SHOPITEM_SHOPID_FIELD.label = 1
SHOPITEM_SHOPID_FIELD.has_default_value = true
SHOPITEM_SHOPID_FIELD.default_value = 0
SHOPITEM_SHOPID_FIELD.type = 13
SHOPITEM_SHOPID_FIELD.cpp_type = 3
SHOPITEM_SCREEN_FIELD.name = "screen"
SHOPITEM_SCREEN_FIELD.full_name = ".Cmd.ShopItem.screen"
SHOPITEM_SCREEN_FIELD.number = 12
SHOPITEM_SCREEN_FIELD.index = 11
SHOPITEM_SCREEN_FIELD.label = 1
SHOPITEM_SCREEN_FIELD.has_default_value = true
SHOPITEM_SCREEN_FIELD.default_value = 0
SHOPITEM_SCREEN_FIELD.type = 13
SHOPITEM_SCREEN_FIELD.cpp_type = 3
SHOPITEM_ITEMID_FIELD.name = "itemid"
SHOPITEM_ITEMID_FIELD.full_name = ".Cmd.ShopItem.itemid"
SHOPITEM_ITEMID_FIELD.number = 13
SHOPITEM_ITEMID_FIELD.index = 12
SHOPITEM_ITEMID_FIELD.label = 1
SHOPITEM_ITEMID_FIELD.has_default_value = false
SHOPITEM_ITEMID_FIELD.default_value = 0
SHOPITEM_ITEMID_FIELD.type = 13
SHOPITEM_ITEMID_FIELD.cpp_type = 3
SHOPITEM_SKILLID_FIELD.name = "skillid"
SHOPITEM_SKILLID_FIELD.full_name = ".Cmd.ShopItem.skillid"
SHOPITEM_SKILLID_FIELD.number = 14
SHOPITEM_SKILLID_FIELD.index = 13
SHOPITEM_SKILLID_FIELD.label = 1
SHOPITEM_SKILLID_FIELD.has_default_value = false
SHOPITEM_SKILLID_FIELD.default_value = 0
SHOPITEM_SKILLID_FIELD.type = 13
SHOPITEM_SKILLID_FIELD.cpp_type = 3
SHOPITEM_HAIRCOLORID_FIELD.name = "haircolorid"
SHOPITEM_HAIRCOLORID_FIELD.full_name = ".Cmd.ShopItem.haircolorid"
SHOPITEM_HAIRCOLORID_FIELD.number = 16
SHOPITEM_HAIRCOLORID_FIELD.index = 14
SHOPITEM_HAIRCOLORID_FIELD.label = 1
SHOPITEM_HAIRCOLORID_FIELD.has_default_value = false
SHOPITEM_HAIRCOLORID_FIELD.default_value = 0
SHOPITEM_HAIRCOLORID_FIELD.type = 13
SHOPITEM_HAIRCOLORID_FIELD.cpp_type = 3
SHOPITEM_NUM_FIELD.name = "num"
SHOPITEM_NUM_FIELD.full_name = ".Cmd.ShopItem.num"
SHOPITEM_NUM_FIELD.number = 17
SHOPITEM_NUM_FIELD.index = 15
SHOPITEM_NUM_FIELD.label = 1
SHOPITEM_NUM_FIELD.has_default_value = false
SHOPITEM_NUM_FIELD.default_value = 0
SHOPITEM_NUM_FIELD.type = 13
SHOPITEM_NUM_FIELD.cpp_type = 3
SHOPITEM_MENUID_FIELD.name = "menuid"
SHOPITEM_MENUID_FIELD.full_name = ".Cmd.ShopItem.menuid"
SHOPITEM_MENUID_FIELD.number = 18
SHOPITEM_MENUID_FIELD.index = 16
SHOPITEM_MENUID_FIELD.label = 1
SHOPITEM_MENUID_FIELD.has_default_value = true
SHOPITEM_MENUID_FIELD.default_value = 0
SHOPITEM_MENUID_FIELD.type = 13
SHOPITEM_MENUID_FIELD.cpp_type = 3
SHOPITEM_SHOPTYPE_FIELD.name = "shoptype"
SHOPITEM_SHOPTYPE_FIELD.full_name = ".Cmd.ShopItem.shoptype"
SHOPITEM_SHOPTYPE_FIELD.number = 19
SHOPITEM_SHOPTYPE_FIELD.index = 17
SHOPITEM_SHOPTYPE_FIELD.label = 1
SHOPITEM_SHOPTYPE_FIELD.has_default_value = true
SHOPITEM_SHOPTYPE_FIELD.default_value = 0
SHOPITEM_SHOPTYPE_FIELD.type = 13
SHOPITEM_SHOPTYPE_FIELD.cpp_type = 3
SHOPITEM_PROFESSION_FIELD.name = "profession"
SHOPITEM_PROFESSION_FIELD.full_name = ".Cmd.ShopItem.profession"
SHOPITEM_PROFESSION_FIELD.number = 20
SHOPITEM_PROFESSION_FIELD.index = 18
SHOPITEM_PROFESSION_FIELD.label = 3
SHOPITEM_PROFESSION_FIELD.has_default_value = false
SHOPITEM_PROFESSION_FIELD.default_value = {}
SHOPITEM_PROFESSION_FIELD.enum_type = PROTOCOMMON_PB_EPROFESSION
SHOPITEM_PROFESSION_FIELD.type = 14
SHOPITEM_PROFESSION_FIELD.cpp_type = 8
SHOPITEM_LIMITTYPE_FIELD.name = "limittype"
SHOPITEM_LIMITTYPE_FIELD.full_name = ".Cmd.ShopItem.limittype"
SHOPITEM_LIMITTYPE_FIELD.number = 21
SHOPITEM_LIMITTYPE_FIELD.index = 19
SHOPITEM_LIMITTYPE_FIELD.label = 1
SHOPITEM_LIMITTYPE_FIELD.has_default_value = true
SHOPITEM_LIMITTYPE_FIELD.default_value = 0
SHOPITEM_LIMITTYPE_FIELD.enum_type = ESHOPLIMITTYPE
SHOPITEM_LIMITTYPE_FIELD.type = 14
SHOPITEM_LIMITTYPE_FIELD.cpp_type = 8
SHOPITEM_DES_FIELD.name = "des"
SHOPITEM_DES_FIELD.full_name = ".Cmd.ShopItem.des"
SHOPITEM_DES_FIELD.number = 22
SHOPITEM_DES_FIELD.index = 20
SHOPITEM_DES_FIELD.label = 1
SHOPITEM_DES_FIELD.has_default_value = false
SHOPITEM_DES_FIELD.default_value = ""
SHOPITEM_DES_FIELD.type = 9
SHOPITEM_DES_FIELD.cpp_type = 9
SHOPITEM_LEVDES_FIELD.name = "levdes"
SHOPITEM_LEVDES_FIELD.full_name = ".Cmd.ShopItem.levdes"
SHOPITEM_LEVDES_FIELD.number = 23
SHOPITEM_LEVDES_FIELD.index = 21
SHOPITEM_LEVDES_FIELD.label = 1
SHOPITEM_LEVDES_FIELD.has_default_value = false
SHOPITEM_LEVDES_FIELD.default_value = ""
SHOPITEM_LEVDES_FIELD.type = 9
SHOPITEM_LEVDES_FIELD.cpp_type = 9
SHOPITEM_BUSINESS_FIELD.name = "business"
SHOPITEM_BUSINESS_FIELD.full_name = ".Cmd.ShopItem.business"
SHOPITEM_BUSINESS_FIELD.number = 24
SHOPITEM_BUSINESS_FIELD.index = 22
SHOPITEM_BUSINESS_FIELD.label = 1
SHOPITEM_BUSINESS_FIELD.has_default_value = false
SHOPITEM_BUSINESS_FIELD.default_value = 0
SHOPITEM_BUSINESS_FIELD.type = 13
SHOPITEM_BUSINESS_FIELD.cpp_type = 3
SHOPITEM_PRECOST_FIELD.name = "precost"
SHOPITEM_PRECOST_FIELD.full_name = ".Cmd.ShopItem.precost"
SHOPITEM_PRECOST_FIELD.number = 25
SHOPITEM_PRECOST_FIELD.index = 23
SHOPITEM_PRECOST_FIELD.label = 1
SHOPITEM_PRECOST_FIELD.has_default_value = false
SHOPITEM_PRECOST_FIELD.default_value = 0
SHOPITEM_PRECOST_FIELD.type = 13
SHOPITEM_PRECOST_FIELD.cpp_type = 3
SHOPITEM_DISPLAY_FIELD.name = "display"
SHOPITEM_DISPLAY_FIELD.full_name = ".Cmd.ShopItem.display"
SHOPITEM_DISPLAY_FIELD.number = 26
SHOPITEM_DISPLAY_FIELD.index = 24
SHOPITEM_DISPLAY_FIELD.label = 1
SHOPITEM_DISPLAY_FIELD.has_default_value = true
SHOPITEM_DISPLAY_FIELD.default_value = 0
SHOPITEM_DISPLAY_FIELD.type = 13
SHOPITEM_DISPLAY_FIELD.cpp_type = 3
SHOPITEM_SHOPORDER_FIELD.name = "shoporder"
SHOPITEM_SHOPORDER_FIELD.full_name = ".Cmd.ShopItem.shoporder"
SHOPITEM_SHOPORDER_FIELD.number = 27
SHOPITEM_SHOPORDER_FIELD.index = 25
SHOPITEM_SHOPORDER_FIELD.label = 1
SHOPITEM_SHOPORDER_FIELD.has_default_value = false
SHOPITEM_SHOPORDER_FIELD.default_value = 0
SHOPITEM_SHOPORDER_FIELD.type = 13
SHOPITEM_SHOPORDER_FIELD.cpp_type = 3
SHOPITEM_IFMSG_FIELD.name = "ifmsg"
SHOPITEM_IFMSG_FIELD.full_name = ".Cmd.ShopItem.ifmsg"
SHOPITEM_IFMSG_FIELD.number = 28
SHOPITEM_IFMSG_FIELD.index = 26
SHOPITEM_IFMSG_FIELD.label = 1
SHOPITEM_IFMSG_FIELD.has_default_value = false
SHOPITEM_IFMSG_FIELD.default_value = 0
SHOPITEM_IFMSG_FIELD.type = 13
SHOPITEM_IFMSG_FIELD.cpp_type = 3
SHOPITEM_ADDDATE_FIELD.name = "adddate"
SHOPITEM_ADDDATE_FIELD.full_name = ".Cmd.ShopItem.adddate"
SHOPITEM_ADDDATE_FIELD.number = 29
SHOPITEM_ADDDATE_FIELD.index = 27
SHOPITEM_ADDDATE_FIELD.label = 1
SHOPITEM_ADDDATE_FIELD.has_default_value = false
SHOPITEM_ADDDATE_FIELD.default_value = 0
SHOPITEM_ADDDATE_FIELD.type = 13
SHOPITEM_ADDDATE_FIELD.cpp_type = 3
SHOPITEM_REMOVEDATE_FIELD.name = "removedate"
SHOPITEM_REMOVEDATE_FIELD.full_name = ".Cmd.ShopItem.removedate"
SHOPITEM_REMOVEDATE_FIELD.number = 30
SHOPITEM_REMOVEDATE_FIELD.index = 28
SHOPITEM_REMOVEDATE_FIELD.label = 1
SHOPITEM_REMOVEDATE_FIELD.has_default_value = false
SHOPITEM_REMOVEDATE_FIELD.default_value = 0
SHOPITEM_REMOVEDATE_FIELD.type = 13
SHOPITEM_REMOVEDATE_FIELD.cpp_type = 3
SHOPITEM_SOURCE_FIELD.name = "source"
SHOPITEM_SOURCE_FIELD.full_name = ".Cmd.ShopItem.source"
SHOPITEM_SOURCE_FIELD.number = 37
SHOPITEM_SOURCE_FIELD.index = 29
SHOPITEM_SOURCE_FIELD.label = 1
SHOPITEM_SOURCE_FIELD.has_default_value = true
SHOPITEM_SOURCE_FIELD.default_value = 0
SHOPITEM_SOURCE_FIELD.enum_type = ESHOPSOURCE
SHOPITEM_SOURCE_FIELD.type = 14
SHOPITEM_SOURCE_FIELD.cpp_type = 8
SHOPITEM_LOCKTYPE_FIELD.name = "locktype"
SHOPITEM_LOCKTYPE_FIELD.full_name = ".Cmd.ShopItem.locktype"
SHOPITEM_LOCKTYPE_FIELD.number = 31
SHOPITEM_LOCKTYPE_FIELD.index = 30
SHOPITEM_LOCKTYPE_FIELD.label = 1
SHOPITEM_LOCKTYPE_FIELD.has_default_value = true
SHOPITEM_LOCKTYPE_FIELD.default_value = 0
SHOPITEM_LOCKTYPE_FIELD.enum_type = ESHOPLOCKTYPE
SHOPITEM_LOCKTYPE_FIELD.type = 14
SHOPITEM_LOCKTYPE_FIELD.cpp_type = 8
SHOPITEM_LOCKARG_FIELD.name = "lockarg"
SHOPITEM_LOCKARG_FIELD.full_name = ".Cmd.ShopItem.lockarg"
SHOPITEM_LOCKARG_FIELD.number = 32
SHOPITEM_LOCKARG_FIELD.index = 31
SHOPITEM_LOCKARG_FIELD.label = 1
SHOPITEM_LOCKARG_FIELD.has_default_value = false
SHOPITEM_LOCKARG_FIELD.default_value = ""
SHOPITEM_LOCKARG_FIELD.type = 9
SHOPITEM_LOCKARG_FIELD.cpp_type = 9
SHOPITEM_DISCOUNTMAX_FIELD.name = "discountmax"
SHOPITEM_DISCOUNTMAX_FIELD.full_name = ".Cmd.ShopItem.discountmax"
SHOPITEM_DISCOUNTMAX_FIELD.number = 33
SHOPITEM_DISCOUNTMAX_FIELD.index = 32
SHOPITEM_DISCOUNTMAX_FIELD.label = 1
SHOPITEM_DISCOUNTMAX_FIELD.has_default_value = false
SHOPITEM_DISCOUNTMAX_FIELD.default_value = 0
SHOPITEM_DISCOUNTMAX_FIELD.type = 13
SHOPITEM_DISCOUNTMAX_FIELD.cpp_type = 3
SHOPITEM_ACTDISCOUNT_FIELD.name = "actdiscount"
SHOPITEM_ACTDISCOUNT_FIELD.full_name = ".Cmd.ShopItem.actdiscount"
SHOPITEM_ACTDISCOUNT_FIELD.number = 34
SHOPITEM_ACTDISCOUNT_FIELD.index = 33
SHOPITEM_ACTDISCOUNT_FIELD.label = 1
SHOPITEM_ACTDISCOUNT_FIELD.has_default_value = false
SHOPITEM_ACTDISCOUNT_FIELD.default_value = 0
SHOPITEM_ACTDISCOUNT_FIELD.type = 13
SHOPITEM_ACTDISCOUNT_FIELD.cpp_type = 3
SHOPITEM_PRODUCENUM_FIELD.name = "producenum"
SHOPITEM_PRODUCENUM_FIELD.full_name = ".Cmd.ShopItem.producenum"
SHOPITEM_PRODUCENUM_FIELD.number = 35
SHOPITEM_PRODUCENUM_FIELD.index = 34
SHOPITEM_PRODUCENUM_FIELD.label = 1
SHOPITEM_PRODUCENUM_FIELD.has_default_value = false
SHOPITEM_PRODUCENUM_FIELD.default_value = 0
SHOPITEM_PRODUCENUM_FIELD.type = 13
SHOPITEM_PRODUCENUM_FIELD.cpp_type = 3
SHOPITEM_NEXTGOODSID_FIELD.name = "nextgoodsid"
SHOPITEM_NEXTGOODSID_FIELD.full_name = ".Cmd.ShopItem.nextgoodsid"
SHOPITEM_NEXTGOODSID_FIELD.number = 36
SHOPITEM_NEXTGOODSID_FIELD.index = 35
SHOPITEM_NEXTGOODSID_FIELD.label = 1
SHOPITEM_NEXTGOODSID_FIELD.has_default_value = false
SHOPITEM_NEXTGOODSID_FIELD.default_value = 0
SHOPITEM_NEXTGOODSID_FIELD.type = 13
SHOPITEM_NEXTGOODSID_FIELD.cpp_type = 3
SHOPITEM_CLOTHCOLORID_FIELD.name = "clothcolorid"
SHOPITEM_CLOTHCOLORID_FIELD.full_name = ".Cmd.ShopItem.clothcolorid"
SHOPITEM_CLOTHCOLORID_FIELD.number = 38
SHOPITEM_CLOTHCOLORID_FIELD.index = 36
SHOPITEM_CLOTHCOLORID_FIELD.label = 1
SHOPITEM_CLOTHCOLORID_FIELD.has_default_value = true
SHOPITEM_CLOTHCOLORID_FIELD.default_value = 0
SHOPITEM_CLOTHCOLORID_FIELD.type = 13
SHOPITEM_CLOTHCOLORID_FIELD.cpp_type = 3
SHOPITEM_CLOTHCOLORIDS_FIELD.name = "clothcolorids"
SHOPITEM_CLOTHCOLORIDS_FIELD.full_name = ".Cmd.ShopItem.clothcolorids"
SHOPITEM_CLOTHCOLORIDS_FIELD.number = 39
SHOPITEM_CLOTHCOLORIDS_FIELD.index = 37
SHOPITEM_CLOTHCOLORIDS_FIELD.label = 3
SHOPITEM_CLOTHCOLORIDS_FIELD.has_default_value = false
SHOPITEM_CLOTHCOLORIDS_FIELD.default_value = {}
SHOPITEM_CLOTHCOLORIDS_FIELD.type = 13
SHOPITEM_CLOTHCOLORIDS_FIELD.cpp_type = 3
SHOPITEM_ITEMTYPE_FIELD.name = "itemtype"
SHOPITEM_ITEMTYPE_FIELD.full_name = ".Cmd.ShopItem.itemtype"
SHOPITEM_ITEMTYPE_FIELD.number = 40
SHOPITEM_ITEMTYPE_FIELD.index = 38
SHOPITEM_ITEMTYPE_FIELD.label = 1
SHOPITEM_ITEMTYPE_FIELD.has_default_value = true
SHOPITEM_ITEMTYPE_FIELD.default_value = 0
SHOPITEM_ITEMTYPE_FIELD.type = 13
SHOPITEM_ITEMTYPE_FIELD.cpp_type = 3
SHOPITEM_PRESENTATION_FIELD.name = "presentation"
SHOPITEM_PRESENTATION_FIELD.full_name = ".Cmd.ShopItem.presentation"
SHOPITEM_PRESENTATION_FIELD.number = 41
SHOPITEM_PRESENTATION_FIELD.index = 39
SHOPITEM_PRESENTATION_FIELD.label = 1
SHOPITEM_PRESENTATION_FIELD.has_default_value = false
SHOPITEM_PRESENTATION_FIELD.default_value = nil
SHOPITEM_PRESENTATION_FIELD.message_type = PRESENTATION
SHOPITEM_PRESENTATION_FIELD.type = 11
SHOPITEM_PRESENTATION_FIELD.cpp_type = 10
SHOPITEM_TABID_FIELD.name = "tabid"
SHOPITEM_TABID_FIELD.full_name = ".Cmd.ShopItem.tabid"
SHOPITEM_TABID_FIELD.number = 42
SHOPITEM_TABID_FIELD.index = 40
SHOPITEM_TABID_FIELD.label = 1
SHOPITEM_TABID_FIELD.has_default_value = false
SHOPITEM_TABID_FIELD.default_value = 0
SHOPITEM_TABID_FIELD.type = 13
SHOPITEM_TABID_FIELD.cpp_type = 3
SHOPITEM.name = "ShopItem"
SHOPITEM.full_name = ".Cmd.ShopItem"
SHOPITEM.nested_types = {}
SHOPITEM.enum_types = {}
SHOPITEM.fields = {
  SHOPITEM_ID_FIELD,
  SHOPITEM_LV_FIELD,
  SHOPITEM_MONEYID_FIELD,
  SHOPITEM_MONEYCOUNT_FIELD,
  SHOPITEM_MONEYID2_FIELD,
  SHOPITEM_MONEYCOUNT2_FIELD,
  SHOPITEM_STARTTIME_FIELD,
  SHOPITEM_ENDTIME_FIELD,
  SHOPITEM_DISCOUNT_FIELD,
  SHOPITEM_MAXCOUNT_FIELD,
  SHOPITEM_SHOPID_FIELD,
  SHOPITEM_SCREEN_FIELD,
  SHOPITEM_ITEMID_FIELD,
  SHOPITEM_SKILLID_FIELD,
  SHOPITEM_HAIRCOLORID_FIELD,
  SHOPITEM_NUM_FIELD,
  SHOPITEM_MENUID_FIELD,
  SHOPITEM_SHOPTYPE_FIELD,
  SHOPITEM_PROFESSION_FIELD,
  SHOPITEM_LIMITTYPE_FIELD,
  SHOPITEM_DES_FIELD,
  SHOPITEM_LEVDES_FIELD,
  SHOPITEM_BUSINESS_FIELD,
  SHOPITEM_PRECOST_FIELD,
  SHOPITEM_DISPLAY_FIELD,
  SHOPITEM_SHOPORDER_FIELD,
  SHOPITEM_IFMSG_FIELD,
  SHOPITEM_ADDDATE_FIELD,
  SHOPITEM_REMOVEDATE_FIELD,
  SHOPITEM_SOURCE_FIELD,
  SHOPITEM_LOCKTYPE_FIELD,
  SHOPITEM_LOCKARG_FIELD,
  SHOPITEM_DISCOUNTMAX_FIELD,
  SHOPITEM_ACTDISCOUNT_FIELD,
  SHOPITEM_PRODUCENUM_FIELD,
  SHOPITEM_NEXTGOODSID_FIELD,
  SHOPITEM_CLOTHCOLORID_FIELD,
  SHOPITEM_CLOTHCOLORIDS_FIELD,
  SHOPITEM_ITEMTYPE_FIELD,
  SHOPITEM_PRESENTATION_FIELD,
  SHOPITEM_TABID_FIELD
}
SHOPITEM.is_extendable = false
SHOPITEM.extensions = {}
BUYSHOPITEM_CMD_FIELD.name = "cmd"
BUYSHOPITEM_CMD_FIELD.full_name = ".Cmd.BuyShopItem.cmd"
BUYSHOPITEM_CMD_FIELD.number = 1
BUYSHOPITEM_CMD_FIELD.index = 0
BUYSHOPITEM_CMD_FIELD.label = 1
BUYSHOPITEM_CMD_FIELD.has_default_value = true
BUYSHOPITEM_CMD_FIELD.default_value = 52
BUYSHOPITEM_CMD_FIELD.enum_type = XCMD_PB_COMMAND
BUYSHOPITEM_CMD_FIELD.type = 14
BUYSHOPITEM_CMD_FIELD.cpp_type = 8
BUYSHOPITEM_PARAM_FIELD.name = "param"
BUYSHOPITEM_PARAM_FIELD.full_name = ".Cmd.BuyShopItem.param"
BUYSHOPITEM_PARAM_FIELD.number = 2
BUYSHOPITEM_PARAM_FIELD.index = 1
BUYSHOPITEM_PARAM_FIELD.label = 1
BUYSHOPITEM_PARAM_FIELD.has_default_value = true
BUYSHOPITEM_PARAM_FIELD.default_value = 1
BUYSHOPITEM_PARAM_FIELD.enum_type = SHOPPARAM
BUYSHOPITEM_PARAM_FIELD.type = 14
BUYSHOPITEM_PARAM_FIELD.cpp_type = 8
BUYSHOPITEM_ID_FIELD.name = "id"
BUYSHOPITEM_ID_FIELD.full_name = ".Cmd.BuyShopItem.id"
BUYSHOPITEM_ID_FIELD.number = 3
BUYSHOPITEM_ID_FIELD.index = 2
BUYSHOPITEM_ID_FIELD.label = 1
BUYSHOPITEM_ID_FIELD.has_default_value = true
BUYSHOPITEM_ID_FIELD.default_value = 0
BUYSHOPITEM_ID_FIELD.type = 13
BUYSHOPITEM_ID_FIELD.cpp_type = 3
BUYSHOPITEM_COUNT_FIELD.name = "count"
BUYSHOPITEM_COUNT_FIELD.full_name = ".Cmd.BuyShopItem.count"
BUYSHOPITEM_COUNT_FIELD.number = 4
BUYSHOPITEM_COUNT_FIELD.index = 3
BUYSHOPITEM_COUNT_FIELD.label = 1
BUYSHOPITEM_COUNT_FIELD.has_default_value = true
BUYSHOPITEM_COUNT_FIELD.default_value = 0
BUYSHOPITEM_COUNT_FIELD.type = 13
BUYSHOPITEM_COUNT_FIELD.cpp_type = 3
BUYSHOPITEM_PRICE_FIELD.name = "price"
BUYSHOPITEM_PRICE_FIELD.full_name = ".Cmd.BuyShopItem.price"
BUYSHOPITEM_PRICE_FIELD.number = 5
BUYSHOPITEM_PRICE_FIELD.index = 4
BUYSHOPITEM_PRICE_FIELD.label = 1
BUYSHOPITEM_PRICE_FIELD.has_default_value = true
BUYSHOPITEM_PRICE_FIELD.default_value = 0
BUYSHOPITEM_PRICE_FIELD.type = 13
BUYSHOPITEM_PRICE_FIELD.cpp_type = 3
BUYSHOPITEM_PRICE2_FIELD.name = "price2"
BUYSHOPITEM_PRICE2_FIELD.full_name = ".Cmd.BuyShopItem.price2"
BUYSHOPITEM_PRICE2_FIELD.number = 6
BUYSHOPITEM_PRICE2_FIELD.index = 5
BUYSHOPITEM_PRICE2_FIELD.label = 1
BUYSHOPITEM_PRICE2_FIELD.has_default_value = true
BUYSHOPITEM_PRICE2_FIELD.default_value = 0
BUYSHOPITEM_PRICE2_FIELD.type = 13
BUYSHOPITEM_PRICE2_FIELD.cpp_type = 3
BUYSHOPITEM_SUCCESS_FIELD.name = "success"
BUYSHOPITEM_SUCCESS_FIELD.full_name = ".Cmd.BuyShopItem.success"
BUYSHOPITEM_SUCCESS_FIELD.number = 7
BUYSHOPITEM_SUCCESS_FIELD.index = 6
BUYSHOPITEM_SUCCESS_FIELD.label = 1
BUYSHOPITEM_SUCCESS_FIELD.has_default_value = false
BUYSHOPITEM_SUCCESS_FIELD.default_value = false
BUYSHOPITEM_SUCCESS_FIELD.type = 8
BUYSHOPITEM_SUCCESS_FIELD.cpp_type = 7
BUYSHOPITEM.name = "BuyShopItem"
BUYSHOPITEM.full_name = ".Cmd.BuyShopItem"
BUYSHOPITEM.nested_types = {}
BUYSHOPITEM.enum_types = {}
BUYSHOPITEM.fields = {
  BUYSHOPITEM_CMD_FIELD,
  BUYSHOPITEM_PARAM_FIELD,
  BUYSHOPITEM_ID_FIELD,
  BUYSHOPITEM_COUNT_FIELD,
  BUYSHOPITEM_PRICE_FIELD,
  BUYSHOPITEM_PRICE2_FIELD,
  BUYSHOPITEM_SUCCESS_FIELD
}
BUYSHOPITEM.is_extendable = false
BUYSHOPITEM.extensions = {}
QUERYSHOPCONFIGCMD_CMD_FIELD.name = "cmd"
QUERYSHOPCONFIGCMD_CMD_FIELD.full_name = ".Cmd.QueryShopConfigCmd.cmd"
QUERYSHOPCONFIGCMD_CMD_FIELD.number = 1
QUERYSHOPCONFIGCMD_CMD_FIELD.index = 0
QUERYSHOPCONFIGCMD_CMD_FIELD.label = 1
QUERYSHOPCONFIGCMD_CMD_FIELD.has_default_value = true
QUERYSHOPCONFIGCMD_CMD_FIELD.default_value = 52
QUERYSHOPCONFIGCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYSHOPCONFIGCMD_CMD_FIELD.type = 14
QUERYSHOPCONFIGCMD_CMD_FIELD.cpp_type = 8
QUERYSHOPCONFIGCMD_PARAM_FIELD.name = "param"
QUERYSHOPCONFIGCMD_PARAM_FIELD.full_name = ".Cmd.QueryShopConfigCmd.param"
QUERYSHOPCONFIGCMD_PARAM_FIELD.number = 2
QUERYSHOPCONFIGCMD_PARAM_FIELD.index = 1
QUERYSHOPCONFIGCMD_PARAM_FIELD.label = 1
QUERYSHOPCONFIGCMD_PARAM_FIELD.has_default_value = true
QUERYSHOPCONFIGCMD_PARAM_FIELD.default_value = 2
QUERYSHOPCONFIGCMD_PARAM_FIELD.enum_type = SHOPPARAM
QUERYSHOPCONFIGCMD_PARAM_FIELD.type = 14
QUERYSHOPCONFIGCMD_PARAM_FIELD.cpp_type = 8
QUERYSHOPCONFIGCMD_TYPE_FIELD.name = "type"
QUERYSHOPCONFIGCMD_TYPE_FIELD.full_name = ".Cmd.QueryShopConfigCmd.type"
QUERYSHOPCONFIGCMD_TYPE_FIELD.number = 3
QUERYSHOPCONFIGCMD_TYPE_FIELD.index = 2
QUERYSHOPCONFIGCMD_TYPE_FIELD.label = 1
QUERYSHOPCONFIGCMD_TYPE_FIELD.has_default_value = false
QUERYSHOPCONFIGCMD_TYPE_FIELD.default_value = 0
QUERYSHOPCONFIGCMD_TYPE_FIELD.type = 13
QUERYSHOPCONFIGCMD_TYPE_FIELD.cpp_type = 3
QUERYSHOPCONFIGCMD_SHOPID_FIELD.name = "shopid"
QUERYSHOPCONFIGCMD_SHOPID_FIELD.full_name = ".Cmd.QueryShopConfigCmd.shopid"
QUERYSHOPCONFIGCMD_SHOPID_FIELD.number = 4
QUERYSHOPCONFIGCMD_SHOPID_FIELD.index = 3
QUERYSHOPCONFIGCMD_SHOPID_FIELD.label = 1
QUERYSHOPCONFIGCMD_SHOPID_FIELD.has_default_value = false
QUERYSHOPCONFIGCMD_SHOPID_FIELD.default_value = 0
QUERYSHOPCONFIGCMD_SHOPID_FIELD.type = 13
QUERYSHOPCONFIGCMD_SHOPID_FIELD.cpp_type = 3
QUERYSHOPCONFIGCMD_GOODS_FIELD.name = "goods"
QUERYSHOPCONFIGCMD_GOODS_FIELD.full_name = ".Cmd.QueryShopConfigCmd.goods"
QUERYSHOPCONFIGCMD_GOODS_FIELD.number = 5
QUERYSHOPCONFIGCMD_GOODS_FIELD.index = 4
QUERYSHOPCONFIGCMD_GOODS_FIELD.label = 3
QUERYSHOPCONFIGCMD_GOODS_FIELD.has_default_value = false
QUERYSHOPCONFIGCMD_GOODS_FIELD.default_value = {}
QUERYSHOPCONFIGCMD_GOODS_FIELD.message_type = SHOPITEM
QUERYSHOPCONFIGCMD_GOODS_FIELD.type = 11
QUERYSHOPCONFIGCMD_GOODS_FIELD.cpp_type = 10
QUERYSHOPCONFIGCMD_SCREEN_FIELD.name = "screen"
QUERYSHOPCONFIGCMD_SCREEN_FIELD.full_name = ".Cmd.QueryShopConfigCmd.screen"
QUERYSHOPCONFIGCMD_SCREEN_FIELD.number = 6
QUERYSHOPCONFIGCMD_SCREEN_FIELD.index = 5
QUERYSHOPCONFIGCMD_SCREEN_FIELD.label = 1
QUERYSHOPCONFIGCMD_SCREEN_FIELD.has_default_value = false
QUERYSHOPCONFIGCMD_SCREEN_FIELD.default_value = 0
QUERYSHOPCONFIGCMD_SCREEN_FIELD.type = 13
QUERYSHOPCONFIGCMD_SCREEN_FIELD.cpp_type = 3
QUERYSHOPCONFIGCMD_TAB_FIELD.name = "tab"
QUERYSHOPCONFIGCMD_TAB_FIELD.full_name = ".Cmd.QueryShopConfigCmd.tab"
QUERYSHOPCONFIGCMD_TAB_FIELD.number = 7
QUERYSHOPCONFIGCMD_TAB_FIELD.index = 6
QUERYSHOPCONFIGCMD_TAB_FIELD.label = 1
QUERYSHOPCONFIGCMD_TAB_FIELD.has_default_value = true
QUERYSHOPCONFIGCMD_TAB_FIELD.default_value = false
QUERYSHOPCONFIGCMD_TAB_FIELD.type = 8
QUERYSHOPCONFIGCMD_TAB_FIELD.cpp_type = 7
QUERYSHOPCONFIGCMD.name = "QueryShopConfigCmd"
QUERYSHOPCONFIGCMD.full_name = ".Cmd.QueryShopConfigCmd"
QUERYSHOPCONFIGCMD.nested_types = {}
QUERYSHOPCONFIGCMD.enum_types = {}
QUERYSHOPCONFIGCMD.fields = {
  QUERYSHOPCONFIGCMD_CMD_FIELD,
  QUERYSHOPCONFIGCMD_PARAM_FIELD,
  QUERYSHOPCONFIGCMD_TYPE_FIELD,
  QUERYSHOPCONFIGCMD_SHOPID_FIELD,
  QUERYSHOPCONFIGCMD_GOODS_FIELD,
  QUERYSHOPCONFIGCMD_SCREEN_FIELD,
  QUERYSHOPCONFIGCMD_TAB_FIELD
}
QUERYSHOPCONFIGCMD.is_extendable = false
QUERYSHOPCONFIGCMD.extensions = {}
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.name = "cmd"
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.full_name = ".Cmd.QueryQuickBuyConfigCmd.cmd"
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.number = 1
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.index = 0
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.label = 1
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.has_default_value = true
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.default_value = 52
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.type = 14
QUERYQUICKBUYCONFIGCMD_CMD_FIELD.cpp_type = 8
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.name = "param"
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.full_name = ".Cmd.QueryQuickBuyConfigCmd.param"
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.number = 2
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.index = 1
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.label = 1
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.has_default_value = true
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.default_value = 3
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.enum_type = SHOPPARAM
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.type = 14
QUERYQUICKBUYCONFIGCMD_PARAM_FIELD.cpp_type = 8
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.name = "itemids"
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.full_name = ".Cmd.QueryQuickBuyConfigCmd.itemids"
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.number = 3
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.index = 2
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.label = 3
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.has_default_value = false
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.default_value = {}
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.type = 13
QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD.cpp_type = 3
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.name = "goods"
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.full_name = ".Cmd.QueryQuickBuyConfigCmd.goods"
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.number = 4
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.index = 3
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.label = 3
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.has_default_value = false
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.default_value = {}
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.message_type = SHOPITEM
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.type = 11
QUERYQUICKBUYCONFIGCMD_GOODS_FIELD.cpp_type = 10
QUERYQUICKBUYCONFIGCMD.name = "QueryQuickBuyConfigCmd"
QUERYQUICKBUYCONFIGCMD.full_name = ".Cmd.QueryQuickBuyConfigCmd"
QUERYQUICKBUYCONFIGCMD.nested_types = {}
QUERYQUICKBUYCONFIGCMD.enum_types = {}
QUERYQUICKBUYCONFIGCMD.fields = {
  QUERYQUICKBUYCONFIGCMD_CMD_FIELD,
  QUERYQUICKBUYCONFIGCMD_PARAM_FIELD,
  QUERYQUICKBUYCONFIGCMD_ITEMIDS_FIELD,
  QUERYQUICKBUYCONFIGCMD_GOODS_FIELD
}
QUERYQUICKBUYCONFIGCMD.is_extendable = false
QUERYQUICKBUYCONFIGCMD.extensions = {}
SHOPSOLDITEM_ID_FIELD.name = "id"
SHOPSOLDITEM_ID_FIELD.full_name = ".Cmd.ShopSoldItem.id"
SHOPSOLDITEM_ID_FIELD.number = 1
SHOPSOLDITEM_ID_FIELD.index = 0
SHOPSOLDITEM_ID_FIELD.label = 1
SHOPSOLDITEM_ID_FIELD.has_default_value = true
SHOPSOLDITEM_ID_FIELD.default_value = 0
SHOPSOLDITEM_ID_FIELD.type = 13
SHOPSOLDITEM_ID_FIELD.cpp_type = 3
SHOPSOLDITEM_COUNT_FIELD.name = "count"
SHOPSOLDITEM_COUNT_FIELD.full_name = ".Cmd.ShopSoldItem.count"
SHOPSOLDITEM_COUNT_FIELD.number = 2
SHOPSOLDITEM_COUNT_FIELD.index = 1
SHOPSOLDITEM_COUNT_FIELD.label = 1
SHOPSOLDITEM_COUNT_FIELD.has_default_value = true
SHOPSOLDITEM_COUNT_FIELD.default_value = 0
SHOPSOLDITEM_COUNT_FIELD.type = 13
SHOPSOLDITEM_COUNT_FIELD.cpp_type = 3
SHOPSOLDITEM_SHOPID_FIELD.name = "shopid"
SHOPSOLDITEM_SHOPID_FIELD.full_name = ".Cmd.ShopSoldItem.shopid"
SHOPSOLDITEM_SHOPID_FIELD.number = 3
SHOPSOLDITEM_SHOPID_FIELD.index = 2
SHOPSOLDITEM_SHOPID_FIELD.label = 1
SHOPSOLDITEM_SHOPID_FIELD.has_default_value = false
SHOPSOLDITEM_SHOPID_FIELD.default_value = 0
SHOPSOLDITEM_SHOPID_FIELD.type = 13
SHOPSOLDITEM_SHOPID_FIELD.cpp_type = 3
SHOPSOLDITEM_TYPE_FIELD.name = "type"
SHOPSOLDITEM_TYPE_FIELD.full_name = ".Cmd.ShopSoldItem.type"
SHOPSOLDITEM_TYPE_FIELD.number = 4
SHOPSOLDITEM_TYPE_FIELD.index = 3
SHOPSOLDITEM_TYPE_FIELD.label = 1
SHOPSOLDITEM_TYPE_FIELD.has_default_value = false
SHOPSOLDITEM_TYPE_FIELD.default_value = 0
SHOPSOLDITEM_TYPE_FIELD.type = 13
SHOPSOLDITEM_TYPE_FIELD.cpp_type = 3
SHOPSOLDITEM.name = "ShopSoldItem"
SHOPSOLDITEM.full_name = ".Cmd.ShopSoldItem"
SHOPSOLDITEM.nested_types = {}
SHOPSOLDITEM.enum_types = {}
SHOPSOLDITEM.fields = {
  SHOPSOLDITEM_ID_FIELD,
  SHOPSOLDITEM_COUNT_FIELD,
  SHOPSOLDITEM_SHOPID_FIELD,
  SHOPSOLDITEM_TYPE_FIELD
}
SHOPSOLDITEM.is_extendable = false
SHOPSOLDITEM.extensions = {}
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.name = "cmd"
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.full_name = ".Cmd.QueryShopSoldCountCmd.cmd"
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.number = 1
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.index = 0
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.label = 1
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.has_default_value = true
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.default_value = 52
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.type = 14
QUERYSHOPSOLDCOUNTCMD_CMD_FIELD.cpp_type = 8
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.name = "param"
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.full_name = ".Cmd.QueryShopSoldCountCmd.param"
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.number = 2
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.index = 1
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.label = 1
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.has_default_value = true
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.default_value = 4
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.enum_type = SHOPPARAM
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.type = 14
QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD.cpp_type = 8
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.name = "items"
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.full_name = ".Cmd.QueryShopSoldCountCmd.items"
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.number = 3
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.index = 2
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.label = 3
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.has_default_value = false
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.default_value = {}
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.message_type = SHOPSOLDITEM
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.type = 11
QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD.cpp_type = 10
QUERYSHOPSOLDCOUNTCMD.name = "QueryShopSoldCountCmd"
QUERYSHOPSOLDCOUNTCMD.full_name = ".Cmd.QueryShopSoldCountCmd"
QUERYSHOPSOLDCOUNTCMD.nested_types = {}
QUERYSHOPSOLDCOUNTCMD.enum_types = {}
QUERYSHOPSOLDCOUNTCMD.fields = {
  QUERYSHOPSOLDCOUNTCMD_CMD_FIELD,
  QUERYSHOPSOLDCOUNTCMD_PARAM_FIELD,
  QUERYSHOPSOLDCOUNTCMD_ITEMS_FIELD
}
QUERYSHOPSOLDCOUNTCMD.is_extendable = false
QUERYSHOPSOLDCOUNTCMD.extensions = {}
SHOPDATAUPDATECMD_CMD_FIELD.name = "cmd"
SHOPDATAUPDATECMD_CMD_FIELD.full_name = ".Cmd.ShopDataUpdateCmd.cmd"
SHOPDATAUPDATECMD_CMD_FIELD.number = 1
SHOPDATAUPDATECMD_CMD_FIELD.index = 0
SHOPDATAUPDATECMD_CMD_FIELD.label = 1
SHOPDATAUPDATECMD_CMD_FIELD.has_default_value = true
SHOPDATAUPDATECMD_CMD_FIELD.default_value = 52
SHOPDATAUPDATECMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SHOPDATAUPDATECMD_CMD_FIELD.type = 14
SHOPDATAUPDATECMD_CMD_FIELD.cpp_type = 8
SHOPDATAUPDATECMD_PARAM_FIELD.name = "param"
SHOPDATAUPDATECMD_PARAM_FIELD.full_name = ".Cmd.ShopDataUpdateCmd.param"
SHOPDATAUPDATECMD_PARAM_FIELD.number = 2
SHOPDATAUPDATECMD_PARAM_FIELD.index = 1
SHOPDATAUPDATECMD_PARAM_FIELD.label = 1
SHOPDATAUPDATECMD_PARAM_FIELD.has_default_value = true
SHOPDATAUPDATECMD_PARAM_FIELD.default_value = 5
SHOPDATAUPDATECMD_PARAM_FIELD.enum_type = SHOPPARAM
SHOPDATAUPDATECMD_PARAM_FIELD.type = 14
SHOPDATAUPDATECMD_PARAM_FIELD.cpp_type = 8
SHOPDATAUPDATECMD_TYPE_FIELD.name = "type"
SHOPDATAUPDATECMD_TYPE_FIELD.full_name = ".Cmd.ShopDataUpdateCmd.type"
SHOPDATAUPDATECMD_TYPE_FIELD.number = 3
SHOPDATAUPDATECMD_TYPE_FIELD.index = 2
SHOPDATAUPDATECMD_TYPE_FIELD.label = 1
SHOPDATAUPDATECMD_TYPE_FIELD.has_default_value = false
SHOPDATAUPDATECMD_TYPE_FIELD.default_value = 0
SHOPDATAUPDATECMD_TYPE_FIELD.type = 13
SHOPDATAUPDATECMD_TYPE_FIELD.cpp_type = 3
SHOPDATAUPDATECMD_SHOPID_FIELD.name = "shopid"
SHOPDATAUPDATECMD_SHOPID_FIELD.full_name = ".Cmd.ShopDataUpdateCmd.shopid"
SHOPDATAUPDATECMD_SHOPID_FIELD.number = 4
SHOPDATAUPDATECMD_SHOPID_FIELD.index = 3
SHOPDATAUPDATECMD_SHOPID_FIELD.label = 1
SHOPDATAUPDATECMD_SHOPID_FIELD.has_default_value = true
SHOPDATAUPDATECMD_SHOPID_FIELD.default_value = 0
SHOPDATAUPDATECMD_SHOPID_FIELD.type = 13
SHOPDATAUPDATECMD_SHOPID_FIELD.cpp_type = 3
SHOPDATAUPDATECMD.name = "ShopDataUpdateCmd"
SHOPDATAUPDATECMD.full_name = ".Cmd.ShopDataUpdateCmd"
SHOPDATAUPDATECMD.nested_types = {}
SHOPDATAUPDATECMD.enum_types = {}
SHOPDATAUPDATECMD.fields = {
  SHOPDATAUPDATECMD_CMD_FIELD,
  SHOPDATAUPDATECMD_PARAM_FIELD,
  SHOPDATAUPDATECMD_TYPE_FIELD,
  SHOPDATAUPDATECMD_SHOPID_FIELD
}
SHOPDATAUPDATECMD.is_extendable = false
SHOPDATAUPDATECMD.extensions = {}
UPDATESHOPCONFIGCMD_CMD_FIELD.name = "cmd"
UPDATESHOPCONFIGCMD_CMD_FIELD.full_name = ".Cmd.UpdateShopConfigCmd.cmd"
UPDATESHOPCONFIGCMD_CMD_FIELD.number = 1
UPDATESHOPCONFIGCMD_CMD_FIELD.index = 0
UPDATESHOPCONFIGCMD_CMD_FIELD.label = 1
UPDATESHOPCONFIGCMD_CMD_FIELD.has_default_value = true
UPDATESHOPCONFIGCMD_CMD_FIELD.default_value = 52
UPDATESHOPCONFIGCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
UPDATESHOPCONFIGCMD_CMD_FIELD.type = 14
UPDATESHOPCONFIGCMD_CMD_FIELD.cpp_type = 8
UPDATESHOPCONFIGCMD_PARAM_FIELD.name = "param"
UPDATESHOPCONFIGCMD_PARAM_FIELD.full_name = ".Cmd.UpdateShopConfigCmd.param"
UPDATESHOPCONFIGCMD_PARAM_FIELD.number = 2
UPDATESHOPCONFIGCMD_PARAM_FIELD.index = 1
UPDATESHOPCONFIGCMD_PARAM_FIELD.label = 1
UPDATESHOPCONFIGCMD_PARAM_FIELD.has_default_value = true
UPDATESHOPCONFIGCMD_PARAM_FIELD.default_value = 6
UPDATESHOPCONFIGCMD_PARAM_FIELD.enum_type = SHOPPARAM
UPDATESHOPCONFIGCMD_PARAM_FIELD.type = 14
UPDATESHOPCONFIGCMD_PARAM_FIELD.cpp_type = 8
UPDATESHOPCONFIGCMD_TYPE_FIELD.name = "type"
UPDATESHOPCONFIGCMD_TYPE_FIELD.full_name = ".Cmd.UpdateShopConfigCmd.type"
UPDATESHOPCONFIGCMD_TYPE_FIELD.number = 3
UPDATESHOPCONFIGCMD_TYPE_FIELD.index = 2
UPDATESHOPCONFIGCMD_TYPE_FIELD.label = 1
UPDATESHOPCONFIGCMD_TYPE_FIELD.has_default_value = false
UPDATESHOPCONFIGCMD_TYPE_FIELD.default_value = 0
UPDATESHOPCONFIGCMD_TYPE_FIELD.type = 13
UPDATESHOPCONFIGCMD_TYPE_FIELD.cpp_type = 3
UPDATESHOPCONFIGCMD_SHOPID_FIELD.name = "shopid"
UPDATESHOPCONFIGCMD_SHOPID_FIELD.full_name = ".Cmd.UpdateShopConfigCmd.shopid"
UPDATESHOPCONFIGCMD_SHOPID_FIELD.number = 4
UPDATESHOPCONFIGCMD_SHOPID_FIELD.index = 3
UPDATESHOPCONFIGCMD_SHOPID_FIELD.label = 1
UPDATESHOPCONFIGCMD_SHOPID_FIELD.has_default_value = false
UPDATESHOPCONFIGCMD_SHOPID_FIELD.default_value = 0
UPDATESHOPCONFIGCMD_SHOPID_FIELD.type = 13
UPDATESHOPCONFIGCMD_SHOPID_FIELD.cpp_type = 3
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.name = "del_goods_id"
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.full_name = ".Cmd.UpdateShopConfigCmd.del_goods_id"
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.number = 5
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.index = 4
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.label = 3
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.has_default_value = false
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.default_value = {}
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.type = 13
UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD.cpp_type = 3
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.name = "add_goods"
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.full_name = ".Cmd.UpdateShopConfigCmd.add_goods"
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.number = 6
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.index = 5
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.label = 3
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.has_default_value = false
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.default_value = {}
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.message_type = SHOPITEM
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.type = 11
UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD.cpp_type = 10
UPDATESHOPCONFIGCMD.name = "UpdateShopConfigCmd"
UPDATESHOPCONFIGCMD.full_name = ".Cmd.UpdateShopConfigCmd"
UPDATESHOPCONFIGCMD.nested_types = {}
UPDATESHOPCONFIGCMD.enum_types = {}
UPDATESHOPCONFIGCMD.fields = {
  UPDATESHOPCONFIGCMD_CMD_FIELD,
  UPDATESHOPCONFIGCMD_PARAM_FIELD,
  UPDATESHOPCONFIGCMD_TYPE_FIELD,
  UPDATESHOPCONFIGCMD_SHOPID_FIELD,
  UPDATESHOPCONFIGCMD_DEL_GOODS_ID_FIELD,
  UPDATESHOPCONFIGCMD_ADD_GOODS_FIELD
}
UPDATESHOPCONFIGCMD.is_extendable = false
UPDATESHOPCONFIGCMD.extensions = {}
EXCHANGESHOPITEM_ID_FIELD.name = "id"
EXCHANGESHOPITEM_ID_FIELD.full_name = ".Cmd.ExchangeShopItem.id"
EXCHANGESHOPITEM_ID_FIELD.number = 1
EXCHANGESHOPITEM_ID_FIELD.index = 0
EXCHANGESHOPITEM_ID_FIELD.label = 1
EXCHANGESHOPITEM_ID_FIELD.has_default_value = false
EXCHANGESHOPITEM_ID_FIELD.default_value = 0
EXCHANGESHOPITEM_ID_FIELD.type = 13
EXCHANGESHOPITEM_ID_FIELD.cpp_type = 3
EXCHANGESHOPITEM_STATUS_FIELD.name = "status"
EXCHANGESHOPITEM_STATUS_FIELD.full_name = ".Cmd.ExchangeShopItem.status"
EXCHANGESHOPITEM_STATUS_FIELD.number = 2
EXCHANGESHOPITEM_STATUS_FIELD.index = 1
EXCHANGESHOPITEM_STATUS_FIELD.label = 1
EXCHANGESHOPITEM_STATUS_FIELD.has_default_value = true
EXCHANGESHOPITEM_STATUS_FIELD.default_value = 1
EXCHANGESHOPITEM_STATUS_FIELD.enum_type = EEXCHANGESTATUSTYPE
EXCHANGESHOPITEM_STATUS_FIELD.type = 14
EXCHANGESHOPITEM_STATUS_FIELD.cpp_type = 8
EXCHANGESHOPITEM_PROGRESS_FIELD.name = "progress"
EXCHANGESHOPITEM_PROGRESS_FIELD.full_name = ".Cmd.ExchangeShopItem.progress"
EXCHANGESHOPITEM_PROGRESS_FIELD.number = 3
EXCHANGESHOPITEM_PROGRESS_FIELD.index = 2
EXCHANGESHOPITEM_PROGRESS_FIELD.label = 1
EXCHANGESHOPITEM_PROGRESS_FIELD.has_default_value = false
EXCHANGESHOPITEM_PROGRESS_FIELD.default_value = 0
EXCHANGESHOPITEM_PROGRESS_FIELD.type = 13
EXCHANGESHOPITEM_PROGRESS_FIELD.cpp_type = 3
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.name = "exchange_count"
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.full_name = ".Cmd.ExchangeShopItem.exchange_count"
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.number = 4
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.index = 3
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.label = 1
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.has_default_value = false
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.default_value = 0
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.type = 13
EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD.cpp_type = 3
EXCHANGESHOPITEM_LEFT_TIME_FIELD.name = "left_time"
EXCHANGESHOPITEM_LEFT_TIME_FIELD.full_name = ".Cmd.ExchangeShopItem.left_time"
EXCHANGESHOPITEM_LEFT_TIME_FIELD.number = 5
EXCHANGESHOPITEM_LEFT_TIME_FIELD.index = 4
EXCHANGESHOPITEM_LEFT_TIME_FIELD.label = 1
EXCHANGESHOPITEM_LEFT_TIME_FIELD.has_default_value = false
EXCHANGESHOPITEM_LEFT_TIME_FIELD.default_value = 0
EXCHANGESHOPITEM_LEFT_TIME_FIELD.type = 13
EXCHANGESHOPITEM_LEFT_TIME_FIELD.cpp_type = 3
EXCHANGESHOPITEM_DELAY_TIME_FIELD.name = "delay_time"
EXCHANGESHOPITEM_DELAY_TIME_FIELD.full_name = ".Cmd.ExchangeShopItem.delay_time"
EXCHANGESHOPITEM_DELAY_TIME_FIELD.number = 6
EXCHANGESHOPITEM_DELAY_TIME_FIELD.index = 5
EXCHANGESHOPITEM_DELAY_TIME_FIELD.label = 1
EXCHANGESHOPITEM_DELAY_TIME_FIELD.has_default_value = false
EXCHANGESHOPITEM_DELAY_TIME_FIELD.default_value = 0
EXCHANGESHOPITEM_DELAY_TIME_FIELD.type = 13
EXCHANGESHOPITEM_DELAY_TIME_FIELD.cpp_type = 3
EXCHANGESHOPITEM.name = "ExchangeShopItem"
EXCHANGESHOPITEM.full_name = ".Cmd.ExchangeShopItem"
EXCHANGESHOPITEM.nested_types = {}
EXCHANGESHOPITEM.enum_types = {}
EXCHANGESHOPITEM.fields = {
  EXCHANGESHOPITEM_ID_FIELD,
  EXCHANGESHOPITEM_STATUS_FIELD,
  EXCHANGESHOPITEM_PROGRESS_FIELD,
  EXCHANGESHOPITEM_EXCHANGE_COUNT_FIELD,
  EXCHANGESHOPITEM_LEFT_TIME_FIELD,
  EXCHANGESHOPITEM_DELAY_TIME_FIELD
}
EXCHANGESHOPITEM.is_extendable = false
EXCHANGESHOPITEM.extensions = {}
UPDATEEXCHANGESHOPDATA_CMD_FIELD.name = "cmd"
UPDATEEXCHANGESHOPDATA_CMD_FIELD.full_name = ".Cmd.UpdateExchangeShopData.cmd"
UPDATEEXCHANGESHOPDATA_CMD_FIELD.number = 1
UPDATEEXCHANGESHOPDATA_CMD_FIELD.index = 0
UPDATEEXCHANGESHOPDATA_CMD_FIELD.label = 1
UPDATEEXCHANGESHOPDATA_CMD_FIELD.has_default_value = true
UPDATEEXCHANGESHOPDATA_CMD_FIELD.default_value = 52
UPDATEEXCHANGESHOPDATA_CMD_FIELD.enum_type = XCMD_PB_COMMAND
UPDATEEXCHANGESHOPDATA_CMD_FIELD.type = 14
UPDATEEXCHANGESHOPDATA_CMD_FIELD.cpp_type = 8
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.name = "param"
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.full_name = ".Cmd.UpdateExchangeShopData.param"
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.number = 2
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.index = 1
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.label = 1
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.has_default_value = true
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.default_value = 7
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.enum_type = SHOPPARAM
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.type = 14
UPDATEEXCHANGESHOPDATA_PARAM_FIELD.cpp_type = 8
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.name = "items"
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.full_name = ".Cmd.UpdateExchangeShopData.items"
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.number = 3
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.index = 2
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.label = 3
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.has_default_value = false
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.default_value = {}
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.message_type = EXCHANGESHOPITEM
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.type = 11
UPDATEEXCHANGESHOPDATA_ITEMS_FIELD.cpp_type = 10
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.name = "del_items"
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.full_name = ".Cmd.UpdateExchangeShopData.del_items"
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.number = 4
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.index = 3
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.label = 3
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.has_default_value = false
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.default_value = {}
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.type = 13
UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD.cpp_type = 3
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.name = "menu_open"
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.full_name = ".Cmd.UpdateExchangeShopData.menu_open"
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.number = 5
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.index = 4
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.label = 1
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.has_default_value = false
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.default_value = false
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.type = 8
UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD.cpp_type = 7
UPDATEEXCHANGESHOPDATA_RESET_FIELD.name = "reset"
UPDATEEXCHANGESHOPDATA_RESET_FIELD.full_name = ".Cmd.UpdateExchangeShopData.reset"
UPDATEEXCHANGESHOPDATA_RESET_FIELD.number = 6
UPDATEEXCHANGESHOPDATA_RESET_FIELD.index = 5
UPDATEEXCHANGESHOPDATA_RESET_FIELD.label = 1
UPDATEEXCHANGESHOPDATA_RESET_FIELD.has_default_value = true
UPDATEEXCHANGESHOPDATA_RESET_FIELD.default_value = false
UPDATEEXCHANGESHOPDATA_RESET_FIELD.type = 8
UPDATEEXCHANGESHOPDATA_RESET_FIELD.cpp_type = 7
UPDATEEXCHANGESHOPDATA.name = "UpdateExchangeShopData"
UPDATEEXCHANGESHOPDATA.full_name = ".Cmd.UpdateExchangeShopData"
UPDATEEXCHANGESHOPDATA.nested_types = {}
UPDATEEXCHANGESHOPDATA.enum_types = {}
UPDATEEXCHANGESHOPDATA.fields = {
  UPDATEEXCHANGESHOPDATA_CMD_FIELD,
  UPDATEEXCHANGESHOPDATA_PARAM_FIELD,
  UPDATEEXCHANGESHOPDATA_ITEMS_FIELD,
  UPDATEEXCHANGESHOPDATA_DEL_ITEMS_FIELD,
  UPDATEEXCHANGESHOPDATA_MENU_OPEN_FIELD,
  UPDATEEXCHANGESHOPDATA_RESET_FIELD
}
UPDATEEXCHANGESHOPDATA.is_extendable = false
UPDATEEXCHANGESHOPDATA.extensions = {}
EXCHANGEITEMINFO_ID_FIELD.name = "id"
EXCHANGEITEMINFO_ID_FIELD.full_name = ".Cmd.ExchangeItemInfo.id"
EXCHANGEITEMINFO_ID_FIELD.number = 1
EXCHANGEITEMINFO_ID_FIELD.index = 0
EXCHANGEITEMINFO_ID_FIELD.label = 1
EXCHANGEITEMINFO_ID_FIELD.has_default_value = false
EXCHANGEITEMINFO_ID_FIELD.default_value = 0
EXCHANGEITEMINFO_ID_FIELD.type = 13
EXCHANGEITEMINFO_ID_FIELD.cpp_type = 3
EXCHANGEITEMINFO_NUM_FIELD.name = "num"
EXCHANGEITEMINFO_NUM_FIELD.full_name = ".Cmd.ExchangeItemInfo.num"
EXCHANGEITEMINFO_NUM_FIELD.number = 2
EXCHANGEITEMINFO_NUM_FIELD.index = 1
EXCHANGEITEMINFO_NUM_FIELD.label = 1
EXCHANGEITEMINFO_NUM_FIELD.has_default_value = false
EXCHANGEITEMINFO_NUM_FIELD.default_value = 0
EXCHANGEITEMINFO_NUM_FIELD.type = 13
EXCHANGEITEMINFO_NUM_FIELD.cpp_type = 3
EXCHANGEITEMINFO.name = "ExchangeItemInfo"
EXCHANGEITEMINFO.full_name = ".Cmd.ExchangeItemInfo"
EXCHANGEITEMINFO.nested_types = {}
EXCHANGEITEMINFO.enum_types = {}
EXCHANGEITEMINFO.fields = {
  EXCHANGEITEMINFO_ID_FIELD,
  EXCHANGEITEMINFO_NUM_FIELD
}
EXCHANGEITEMINFO.is_extendable = false
EXCHANGEITEMINFO.extensions = {}
EXCHANGESHOPITEMCMD_CMD_FIELD.name = "cmd"
EXCHANGESHOPITEMCMD_CMD_FIELD.full_name = ".Cmd.ExchangeShopItemCmd.cmd"
EXCHANGESHOPITEMCMD_CMD_FIELD.number = 1
EXCHANGESHOPITEMCMD_CMD_FIELD.index = 0
EXCHANGESHOPITEMCMD_CMD_FIELD.label = 1
EXCHANGESHOPITEMCMD_CMD_FIELD.has_default_value = true
EXCHANGESHOPITEMCMD_CMD_FIELD.default_value = 52
EXCHANGESHOPITEMCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
EXCHANGESHOPITEMCMD_CMD_FIELD.type = 14
EXCHANGESHOPITEMCMD_CMD_FIELD.cpp_type = 8
EXCHANGESHOPITEMCMD_PARAM_FIELD.name = "param"
EXCHANGESHOPITEMCMD_PARAM_FIELD.full_name = ".Cmd.ExchangeShopItemCmd.param"
EXCHANGESHOPITEMCMD_PARAM_FIELD.number = 2
EXCHANGESHOPITEMCMD_PARAM_FIELD.index = 1
EXCHANGESHOPITEMCMD_PARAM_FIELD.label = 1
EXCHANGESHOPITEMCMD_PARAM_FIELD.has_default_value = true
EXCHANGESHOPITEMCMD_PARAM_FIELD.default_value = 8
EXCHANGESHOPITEMCMD_PARAM_FIELD.enum_type = SHOPPARAM
EXCHANGESHOPITEMCMD_PARAM_FIELD.type = 14
EXCHANGESHOPITEMCMD_PARAM_FIELD.cpp_type = 8
EXCHANGESHOPITEMCMD_ID_FIELD.name = "id"
EXCHANGESHOPITEMCMD_ID_FIELD.full_name = ".Cmd.ExchangeShopItemCmd.id"
EXCHANGESHOPITEMCMD_ID_FIELD.number = 3
EXCHANGESHOPITEMCMD_ID_FIELD.index = 2
EXCHANGESHOPITEMCMD_ID_FIELD.label = 1
EXCHANGESHOPITEMCMD_ID_FIELD.has_default_value = false
EXCHANGESHOPITEMCMD_ID_FIELD.default_value = 0
EXCHANGESHOPITEMCMD_ID_FIELD.type = 13
EXCHANGESHOPITEMCMD_ID_FIELD.cpp_type = 3
EXCHANGESHOPITEMCMD_ITEMS_FIELD.name = "items"
EXCHANGESHOPITEMCMD_ITEMS_FIELD.full_name = ".Cmd.ExchangeShopItemCmd.items"
EXCHANGESHOPITEMCMD_ITEMS_FIELD.number = 4
EXCHANGESHOPITEMCMD_ITEMS_FIELD.index = 3
EXCHANGESHOPITEMCMD_ITEMS_FIELD.label = 3
EXCHANGESHOPITEMCMD_ITEMS_FIELD.has_default_value = false
EXCHANGESHOPITEMCMD_ITEMS_FIELD.default_value = {}
EXCHANGESHOPITEMCMD_ITEMS_FIELD.message_type = EXCHANGEITEMINFO
EXCHANGESHOPITEMCMD_ITEMS_FIELD.type = 11
EXCHANGESHOPITEMCMD_ITEMS_FIELD.cpp_type = 10
EXCHANGESHOPITEMCMD.name = "ExchangeShopItemCmd"
EXCHANGESHOPITEMCMD.full_name = ".Cmd.ExchangeShopItemCmd"
EXCHANGESHOPITEMCMD.nested_types = {}
EXCHANGESHOPITEMCMD.enum_types = {}
EXCHANGESHOPITEMCMD.fields = {
  EXCHANGESHOPITEMCMD_CMD_FIELD,
  EXCHANGESHOPITEMCMD_PARAM_FIELD,
  EXCHANGESHOPITEMCMD_ID_FIELD,
  EXCHANGESHOPITEMCMD_ITEMS_FIELD
}
EXCHANGESHOPITEMCMD.is_extendable = false
EXCHANGESHOPITEMCMD.extensions = {}
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.name = "cmd"
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.full_name = ".Cmd.ResetExchangeShopDataShopCmd.cmd"
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.number = 1
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.index = 0
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.label = 1
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.has_default_value = true
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.default_value = 52
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.type = 14
RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD.cpp_type = 8
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.name = "param"
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.full_name = ".Cmd.ResetExchangeShopDataShopCmd.param"
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.number = 2
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.index = 1
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.label = 1
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.has_default_value = true
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.default_value = 9
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.enum_type = SHOPPARAM
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.type = 14
RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD.cpp_type = 8
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.name = "items"
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.full_name = ".Cmd.ResetExchangeShopDataShopCmd.items"
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.number = 3
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.index = 2
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.label = 3
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.has_default_value = false
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.default_value = {}
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.message_type = EXCHANGESHOPITEM
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.type = 11
RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD.cpp_type = 10
RESETEXCHANGESHOPDATASHOPCMD.name = "ResetExchangeShopDataShopCmd"
RESETEXCHANGESHOPDATASHOPCMD.full_name = ".Cmd.ResetExchangeShopDataShopCmd"
RESETEXCHANGESHOPDATASHOPCMD.nested_types = {}
RESETEXCHANGESHOPDATASHOPCMD.enum_types = {}
RESETEXCHANGESHOPDATASHOPCMD.fields = {
  RESETEXCHANGESHOPDATASHOPCMD_CMD_FIELD,
  RESETEXCHANGESHOPDATASHOPCMD_PARAM_FIELD,
  RESETEXCHANGESHOPDATASHOPCMD_ITEMS_FIELD
}
RESETEXCHANGESHOPDATASHOPCMD.is_extendable = false
RESETEXCHANGESHOPDATASHOPCMD.extensions = {}
BuyShopItem = protobuf.Message(BUYSHOPITEM)
EEXCHANGESTATUSTYPE_DELAY = 3
EEXCHANGESTATUSTYPE_EMPTY = 2
EEXCHANGESTATUSTYPE_OK = 1
EEXCHANGESTATUSTYPE_UNLOOK = 4
EPRESENTTYPE_LOCK = 1
EPRESENTTYPE_NORMAL = 0
ESHOPLIMITTYPE_ACC_MONTH = 128
ESHOPLIMITTYPE_ACC_USER = 4
ESHOPLIMITTYPE_ACC_USER_ALWAYS = 8
ESHOPLIMITTYPE_ACC_WEEK = 64
ESHOPLIMITTYPE_GUILD_MATERIAL_MAXCOUNT = 256
ESHOPLIMITTYPE_MAX = 512
ESHOPLIMITTYPE_MIN = 0
ESHOPLIMITTYPE_ONE_ONLY = 2
ESHOPLIMITTYPE_USER = 1
ESHOPLIMITTYPE_USER_MONTH = 32
ESHOPLIMITTYPE_USER_WEEK = 16
ESHOPLOCKTYPE_GUILDBUILDING = 2
ESHOPLOCKTYPE_MAX = 3
ESHOPLOCKTYPE_MIN = 0
ESHOPLOCKTYPE_QUEST = 1
ESHOPSOURCE_GUILD = 1
ESHOPSOURCE_USER = 0
ESHOPSOURCE_USER_GUILD = 2
ExchangeItemInfo = protobuf.Message(EXCHANGEITEMINFO)
ExchangeShopItem = protobuf.Message(EXCHANGESHOPITEM)
ExchangeShopItemCmd = protobuf.Message(EXCHANGESHOPITEMCMD)
Presentation = protobuf.Message(PRESENTATION)
QueryQuickBuyConfigCmd = protobuf.Message(QUERYQUICKBUYCONFIGCMD)
QueryShopConfigCmd = protobuf.Message(QUERYSHOPCONFIGCMD)
QueryShopSoldCountCmd = protobuf.Message(QUERYSHOPSOLDCOUNTCMD)
ResetExchangeShopDataShopCmd = protobuf.Message(RESETEXCHANGESHOPDATASHOPCMD)
SHOPPARAM_BUYITEM = 1
SHOPPARAM_EXCHANGEITEM_CMD = 8
SHOPPARAM_QUERY_SHOP_CONFIG = 2
SHOPPARAM_QUERY_SHOP_SOLD_COUNT = 4
SHOPPARAM_QUICKBUY_SHOP_CONFIG = 3
SHOPPARAM_RESET_EXCHANGESHOP_DATA = 9
SHOPPARAM_UPDATE_DATA = 5
SHOPPARAM_UPDATE_EXCHANGESHOP_DATA = 7
SHOPPARAM_UPDATE_SHOP_CONFIG_CMD = 6
ShopDataUpdateCmd = protobuf.Message(SHOPDATAUPDATECMD)
ShopItem = protobuf.Message(SHOPITEM)
ShopSoldItem = protobuf.Message(SHOPSOLDITEM)
UpdateExchangeShopData = protobuf.Message(UPDATEEXCHANGESHOPDATA)
UpdateShopConfigCmd = protobuf.Message(UPDATESHOPCONFIGCMD)
